/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://media.adonix.org/car_talk_2007-04-28.mp3",
        filename: "car_talk_2007-04-28.mp3",
        title: "#0717: April 28, 2007",
        description: "Car Talk's weekly full-show podcast for April 28, 2007.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-04-28",
        seconds: 3319.405625,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-05-05.mp3",
        filename: "car_talk_2007-05-05.mp3",
        title: "#0718: May 5, 2007",
        description:
            "An ill-fated trip to the Big City for Sid and his Mulchmobile. Also, an Alfa owner wants to give her car a homecoming, but, may have to ditch her self-appointed interpereters. And, a single Mom searches for her dream car: reliable, safe, fuel efficient, and snazzy--for under 12 grand.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-05-05",
        seconds: 3323.89875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-05-14.mp3",
        filename: "car_talk_2007-05-14.mp3",
        title: "#0719: Hello You're on Mom Talk!",
        description:
            "A collection of Car Talk appearances featuring their long-suffering Mom, Elizabeth Magliozzi. Find out whether she knows as much about parenting as they do about cars...and, where the guys learned to laugh.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-05-12",
        seconds: 3308.4865,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-05-19.mp3",
        filename: "car_talk_2007-05-19.mp3",
        title: "#0720: May 19, 2007",
        description:
            "Does automotive fidelity equal marital fidelity? Also, A Honda that may be ready for Rogaine, A Volvo owner wonders if he can live without a part he never knew he had, a new automotive Puzzler, and lots nore.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-05-19",
        seconds: 3323.350125,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-05-26.mp3",
        filename: "car_talk_2007-05-26.mp3",
        title: "#7021: May 26, 2007",
        description:
            "Ray's misadventure with Sno-Seal prompts listeners to share their own medicine cabinet mishaps. Also, what to do when your car turns into a mouse's pantry, a very scary ride in an Escape, and a bit of maternal history from Tom and Ray.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-05-26",
        seconds: 3308.53875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-06-02.mp3",
        filename: "car_talk_2007-06-02.mp3",
        title: "#0722: June 2, 2007",
        description:
            "Fans of auto-noise reenactments, rejoice! Have we got a doozy for you. Also, an ABS tutorial, a Saab that will take 35 dollars of gas--no more, no less--and how cars are handed down from one generation to the next in the Mgaliozzi household.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-06-02",
        seconds: 3309.71425,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-06-09.mp3",
        filename: "car_talk_2007-06-09.mp3",
        title: "#0723: June 9, 2007",
        description:
            "In time for Father's Day, Tom and Ray share a couple of stories about theie dear old Dad. Also, the hacksaw repair strategy strikes again, a dutiful girlfriend suffers unneeded guilt, a yarn of a new Puzzler, and, the Chinese food delivery guy makes a cameo!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-06-09",
        seconds: 3318.700375,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-06-16.mp3",
        filename: "car_talk_2007-06-16.mp3",
        title: "#0724: June 16, 2007",
        description:
            "This week on Car Talk, we meet the self-proclimaed \"Dr. Granola\", who's looking for any way to avoid opening his wallet to fix the AC in his Lincoln. Also, a wife complains that her husband's making her feel like Job on their road trips, and in search of the perfect wine tour-bus--but, if you do enough wine touring, does the bus really matter?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-06-16",
        seconds: 3320.946875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-06-23.mp3",
        filename: "car_talk_2007-06-23.mp3",
        title: "#0725: June 23, 2007",
        description:
            "This week on Car Talk, our humble additions to the Pope's 10 Commandments for motorists. Also, a search for wayward jelly beans, why a fluid change may be best left for after Thanksgiving, and the Wheel of Misfortune gets frozen out.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-06-23",
        seconds: 3310.602375,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-06-30.mp3",
        filename: "car_talk_2007-06-30.mp3",
        title: "#0726: June 30, 2007",
        description:
            "Tom and Ray answer personal questions from listeners. Were the brothers ever wedgie victims? And whos' behind the trademark Car Talk snort? Also, mechanics joyriding in Lance's Lumina, the pitfalls of not cleaning off your wiper blades, a new puzzler and lots more.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-06-30",
        seconds: 3217.946,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-07-07.mp3",
        filename: "car_talk_2007-07-07.mp3",
        title: "#0727: July 07, 2007",
        description:
            "Are car salesmen unfairly stereotyped? Tom and Ray tackle this and other weighty questions, such as: What's that sulphur smell? How can Katherine make up for rear ending her boss's car? Is 12 years too late to bring your car in for a recall? All this and more on this week's Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-07-07",
        seconds: 3320.293875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-07-14.mp3",
        filename: "car_talk_2007-07-14.mp3",
        title: "#0728: July 14, 2007",
        description:
            "This week on Car Talk: Are older brothers really smarter? Not according to younger brother Ray. And we hear about strangled cats, diamond mines and the dog who ate a Lexus.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-07-14",
        seconds: 3311.621125,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-07-21.mp3",
        filename: "car_talk_2007-07-21.mp3",
        title: "#0729: July 21, 2007",
        description:
            "A classic show from our archives, featuring one of our all-time favorite calls: Christy and her Dad. Did she destroy his Citation 15 years ago? Also, A Taurus renders Viagra unnecessary in Silver Spring, and how many rocks equal a Mother in Law?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-07-21",
        seconds: 3317.681625,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-07-28.mp3",
        filename: "car_talk_2007-07-28.mp3",
        title: "#0730: July 28, 2007",
        description:
            "This week's show features one of our all-time classic calls, from Dave in Bemidji, Minnesota. Find out how a barbecue grill helped save his Cavalier. Also, some shocking truths about lying, what every student really needs this year, and, why you shouldn't trust a stuck glove compartment door to Helmut.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-07-28",
        seconds: 3319.04,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-08-04.mp3",
        filename: "car_talk_2007-08-04.mp3",
        title: "#0731: August 4, 2007",
        description:
            "This week's classic show features one of our all-time great wacko callers: Dinesh, whose Summer vacation involves a stroll across Death Valley. Also, a classic listener tale of good intentions gone awry at the gym at the hands of Tanya the Trainer. And, when's it safe for a guy to let a woman see his inner slob? All that and more!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-08-04",
        seconds: 3308.6955,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-08-11.mp3",
        filename: "car_talk_2007-08-11.mp3",
        title: "#0732: August 11, 2007",
        description:
            "Can a remote control really work better when it's pointed the wrong way? Also, the secrets to a happy marriage, a 20,000 mile weekend for a VW, yet another lesson why you should never listen to your brother, and an unfortunate end for a bird clock.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-08-11",
        seconds: 3315.670125,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-08-18.mp3",
        filename: "car_talk_2007-08-18.mp3",
        title: "#0733: August 18, 2007",
        description:
            "A Mom wonders why her Student Driver daughter can't relax behind the wheel, but, doesn't get the answer she was hoping for. Also, when not to play \"Little Miss Sunshine\" in real life.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-08-18",
        seconds: 3308.591,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-08-25.mp3",
        filename: "car_talk_2007-08-25.mp3",
        title: "#0734: August 25, 2007",
        description:
            "On this week's encore show, alarming news about a mechanic's best friend. Also, why the male psyche is so fragile when it comes to fixing cars. And, \"Car Talk: The Next Generation\", as the guys look outside the studio for help.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-08-25",
        seconds: 3308.094625,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-09-01.mp3",
        filename: "car_talk_2007-09-01.mp3",
        title: "#0735: September 1, 2007",
        description:
            "The new owner of an old truck considers the ramifications of changing its name--and gender. Also, what NOT to say to your wife, and a decal made just for Tommy.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-09-01",
        seconds: 3309.217875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-09-08.mp3",
        filename: "car_talk_2007-09-08.mp3",
        title: "#0736: September 8, 2007",
        description:
            "Ther auto add-on market hits a new high--in uselessnes. Also, a case of unintinded seat-warmer activation, and Stump the Chumps.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-09-08",
        seconds: 3309.453,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-09-15.mp3",
        filename: "car_talk_2007-09-15.mp3",
        title: "#0737: September 15, 2007",
        description:
            "Listeners weigh in on the great car naming debate. Also, a wild ride down Mount Saint Helens, and the return of the Puzzler.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-09-15",
        seconds: 3312.16975,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-09-22.mp3",
        filename: "car_talk_2007-09-22.mp3",
        title: "#0738: September 22, 2007",
        description:
            "A 4-Runner of many noises causes a sibling dispute. Find out if peace reign at Car Talk Plaza. Also, the need for men to do stupid things, and the Puzzler returns to Horsetown.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-09-22",
        seconds: 3313.711,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-09-24.mp3",
        filename: "car_talk_2007-09-24.mp3",
        title: "#0738: September 22, 2007 (corrected)",
        description:
            "A Toyota of many noises causes a sibling dispute. Find out if peace reign at Car Talk Plaza. Also, the need for men to do stupid things, and the Puzzler returns to Horsetown.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-09-24",
        seconds: 3313.711,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-09-29.mp3",
        filename: "car_talk_2007-09-29.mp3",
        title: "#0739: September 29, 2007",
        description:
            "Tom and Ray save a family road trip from disaster, in an unexpected way. Also, repair by Dixie cup, and how not to hurt Grandma's feelings.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-09-29",
        seconds: 3308.355875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-10-09.mp3",
        filename: "car_talk_2007-10-09.mp3",
        title: "#0740: October 6, 2007",
        description:
            'Two clowns try to help a third, as IRS agent/Shriner Clown "Looney" asks Tom and Ray how to double-clutch his \'29 Ford. Also, a new Puzzler, and a recurring case of 40,000 mile flatulence.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-10-06",
        seconds: 3327.921625,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-10-13.mp3",
        filename: "car_talk_2007-10-13.mp3",
        title: "#0741: October 13, 2007",
        description:
            "A guilt-wracked sister asks Tom and Ray to help her fess up to her brother about his beloved truck. Also, a new Mini with a small problem--it occasionally stops moving, who owns the center console, and a retired meatman arms himself with a spray can--can any good come of that?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-10-13",
        seconds: 3320.50275,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-10-20.mp3",
        filename: "car_talk_2007-10-20.mp3",
        title: "#0742: October 20, 2007",
        description:
            "The owner/resident of a Chevy van asks for help with a stalling problem, and winds up in the middle of an on-air repair project. Also, the joy of whacking your shifter, and would you like your brakes on hangers, and with or without starch?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-10-20",
        seconds: 3315.5395,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-10-27.mp3",
        filename: "car_talk_2007-10-27.mp3",
        title: "#0743: October 27, 2007",
        description:
            "A classic Car Talk listener conundrum takes on new significance. Also, a Novena for Nolina at the altar of Barsleak? And, Grandma's Olds threatens a marriage. Plus, a new Puzzler and Stump the Chumps.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-10-27",
        seconds: 3322.070125,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-11-03.mp3",
        filename: "car_talk_2007-11-03.mp3",
        title: "#0744: November 3, 2007",
        description:
            'A post-jumpstart electrical breakdown puts a strain on a friendship--can Tom and Ray restore harmony? Also, a 30-year obsession with tire pressure gets closure, we hope. And, has an "old-fashioned Russian" uncovered the great Oil Change Conspiracy?',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-11-03",
        seconds: 3324.786875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-11-10.mp3",
        filename: "car_talk_2007-11-10.mp3",
        title: "#0745: November 10, 2007",
        description:
            "A retired soldier enters marital Basic Training, and fhis beloved truck has failed inspection. Can Tom and Ray help him find a new ride? Also, meatloaf a la manifold, and Car Talk ruins an otherwise perfect vacation. Plus, a new Puzzler, and lots more.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-11-10",
        seconds: 3313.057875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-11-17.mp3",
        filename: "car_talk_2007-11-17.mp3",
        title: "#0746: November 17, 2007",
        description:
            "Necessity is the mother of invention? Two 8-year olds develop an anti-wedgie deense system. Also, the correct way to use your wallet to diagnose a scary noise, the optimal speed for good gas mileage, and a concrete way to keep your teenage driver from hauling around her entire high school class?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-11-17",
        seconds: 3325.648875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-11-24.mp3",
        filename: "car_talk_2007-11-24.mp3",
        title: "#0747: November 24, 2007",
        description:
            "A cautionary tale for frustrated shade tree mechanics--be sure to choose the right caliber. Also, Stump the Chumps ponders, when is a thunk not a thunk? A weekend mountain getaway goes awry, and windshield wipers gone wild!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-11-24",
        seconds: 3317.76,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-12-01.mp3",
        filename: "car_talk_2007-12-01.mp3",
        title: "#0748: December 1, 2007",
        description:
            "A recent Puzzler breaks the all-time record for bogosity. Also, The Washington Post tries to stump us, Tom and Ray recommend AGAINST a duct tape fix, and a Ford F-150 goes for a very slow midnight ride.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-12-01",
        seconds: 3313.266875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-12-08.mp3",
        filename: "car_talk_2007-12-08.mp3",
        title: "#0749: December 8, 2007",
        description:
            "A listener finds the man of her dreams in a car that's a nightmare. Also, what to do when all you have left is your gas tank, we debunk the Key Hokey-Pokey, and the Chinese food delivery guy makes a cameo appearance.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-12-08",
        seconds: 3323.324,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-12-15.mp3",
        filename: "car_talk_2007-12-15.mp3",
        title: "#0750: December 15, 2007",
        description:
            "What's a Suzuki owner to do when Jesus seems to make an appearance on her rear windshield? Also, the plural car model Puzzler retuens--again, an Eclipse gets hot and bothered at Burger King, and what's the fastest way to heat a chilly car?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-12-15",
        seconds: 3320.26775,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-12-22.mp3",
        filename: "car_talk_2007-12-22.mp3",
        title: "#0751: December 22, 2007",
        description:
            "What's an 82 year old woman to do when her 18 year old car is taking on more water than the Titanic? Tom and Ray have a solution--open her son's wallet for a new set of wheels. Also, a new use for a seatbelt and a really bad way to clean a windshield.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-12-22",
        seconds: 3323.715875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2007-12-29.mp3",
        filename: "car_talk_2007-12-29.mp3",
        title: "#0752: December 29, 2007",
        description:
            "Tom and Ray answer personal questions from listeners, including, \"Why don't you look like you sound?\" Also, a guy thinks his T-Bird is making him stupid, and what do you do with a truck that you look great sitting in, except when it's on fire?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2007,
        date: "2007-12-29",
        seconds: 3320.0065,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
];
