/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://media.adonix.org/car_talk_2008-01-05.mp3",
        filename: "car_talk_2008-01-05.mp3",
        title: "#0801: January 5, 2008",
        description:
            "A new Mom of floats a really bad idea for keeping the kids entertained--putting a heap in the backyard. Also, the fate of a marrage may rest on whether Topm and Ray can diagnose a starting problem, and what's a guy to do when his rental car bursts into flames?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-01-05",
        seconds: 3218.288798,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-01-16.mp3",
        filename: "car_talk_2008-01-16.mp3",
        title: "#0802: January 12, 2008",
        description:
            'What fun is a vintage car if your kids have to get out and push you up hills? The owner of a \'57 Morris Minor wonders if he can cram a few more horses under the hood. Also, is a 40,000 dollar Audi really not "car wash ready"? And, the usual assortment of odd noises, wacko remedies, and wheels on the verge of falling off.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-01-12",
        seconds: 3263.016259,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-01-19.mp3",
        filename: "car_talk_2008-01-19.mp3",
        title: "#0803: January 19, 2008",
        description:
            "A new Mom seeks help keeping her baby warm in her car, and gets a lot more advice than she asked for. Also, a Honda that should stay away from farm animals, a Dodge Caravan key acquires mysterious powers, and a Ford Falcon owner tries to say farewell.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-01-19",
        seconds: 3285.138756,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-01-26.mp3",
        filename: "car_talk_2008-01-26.mp3",
        title: "#0804: January 26, 2008",
        description:
            "A Winter dilemma shared by many--why do you get a shock when you touch your car after driving? Also, a solution to another Winter scourge--frozen door locks. Plus, a couple of vintage VW owners headed to Craig's List, and when NOT to change your oil.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-01-26",
        seconds: 3282.134625,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-02-02.mp3",
        filename: "car_talk_2008-02-02.mp3",
        title: "#0805: February 2, 2008",
        description:
            "On Stump the Chumps, find out of Tom and Ray successfully decoded one of the most baffling noises to ever confront them. Also, is a car a bad subsitute for a crib? Do Minis eat clutches for lunch? And, just when you think you've seen all kinds of distracted driving, have we got a story for you!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-02-02",
        seconds: 3271.6335,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-02-09.mp3",
        filename: "car_talk_2008-02-09.mp3",
        title: "#0806: February 9, 2008",
        description:
            'Ray recalls one of his all-time favorite customers, the legendary "Heavy Duty". Also, has a beloved CRX turned into a chick repellant for single guy Glenn? Why is a Massachusetts town in red alert over a mlost Saab key? And, does a Passat get to share in a family\'s Alaskan adventure?',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-02-09",
        seconds: 3273.432721,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-02-16.mp3",
        filename: "car_talk_2008-02-16.mp3",
        title: "#0807: February 16, 2008",
        description:
            'A long-distance relationship is put to the test by one half\'s inability to drive. Also, if your hear takes you to Alaska, can your Maxivan follow? And,a re the words, "Yes, dear" the secret to a happy marriage?',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-02-16",
        seconds: 3267.990499,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-02-23.mp3",
        filename: "car_talk_2008-02-23.mp3",
        title: "#0807: February 23, 2008",
        description:
            "The great Lost Saab Key crisis in Norfolk, MA has a happy ending, on Stump the Chumps. Also, Dad and son bond over wacking the bejeebers out of a Civic CV Joint, a Forester owner ponders life without 5th gear, and, if you're searching for a time machine, look no further!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-02-23",
        seconds: 3268.446735,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-03-01.mp3",
        filename: "car_talk_2008-03-01.mp3",
        title: "#0809: March 1, 2008",
        description:
            "A Volvo owner is vexed by a noise she can't hear, a Mom and her 14 year old son argue over what's ailing her Kia, and the adventure of a lifetime: going 300 miles to pick up your new Suzuki? Also, the Washington Post helps answer the question: How do you know if you're a loser (aside from listening to Car Talk)?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-03-01",
        seconds: 3273.875714,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-03-08.mp3",
        filename: "car_talk_2008-03-08.mp3",
        title: "#0810: March 8, 2008",
        description:
            "A new Mom faces a driver's door that won't open, and a passenger door that won't close. Her response? A bungee cord and a good laugh. Find out if Tom and Ray can do any better. Also, a faulty gas cap brings out the guys' inner 6th graders, a plow truck channels Popeye, and why one woman has turned her daily commute into a deluxe tour of New Haven.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-03-08",
        seconds: 3276.493673,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-03-15.mp3",
        filename: "car_talk_2008-03-15.mp3",
        title: "#0811: March 15, 2008",
        description:
            "A musician searches for a creative (cheap) fix to a noisy exhaust. Also, the Wisdom of Homer, a very expensive clogged drain, and on Stump the Chumps--Ray stands alone. Will he have the last laugh?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-03-15",
        seconds: 3261.311497,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-03-22.mp3",
        filename: "car_talk_2008-03-22.mp3",
        title: "#0812: March 22, 2008",
        description:
            "Dad's dream car becomes his daughter's nightmare. Can Tom and Ray help her find her way out of a luxury car she's not ready for? Also, we meet the most unlikely resident of Twin Falls, Idaho; a Volvo sounds a tornado warning, and can you trust your brother, even if he's a mechanic?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-03-22",
        seconds: 3259.840159,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-03-29.mp3",
        filename: "car_talk_2008-03-29.mp3",
        title: "#0813: March 29, 2008",
        description:
            "A soccer Mom develops an obsession with a potential new ride. Also, how the Tom Magliozzi Principle can guide a cross-country drive in a 1938 Dodge, a Dad shares his dream of handing down a '92 Subaru--in 2019, and Ray's son has a terrific birthday--at someone else's expense.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-03-29",
        seconds: 3258.703265,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-04-05.mp3",
        filename: "car_talk_2008-04-05.mp3",
        title: "#0814: April 5, 2008",
        description:
            "A husband raises the stakes in a marital dispute over an over-populated key ring. Also, an '02 Nissan with almost 600,000 miles gets clogged, a Volvo owner enjoys life without a muffler, and is the Autobahn really the place to break in a new BMW? Pluse, new hope for ugly guys! Within reason, of course.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-04-05",
        seconds: 3263.105737,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-04-12.mp3",
        filename: "car_talk_2008-04-12.mp3",
        title: "#0815: April 12, 2008",
        description:
            'An encore show featuring stories about one of Tom and Ray\'s oldest (and loudest) friends. Also, a lesson in windhshield wiper fluid dynamics that violates most, if not all, laws of physics; another way to drive your wife crazy; And, the introduction of a new high-level auto-technical term: "Shmutz on the Clutch". (Note: includes the phrase" chicken asses")',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-04-12",
        seconds: 3262.157574,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-04-20.mp3",
        filename: "car_talk_2008-04-20.mp3",
        title: "#0816: April 19, 2008",
        description:
            "How a long flight to Iceland, and an overdose of lutefisk helped create a new addition to the Car Talk lexicon. Also, the new owner of a Ford pick-up discovers a bonus gas tank he may be better off using for hamburgers, a new Dad wonders why his wife won't let him take baby for a ride in his Jag, and a Cabrio owner wonders why her shoulder's all wet.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-04-19",
        seconds: 3278.126077,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-04-26.mp3",
        filename: "car_talk_2008-04-26.mp3",
        title: "#0817: April 26, 2008",
        description:
            "Ray's inadvertent hijacking of Grammy's birthday cake (She Show #0813) opens the auto-confessional door. If you've ever cooked a friend's car, here's an opportunity to make amends. ?lso, a Kia owner cooks her own car, and we hear the evidence. And, does drafting to save gas cost the draftee anything?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-04-26",
        seconds: 3270.399229,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-05-03.mp3",
        filename: "car_talk_2008-05-03.mp3",
        title: "#0818: May 3, 2008",
        description:
            'An innocent Porsche begins rolling towards a cliff--backwards and uphill. Is there an explanation aside from the fact it\'s in the aptly named town of "Radium Springs" ? Also, "foreign accent syndrome" takes on a new dimension, when not to use "belt dressing", and two callers get homework assignments.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-05-03",
        seconds: 3271.315669,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-05-10.mp3",
        filename: "car_talk_2008-05-10.mp3",
        title: "#0819: May 10, 2008",
        description:
            "A restitution offer is received--but, is it accepted? Also, can selective blinker use ruin an otherwise perfect relationship, and, how not to make friends with your neighbor.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-05-10",
        seconds: 3267.707211,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-05-17.mp3",
        filename: "car_talk_2008-05-17.mp3",
        title: "#0820: May 17, 2008",
        description:
            "A huband plans to convert his wife's minivan to hydrogen power--she looks to Tom and Ray to talk some sense into him. Bad idea. Also, one car fire our hosts didn't cause, the sound of a transmission kapuit-ing, and one man finds his soulmate--a '62 Austin.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-05-17",
        seconds: 3271.685079,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-05-24.mp3",
        filename: "car_talk_2008-05-24.mp3",
        title: "#0821: May 24, 2008",
        description:
            "A boyfriend's surprise car wash gets him in hot water. Also, a friendly family debate over--what's the most damaging kind of car crash. Plus, a backfire has a woman eyeing her husband differently, and how do you fix your carburetor when you don't have one?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-05-24",
        seconds: 3263.574104,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-05-31.mp3",
        filename: "car_talk_2008-05-31.mp3",
        title: "#0822: May 31, 2008",
        description:
            "Tom and Ray Magliozzi of Car Talk answer callers questions about their cars from sticky brakes and faulty starters, to marital disputes and an ethical puzzler.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-05-31",
        seconds: 3259.667891,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-06-07.mp3",
        filename: "car_talk_2008-06-07.mp3",
        title: "#0823: June 7, 2008",
        description:
            '83-year old Lillian gets a fishy-sounding diagnosis on her Lincoln, and turns to Tom and Ray for guidance. They decide to play "60 Minutes", and go right to the source. Also, our on-call Physicist explains how the guys got their heads up their keisters on head-on collisions, a new Puzzler, and lots more.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-06-07",
        seconds: 3188.486054,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-06-14.mp3",
        filename: "car_talk_2008-06-14.mp3",
        title: "#0824: June 14, 2008",
        description:
            "A \"foreign body\" finds its way itno a Land Rover's differential. Fortunately, it's inanimate. Also, advice to mechanics: don't tell a customer complaining about noisy brakes that the problem is hormonal. And, a Dad gives his daughter useful automotive advice that could land them both in jail.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-06-14",
        seconds: 3200.172177,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-06-21.mp3",
        filename: "car_talk_2008-06-21.mp3",
        title: "#0825: June 21, 2008",
        description:
            "A frustrated VW owner plans a less-than fond farewell to her Beetle. Also, the victim of sibling-induced timing chain obsession seeks guidance, Scooby Doo appears in a PT Cruiser, and would you share your wedding vows with a '61 Corvair Greenbrier?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-06-21",
        seconds: 3193.040522,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-06-28.mp3",
        filename: "car_talk_2008-06-28.mp3",
        title: "#0826: June 28, 2008",
        description:
            "Tom and Ray's thoughts on the passing of comedian and longtime Car Talk Plaza hero, George Carlin. Also, would you pay 700 bucks just to get some really bad news? Plus, a joyride IN a warehouse jeopardizes a Suzuki Swift, and straight outta the Witness Protection program in Twin Falls, our pal Dino returns for Stump the Chumps.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-06-28",
        seconds: 3234.884626,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-07-05.mp3",
        filename: "car_talk_2008-07-05.mp3",
        title: "#0827: July 5, 2008",
        description:
            "A lesson in how NOT to let off steam after a marital tiff. Also, two women's worst nightmares: one is gonna be stuck with her '87 Camry a little longer, and the other has to face the fact that her husband was right about a clogged AC. And, why you should never trust a mechanic who keeps his boat parked near his garage.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-07-05",
        seconds: 3213.7539,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-07-12.mp3",
        filename: "car_talk_2008-07-12.mp3",
        title: "#0828: July 12, 2008",
        description:
            "Tommy reminisces about his days in the U.S. Army, especially the one in which he rose to the rank of Private. Also, why a Volvo owner may wish she'd married a gecko, and what happens when you give a 3-year old a golf ball and put him near your exhaust pipe? Yep, you guessed right.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-07-12",
        seconds: 3213.585941,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-07-19.mp3",
        filename: "car_talk_2008-07-19.mp3",
        title: "#0829: July 19, 2008",
        description:
            "An all-time classic Shaggy Dog story--literally. Also, Ray's misadventure on the exercise bike; a wife searches for a low-decibel strategy to keep her husband from driving off the road; a Buick that drinks oil faster than its owner can drink beer; and, we meet the Chuck Yeager of CV Joints?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-07-19",
        seconds: 3213.17907,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-07-26.mp3",
        filename: "car_talk_2008-07-26.mp3",
        title: "#0830: July 26, 2008",
        description:
            "A driver wonders if she should fess up for skipping a toll she didn't have Exact Change for, but, she may have no choice, thanks to Tom and Ray. Also, is all fair and love and grease? How to win a mechanic's heart. And, welcome to the world of electric brakes.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-07-26",
        seconds: 3195.211315,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-08-02.mp3",
        filename: "car_talk_2008-08-02.mp3",
        title: "#0831: August 2, 2008",
        description:
            "A listener thanks Tom and Ray for inadvertently solving a decades-old philosophical question. Also, the ever-annoying Melissa Peterson asks the guys to go to bat for her, and because some fool demanded it, The Car Talk Barbershop Quarter Minus Two makes its first and (we hope) last appearance.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-08-02",
        seconds: 3230.718073,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-08-10.mp3",
        filename: "car_talk_2008-08-10.mp3",
        title: "#0832: August 9, 2008",
        description:
            "When a relationship ends, who get to keep taking their car to the trusty mechanic? Also, why a smoking Jetta is just like a Magliozzi, a truck sends Tom and Ray into Duck and Cover mode, and more thoughts on the legendary Andy letter.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-08-09",
        seconds: 3190.848934,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-08-17.mp3",
        filename: "car_talk_2008-08-17.mp3",
        title: "#0833: August 16, 2008",
        description:
            "A messy divorce gets messier, and more fun. Also: A 13-year old kid plus a 14-year old Nissan equals one worried Mom. On Stump the Chumps, what made a Porsche turn semi-suicidal? Honda's brilliant anti-theft system? Maybe not.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-08-16",
        seconds: 3222.626689,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-08-23.mp3",
        filename: "car_talk_2008-08-23.mp3",
        title: "#0834: August 23, 2008",
        description:
            "10 years after the fact, Tom and Ray's pal the Pep learns the deep dark secret of what really happened to his beloved Lincoln. Also, how to tow a car you'd rather just get rid of, does a warning count if it's not in all capital letters, and what does Google really think Car Talk?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-08-23",
        seconds: 3224.98229,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-08-30.mp3",
        filename: "car_talk_2008-08-30.mp3",
        title: "#0835: August 30, 2008",
        description:
            "Tom and Ray wade into the waters of gas pump etiquette--when does one customer's last drop belong to the next person? Also, another lesson why you should never buy a car from your brother, a soldier and his Toyota prepare for duty, and the essence of Car Talk is captured by a single word.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-08-30",
        seconds: 3210.119116,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-09-06.mp3",
        filename: "car_talk_2008-09-06.mp3",
        title: "#0836: September 6, 2008",
        description:
            'Some new ways to refer to those who are "one taco short of a combination plate." Also, Stump the Chumps tests the relationship between Lillian and her mechanic Bobby; a husband wonders how to stop his wife from killing Fords, and a really dirty fuel flush scam.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-09-06",
        seconds: 3208.282109,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-09-13.mp3",
        filename: "car_talk_2008-09-13.mp3",
        title: "#0837: September 13, 2008",
        description:
            "A new Prius owner worries that he may have accidentally stepped into the wrong gender. Also, the worst place in the world to learn to drive a stick shift, a Civic develops agorophobia in its garage, and the Puzzler returns!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-09-13",
        seconds: 3214.17229,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-09-20.mp3",
        filename: "car_talk_2008-09-20.mp3",
        title: "#0838: September 20, 2008",
        description:
            'Tom and Ray referee a couple\'s auto-relational dispute over when to shift their Scion XA. Also, field research on the "getting the last drop" gas station strategy, a poorly steered answer on Stump the Chumps, and a new Puzzler from the "Dining with the Magliozzis" series.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-09-20",
        seconds: 3209.163923,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-09-27.mp3",
        filename: "car_talk_2008-09-27.mp3",
        title: "#0839: September 27, 2008",
        description:
            "He's a med student, good looking, and eats with minimal grunting--so why is Tara in California concerned about her new boyfriend? Could it be that his choice of domicile is an '86 VW van? Also, the fuel line (wallet) flush pitch appears at \"Fanny's Parasol Barbosh\", a Nissan owner suffers horn envy, and why would a clutch get depressed at 2,000 feet?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-09-27",
        seconds: 3210.323333,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-10-04.mp3",
        filename: "car_talk_2008-10-04.mp3",
        title: "#0840: October 4, 2008",
        description:
            'This week, the Magliozzi mantra for handling any customer service nightmare. Also, an update from the VW van dweller, a warning light that can hibernate for the Winter, and is there such a thing as a "diginifed" fart? Plus, a new Puzzler from the Travel and Leisure series, and lots more.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-10-04",
        seconds: 3198.749161,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-10-11.mp3",
        filename: "car_talk_2008-10-11.mp3",
        title: "#0841: October 11, 2008",
        description:
            'An abandoned Nissan takes residence on a Staten Island street--who better to advise on how to get rid of it than Tom and Ray? Also, why a Subaru should not be mistaken for a sardine can, how a Honda magically turned into a Town and Country, and can the words "perfectly safe" be used in the same sentence as "66 MG"?',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-10-11",
        seconds: 3231.482857,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-10-18.mp3",
        filename: "car_talk_2008-10-18.mp3",
        title: "#0842: October 18, 2008",
        description:
            "Winter draws closer, and the good folks of Tofte, Minnesota are in a dispute over how best to orient a snowplow. And, for some reason, they think Tom and Ray will be able to help. Also, a Chevy Venture groans, even in its off hours, a Highlander driver may need to bolt her kitchen seat in, and why is a Mini resembling a tossed salad?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-10-18",
        seconds: 3219.9022,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-10-25.mp3",
        filename: "car_talk_2008-10-25.mp3",
        title: "#0843: October 25, 2008",
        description:
            "A family tries to turn their Dad's beloved car into a shrine. Also, a Miata owner considers looking a gift Camry in the mouth, a Plymouth van starts percolating, and why shakes, rattles, and rolls are what Jeep ownership's all about. Plus, a new Puzzler, and some new models that may be coming to a Chryotors dealership near you.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-10-25",
        seconds: 3201.165669,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-11-01.mp3",
        filename: "car_talk_2008-11-01.mp3",
        title: "#0844: November 1, 2008",
        description:
            "Thieves break into a Ford Focus and make off with nothing but the owner's manual. Also, a would be shade-tree mechanic prepares to jump in, with his pals Stumpy and Meat by his side, a repair that could make a car stop running altogether, and Car Talk's new listener demographic--we\"re going ovine!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-11-01",
        seconds: 3229.028685,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-11-08.mp3",
        filename: "car_talk_2008-11-08.mp3",
        title: "#0845: November 8, 2008",
        description:
            "Is a gentle toot the best way to let a fellow driver know he's done a bad thing, or should you just let it be? Also, a tropical storm- plagued Miata, a Subaru with \"squirrels in the blender syndrome\", one listener's alarming parking fixation, and what do you do when your mechanic's hearing loss could mean your engine loss?",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-11-08",
        seconds: 3202.858458,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-11-15.mp3",
        filename: "car_talk_2008-11-15.mp3",
        title: "#0846: November 15, 2008",
        description:
            "This week on Car Talk, a list of rejected Doctoral Dissertation topics. And Tom and Ray help one caller find the cause of his engine fires. Watch out... it might bite you!",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-11-15",
        seconds: 3274.718798,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-11-22.mp3",
        filename: "car_talk_2008-11-22.mp3",
        title: "#0847: November 22, 2008",
        description:
            "Field research confirms a strange attraction to our show among...sheep! Also, two callers learn they're a day late a few quarts short of some expensive repairs, an unloved Beetle finds a new home while it's former owner finds lower blood pressure, and a clown car doesn't know when to stop running.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-11-22",
        seconds: 3207.241519,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-11-29.mp3",
        filename: "car_talk_2008-11-29.mp3",
        title: "#0848: November 29, 2008",
        description:
            "A college student pleads for help navigating the existential crisis known as Freshman year. Also, a truck owner tries to get her faithful pooch to ride somewhere other than the roof of her truck, and a not so mysterious coolant mystery. Encore episode.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-11-29",
        seconds: 3212.973197,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-12-06.mp3",
        filename: "car_talk_2008-12-06.mp3",
        title: "#0849: December 6, 2008",
        description:
            'After four years, a New Yorker tires of "creative" parallel parking, and wonders why his Jetta won\'t go in reverse. Also, a novice driver looks for the perfect car--small, cute, safe, reliable...and cheaper than 5,000 bucks. Can Tom and Ray stop laughing long enough to suggest anything? And, on Stump the Chumps, an unwelcome neighbor departs.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-12-06",
        seconds: 3228.989365,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-12-13.mp3",
        filename: "car_talk_2008-12-13.mp3",
        title: "#0850: December 13, 2008",
        description:
            "As if lousy advice wasn't bad enough, have we resorted to adding a \"Snort Track\" to the show? Also, a Doctor's Lincoln starts to remind him of his mother, why new tires can be shocking, and a guy who can even out-laugh us.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-12-13",
        seconds: 3203.376621,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-12-20.mp3",
        filename: "car_talk_2008-12-20.mp3",
        title: "#0851: December 20, 2008",
        description:
            "A 3-year old, a golfball, and the tailpipe of a Toyota Highlander come together, resulting a very nervous Dad. Also, Ray revives his proposal for a national gas tax, an all-mouse production of The Nutcracker Meets La Boheme takes the stare in an Element, and how NOT to keep a loved one from flying through the windshield.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-12-20",
        seconds: 3208.084875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2008-12-27.mp3",
        filename: "car_talk_2008-12-27.mp3",
        title: "#0852: December 27, 2008",
        description:
            "An eyewitness account of Ray's short-lived careers as a blizzard chaser. Also, a wet night in a dry wash turns everything inside out for a Camry, a possible case of spousal truck arson, and what could make Tommy say, \"He's doing pretty good, but for the wackiest reasons I've ever heard!\"",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2008,
        date: "2008-12-27",
        seconds: 3222.012177,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
];
