/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/122176082/npr_122176082.mp3",
        filename: "car_talk_2010-01-02.mp3",
        title: "Car Talk 1001 January 2, 2010",
        description:
            "The Car Talk forensics team tries to help Judith in Virginia figure out why her Mazda burst into flames while driving home for the holidays. Also, will speeding over speed bumps do more damage to a Jeep or the driver's teeth, a backyard clutch replacement gets challenged, and on Stump the Chumps, did someone actually follow Click and Clack's career counseling?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-01-02",
        seconds: 3226.588798,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/122565632/npr_122565632.mp3",
        filename: "car_talk_2010-01-14.mp3",
        title: "Car Talk 1002 January 9, 2010",
        description:
            "This week on Car Talk, a few choice lines from Rodney Dangerfield set the stage for Sam in Vermont, who's about to learn he has a cracked block--and his car isn't doing so hot, either. Also, a married Dad's need for speed hits a bump in the form of his wife, and Tom and Ray; a Yukon owner tries to convince her Dad and her mechanic that her car really is making a strange noise; and a cardinal becomes overly fond of a Side-view mirror.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-01-09",
        seconds: 3232.008934,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/122653292/npr_122653292.mp3",
        filename: "car_talk_2010-01-16.mp3",
        title: "Car Talk 1003 January 16, 2010",
        description:
            "A teenager's birthday present for Dad turns the family BMW into a roach coach--literally. Also, on Stump the Chumps, a repair with a very different outcome than we'd imagined; a Golf tries to escape; a Mustang owner looks for a cheap (if not totally ethical) fix for a cracked roof; and, a new career for Tommy?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-01-16",
        seconds: 3221.809206,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/122900770/npr_122900770.mp3",
        filename: "car_talk_2010-01-23.mp3",
        title: "Car Talk 1004 January 23, 2010",
        description:
            "A Winter driving tip: don't leave your Mini parked in a slush puddle, unless you want ti find it encased in ice. Also, a simple timing belt repair turns into a scavenger hunt inside the engine of a '96 Civic; an unfortunate oyster shucking incident somehow leads to a new grinding noise in an '01 Escort; and, is a '91 Cougar asking for a bale of hay?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-01-23",
        seconds: 3233.744286,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/123162608/npr_123162608.mp3",
        filename: "car_talk_2010-01-30.mp3",
        title: "Car Talk 1005 January 30, 2010",
        description:
            "A used car salesman chooses an opportune moment to become a consumer advocate. Also, a pregnancy induced impulse buy turns into a very large and unreliable gas guzzler the one family member can't even fit in. Plus, how not to fix a vacuum leak if you value your eyebrows, and Tommy gets hit with a flash of brilliance--or idiocy. You decide.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-01-30",
        seconds: 3229.545782,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/123445167/npr_123445167.mp3",
        filename: "car_talk_2010-02-06.mp3",
        title: "Car Talk 1006 February 6, 2010",
        description:
            "A Volvo owner's heater problem becomes more acute, due to her dog's flatulence problem. Also, the new owner of a Crown Vic needs help de-copifying his car, a Mom wonders if a blowtorch is the best way to remove a piece of tree bark her son stuck in the driver's door lock, a new word for Subaru drivers, and the number one reason mechanics love Saab owners--they never blink!",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-02-06",
        seconds: 3222.595261,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/123692572/npr_123692572.mp3",
        filename: "car_talk_2010-02-13.mp3",
        title: "Car Talk 1007 February 13, 2010",
        description:
            "Did Tom and Ray help dislodge a Mini from a frozen puddle? We find out, as Katie from Boulder returns for Stump the Chumps. Also, a Jeep makes what is most likely the most embarrassing car noise possible, a Chevy owner needs to run red lights to avoid cold air, a couple gets into a heated debate over warming up cars, and how a toothbrush helped start a Mercedes.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-02-13",
        seconds: 3228.347347,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/123926026/npr_123926026.mp3",
        filename: "car_talk_2010-02-20.mp3",
        title: "Car Talk 1008 February 20, 2010",
        description:
            "We hear from our most astute critics--a class of 8th Graders. Also, a \"bogging out\" Accord bums out Dad's wallet, a Physics Professor lives on the edge of timing belt disaster, a truck won't stop starting, and on Stump the Chumps, the Good Neighbor policy gets a big test.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-02-20",
        seconds: 3228.858912,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/124155186/npr_124155186.mp3",
        filename: "car_talk_2010-02-27.mp3",
        title: "Car Talk 1009 February 27, 2010",
        description:
            "Familial crises abound, from a daughter leaving Mom's Ford Explorer left running overnight, to a husband unable to wash his wife's Nissan without rendering it unable to start the next day, and a marital disagreement over who owns a freshly shoveled parking space. Also, door locks that don't know when to quit, and a Puzzler from the chicken soup department.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-02-27",
        seconds: 3212.373764,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/124398975/npr_124398975.mp3",
        filename: "car_talk_2010-03-06.mp3",
        title: "Car Talk 1010 March 6, 2010",
        description:
            'How to choose between two mid-life crisis heaps, and keep your wife from knowing about it. Also, an English teacher\'s plan to treat his students to a recreation of "On the Road" prompts Ray to recall dear old Uncle Dodo; black tape over a Check Engine light fails to solve a fuel problem; a team of janitors take up shop under the floor of a Grand Cherokee; and an offer too good for Tommy to refuse?',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-03-06",
        seconds: 3197.040499,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/124655241/npr_124655241.mp3",
        filename: "car_talk_2010-03-13.mp3",
        title: "Car Talk 1011 March 13, 2010",
        description:
            "Ed in PA needs help choosing an engine for the airplane he's building in his garage. Do Tom and Ray have enough liability insurance to give him an answer? Also, guilt-racked Cindy worries that she killed her engine driving in a post-carbon monoxide poisoning haze, Sarah in Boston would like her car to be less hospitable to thieves, and less of a target for delivery trucks, and is a trip to the Giggle Hut as healthy as a trip to the gym?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-03-13",
        seconds: 3216.479524,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/124962171/npr_124962171.mp3",
        filename: "car_talk_2010-03-20.mp3",
        title: "Car Talk 1012 March 20, 2010",
        description:
            "Teresa in Yakima, WA needs help drying her hair during her morning commute. Also, for Adam in Oregon, the price for ignoring a balky transmission and blinking Check Engine light is a few thousand dollars, and ridicule in front of a national audience. Also, Stratus owner Ravi's love is tested by a pending engine rebuild, and Jane in Alabama's not crying over spilled milk, but she is pretty bummed about spilled crem in her husband's BMW.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-03-20",
        seconds: 3214.594717,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/125259859/npr_125259859.mp3",
        filename: "car_talk_2010-03-27.mp3",
        title: "Car Talk 1013 March 27, 2010",
        description:
            "We prepare for baseball season with a few choice quotes from Yogi Berra. Then, we prepare two callers for visits with their loan officers, or the local junkyard. Also, one woman tries to decide which bit of Car Talk wisdom is less lousy, a simple oil change turns into the Worst Day Ever, and is a Honda Civic trying to discourage its owner from moving it from Santa Barbara, CA to Our Fair State?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-03-27",
        seconds: 3218.158526,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/125539515/npr_125539515.mp3",
        filename: "car_talk_2010-04-03.mp3",
        title: "Car Talk 1014 April 3, 2010",
        description:
            'Tom poses the question listeners have been asking for decades--"What are we doing here, anyway?" Happily, Ray is on hand to provide an answer. Also, what do a blower motor in Utah and a spark plug in Connecticut have in common? They may both be making unexpected appearances. And, can an odometer really be off by a factor of 10, or does Ruth in Virginia need to have a loooonggg talk with her teenage son.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-04-03",
        seconds: 3221.054989,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/125817277/npr_125817277.mp3",
        filename: "car_talk_2010-04-10.mp3",
        title: "Car Talk 1015 April 10, 2010",
        description:
            "Tom and Ray whistle their way through a Mexican graveyard, noting s a few interesting inscriptions along the way. Also, another lesson in why not to ignore your Oil Warning light, how a clerical collar could help compensate for overly aggressive braking, and how do you replace an irreplaceable car?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-04-10",
        seconds: 3228.944535,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/126074298/npr_126074298.mp3",
        filename: "car_talk_2010-04-17.mp3",
        title: "Car Talk 1016 April 17, 2010",
        description:
            "Ray misses a Car Talk staff retreat, but Tom finds a way to make him feel like he was there. Also, is knitting near an airbag a good idea, how to get in trouble with your mother in law in one easy step, can a non-English speaking tennis pro change the timing belt on a Volvo, and does a mid-life crisis car lose its curative pawers if you worry about its roof?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-04-17",
        seconds: 3217.602063,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/126247415/npr_126247415.mp3",
        filename: "car_talk_2010-04-24.mp3",
        title: "Car Talk 1017 April 24, 2010",
        description:
            "Do twin brothers working in the same garage have the same auto-diagnostic skills? As one unfortunate caller learns, probably not. Also, is a $10,000 Camaro repair worth doing, if it means also budgeting for a divorce? And, a prank is delivered via Post-It, and on Stump the chumps, was mild mannered Teresa really being trailed by Black Op helicopters?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-04-24",
        seconds: 3226.958277,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/126441671/npr_126441671.mp3",
        filename: "car_talk_2010-05-01.mp3",
        title: "Car Talk 1018 May 1, 2010",
        description:
            "Courtesy of the Washington Post, a new word that helps explain Tom and Ray's eternal unpenetrability. Also, a marital dispute over patience vs. persistence, Tommy's automotive soul mate reveals herself, and a lesson for shade tree mechanics: unplugging does not equal diagnosing!",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-05-01",
        seconds: 3214.683764,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/126637199/npr_126637199.mp3",
        filename: "car_talk_2010-05-08.mp3",
        title: "Car Talk 1019 May 8, 2010",
        description:
            "Sarah in New Jersey suspects her kids of conducting a peeing contest on her Villager while she was out of town. Find out if the Car Talk Olfactory Forensics Unit can get the kids off the hook. Meanwhile, Ronnie in Florida thinks her husband's full of hot air for suggesting they'll flambe their tuchuses in a black car, Barry in Michigan thinks his Mercedes should be too fast for bugs, and did you hear the one about the parrot and the magician?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-05-08",
        seconds: 3221.970862,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/126853228/npr_126853228.mp3",
        filename: "car_talk_2010-05-15.mp3",
        title: "Car Talk 1020 May 15, 2010",
        description:
            'Our favorite van-dwelling couple, Tara and Curtis, need help resolving a naming dispute over their forthcoming child. Also, proof you really can\'t trust a used-car salesman, even (or especially) if he\'s your brother, a son tries to find the line between "good son" and "cheapskate", and a Subaru gives its life to save a neighborhood.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-05-15",
        seconds: 3211.990499,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/127058532/npr_127058532.mp3",
        filename: "car_talk_2010-05-22.mp3",
        title: "Car Talk 1021 May 22, 2010",
        description:
            "Does it bode ill for a marriage's long-term success if the happy couple can't agree on whose car to use to leave the church? Also, the Rental Car Fugitive ponders a confession, a bird researcher seeks an automotive fix for a broken hot water heater, and will $20 buy de-dentification for a Taurus?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-05-22",
        seconds: 3235.48873,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/127262019/npr_127262019.mp3",
        filename: "car_talk_2010-05-29.mp3",
        title: "Car Talk 1022 May 29, 2010",
        description:
            "Did Tom and Ray succeed in keeping Heidi's husband away from the timing belt on her Volvo? Also, A Ford Escort owner wonders if his hang-glider is killing his car's suspension, a Hyundai Sonata doesn't want to leave the gas station, mud-bogging takes its toll on an F-350's steering, and one caller shares a fond childhood memory in hopes of finding out whether his Dad was a complete wacko.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-05-29",
        seconds: 3237.113107,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/127501035/npr_127501035.mp3",
        filename: "car_talk_2010-06-05.mp3",
        title: "Car Talk 1023 June 5, 2010",
        description:
            "A Car Talk-style salute to the late Puzzler Master Martin Gardner. Meanwhile, a leaky moon roof becomes a good test of a relationship, as does a Chevy Malibu's passenger seat relocated to the dining room table. Also, the horrible truth about a blast of body odor that only occurs on left turns, and a valuable lesson--before you drive your car from North Carolina to Alaska, learn how to drive it!",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-06-05",
        seconds: 3218.523084,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/127798835/npr_127798835.mp3",
        filename: "car_talk_2010-06-12.mp3",
        title: "Car Talk 1024 June 12, 2010",
        description:
            "Ray offers a mea culpa on a recent Puzzler, with a little technical help from Tommy. Then it's off to New Mexico, where Ramey's got crickets under the hood, and to South Dakota, where David's got birds leaving calling card on his truck. Also, how do you tell a know-it-all friend she's rife with bogosity, and why one truck might ride better with a piano on its roof.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-06-12",
        seconds: 3227.231315,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/127954327/npr_127954327.mp3",
        filename: "car_talk_2010-06-19.mp3",
        title: "Car Talk 1025 June 19, 2010",
        description:
            'Anne in Texas learns not to park her Mazda near a stable at lunch time. Also, an Olds Cutlass owner is advised to go "all additive"; an Audi owner may want to consider adding a third foot in lieu of repairs; a mechanic promises eternal engine life with a tachometer; and a marriage counselor sends her client to the wrong guy--Tommy!',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-06-19",
        seconds: 3199.71254,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/128132480/npr_128132480.mp3",
        filename: "car_talk_2010-06-26.mp3",
        title: "Car Talk 1026 June 26, 2010",
        description:
            "Tom and Ray triage an epidemic of men behaving badly, including one husband who scratched his wife's car, and then told her it was her fault. Also, further evidence that our Producer Dougie Berman is a bad influence, a budding bassist gets to choose between a Ford Freestyle and pair of Clark Wallabees, and a graduation gift that will keep on giving--waves of nausea. And, the Puzzler comes to w wordy season finale.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-06-26",
        seconds: 3227.568254,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/128289368/npr_128289368.mp3",
        filename: "car_talk_2010-07-03.mp3",
        title: "Car Talk 1027 July 3, 2010",
        description:
            "Should Mary in Minnesota tell prospective buyers of her Accord that it likely needs a new water pump? Can two mechanics handle this ethical dilemma, or will outside intervention be needed? Also, Male Answer Syndrome comes to mountain driving, a convertible owner develops a ballet worthy of Balanchine to get his top up and down, and on Stump the Chumps, did Tom and Ray correctly diagnose a truck's non-mother in law related shimmy?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-07-03",
        seconds: 3230.175306,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/128434414/npr_128434414.mp3",
        filename: "car_talk_2010-07-10.mp3",
        title: "Car Talk 1028 July 10, 2010",
        description:
            "Male solidarity goes down for the count in a marital dispute over parking brake methodology. Also, Nissan owner Scott tries to start his truck and save himself from helpful neighbor Fat Tony and his big bucket o' tools; Heather in New York turns into a hostile witness; and, on Stump the Chumps, did Tom and Ray help Howard get his mattress to Hunga Dunga?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-07-10",
        seconds: 3212.445986,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/128590709/npr_128590709.mp3",
        filename: "car_talk_2010-07-17.mp3",
        title: "Car Talk #1029: The Pep's Lincoln",
        description:
            "Tom and Ray's pal learns the horrible truth about what happened to his Lincoln on a snowy night. Also, mechanics pass up a chance to save a life and get a boat payment, a minivan owner tries to sex up his ride, and does a spark plug warning not to regap count if it's not in all capital letters?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-07-17",
        seconds: 3217.65059,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/128743681/npr_128743681.mp3",
        filename: "car_talk_2010-07-24.mp3",
        title: "Car Talk #1030: The New Delhi Catessens",
        description:
            "We kick off with a few international sports team names that never caught on, for some reason. Also, critters are chewing on Devon's Jeep, but the solution may be as close as her baby's diaper; a husband learns the cost of making his wife drive a mini-van while he tools around in a Lexus, and a well worn Car Talk answer makes a return appearance.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-07-24",
        seconds: 3219.031927,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/128897849/npr_128897849.mp3",
        filename: "car_talk_2010-07-31.mp3",
        title: "Car Talk #1031: Bugsy's Letters From Camp",
        description:
            "Childhood writings by our Technical Advisor John Bugsy Lawlor offer a glimpse of the man he'd become, and give our hosts the chance to laugh--a lot. Also, is wanting to start your car without whacking the fuel pump asking too much? Or, wanting your door to close without the use of rope? And, a Creative Writing class exercise shows a very deep failure to communicate.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-07-31",
        seconds: 3224.442358,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129051732/npr_129051732.mp3",
        filename: "car_talk_2010-08-07.mp3",
        title: "Car Talk #1032: Practical Jokes",
        description:
            "A few cruel (and funny) practical jokes submitted by our listeners. Also, what a failing clutch master cylinder has in common with Ray's dental work, an impatient Boston driver seeks a 2-horn solution to rush hour, and on Stump the Chumps we find out if Sarah's minivan was indeed the site of a peeing contest in her absence.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-08-07",
        seconds: 3208.754036,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129201238/npr_129201238.mp3",
        filename: "car_talk_2010-08-14.mp3",
        title: "Car Talk #1033: A Huge Bag of Crab",
        description:
            "A gift keeps on giving--an awful stench, after Annette from Alaska leaves a bag of king crabs in her Mercedes overnight. Also, after decades of sleepless nights, tow truck driver Franks tries to find out what made a car explode on the freeway; a bride-to-be discovers a toilet brush may be her best weapon in a driving dispute with her fiance; and, Ray's new $1,000,000 idea--undercover salesmen!",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-08-14",
        seconds: 3222.444762,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129347900/npr_129347900.mp3",
        filename: "car_talk_2010-08-21.mp3",
        title: "Car Talk #1034: He's Nothin' to Me",
        description:
            "Vern from Ohio wonders if he really destroyed his wife's sister's husband's minivan, and, whether it matters, since he's not related to the guy? Also, a close call at Car Talk Plaza reaffirms the value of goofing off; an expectant Mini owner worries about past encounters with shifters; and some ways for Tommy to get out of trouble next time he likens his wife to a truck.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-08-21",
        seconds: 3188.634127,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129497455/npr_129497455.mp3",
        filename: "car_talk_2010-08-28.mp3",
        title: "Car Talk #1035: The Roulette Wheel of Misfortune",
        description:
            "A new diagnostic aid enters the Car Talk studio, but isn't enough to prevent Tom and Ray from recommending a can of mace, a garter snake, and an empty swimming pool as solutions to assorted problems. Also, on Stump the Chumps, accidental diesel user Mary Beth reports on the state of her gas tank, her warranty, and her bank account!",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-08-28",
        seconds: 3228.995578,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129652865/npr_129652865.mp3",
        filename: "car_talk_2010-09-04.mp3",
        title: "Car Talk #1036: The Lovelorn Mechanic",
        description:
            "How do you break your mechanics' heart without him taking out his angst on your car? Also, Tom and Ray try to adjudicate disputes over car colors and frog avoidance; a Ford engine may be getting too powerful for its transmission; and, what better way to begin--and end--a relationship than by rear-ending your new boyfriend?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-09-04",
        seconds: 3221.521202,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129799297/npr_129799297.mp3",
        filename: "car_talk_2010-09-11.mp3",
        title: "Car Talk #1037: Leapin' Lizards!",
        description:
            "A gecko hitches a ride, and takes up residence in a Lexus. Also, two lessons in what not to do with a borrowed car: get it stuck in 4-Wheel drive and drop a pen cap into the gas tank; Plus, a Kia experiences symptoms of eating too many burritos; the Puzzler returns from Summer vacation; and, is being right worth having a stinky, sweaty boyfriend?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-09-11",
        seconds: 3225.980045,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/129959661/npr_129959661.mp3",
        filename: "car_talk_2010-09-18.mp3",
        title: "Car Talk #1038: Coke Vs Dr Pepper",
        description:
            'Is Coke "it" when it comes to dissolving battery corrosion, or can Dr. Pepper fill in? And why would either one work? Also, a used Jetta evokes a pancake breakfast, while a Camry\'s got a coffee grinder under the hood. Plus, a beleaguered wife seeks help getting rid of the heaps her husband is making her drive, and on Stump the Chumps, did Tom and Ray get a car to stop playing Beat the Clock?',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-09-18",
        seconds: 3205.592562,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/130125226/npr_130125226.mp3",
        filename: "car_talk_2010-09-25.mp3",
        title: "Car Talk #1039: Extreme Dashboard Makeover",
        description:
            "Jame in Georgia seeks a quick and cheap way to fix the cracks in his dashboard. Tom and Ray's suggestions start with driveway sealant, and go downhill from there. Also, an ethical dilemma in the carpool lane; the heavy duty clutch claims another victim; a squealing Supra comes between brother and sister; and on Stump the Chumps, did Tom and ray's advice put an end to a husband's weasliness?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-09-25",
        seconds: 3219.206599,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/130293064/npr_130293064.mp3",
        filename: "car_talk_2010-10-02.mp3",
        title: "Car Talk #1040: The Dr Pepper Experiment",
        description:
            "Car Talk's chemist-on-call offers a (somewhat) definitive answer to the question of whether Dr. Pepper can remove battery corrosion as well as Coca Cola can. Also, a second marriage may be the best solution to a twitching side-view mirror problem; a Subaru owner wonders if hill-hold is flammable; and, everything you need to know about rescuing a car from a quarry.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-10-02",
        seconds: 3231.217188,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/130494795/npr_130494795.mp3",
        filename: "car_talk_2010-10-11.mp3",
        title: "Car Talk #1041: Pre-Disastered Truck For Sale",
        description:
            "Does a Chevy Blazer owner need to divulge that the truck he's selling was struck by lightning? Could that news make it more attractive to a buyer? Also, how many near-misses and moving violations does a driver need to be classified as \"Stinko\"; a student tries to get one more year out of an '84 Prelude; and, how do you stop a self-starting Suburban?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-10-11",
        seconds: 3221.114286,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/130615187/npr_130615187.mp3",
        filename: "car_talk_2010-10-16.mp3",
        title: "Car Talk #1042: Fire Sale",
        description:
            "A $1600 dream goes up in flames--literally, as a Chrysler catches fire just before going up for sale. What's the blue book value on a somewhat charred LHS? Also, why parolees around St. Louis may be having an easier time giving their officer the slip; and a Subaru gets much ruder, thanks to a prank.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-10-16",
        seconds: 3218.285125,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/130776915/npr_130776915.mp3",
        filename: "car_talk_2010-10-23.mp3",
        title: "Car Talk #1043: The Forgetful Dealer",
        description:
            "If a car dealer sells a van, but doesn't ask for any money, does he get to keep his plaid pants? Also, why would you put gas that's not good enough for a camp stove into your car? Meanwhile, a Dodge Colt owner faces two choices: visit a junkyard, or buy a bungee cord; and on Stump the Chumps, did Tom and Ray help Murray get his VW dealer to stop busting his chops over a warranty claim?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-10-23",
        seconds: 3222.208685,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/130941420/npr_130941420.mp3",
        filename: "car_talk_2010-10-30.mp3",
        title: "Car Talk #1044: The Mysterious Man in White",
        description:
            "Tom and Ray try to unravel a mystery involving a dead Camry, a remote mountain top, and a mysterious stranger who uttered, \"Just start the car.\" Also, what's the going price for a friend who set your car on fire while trying to fix it? Plus, a Jeep with a flatulence problem; a Lincoln's brake problem prompts some thoughts on Tommy's wardrobe; and, can over-revving an engine cook s catalytic converter?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-10-30",
        seconds: 3224.384943,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/131125946/npr_131125946.mp3",
        filename: "car_talk_2010-11-06.mp3",
        title: "Car Talk #1045: Pi Over Two Dopes",
        description:
            'A trucker with a busted gas gauge needs a formula to measure how full his tank is. Can two MIT grads come to his rescue? Also, a Honda Accord smells of burnt toast; why "oil replenishment" is like vacuuming your living room with no bag in the cleaner; and, Tommy goes on the rampage against--Gomer Pyle?!!!',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-11-06",
        seconds: 3212.327982,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/131298015/npr_131298015.mp3",
        filename: "car_talk_2010-11-13.mp3",
        title: "Car Talk #1046: Math Geeks to the Rescue!",
        description:
            "Tom, Ray, and a few thousand devoted Car Talk math geeks figure out how to measure a cylindrical gas tank. Also, a Jeep comes out of the shop with more problems than when it went in; how to politely ask your neighbor to stop poisoning you; can a 350-pound carpool passenger throw a Corolla out of alignment; and, how do you sell a used car whose biggest attribute is its flashing fire chief light?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-11-13",
        seconds: 3194.366984,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/131471650/npr_131471650.mp3",
        filename: "car_talk_2010-11-20.mp3",
        title: "Car Talk #1047: Let Sleeping Camrys Lie",
        description:
            "A bad case of auto-marital guilt has Alethea in Texas reaching for her hot glue gun to keep her husband's hubcaps on. Also, Amy's husband refers to his '92 Pathfinder as \"the Giving Tree.\" She calls it a piece of junk. Will Tom and Ray give her the ammunition to send it to the crusher? And, do 300,000 miles and bald tires equal a good divorce settlement?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-11-20",
        seconds: 3180.348594,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/131630277/npr_131630277.mp3",
        filename: "car_talk_2010-11-27.mp3",
        title: "Car Talk #1048: Throw Your Keys Down the Drain",
        description:
            "Here's a new complaint: \"My car is getting too miles per gallon\". This week, Ephraim ponders his Audi's new thriftiness, and wonders if it's just trying to congratulate him on his engagement. Also, holiday family gatherings mean family arguments. Specifically, is it possible to park in a way that makes it impossible to get out the way you went in; and, will a wreath on the hood cook an engine? And, if a Brigadier General wants to drive 140 mph, who are we to stop him?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-11-27",
        seconds: 3220.01,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/131812523/npr_131812523.mp3",
        filename: "car_talk_2010-12-04.mp3",
        title: "Car Talk #1049: Your Car Fell Off the Lift. LOL!",
        description:
            'We kick off with a few auto-confessionals, including a case study in how not to deliver bad news to a customer. Also, a stuck rotor leads to fire and a bump on the forehead for Dave in Pennsylvania; Sarah in Illinois wants to use her Saturn to haul her worldly belongings to Arizona; and how do you tell your father in law, "Thanks, but I really don\'t want that Bricklin"?',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-12-04",
        seconds: 3232.665578,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/131994570/npr_131994570.mp3",
        filename: "car_talk_2010-12-11.mp3",
        title: "Car Talk #1050: Tommy's Knee and Jack's MGB",
        description:
            "Truth is funnier than Tommy's memory as we find out what really happened on an ill-fated ski trip 40 years ago. Meanwhile, the truth might mean divorce for Jack in Houston when his wife find out he didn't get rid of his 1970 MGB. Also, cold weather makes a Subaru stink, and a Chrysler cry, and on Stump the Chumps, did Adam Beat the Clock on fixing his girlfriend's Jeep?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-12-11",
        seconds: 3210.76576,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/132166787/npr_132166787.mp3",
        filename: "car_talk_2010-12-18.mp3",
        title: "Car Talk #1051: Gifts For Guys",
        description:
            'Some last-minute holiday gift giving suggestions for the man in your life. Also, some holiday wishes from our callers--a de-doggified Odyssey for Braden; Elizabeth wants car windows she can see out of; and Adrienne wants her husband to stop barreling down the mountain with the cruise control on! And, we try to answer the question, "Am I my sister\'s ticket payer"?',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-12-18",
        seconds: 3236.118957,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/132329672/npr_132329672.mp3",
        filename: "car_talk_2010-12-25.mp3",
        title: "Car Talk #1052: Tidings of Boat Payments",
        description:
            "It's a Merry Christmas for mechanics across the land--at least, if Tom and Ray's diagnoses of serious (and expensive) problems are on target. Also, the guys recall some horrendous Christmas gifts, and an excellent prank; a wife wonders how to cure her husband of windshield replacement denial syndrome; and one caller wants to know where to get a \"This car braked down Mount Washington\" bumper sticker.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2010,
        date: "2010-12-25",
        seconds: 3211.463673,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
