/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/132624776/npr_132624776.mp3",
        filename: "car_talk_2011-01-03.mp3",
        title: "Car Talk #1101: Bicycling the Seven Seas",
        description:
            "January 3, 2011 • Eleanor is about to head off on a 6-month 'round the world trip by bicycle. She wants to know how to take care of her truck while she's gone, but Tom and Ray are more interested in how she plans to pedal across several large bodies of water. Also, an opera singer begins doing arias under a Honda Civic; a vintage T-Bird puts its owner to sleep; and meet the car that strikes fear into mechanics near and far.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-01-03",
        seconds: 3220.647324,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/132766222/npr_132766222.mp3",
        filename: "car_talk_2011-01-08.mp3",
        title: "Car Talk #1102: Hood Sag",
        description:
            "January 8, 2011 • A Honda owner is concerned because his Accord's hood seems a little low--literally. Can Tom and Ray diagnose the sagging hood without sending the bogosity meter into the red? Other areas of concern: Sandra fears for her engine's life after accidentally using diesel fuel, while Natalie fears for her own life after denting Dad's car while he's away. Also, to tip or not to tip, at the pump?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-01-08",
        seconds: 3216.729025,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/132962503/npr_132962503.mp3",
        filename: "car_talk_2011-01-15.mp3",
        title: "Car Talk #1103: The Superball Bumper",
        description:
            "January 15, 2011 • A new strategy for backing a car without reverse--go forward and bounce. Also, does one half a tank of gas last longer than the other, could a mis-applied parking brake destroy two trucks, and what would draw a swarm of bees to a '72 El Camino?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-01-15",
        seconds: 3209.528345,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/133143119/npr_133143119.mp3",
        filename: "car_talk_2011-01-22.mp3",
        title: "Car Talk #1104: Power to the People",
        description:
            "January 22, 2011 • It's the Candy Bar Wrapper Rebellion, as one Magliozzi frees herself from the shackles of a neat car. Also, a re-located airline pilot considers settling down in a VW Westphalia, with the mailing address \"Employee Parking Lot\"; on Stump the Chumps we find out if Scott got his Nissan to start, and survived Fat Tony and his big bucket o' tools; and if your Dad's a mechanic, but won't fix your heater, does it mean he doesn't love you?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-01-22",
        seconds: 3211.151769,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/133331849/npr_133331849.mp3",
        filename: "car_talk_2011-01-29.mp3",
        title: "#1105: The Flaming Winnebago",
        description:
            "January 29, 2011 • A family road trip in a Winnebago lands them on Smoky Bear's Most Wanted list, in the latest from our series of auto-confessionals. Also, a quick lesson in the giving of dope slaps; the truth about 8th Grade (at least, Tom and ray's version of it); and what do you tell prospective parents who'd rather drive a horse and buggy than a mini-van? \"Saddle up!\"",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-01-29",
        seconds: 3213.166122,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/133525949/npr_133525949.mp3",
        filename: "car_talk_2011-02-05.mp3",
        title: "Car Talk #1106: Beware the Anonymous Physicist",
        description:
            "February 5, 2011 • Ray tries to erase a recent Puzzler from the collective consciousness. Then, he and his his brother try to stimulate the economy by encouraging Shawn to buy a new car for his one-woman demolition derby wife, and Martha, who's a couple hundred dollars away from being able to take her key out of the ignition. And, a Sentra falls victim to sibling rivalry.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-02-05",
        seconds: 3219.172676,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/133747453/npr_133747453.mp3",
        filename: "car_talk_2011-02-14.mp3",
        title: "Car Talk #1107: Genius and Bogus Effluent",
        description:
            "February 14, 2011 • \"The Male Competence/Incompetence Syndrome\" - the key to understanding Tom and Ray's simultaneous brilliance and stupidity! Meanwhile, Bridget is concerned about the noise her Saturn is making, but she's downright terrified by the guys' efforts to imitate it. And Pam in Virginia has got a Volvo that's blowing more smoke than her husband. Also, Tom and Ray are called to account by Father Bryan, for naming his beloved Yugo the worst of the century.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-02-14",
        seconds: 3227.830522,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/133901061/npr_133901061.mp3",
        filename: "car_talk_2011-02-19.mp3",
        title: "Car Talk #1108: The Pocket Plow",
        description:
            "February 19, 2011 • Leanne in Connecticut dreams of fashioning her own mini-snowplow for her Subaru. Her husband thinks she's nuts, but Tom and Ray think she could be the next late-night infomercial superstar. Also, a Toyota comes home from the Philippines with a bang; a new alternator puts a spark in a marriage; and Tommy drives to the Dark Side.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-02-19",
        seconds: 3230.921678,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/134088767/npr_134088767.mp3",
        filename: "car_talk_2011-02-26.mp3",
        title: "Car Talk #1109: The Yugo in the Living Room",
        description:
            "February 26, 2011 • Another voice rises in defense of the much-maligned Yugo. After all, how many cars can you garage in your living room? Also, a Lexus develops a very sweet, and expensive smell, while Eau de Skunk has taken up permanent residence in a BMW. And, bad fatherly advice leads to a very chilly Winter in Maryland. All this, plus Stump the Chumps, and lots more.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-02-26",
        seconds: 3223.994875,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/134294214/npr_134294214.mp3",
        filename: "car_talk_2011-03-05.mp3",
        title: "Car Talk #1110: Another Dodge Dart!",
        description:
            "March 5, 2011 • What's the best spare part to bring along on an extended road trip in your '64 Dodge Dart? Aside from our Show Title, we mean. Also, a case study in you should drive now, jelly later; a noxious Saab prompts a game of \"Who farted\" between mother and son; and is it worth it to each a teenager how to drive a stick shift?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-03-05",
        seconds: 3224.456984,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/134492252/npr_134492252.mp3",
        filename: "car_talk_2011-03-12.mp3",
        title: "Car Talk #1111: The Lexus ATM",
        description:
            "March 12, 2011 • Eric in Arizona is finding 100 dollar bills under the seats in his recently purchased '06 Lexus. Is it a unique rebate program? Also, the Chicago Blizzard claims a Ford Escape as victim; a dog and a Chevy Trailblazer prove a bad match; and a gift car that comes with a headache.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-03-12",
        seconds: 3218.36932,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/134689806/npr_134689806.mp3",
        filename: "car_talk_2011-03-19.mp3",
        title: "Car Talk #1112: The Bowling Ball Incident",
        description:
            "March 19, 2011 • Driving over a bowling ball is bad for your car, but makes for a funny story, especially when it happens in front of a topless bar. Also, Kat in San Diego wonders why she goes through brakes faster than Tommy goes through ex-wives; a Volvo begins speaking Greek; and the first results from our pseudo-scientific survey on heated seats.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-03-19",
        seconds: 3186.676168,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/134862547/npr_134862547.mp3",
        filename: "car_talk_2011-03-25.mp3",
        title: "Car Talk #1113: Slugging Etiquette",
        description:
            "March 25, 2011 • When your daily commute depends on the kindness of strangers, are you allowed to give them a dope-slap? Also, Wendy in Vermont fears her struggles with her fiance's clutch will cause his Dad to think she's a ditch; Taurus owner Mike is torn between conflicting advice, and needs to know who's the genius and who's the wacko--happily, we have one of each to help him; and is there scientific evidence that one Magliozzi is smarter (or just less stupid) than the other?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-03-25",
        seconds: 3191.220023,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/135072239/npr_135072239.mp3",
        filename: "car_talk_2011-04-02.mp3",
        title: "Car Talk #1114: The Volvo Valhalla",
        description:
            "April 2, 2011 • Spring is here, and Jilinda's backyard is bursting with--busted Volvos. Can Tom and ray help her find a way to get her husband to stop collecting them? Also, a fluid mishap has George convinced that stepping on his brakes may turn on his wipers; a med student plans an ill-advised post-graduation road trip; and on Stump the Chumps, is Mary Gordon no longer suffering One Note-itis?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-04-02",
        seconds: 3217.558662,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/135272883/npr_135272883.mp3",
        filename: "car_talk_2011-04-09.mp3",
        title: "Car Talk #1115: Caller Intimidation",
        description:
            "April 9, 2011 • What do you do when callers won't give the \"right\" answers? Tom and Ray try a new tactic: badger them until they do. Also, a couple debates whether buying a used former rental means inheriting many drivers' bad habits; one MG owner may have to solve Tommy's problem before having his addressed; and, the most creative engine removal of all time.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-04-09",
        seconds: 3216.906349,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/135471806/npr_135471806.mp3",
        filename: "car_talk_2011-04-16.mp3",
        title: "Car Talk #1116: The Incurable Backseat Driver",
        description:
            "April 16, 2011 • Lani's husband's driving has improved, but her nagging hasn't. Is there a cure for her? Meanwhile, Marg wants to know why her husband's Mazda rolled into the backyard, and how she's gonna tell him about it when he gets home from sailing around the world; a couple debates the benefits of a car colonic; and, on Stump the Chumps, did Tom and Ray's semi-divine intervention help Father Patrick?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-04-16",
        seconds: 3196.109161,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/135662545/npr_135662545.mp3",
        filename: "car_talk_2011-04-23.mp3",
        title: "Car Talk #1117: Bird Doo Due Diligence",
        description:
            "April 23, 2011 • Lisa in Florida wonders whether her husband is full of (see Show Title), by telling her she needs to clean bird poop off her car every 24 hours. Also, spark plug wires try to escape a Sentra, while the keys refuse to exit a Maxima. And, can Hope sell her Chevy before she runs out of brain cells lost to a cracked exhaust manifold?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-04-23",
        seconds: 3209.050068,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/135872689/npr_135872689.mp3",
        filename: "car_talk_2011-04-30.mp3",
        title: "Car Talk #1118: You Say Kilometer",
        description:
            'April 30, 2011 • Penny in Oregon is a bit "stroppy" over the pronunciation of "kilometer." Her stress in nothing compared to fellow Oregonian Curtis, whose Vanagon is being stolen, one piece at a time. Also, Bob in Massachusetts tries to make the perfect birthday gift even more perfect by painting it pink; and a \'67 Plymouth Fury owner looks to increase his MPG from 13 to--13.5?',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-04-30",
        seconds: 3198.025011,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/136092498/npr_136092498.mp3",
        filename: "car_talk_2011-05-07.mp3",
        title: "Car Talk #1119: Shut Up, Hon",
        description:
            "May 7, 2011 • Gender equity comes to Car Talk Plaza this week, as male and female callers are both advised to respond to spousal auto-critiques with a polite, but firm, \"Shut up, Hon.\" Elsewhere, Stuart's Camry is making a scary metallic quacking sound; Bill is wondering if Radiator Stop Leak will work on his wooden hot tub; and Liz the Librarian is about to learn why she shouldn't make jack-rabbit starts. And, for Mother's Day, one Mom's tale of a teenager to be greatly admired--and feared.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-05-07",
        seconds: 3221.65415,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/136312419/npr_136312419.mp3",
        filename: "car_talk_2011-05-14.mp3",
        title: "Car Talk #1120: Tommy vs Muir Woods",
        description:
            "May 14, 2011 • Rashomon comes to Car Talk Plaza, as Tom and Ray offer vastly different recollections of a trip to Muir Woods. They may interrupt for a few moments to tell Colleen why her truck is melting air filters. Meanwhile, Dan in Oregon may find his faith tested by a coolant leak; John treated his Excort to a new clutch and got a new noise from it in return; and Jennifer needs help escaping her husband's new BFF's--the Miata Owners Club.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-05-14",
        seconds: 3221.39746,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/136530745/npr_136530745.mp3",
        filename: "car_talk_2011-05-21.mp3",
        title: "#1121: Pranks, Painting and Personal Problems",
        description:
            "May 21, 2011 • This week on Car Talk, we dive head first into the three automotive P's: pranks, painting and personal problems!",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-05-21",
        seconds: 3242.620567,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/136750478/npr_136750478.mp3",
        filename: "car_talk_2011-05-28.mp3",
        title: "#1122: Book This, Dad",
        description:
            "May 28, 2011 • Rebecca makes a bid for automotive independence, and gets an unwanted bonus: financial independence. Also, Ben learns a smoky lesson about his power steering stunt; Mary Beth wonders how to open her hood to repair the broken latch that's preventing her from opening the hood; and, have mice been singing their way into Dale's exhaust?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-05-28",
        seconds: 3231.097098,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/136957795/npr_136957795.mp3",
        filename: "car_talk_2011-06-04.mp3",
        title: "#1123: A Cavalcade of Cheapskates",
        description:
            "June 4, 2011 • This week, everyone wants to be a shade-tree mechanic. Andrew is wondering if a degree in Nuclear Engineering qualifies him to change the clutch on his Escort, while Susan's husband's chief qualification for fixing a falling headliner seems to be height. Also, what the best car for a cross-country road trip inspired by Thelma & Louise--without the killing? And, strange door behavior in a Land Cruiser prompts the age-old question, \"Doesn't anyone screen these calls?\"",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-06-04",
        seconds: 3216.911088,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/137127751/npr_137127751.mp3",
        filename: "car_talk_2011-06-11.mp3",
        title: "Car Talk #1124: The Chicken Mahal",
        description:
            "June 11, 2011 • This week on Car Talk, Jackson has built a McMansion for his wife's chickens, and now he needs to transport it across Vermont. His plan involves a Toyota Tacoma, a snowmobile trailer-- and one ginormous coop of unknown poundage. Are his fears of a catastrophic collapse justified? Will the chickens have to get out and push? Elsewhere, Chantel in California has decided to come clean about an incident that may have croaked Dad's Volvo a decade back. Can Tom and Ray can keep her in Dad's will? Also, a Prius turns into a gas geyser, a VW owner learns about the high cost of driving through a deep puddle, and, is Tommy's addition to the Miata universe enough to strip it of \"chick car\" status? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-06-11",
        seconds: 3217.395193,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/137269962/npr_137269962.mp3",
        filename: "car_talk_2011-06-18.mp3",
        title: "Car Talk #1125: Book This, Rebecca",
        description:
            "June 18, 2011 • This week on Car Talk, Dad gets equal time. Topher, whose daughter Rebecca rebelled against his strict record-keeping, checks in to explain the origins of his now-infamous little maintenance book, and whether Rebecca really is off the family payroll. Another follow-up comes from Car Talk's on-call chemist, Jim Davis, who's been in the lab trying to get Sprite to char a leather car seat. In new business, Cameron's got a starter that's been screeching for 8 months; Bill in Maine is hoping to get one working Probe out of the three in his driveway; and Episcopal priest Jep is wondering if he needs to grant absolution to the mechanic who may have messed up his timing belt job. And, from Germany, a fiery \"Hey guys, watch this!\" story. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-06-18",
        seconds: 3221.106757,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/137420613/npr_137420613.mp3",
        filename: "car_talk_2011-06-25.mp3",
        title: "#1126: The Engine and Wallet Shampoo",
        description:
            "June 25, 2011 • This week on Car Talk, Ryan went for an oil change, and got talked into an \"engine shampoo\" (no creme rinse, please)! Now, he's become a walking punchline among his friends, and he's wondering if his engine isn't the only thing that got taken to the cleaners. Elsewhere, Marina loves her Jeep, but after 250,000 miles, is it finally time to deep six it in Lake Erie? Alicia needs help fixing her Saab without having to go on a second date with her mechanic; and did the Car Talk podcast really help save a marriage? All this, and lots more, on this week's cleansing hour of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-06-25",
        seconds: 3236.454739,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/137579039/npr_137579039.mp3",
        filename: "car_talk_2011-07-02.mp3",
        title: "Car Talk #1127: You're Driving a Medicare Sled",
        description:
            "July 2, 2011 • This week on Car Talk, what happens when you a tell a woman her Sable is a Granny car? If you're Mac's wife, you co-opt his pickup truck and drive that instead! Now Mac is hoping Tom and Ray can help liberate his beloved Tacoma from her clutches. Elsewhere on the marital front, Amanda's all hot and bothered over her husband's refusal to turn on the air conditioning. Also, why Danielle's stuck windshield wipers are helping keep her car clean; a side-view mirror masher tries to blame the victim; and on Stump the Chumps, we find out if Jackson's bad idea for moving a chicken coop came home to roost. All this, plus the Puzzler Finale from the Prisoners in Hats series, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-07-02",
        seconds: 3213.015782,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/137731973/npr_137731973.mp3",
        filename: "car_talk_2011-07-09.mp3",
        title: "#1128: Double-Dog Daylight Savings",
        description:
            "July 9, 2011 • This week on Car Talk, Ray's quest for more \"usable\" sunshine leads him to a proposal both brilliant and wacko: Double-Dog Daylight Savings, probably not coming to a time zone near you. Then, Davis' squeaky Durango sparks another novel idea: if you don't know where a squeak is coming from, just dip the whole car in silicone spray. Elsewhere, Sarah's got an exploding rear windshield, Ben can't shift his Accord into Park, and Natalie's trying to convince her husband that spending lunch hour in his car listening to sports talk radio is a bad idea. Finally, Chris is looking for a suitable prank to get back at the guys who left a dead fish in his truck. Fortunately for Chris, our hosts might just have a few ideas. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-07-09",
        seconds: 3211.981701,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/138190496/npr_138190496.mp3",
        filename: "car_talk_2011-07-16.mp3",
        title: "#1129: The Non-Alcoholic Windshield",
        description:
            "July 16, 2011 • This week on Car Talk, Scott in Alaska is searching for a way to keep his windshield clean, and the local salmon population happy. You'd think a couple of MIT grads would know the perfect eco-friendly, wiper fluid solution, right? Well, maybe not so much. Meanwhile, Gregory's Chevy has a nasty habit of stalling when he parks facing uphill--which wouldn't be a big deal, except for the fact that he lives in San Francisco. Also, Cynthia's convinced that clean oil is improving her Acura's gas mileage, and has 100 bucks riding on Tom and Ray agreeing with her; Andy's got a pesky Check Engine light that's ignoring his best efforts to ignore it--and, why you never want to go to a movie with Ray. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-07-16",
        seconds: 3222.725624,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/138644124/npr_138644124.mp3",
        filename: "car_talk_2011-07-23.mp3",
        title: "#1130: Tickling the Electrons",
        description:
            "July 23, 2011 • This week on Car Talk, are you ready for some wacko theories? Dennis in California puts Tom and Ray to the test, pondering his friend's contention that the best way to charge a dead car battery is by turning on every accessory in sight. Is there anything to this notion of \"tickling the electrons\"? Elsewhere in Wackyland, Jenny is convinced that her Civic has a harder time starting when its gas tank's not full; Linda needs to retro-fit her ATV to make it a good Summer sled-dog training vehicle; and mechanic-turned-sculptor Coby learns what happens when you add a few extra tons to a half-ton pickup. All this, plus some choice Last Words, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-07-23",
        seconds: 3218.738707,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/138856969/npr_138856969.mp3",
        filename: "car_talk_2011-07-30.mp3",
        title: "#1131: Love and Rust Spots",
        description:
            "July 30, 2011 • This week's Car Talk kicks off with a cautionary tale of what not to say the first time your girlfriend tells you she loves you. Elsewhere in Relationship Land, Jackie's racking up huge chiropractor bills thanks to her boyfriend's starting method, and Lori's trying to learn how to drive the ancient trucks her boyfriend's taken to collecting. Also, a good dope slap gets an alternator to behave; shop rags become uninvited and unwelcome guests in Joel's transmission; and a wonderful evening of hood dancing takes its toll on a $200 Chevy Nova. All this, plus a used car ad sets a new high for truth in advertising, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-07-30",
        seconds: 3217.535215,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/139052257/npr_139052257.mp3",
        filename: "car_talk_2011-08-06.mp3",
        title: "#1132: Heard it Through the Grape-Nuts",
        description:
            "August 6, 2011 • We're all getting older, so as a public service, this week on Car Talk we update a few classic songs to reflect our demographic shift. For example, \"I get by with a little help from Depends.\" In matters automotive, Mickey's Nissan sounds like it's getting a wedgie whenever he turns on the AC, and a recent fender bender has Stephanie worried about passing an upcoming smog test. Also, Lisa's looking for help trying to convince her husband to rent an RV for a road trip to Graceland, and Doctor Rich's new cigar habit's given him both a stinky car-- and a nasty cough. And, what bad advice could leave Sally with a tombstone reading \"She died getting 95 miles per gallon\"? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-08-06",
        seconds: 3180.915034,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/139607416/npr_139607416.mp3",
        filename: "car_talk_2011-08-13.mp3",
        title: "#1133: The Nina Totenburger",
        description:
            "August 13, 2011 • This week on Car Talk, a million dollar idea from one of our listeners: an NPR-themed restaurant. The only problem is, the menu is a bit limited--to two items. In matters automotive, Renee in New York got two nasty surprises recently. Her Acura wouldn't start, and when she opened the hood, she was greeted by the leftovers from an engine picnic, including chicken bones, coldcuts, and a bag of Doritos. Meanwhile, Fran's got a brilliant idea for changing his oil and killing his engine at the same time, and Foreign Service Officer Joan is wondering how many trunks of spare car parts she needs to bring to her next assignment in Madagascar. Also, how to get revenge on a soon to be ex-husband who's planted a GPS unit in your car. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-08-13",
        seconds: 3221.654649,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/139819274/npr_139819274.mp3",
        filename: "car_talk_2011-08-20.mp3",
        title: "#1134: The Lexus Aquatic",
        description:
            "August 20, 2011 • This week on Car Talk, Dickie in Louisiana gets a big surprise when he takes the steering wheel off his girlfriend's Lexus-- and water comes gushing out the steering column. Dickie's hydraulic confrontation leads us to Car Talk mystery #1: Is it coming from above or below? (We're not talking about the water, we're talking about from which part of Ray's anatomy he's grabbing the answer.) Mystery #2 this week comes from the Northwest, where Bob is wondering just how much damage a sock can do when it gets sucked into the engine manifold. Also, Volvo introduces the remote dope slap, the Puzzler's work ethic is questioned, and on Stump the Chumps, we find out if a truck can be overpriced-- at $170. All that and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-08-20",
        seconds: 3225.605102,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/139996099/npr_139996099.mp3",
        filename: "car_talk_2011-08-27.mp3",
        title: "#1135: Marc Vs Goober",
        description:
            "August 27, 2011 • This week on Car Talk, Marc in New Hampshire learns what catastrophes await when you, A) buy a 100 dollar Peugeot, and B) pay a mechanic in advance. Can Tom and Ray help him get his car back? Or, can they at least stop laughing at him? Meanwhile, chemistry class is in session for John in Ohio, and today's lesson involves his van's radiator, and a certain co-host's dubious \"hungry water theory\". Elsewhere, Julia is worried that her Dad's obsession with putting a new engine in his Suburban may be causing marital strife; Carla's Accord is making a screech that's scaring her entire neighborhood; and Ariel wants to know how to prepare herself for her first trip to a new car dealer--maybe start with a suit of armor? All this, plus proof that Car Talk can aid physical fitness, and lots more,this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-08-27",
        seconds: 3210.36873,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/140170258/npr_140170258.mp3",
        filename: "car_talk_2011-09-03.mp3",
        title: "Don't Drive Like Tom: #1136",
        description:
            "September 3, 2011 • This week on Car Talk, we hear some listener rants about Tom's EZ Pass theory and why no one should ever take his advice! Plus, what's the best way to ask for directions? And Tom sheds light on why men are from GM, and women are from Ford, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-09-03",
        seconds: 3205.947324,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/140363606/npr_140363606.mp3",
        filename: "car_talk_2011-09-10.mp3",
        title: "#1137: Jeep Tipping",
        description:
            "September 10, 2011 • This week on Car Talk, the Big Book of Bad Ideas gets a new chapter. Ted wants to work on his 1947 Jeep by tipping it on its side-- yes, on its side--and relying on his three brothers to hold it place. Can Tom and Ray move Ted towards a less life-threatening approach? Meanwhile, Lynn in Colorado is concerned about her new Subaru's key heating feature; Russell in North Carolina is being serenaded by George Gershwin every time he turns on his air conditioning; and is \"sometimes they just need a good kick in the pants\" really the right answer to Steve's transmission mystery? Finally, a shout out to any bird poop terminal velocity experts in the audience--Tom and Ray could use your help! All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-09-10",
        seconds: 3197.950385,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/140561681/npr_140561681.mp3",
        filename: "car_talk_2011-09-17.mp3",
        title: "#1138: Cleanliness Is Next to Boat Payment",
        description:
            "September 17, 2011 • This week on Car Talk, does a clean car get better treatment from mechanics? Leif in Pennsylvania has been conducting field research, and has some expensive evidence that supports his theory. Elsewhere, Lancelot just got home from Burning Man with a souvenir he didn't ask for-- the alkali salt dust now in every pore of his Pathfinder. Also, Karilee's about to say, \"I do\", but needs help convincing her fiance to say, \"I will buy you a Volvo\"; Kurt's looking for a way to eek out a few more cool days from his dying air conditioner and, in honor of the Puzzler's return, we ponder the many definitions of bogosity. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-09-17",
        seconds: 3197.337438,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/140789757/npr_140789757.mp3",
        filename: "car_talk_2011-09-25.mp3",
        title: "#1139: Wake Up, Kevin!",
        description:
            "September 25, 2011 • This week, we proudly introduce a sure-fire cure for Car Talk-induced narcolepsy. Did we make the show more engaging and compelling? Sorry, we're not miracle workers. Meanwhile, in matters automotive, Mike is baffled by his Chevy's ability to suck a shirt in through it's exhaust, and even more baffled by Tom and Ray's attempts to explain it. Also, Tamara's wondering if it's time to bid farewell to her beloved Vanagon for something a bit less barbaric; Marc wants to know if late night TV really can improve his gas mileage; and on Stump the Chumps, did Tom and Ray correctly diagnose Becka's cough and sputter? All this, plus a new Puzzler from Fahrenheit Celsius series, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-09-25",
        seconds: 3205.982902,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/140980202/npr_140980202.mp3",
        filename: "car_talk_2011-10-01.mp3",
        title: "#1140: Latent Junkman Syndrome",
        description:
            "October 1, 2011 • This week on Car Talk, Joe's brother-in-law collects heaps. Unfortunately he deposits them in other people's yards-- like Joe's, for instance. Now Joe's got an '83 Civic sprouting weeds out of the headliner. Can Tom and Ray help Joe cure a bad case of Latent Junkman Syndrome? Meanwhile, Kristy's husband has developed a warm relationship with their mechanic, which is all well and good, except that said mechanic has charged them $600, and their Stanza still won't start. Also, a bad day gets worse for Matt in L.A., when his Volvo falls off a tow truck, and his insurance company tries to convince him it's actually not totaled. And, is the Supreme Court using Car Talk methodology? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-10-01",
        seconds: 3206.982585,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/141181170/npr_141181170.mp3",
        filename: "car_talk_2011-10-08.mp3",
        title: "#1141: The Pot-Mobile",
        description:
            "October 8, 2011 • This week on Car Talk, Stephen is riding high--unwittingly so. He got new engine mounts in his Mercury, and now the car reeks of marijuana. Did his mechanic leave a little bag under hood? Elsewhere, 11-year-old Hannah's Dad is having a jolly good time blowing his car horn at her. Is she seeking mechanical advice from Tom and Ray on, say, how to disconnect the horn? No, she wants a prank to get even with dear old Dad. Also, our Physicist on call weighs in on the great bird poop- cracked windshield debate; Ray reveals his love for Fiat's new arrival on our shores; and proof that listening to Car Talk is great training for a career... in Interior decorating. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-10-08",
        seconds: 3213.027528,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/141383761/npr_141383761.mp3",
        filename: "car_talk_2011-10-15.mp3",
        title: "#1142: Do Cars Have Souls?",
        description:
            "October 15, 2011 • This week on Car Talk, does a car have a soul? That's the auto-philosophical conundrum underpinning the engine transplant Jeff's Isuzu needs. And if a car does have a soul... where does it live, anyway? In the engine, the gas tank... or maybe the fuzzy dice? Meanwhile, Andy's Jeep overheated in the desert, and since he had no water, he used the only fluid he had on him to top off the radiator. Yep, that one. Which leads to his question for our hosts: just what are the corrosive effects of a pint of urine? Elsewhere, Mary's Camry is quacking, Diane's Thunderbird is fish-tailing, and Helena and her husband just picked up a '66 Rambler that's perfect-- except for the fact it can only go in reverse. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-10-15",
        seconds: 3213.286916,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/141620605/npr_141620605.mp3",
        filename: "car_talk_2011-10-22.mp3",
        title: "#1143: The Camry Collage",
        description:
            "October 22, 2011 • This week on Car Talk, Tac and her siblings are looking for a way to keep their dearly departed Dad's car in their memories, but out of their wallets. So before they bid farewell to his Camry, she's wondering what parts work best as keepsakes. Maybe a tire to hang on the wall? Elsewhere, Anne is longing to buy a vintage MG convertible, but her husband's insisting it come with one accessory--an English mechanic in the trunk. Also, our resident Chemist Jim Davis follows up on the hazards of urine in a radiator; the Men of Maple Corner try to keep their parade car from bursting into flames; and can Chris' carburetor problems be solved by a run through the dishwasher? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-10-22",
        seconds: 3198.934943,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/141834652/npr_141834652.mp3",
        filename: "car_talk_2011-10-30.mp3",
        title: "#1144: Road Trip from Hell",
        description:
            "October 30, 2011 • This week on Car Talk, could anything possibly go wrong when you take a cross-country road trip with your beloved fiance and dear old mom? Well, meet Charity-- and let's just say that car trouble was the least of her problems! Then, it's off to Oregon, where Jackie is wondering if her bra can withstand the car wash. (Shrinkage, anyone?!) Meanwhile, Tami's neighbors are wondering if her Buick has gas... and we're not talking 93 octane, if you catch our drift. And in Minnesota, Peter wants to know how to lure a hamster out of his wife's Acura. Four-course meal, anyone? All that, plus a new puzzler from Ray's Ceiling Lights Series, on this week's electrifying hour of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-10-30",
        seconds: 3190.464172,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/142059543/npr_142059543.mp3",
        filename: "car_talk_2011-11-05.mp3",
        title: "#1145: The Day The Isuzu Stood Still",
        description:
            "November 5, 2011 • This week on Car Talk, science fiction comes to Keller, Texas, as Isuzus cease functioning when they come close to a mysterious FAA \"weather device.\" Is GORT up to his old tricks, or is the answer a bit more down to earth? Elsewhere, Kathleen and her husband escaped a scary rollover in their Subaru. But, what's truly frightening is that Kathleen's husband is still intent on driving it. Also, a Land Rover needs either a new transmission or two in the hat; a clutch job goes bad in New Jersey; and, a husband turns to science to explain why his wife shouldn't listen to Car Talk. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-11-05",
        seconds: 3194.637052,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/142279483/npr_142279483.mp3",
        filename: "car_talk_2011-11-13.mp3",
        title: "#1146: The Model A Prius",
        description:
            "November 13, 2011 • This week on Car Talk, Patrick in Alaska loves his Prius' gas mileage, but thinks the car could look cooler--say, if its engine was in the body of a Model A Ford. Is it a worthwhile project, or one destined for the Hall of Fame of Bad Ideas? Meanwhile, Nicole is wondering why her Dad's balking at her plan to take a road trip in a 2009 Subaru--especially since the old man recently drove across the country in a '37 Chevy. Elsewhere, Diana's looking for a car with just a few requirements: safety, reliability, good gas mileage, room for her to sleep, crappy looks, a microwave oven-- okay, strike that last item. Also, a braking strategy that's guaranteed to make nobody ride with you; a few really bad car slogans; and a new Puzzler from the African Rainforest series. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-11-13",
        seconds: 3202.505442,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/142548609/npr_142548609.mp3",
        filename: "car_talk_2011-11-19.mp3",
        title: "#1147: I Love You, So Please Shut Up",
        description:
            "November 19, 2011 • This week on Car Talk, Sonia's husband Barry may be taking his anti-distracted driving stance a little too far. He refuses to talk to Sonia while driving, even when they're in the car together. Other families in crisis: Anita needs a cure for sister-induced car sickness, and Monique's kids want to get her sister's old Miata running, after it's been sitting with a dead battery for the last 10 years. Also, Reverend Dave thinks unholy thoughts about his stuck key; Patrice can't get her VW Bus to start, even after pouring Coke on the battery; and on Stump the Chumps, we find out if Aron's car no longer sounds like Larry of the 3 Stooges snoring. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-11-19",
        seconds: 3217.013673,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/142805454/npr_142805454.mp3",
        filename: "car_talk_2011-11-26.mp3",
        title: "#1148: I've Turned Into My Mother",
        description:
            "November 26, 2011 • This week on Car Talk, is back-seat driving genetic? Apparently so for Liz in Massachusetts, who's picked up the nagging habit from her Mom. Making matters worse, Liz's husband's poor navigation skills make him a prime target. Can Tom and Ray break this cycle of rolled eyes and loud sighs? Elsewhere, Jay did a little backyard maintenance on his Honda and saw his gas mileage drop by 30 percent; Ivan's suffering from an epidemic of flat tires, accompanied by odd circular abrasions; and Alexandria's car doesn't like starting on warm days. Also, why Tommy is #1 on the Must Bite list among the dogs of Unadillia, New York. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-11-26",
        seconds: 3216.628798,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/143092266/npr_143092266.mp3",
        filename: "car_talk_2011-12-03.mp3",
        title: "#1149: Snotsicles, Oodjas, and Stupiphanies",
        description:
            "December 3, 2011 • This week, Car Talk kicks off with a few new words that may be coming to a dictionary near you. Then, they put one of those words right to work, with a series of brilliant stupiphanies: Jim in Florida learns why his next boat trip may leave him stranded in international waters; Liz in Missouri discovers that Porsche ownership comes with a monthly dose of sticker shock; and Jean finds out why her car may have violated just about every one of Newton's laws. Also, Rich needs help choosing the perfect $100 Demolition Derby car; and Will has a serious interior decorating concern: how do you mount a dashboard hula dancer so it doesn't become a projectile if the airbag deploys? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-12-03",
        seconds: 3206.006712,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/143506029/npr_143506029.mp3",
        filename: "car_talk_2011-12-10.mp3",
        title: "#1150: Blinker Transgressions",
        description:
            "December 10, 2011 • This week on Car Talk, Molly's boyfriend gets irate when other drivers fail to use their turn signals. But when Molly caught him committing his own blinker transgression, said boyfriend had a ready explanation, that may send the bogosity meter way into the red. Elsewhere, Terry in New Mexico has a long history of breaking in new cars and wives, both of which are being tested by his new Rav 4; Peter in Brooklyn's good deed went bad, after several gallons of post-Thanksgiving turkey oil spilled in the back of his Passat; and Jill in Wyoming is wondering why the local horses find her Jeep's hood so tasty. All this, plus a new Puzzler from the Road Trip series, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-12-10",
        seconds: 3220.030839,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/143894750/npr_143894750.mp3",
        filename: "car_talk_2011-12-17.mp3",
        title: "#1151: A New Pigmobile",
        description:
            "December 17, 2011 • This week on Car Talk, Susan leads a double life--Philosophy Professor by day, and animal rescuer by night. Unfortunately, she's come to realize her beloved Honda Civic can't handle the olfactory implications of her full range of clientele. Can Tom and Ray help her find the perfect Pig and Prof-mobile? Elsewhere, Jim's having dipstick removal issues; Dave's wife's friendliness is scaring the dickens out of him; and Samantha and her husband are having a raging debate over… how best to hang dry cleaning in a car? Really? And, on Stump the Chumps, we find out if the second carburetor was the charm for Chelsea. All this, plus an explosive tale from Ray's high school days, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-12-17",
        seconds: 3202.000045,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/144230219/npr_144230219.mp3",
        filename: "car_talk_2011-12-24.mp3",
        title: "#1152: Chinese Food Delivery",
        description:
            "December 24, 2011 • This week on Car Talk, Santa comes through big-time for Tom and Ray in their never ending quest to escape difficult callers. They're now the proud owners of the Get Off the Phone Excuse Machine, and it's likely to get an early test, thanks to Nancy and the Tupperware-like noise cooing from her Volvo. Elsewhere, desperate times call for wacko measures, as Jamie considers plugging a cracked head with oatmeal, Mark ponders giving his Suburban a full drive-train transplant into a new body, and Julie goes shopping for any car that can survive her husband's aversion to the emergency brake. And, Jan \"The Waver\" responds to her husband's concerns about her overly friendly driving style. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-12-24",
        seconds: 3235.517823,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/144523922/npr_144523922.mp3",
        filename: "car_talk_2011-12-31.mp3",
        title: "#1153: That Car Needs a Fin",
        description:
            "December 31, 2011 • This week on Car Talk, does a dorsal fin make a car less aerodynamic? That's Dan's question, after he decided his Tercel was lacking that important fishy feature. So, he sculpted one for the hood. Is such a problem even possible for a Tercel? Elsewhere, Mary's been driving her Mustang around with a trunk full of compost. Her husband says it's time to clean it out, but Mary thinks the ballast is worth a few mold spores. Also, Vanessa's Sunbird's making a classic rattle, Eddie's F-150 won't start, Megan's looking to get a new car and a new guy; and Stephan's about to learn there's a fine line between Genius and Wacko--and me may have just crossed it. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2011,
        date: "2011-12-31",
        seconds: 3225.919569,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
