/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://media.adonix.org/car_talk_2012-01-07.mp3",
        filename: "car_talk_2012-01-07.mp3",
        title: "#1201: 20 Miles Per Woodchip",
        description:
            "This week on Car Talk, Hans recalls fleeing from Germany during World War II in a car powered by woodchips, but he's never been able to figure out exactly how it worked. So who better than two car experts with MIT degrees to figure this out? Well, maybe anyone would be better in this case. Tom and Ray will likely do better helping David figure out how a three-pound bag of Hershey Kisses disappeared from his Civic overnight, and why his car now smells of melted chocolate. Elsewhere, Victoria's Mom needs to trade in her Corvette after surgery, so Victoria's wondering what car's right for a hip Mom with a new hip; Aaron's windshield wipers are stuck in a salute position; and, is Mary-Ellen wearing out her brakes parking in \"The Gulch\" every day? A box of doughnuts is riding on the answer, so this is serious business. All this and lots more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-01-07",
        seconds: 3222.93839,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-01-14.mp3",
        filename: "car_talk_2012-01-14.mp3",
        title: "#1202: Mud Chiggers in the Fuel Line",
        description:
            "This week on Car Talk, life in the Big Easy is proving to be anything but that for Betsy and her truck. Since relocating to New Orleans, her Toyota has taken to spewing gas all over the place. Her mechanic's first guess? Mud chiggers in the fuel line! Entomology also comes into play later on, as Ray uses an ant colony to help explain why Nancy's Nissan won't start in cold weather unless she turns the heater on first. Also, Rob has to replace a Camry door that won't open; Susanne's DIY thermostat repair created a host of other problems, without fixing the one she was trying to address; and Daniel and his wife are struggling over the question, \"Whose arm rest is this?\" All this, plus the truth about woodchip fired engines, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-01-14",
        seconds: 3219.733152,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-01-21.mp3",
        filename: "car_talk_2012-01-21.mp3",
        title: "#1203: Snakes in the Fusion",
        description:
            "This week on Car Talk, Josh let a boa constrictor get loose in his wife's Fusion. In the ensuing snake hunt, he removed just about every bit of the car's interior. Now, after putting it all back together, he's got a few pieces left over. Will a few missing parts make such a big difference? Elsewhere, Larry's got a minor problem with a sticky throttle, but may be in more trouble over his choice of an engagement ring; and, Deb's so worried about her Camry's jingling sound that she's waited a full year to tell anyone about it. Also, Molly's having a tough time teaching her daughter to drive after a garage mishap, but is Molly's daughter the problem or is Molly? And, it's a happy day for Tommy: The venerable Dodge Dart is back! All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-01-21",
        seconds: 3205.009751,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-01-28.mp3",
        filename: "car_talk_2012-01-28.mp3",
        title: "#1204: It's Snowing in My Car",
        description:
            "This week on Car Talk, Steve's cross-country road trip got a little more exciting when high winds began blowing open the driver's door on his Pathfinder. He's wondering if this is just a design quirk to make the car feel more outdoors-y, or if there's an actual problem--and can said problem be fixed with anything other than duct tape or rope? Elsewhere, Patricia loves her Rambler-- except for the calling card of black soot it leaves in every parking space; Jamie's suffering an epidemic of escaping spark plugs; and, after a \"low smoke\" at-home alternator replacement, Helen's oil light is flashing a little too much for comfort. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-01-28",
        seconds: 3214.501723,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-02-04.mp3",
        filename: "car_talk_2012-02-04.mp3",
        title: "#1205: Carla, Come Home",
        description:
            "This week on Car Talk, after 18 years in Homer, Alaska, Carla is ready to return to civilization. Her truck? Not so much. It can only climb hills in Reverse. Find out if Tom and Ray can stop laughing long enough to help Carla and her truck move forward. Elsewhere, Elizabeth's truck hasn't started for such a long time, her neighbors decorated it with Christmas lights. And the last time her mate tried to start it, he lit it on fire, so the long-term prognosis here may not be good. Also, Kathy's Stratus smells of burnt popcorn; Matt's Vanagon is leaking coolant from all four corners of the head gasket; and Wilbur hears his Dad scolding him from hundreds of miles away every time he tries to get frost off his windshield. All this plus an MG trick we urge you not to try at home, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-02-04",
        seconds: 3228.253673,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-02-11.mp3",
        filename: "car_talk_2012-02-11.mp3",
        title: "#1206: Help Me Blow Up an LTD",
        description:
            "This week on Car Talk, DIY filmmaker Seth is preparing to shoot a big scene: a car explosion in the front yard (of his neighbor's house, of course). Seth's hoping Tom and Ray can help minimize the risk of seeing his house go up in smithereens, and his eyebrows getting that old familiar \"Acme Dynamite\" look. Can our Chief Counsel Hugh Louis Dewey duct tape the guys' mouths before they wade in to litigious waters? Elsewhere, Michael's RAV 4 is whining in the cold weather even louder than Tommy usually does; Ray trips the Bogosity alarm by introducing the \"Connecting Rod Stretch Theory\" to explain an Explorer's knocking sound; and on Stump the Chumps, did Tom and Ray diagnose the \"amorous donkey\" noise in Joan's Honda? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-02-11",
        seconds: 3222.397415,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-02-18.mp3",
        filename: "car_talk_2012-02-18.mp3",
        title: "#1207: Washer Fluid Dynamics",
        description:
            "This week on Car Talk, cleanliness is next to impossible for Andrew, due to his Subaru's weak rear windshield washer spray. Unfortunately for Andrew, the only thing less productive than the spray may be Tom and Ray's explanation of the cause. Elsewhere, Kate discovered a long gray hair sticking out of her Civic, and is worried she may have a UFO-- that's an Unidentified Furry Object-- living in her exhaust; Joyce is wondering why her mellow, meditation-teaching husband turns into a mix of Mario Andretti and Tony Soprano when he gets behind the wheel; and 14-year-old Matthew is about to learn a valuable Magliozzi lesson about the benefits of doing a lousy job cleaning his parents' car. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-02-18",
        seconds: 3231.987483,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-02-25.mp3",
        filename: "car_talk_2012-02-25.mp3",
        title: "#1208: The Elvis Idle",
        description:
            "This week on Car Talk, The Elvis Idle meets the Mechanic's Shrug, as Tom and Ray try to diagnose a Nissan's intermittent stutter. Meanwhile, strange things are happening in Waccabuc, New York, where Sally heard a loud electrical charge and saw a flash of bright light while driving under a power line. Also, Brad's got a Hydrological and Meteorological crisis, with water appearing in his Civic's spare tire well; Jack's horn went from sounding like James Early Jones to Pee Wee Herman overnight; and Melissa's decision to use her Jeep's heater as a clothes dryer may have expensive consequences. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-02-25",
        seconds: 3196.474558,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-03-03.mp3",
        filename: "car_talk_2012-03-03.mp3",
        title: "#1209: Who Moved My Alamo",
        description:
            "This week on Car Talk, Ray reveals perhaps his best wacko consipracy theory of all time--the reolocation of the Alamo, and his own unsuccessful attempts to rectify the situation. This all takes place as Kelly from San Antonio waits to find out if her fiance's promiscuous use of a plug-in seat massager is responsible for her car's drop in gas mileage. Elsewhere, Marshall's Jeep is making a stnge clunking sound, akin to being hit from behind by a Nerfmobile; Debbie's clutch is whistling a tune laden with hints of boat payments to come; and on Stump the Chumps, we find out if Eddie in New Hampshire got his truck started. All this, plus a creative, if incredibly insincere wedding inviation, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-03-03",
        seconds: 3199.958866,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-03-10.mp3",
        filename: "car_talk_2012-03-10.mp3",
        title: "#1210: The Mothership Has Landed",
        description:
            "This week on Car Talk, we revisit a caller's unexplained electrifying vehicular event. Was it an atmospheric abnormality? A UFO? Beam 'em up, Scotty! Then it's warp speed to Georgia where Caroline has another curious conundrum: has a car alarm mysteriously installed itself on her Saturn? Elsewhere, Libby is looking for the perfect car to run away in, and Bob is in dire need of marriage advice. Could the turn signal hold the answer to marital bliss? All that, plus a new tantalizing puzzler from our Travel and Leisure series, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-03-10",
        seconds: 3201.998299,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-03-17.mp3",
        filename: "car_talk_2012-03-17.mp3",
        title: "#1211: Ashley Wants the Wheel",
        description:
            "This week on Car Talk, actress Ashley Judd learns one downside of marriage to a professional race-car driver--he insists on driving every time they're in the car together. You'd think the guy would want a day off, wouldn't you? Find out if Tom and Ray can keep this auto-marital dispute off the front page of the National Enquirer. Elsewhere, Andy's steering wheel is making a noise which he'd like to handle with WD-40, but might be better taken care of by singing a chorus of \"Chattanooga Choo Choo,\" and Tom in New Jersey would really like to blame a tow truck driver for his Honda's computer failure. Finally, Mary Rawson's friend has offered to fix her brakes for free, and perhaps get a date at the same time. Can she turn him down and still have a car that will stop? All this and lots more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-03-17",
        seconds: 3208.527551,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-03-24.mp3",
        filename: "car_talk_2012-03-24.mp3",
        title: "#1212: Catzilla's Great Adventure",
        description:
            "This week on Car Talk, after missing for two months, Jane's cat showed up at a house seven miles away, and across two major highways. Did Catzilla stow away during Jane's daily commute? Elsewhere, Sharon's Explorer is growling, and Gunther thinks a toilet is flushing under his Astrovan's dashboard. Also, Lori in Arizona threatens to make Male Answer Syndrome obsolete, with two words: \"Google it!\"; and, more than you ever wanted to know about Senior Prom planning in Yosemite National Park. All this, plus a new Puzzler from the Dates and Nuts series, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-03-24",
        seconds: 3197.481043,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-03-31.mp3",
        filename: "car_talk_2012-03-31.mp3",
        title: "#1213: Ashes to Asphalt",
        description:
            "This week's Car Talk kicks off with an Auto-Spiritual conundrum: Can Sajay have his cremated ashes poured into his car's gas tank, without doing damage? Then it's off to Somerville, MA, where Rebecca's got a squeaking clutch, and Tommy's having a TMI moment from his childhood. Also, Will's secret mid-life crisis Porsche purchase may be a little harder to keep quiet, now that it needs a new transmission; Whitney's got a husband determined not to fill up his gas tank until he's down to the last drop; and Josh may need help from late night TV to get dried concrete off his Corolla. All this, plus the Puzzler welcomes the return of baseball season, and lots more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-03-31",
        seconds: 3206.488594,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-04-07.mp3",
        filename: "car_talk_2012-04-07.mp3",
        title: "#1214: The Flower and Blue Cheese Belvedere",
        description:
            "This week on Car Talk, Chris' 1959 Belvedere has turned into a greenhouse and Fromagerie, courtesy of some poorly placed birdseed, and a kid who though it would be fun to hide four bricks of blue cheese in the vents. Can he kill the plants and smell without also taking himself out? Elsewhere, Jonathan's wife is blaming his speed-bump strategy for his Civic's alignment problems. His reaction to Tom and Ray's analysis? \"I'm a dead man.\" Also, Jeannie's looking for validation that the guys telling her to use her emergency brake have their heads up their keisters; and Amy wants to give her husband a dope slap for fixing their Maxima's rack and pinion with nothing but a hammer. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-04-07",
        seconds: 3213.578526,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-04-14.mp3",
        filename: "car_talk_2012-04-14.mp3",
        title: "#1215: Beth's Road Ugly Thesis",
        description:
            "This week on Car Talk, a new entry to the Hall of Wacko Auto-Anthropological Research, courtesy of Beth in Oregon. Beth believes that women, and only women, become less attractive after driving for three hours. Can Tom and Ray offer an explanation, or is this one for Paul Murkey, of Car Talk's Murkey Research team? Elsewhere, Paula's Bronco seems to be whistling with perfect pitch; Jonathan's Saturn is laying out a smoke screen worthy of an Army tank; and former Bostonian Tim is finding the driving style in Vermont to be a little too polite. Also, a brilliant wiring job turned Helen's VW bus into a home. Sadly, it also may have made climbing hills an impossible dream. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-04-14",
        seconds: 3218.36102,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-04-21.mp3",
        filename: "car_talk_2012-04-21.mp3",
        title: "#1216: Buona Fortuna",
        description:
            "This week on Car Talk, Heather is about to embark on a two-year relocation to Italy, and is considering taking her '91 Alfa with her. Will it be happier if it dies on its home soil? Elsewhere, Brooke's Lumina is giving a good strong Tarzan yell in Reverse; Kristie's engine sounds like a Gatling gun, and she just noticed oil is pouring out of it as well; and Drew tried to clean his fiancee's car, but left a huge scratch in the hood, and is looking for a way to make it up to her. Also, is there any way for Jessica to fully de-maggot her Camry? All this, and lots more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-04-21",
        seconds: 3200.989002,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-04-28.mp3",
        filename: "car_talk_2012-04-28.mp3",
        title: "#1217: Cynthia and the Swimming Goats",
        description:
            "This week on Car Talk, Cynthia's 1987 Vanagon is dying, so she needs a new ride for her three Nigerian swimming goats. After all, the goats have to get to their pool parties, right? Another family transport crisis is unfolding in San Diego, where Scott's wife wants to buy a motorcycle complete with a sidecar, to get around town with their two small kids. Meanwhile, Kat in Seattle is about to learn an expensive lesson about why you shouldn't speed over speed bumps; and, Lisa's efforts to save money on a catalytic converter revives the adage, \"It's the stingy person who spends the most.\" Also, Dan is about to sell the car his son was born in, but wants to keep a memento--the front seat?!! All this, plus a new Puzzler from the Games of Chance series, and lots more, this week on Car Talk",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-04-28",
        seconds: 3190.064195,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-05-05.mp3",
        filename: "car_talk_2012-05-05.mp3",
        title: "#1218: Tire Pressure Goblins",
        description:
            "This week on Car Talk, strange things are happening in the night: Bruce's tires are going from full to flat while he sleeps; Cynthia is adding Maalox to her engine instead of motor oil; and Jinx's romantic moonlight drive is interrupted by smoke billowing from the dashboard after he turned off his headlights. Smoke is also an issue for Henry in California. Actually, it may be more of an issue for his neighbor, who happened to be standing behind Henry's car when it made its morning billow from his tailpipe. Elsewhere, Lisa's Passat is sounding like a bad 1950's science fiction movie; and Michal can't understand why her partner becomes turn-signal averse as soon as he gets on the freeway. All this, plus a few subtle signs it may be time for a new car, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-05-05",
        seconds: 3213.024127,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-05-12.mp3",
        filename: "car_talk_2012-05-12.mp3",
        title: "#1219: The LTD of Destruction",
        description:
            "This week on Car Talk, good intentions go bad. For starters, Todd decided to buy his girlfriend a 1973 Ford LTD, on the premise it would be safe and easy to work on. Unfortunately, the car's loud backfire has led to one dead cat, several deceased goldfish, and one very strained relationship. Elsewhere, Kate's friends decided to surprise her by picking her up in her car. The only problem? They didn't know how to drive a stick, and burned out her clutch. And out in Montana, Dari's mechanics were fixing a sensor on her truck when it just happened to fall off the lift, at full height. Also, Peter in Alaska discovers a new Primordial soup on his dipstick; and should Sven realize his life-dream of owning a '62 Mini, even if it's been sitting on blocks for 25 years and the owner won't tell him why? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-05-12",
        seconds: 3202.678435,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-05-19.mp3",
        filename: "car_talk_2012-05-19.mp3",
        title: "#1220: The Black Hole of Auto Metaphysics",
        description:
            "This week's Car Talk kicks off with one listener's brilliant (and only sorta wacko) theory: a non-essential repair on an old car creates a parallel universe in which everything else starts to break. Then it's off to New Mexico, where Nolina has two choices for dealing with a disintegrating head gasket: a $2500 engine re-build, or a $10 can of Bar's Leaks. Any bets on which side Tom and Ray come down on? Elsewhere, Michael in New Jersey needs to replace his beloved minivan with something that can accommodate his Daniel Pinkwater-ish body and his very picky teenage daughter; Brian's looking for a way to convince Little League parents to stop parking in his driveway that doesn't involve slashing tires; and on Stump the Chumps, does Tom manage to snatch defeat from the jaws of a Ray victory? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-05-19",
        seconds: 3200.982789,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-05-26.mp3",
        filename: "car_talk_2012-05-26.mp3",
        title: "#1221: The Steve Revolution",
        description:
            "This week on Car Talk, could one honest man de-sleazify the entire used car industry? Probably not, but that won't stop Tom and Ray from trying to convince Steve that it'd be a good idea to fix or disclose his CRV's tendency to take on water before trading it in. This week's other probing auto-behavioral question comes from Dan in New Hampshire: Do people who keep their cars longer, stay married longer? On the technical front, Anna's Volvo will only start when it's facing downhill; Michelle's gas pedal doesn't like to move first thing in the morning; and, on Stump the Chumps, we find out if Raymond in Utah really had a chicken bone stuck in his fan. Finally, how should Sam handle his newly retired Dad, who's keeping himself busy be destroying Mom's Beetle? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-05-26",
        seconds: 3215.647347,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-06-02.mp3",
        filename: "car_talk_2012-06-02.mp3",
        title: "#1222: Burnt Clutches, Blown Relationships",
        description:
            "This week on Car Talk, Caroline's ex-boyfriends have labeled her a Clutch Killer. She's ignored their admonitions because, well, she was driving their cars. But, now she's got her own car, and first gear's getting a little jerky. Is she ready to face the music? Meanwhile, family trouble may be brewing for Mac out in California. Mac's brother borrowed his truck, and while driving it, the hood flew open, and caused a few boat payments-worth of damage, for which Mac's brother didn't offer to help pay. Elsewhere, Adam's Maxima's windows are mysteriously descending overnight, and he can't blame his girlfriend anymore; Sarah broke up with her mechanic after two bad mistakes but is considering giving him another chance; and on Stump the Chumps we find out if Muriatic acid de-cemented Josh's Corolla. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-06-02",
        seconds: 3202.006621,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-06-09.mp3",
        filename: "car_talk_2012-06-09.mp3",
        title: "#1223: Emboldened Electrons",
        description:
            "This week on Car Talk, David's Dodge is having trouble starting, unless he turns the key and counts to 10. Can his problems be solved by a Few Brave Electrons and a broom handle? Meanwhile, Barbara is about to leave her accounting job and head off on a six-month road trip, and wants to do it in the least fiscally prudent vehicle possible--a VW Camper Van. Her biggest problem may be grabbing one before Tommy does. Also, Rachel in Minnesota had a very bad windshield wiper day--one blade stopped moving, and the other flew off the car; Carly in Oakland has a Civic that's been been violently shaking for three years, and she's finally ready to address the problem; and is Kara's car doomed after she went to her local gas station and filled up-- on water? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-06-09",
        seconds: 3221.968163,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-06-16.mp3",
        filename: "car_talk_2012-06-16.mp3",
        title: "#1224: You Sap",
        description:
            "This week on Car Talk, alas poor Yousef. His fiancee called him a sap, after he fell for a recommendation that he use special \"high mileage oil\" in his Saturn. Will Tom and Ray be any more sympathetic, or will they try to sell him the Brooklyn Bridge? Elsewhere, Maggie's hand-me-down Buick is shaking while climbing; Nick's fuel pump is buzzing after the car is turned off; and Jason's brakes are squealing--when he's not stepping on them. Also, on Stump the Chumps, we find out if Tom and Ray correctly diagnosed Todd's backfiring LTD, and got his neighbor and girlfriend to start speaking to him again. All this, plus a few classic Bulwer-Lytton Ccontest winners for bad fiction writing, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-06-16",
        seconds: 3228.985034,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-06-23.mp3",
        filename: "car_talk_2012-06-23.mp3",
        title: "#1225: Do One To Others",
        description:
            "This week on Car Talk, kids give the \"Golden Rule\" and a few other maxims an innocent (yet funny) twist. Then it's off to Arizona where Lily's Taurus is making a noise that she hopes will lead her husband to make another noise-- namely, \"Let's buy you a new Mustang.\" But all is not well in Mustang-land for Martin--his is emitting blue smoke, so his wallet may be emitting a large boat payment. Meanwhile, out in Washington, Amanda's marriage is only a few days away, but if she and her fiance can't figure out what to do with their four cars, the divorce may not be far behind. Also, a hand-me-down Accord develops a distaste for Reverse; a DIY CV joint replacement turns into a demolition project; and, can a few strategically placed magnets prolong Peter's engine life? All this and lots more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-06-23",
        seconds: 3234.931655,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-06-30.mp3",
        filename: "car_talk_2012-06-30.mp3",
        title: "#1226: Who Drowned My Corolla",
        description:
            "This week on Car Talk, Maria's car was minding its own business in her boyfriend's driveway, until his ex-wife came along and gave it a tap, which sent it rolling straight on down to the Connecticut River. Was the ex's tap more of a shove, or is Maria's boyfriend guilty of leaving it in \"ready to roll\" position? Elsewhere, Debra's truck is making a mysterious knocking sound; Matt's wife won't go near their new car after a mouse spotting; and Sara's got the DIY bug, and wants to tackle a transmission rebuild. Also, on Stump the Chumps, did Tom and Ray help dog-trainer Vicky choose the right pet-mobile? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-06-30",
        seconds: 3220.956916,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-07-07.mp3",
        filename: "car_talk_2012-07-07.mp3",
        title: "#1227: A Civic Divorce",
        description:
            'This week on Car Talk, after three crashes, nine vandalizations, and one, "Ah, never mind" theft, Ellen has decided to part ways with her Honda Civic. Does she need to disclose its troubled past to prospective buyers? Elsewhere, Glenn loves his CRX, but his friends are telling him the car is scaring away potential dates. Does he need new wheels, or maybe just a new wardrobe? Also, Greg\'s Jetta begins shedding hair; Alicia decides that four years is long enough to ignore a flashing Check Engine light, and, after an unfortunate spider incident causes Gina to ditch her car in Lake Minnetonka, she wants to know if "Totaled" really does mean totaled. All this, and lots more, this week, on Car Talk.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-07-07",
        seconds: 3218.967052,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-07-14.mp3",
        filename: "car_talk_2012-07-14.mp3",
        title: "#1228: Karmen and the Burper",
        description:
            "This week on Car Talk, Karmen's husband is a \"burper.\" At the gas pump, he shakes the car to get the air out, and more gas in. Karmen thinks this is wacko--which it is--but is her nozzle technique any less crazy? Elsewhere in matters auto-relational, Jim just noticed that all of his romances have been with women who drive Volkswagens; and Derek needs to get his beloved Jeep off the front lawn, before his wife gets him out of the house. Also, a passenger-side farting sound is causing some major embarrassment for Alicia; Paul needs to figure out why his wife's Hyundai is moaning before she gives birth; and Ben is wondering if a potato can really fill in for a radio antenna. All that and lots more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-07-14",
        seconds: 3205.232086,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-07-21.mp3",
        filename: "car_talk_2012-07-21.mp3",
        title: "#1229: The Lincoln Stretch Bike Carrier",
        description:
            "This week on Car Talk, Sherry and her husband discovered they couldn't mount their bike rack on the roof their new Lincoln Town Car. How are they going to haul around their kids and bikes? His solution is a Minivan. Hers? A Town Car Stretch Limo. Can Tom and Ray bring a return to domestic tranquility? Elsewhere, Michele's husband thinks she has too many keys dangling from her ignition, and has made the most dire threat: either she divests of a few keys, or his Mom's moving in with them. Also, just a few weeks after a Freon refill, Michelle's Escort's back to blowing hot air; Brad's adding an alarming amount of fluid to his Camry's clutch; and Pradeep is being slowly driven crazy by the cell phone he dropped into his BMW's duct work. Will Tom and Ray have any suggestions for removing it that are more helpful than, say, turning the car upside down and shaking it? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-07-21",
        seconds: 3230.79551,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-07-28.mp3",
        filename: "car_talk_2012-07-28.mp3",
        title: "#1230: A High Octane Straw",
        description:
            "This week on Car Talk, Andy borrowed his Dad's Buick for a romantic drive to the country. All was right with the world, until he ran out of gas. A Good Samaritan gave him a few gallons, but somehow Andy managed to drop a straw into the gas tank. Now, Dad's car is running lousy, and Andy needs to know if one straw could cause a few boat payments worth of damage. Elsewhere, Brian is trying to decide whether his Mercedes' new noise is the sound of it playing Taps; Mary wants to coax a few more miles from her Altima's slipping clutch; and Gail wants to retro-fit a vintage VW Beetle with air conditioning--maybe a nice window unit from Home Depot? Also, on Stump the Chumps, did Tom and Ray successfully diagnose Susanne's overheating Mazda? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-07-28",
        seconds: 3216.20941,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-08-04.mp3",
        filename: "car_talk_2012-08-04.mp3",
        title: "#1231: The Clairvoyant Mechanic",
        description:
            "This week on Car Talk, Ann's car is emitting a mysterious gummy substance through the vents. Her mechanic doens't know what it is, or where it's coming from. But, that hasn't stopped him from telling Ann it'll cost her $1000 to fix it! Talk about psychic powers! Elsewhere, 13-year old Thomas was gifted a '94 Altima for helping a car dealer. Now, he needs Tom and ray's help convincing him Mom to let him drive it when he gets his license in three years. Also, Alita needs help keeping the Truck That Wouldn't Die from, uh, dying; Amy's been convinced that her Civic's starting problem is a Honda safety feature that was so special they only used it on her car; and on Stump the Chumps we find out why Jean's Porsche almost rolled off a cliff while in Park. All this and lots more, this week on Car Talk",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-08-04",
        seconds: 3201.217687,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-08-11.mp3",
        filename: "car_talk_2012-08-11.mp3",
        title: "#1232: Everything You Never Wanted to Know About Click and Clack",
        description:
            "This week on Car Talk, Tom and Ray dip into the mailbag to answer some personal questions from listeners. To name a few: Which brother snorts? Was either one wedgied as a kid? And, has either brother ever been hauled off to jail? We're not sure why anyone wants to know this stuff, either, but fortunately there's also time for some car questions. There's Debra, who can't turn her key in the ignition until she pushes the car forward; Rane, who's worried that the engine might be about to fall out of her Isuzu; and Prashanth, whose wife is coming over from India, but may hop on the first plane back after she sees his banged up Corolla. Also, what's a husband to do when he turns his wife's car into Florida's newest swamp? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-08-11",
        seconds: 3222.470612,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-08-18.mp3",
        filename: "car_talk_2012-08-18.mp3",
        title: "#1233: It's All About the Hot Butt",
        description:
            "This week on Car Talk, Tom and Ray discuss the ever-so-important car accessories: butt coolers and heaters! Cupholders and fuzzy dice are so passé--keeping your derriere at the optimum temperature is now what it takes to be au courant. At least, if you're Ray Magliozzi. Then, we delve into other pressing automotive issues... like how often should you clean bird poop off your car? And when it comes to breaking in a new vehicle, do you have to drive like a blue-haired old lady? And, when you leave a gas station with the pump nozzle in your gas tank, can you sue for emotional damage? Tom and Ray consider these slightly automotive but highly pressing ethical questions, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-08-18",
        seconds: 3257.100454,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-08-25.mp3",
        filename: "car_talk_2012-08-25.mp3",
        title: "#1234: I Spit On Your Volvo",
        description:
            "This week on Car Talk, remember Heather's Volvo that was dying at high altitudes? Tom and Ray get an update on Helmut the Cranky Mechanic, who may have caused the problem. Did he finally 'fess up? Find out on Stump the Chumps. Elsewhere, Elizabeth thought a herd of cows was following her on her Summer roadtrip, until she realized the mooing was coming from her air conditioner; Bruce just learned why you shouldn't buy a used car from your brother; and Wendy's wondering if a vintage Beetle can handle a drive from Kansas to Washnigton DC in less than, say, 6 months. Also, did Tim's drive on washboard roads crush the engine mounts on his wife's Saturn? And, if so, how much laundry does he need to do as penance? All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-08-25",
        seconds: 3208.457166,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-09-01.mp3",
        filename: "car_talk_2012-09-01.mp3",
        title: "#1235: A Truck By Any Other Name",
        description:
            "This week on Car Talk, Robert is a \"Car Namer.\" More specifically, he's always given his vehicles female monikers. So imagine his shock when he learned that his truck's previous owner had already named it... Mark! Can Robert change his truck's name (and gender!) without giving it an identity crisis? Then we dig into the Department of Odd Noises. Elisha's Honda is making a sound she describes as \"a mouse wearing stilettos, doing a tap dance on a marble floor.\" And, Maureen's looking for a way to compensate her mechanic who suffered head injuries while working on her car. Can baked goods make him forget about a permanently damaged forehead? All that and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-09-01",
        seconds: 3241.141905,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-09-08.mp3",
        filename: "car_talk_2012-09-08.mp3",
        title: "#1236: Bernoulli This!",
        description:
            "This week on Car Talk, the best defense is--a boooogus scientific explanation? Hey, it's always worked for Tom and Ray! Katie's roommate cited the Bernoulli Effect to explain why he gunned the engine to dislodge her stuck car door. She told him where he could stick his Bernoulli. Will Tom and Ray back her up? Elsewhere, Ray has a perfect diagnosis for Heidi's noisy 4Runner--if he can convince her that a \"shugga shugga\" is actually a groan, and Frank may need a box of doughnuts to help him fix his Forester's creaky window himself. Also, on Stump the Chumps, we find out if Steve's cross-country bachelor party road trip in a '66 Econoline ended with him taking his vows on a tow truck; and, the most perplexing question of the week: Why on earth would anyone steal the seats out of a 1999 Miata? All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-09-08",
        seconds: 3210.72034,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-09-15.mp3",
        filename: "car_talk_2012-09-15.mp3",
        title: "#1237: Vlad the Impala",
        description:
            "This week on Car Talk, listeners weigh in on the great Car Naming debate, including one very persuasive cautionary tale about why you shouldn't name your car after your wife. Then it's off to Wisconsin, where Martha's unnamed Chevy van has developed a nasty habit of acting like it's run out of gas; and to Ohio where Fatymah's beloved Civic, \"Little Red,\" has a big transmission problem. Elsewhere, Kate's family trip turns into a terror-filled ride down Mount St. Helens, all because nobody bothered to read the owner's manual in their rental; Matt's brother talked him into a DIY timing belt replacement on Mother's Day… and it's still not finished. And, could Elizabeth's noisy Volvo get her expelled from college? All this, plus the return of the Puzzler, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-09-15",
        seconds: 3217.43034,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-09-22.mp3",
        filename: "car_talk_2012-09-22.mp3",
        title: "#1238: My Engine Is on Fire",
        description:
            "This week on Car Talk, Glen's summer vacation got a little more exciting when his rental car caught on fire, after he spilled oil on the manifold. He escaped unscathed, but did the car? And, more importantly, did he 'fess up to the rental company? Elsewhere, Joann's getting a foot bath from her Grand Caravan; Ed's Jetta needs a few seconds to convince itself it really wants to go into Reverse; and Sue's wondering why PAM cooking spray quieted her noisy fan belt. But our deepest question of the week comes from Vera in New Orleans: Is it legal to drive barefoot? All this, plus the truth about duct tape, a new Puzzler from the Baseball Algebraic series, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-09-22",
        seconds: 3215.74093,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-09-29.mp3",
        filename: "car_talk_2012-09-29.mp3",
        title: "#1239: The Truth About Leaf Peepers",
        description:
            "This week on Car Talk, welcome to foliage season! Tourists are descending on New England, and locals like Kurt have plenty of time to sit in traffic, developing theories about the drivers clogging his roads. Hey, if wacko Auto-Sociological musings keep his blood pressure down, who are we to argue? Elsewhere, Angela's about to get some sour news about the sweet smell emanating from her dashboard; no good jump start goes unpunished for Bridget, after a friend accused her of doing $1,300 of damage by charging the battery backwards; and, is Ed really about to turn to electric shock therapy to keep his beloved cats from marking their territory on his cars? Also, on Stump the Chumps, we find out if Kate acted on her Matrix buyer's remorse. All this, plus a new Puzzler from the inky shadows of the World War II series, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-09-29",
        seconds: 3233.956372,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-10-06.mp3",
        filename: "car_talk_2012-10-06.mp3",
        title: "#1240: The Forget-A-Key",
        description:
            "This week on Car Talk, medical school student Christine is having a little trouble remembering things--happily, she's not leaving any forceps in patients, but she is repeatedly leaving her keys locked in her Camry. Does she need to gift all of her classmates with copies of her key? Elsewhere, Judy and her husband went car shopping and agreed on everything except the color. So who better to ask to adjudicate than two guys who are color blind? Also, Jose hopes his MIT degree has prepared him to tackle a leaky valve cover; Sarah faces one more Anchorage winter with a recalcitrant heater; and on Stump the Chumps we welcome back Dickie, who couldn't figure out why water was shooting out of his girlfriend's steering column. All this, plus a new Puzzler from the Matchstick series, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-10-06",
        seconds: 3225.995601,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-10-13.mp3",
        filename: "car_talk_2012-10-13.mp3",
        title: "#1241: The Shrink-Wrapped Land Rover",
        description:
            "This week on Car Talk, Mike is about to leave Anchorage, and embark on a two-year sailing trip. But, he doesn't know if his lovingly restored Land Rover can survive two Alaskan Winters without him. Will Cosmoline or late-night TV save the day? Elsewhere, Eileen is having trouble starting her Celica, and thinks the problem is related to her \"cute little foot,\" and Darryl's Isuzu only runs smoothly when the Check Engine light comes on. Also, Amanda's dad gifted her an Infiniti which is way too nice for her, her infant, and her dog, and she needs an exit strategy. And, will a strategically placed blanket and light bulb really reduce Judy's engine wear by 95%? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-10-13",
        seconds: 3219.852449,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-10-20.mp3",
        filename: "car_talk_2012-10-20.mp3",
        title: "#1242: Diplomatic Immunity",
        description:
            "This week on Car Talk, the untended 3:00 AM car alarm is one of the great nuisances of urban life. But, for Mike in DC, the problem is especially annoying. The offending car is parked at a nearby embassy, and the Police won't go near it. Does Mike need to get a vote from the UN Security Council to finally get a good night's sleep? Meanwhile, Twila in Missouri is hoping Tom and Ray can intervene, and break the news to her brother that his truck got smashed while under her watch--even though it wasn't her fault. Also, a fiery trip down a mountain teaches Jerry the importance of downshifting; a 15-year-old asks whether eccentricity is a matter of Nature or Nurture; and on Stump the Chumps we find out why Carla in Alaska's truck could only climb hills backwards. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-10-20",
        seconds: 3217.04059,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-10-27.mp3",
        filename: "car_talk_2012-10-27.mp3",
        title: "#1243: Bemidji or Bust",
        description:
            "This week's Car Talk features our favorite road trip story, ever. It stars Dave and his girlfriend; travels from Alaska to Bemidji, Minnesota; and the featured cast includes an overheating Chevy Cavalier, a crescent wrench with no sockets, an old campfire grill, and-- yes-- a zit on Dave's forehead. As for the plot, well, you'll just have to hear for yourself. Elsewhere, Ann thinks her Buick's radio is trying to \"Gaslight\" her into thinking she has a hearing problem; Jed's learning why taking his Chevy Suburban to Budapest may not have been such a great idea after all; and, Alana's Civic is spitting gas back at her. Also, Tommy provides a great lesson in how NOT to start a car that's been sitting untouched for four years--that is, unless you're a big fan of billowing black smoke. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-10-27",
        seconds: 3222.996281,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-11-03.mp3",
        filename: "car_talk_2012-11-03.mp3",
        title: "#1244: Grandma Is Peeling Rubber",
        description:
            "This week on Car Talk, Linda has no problems driving her Forester. But when she's hauling her grandkids in her daughter's minivan, she can't take off from a stop without the car sounding like she's drag racing. Can Tom and Ray help her, before the kids tattle on her? Elsewhere, Charlotte and her husband decided to liven up their lives by adopting four little kids. And to make things more exciting, they're thinking a beater car in the backyard might make a good playhouse for the tykes. Also, Travis can't even look at his Land Cruiser without it overheating; Tammie thinks her Buick is having territorial issues, because it growls when anyone walks near it; and Peter needs to retrieve an escaped hamster from his Acura's dashboard, before it becomes a permanent, or decaying, resident. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-11-03",
        seconds: 3204.280295,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-11-10.mp3",
        filename: "car_talk_2012-11-10.mp3",
        title: "#1245: The Car Talk Economic Stimulus",
        description:
            "This week on Car Talk, how many thousands of dollars can one hour of lousy car advice pump into an ailing economy? Well, when that hour starts with a Saab owner who's going to be transmission shopping, we may be able to match the Gross Domestic Product of Guinea Bissau. Or better. Things take a turn for the bearish, though, when Jacob scores a free do-over on his timing belt replacement-- and when Lee's Lincoln turns out to need a new \"Whoop Tube.\" (How do you figure costs of replacing an imaginary part?) Happily, Laura brings us back on track. She loves her Camry so much, she can't wait to dump it and get something more suited to her growing dog. Elsewhere, Joanne is trying to teach her teenage kids to drive a stick without causing daily whiplash outbreaks; and, on Stump the Chumps, did Tom and Ray help save Mark's socks from being soaked by transmission fluid? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-11-10",
        seconds: 3215.144921,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-11-17.mp3",
        filename: "car_talk_2012-11-17.mp3",
        title: "#1246: The Acura Bird Poop Magnet",
        description:
            "This week on Car Talk, do birds aim their droppings? Ross in Seattle traded his green Acura for a white one, and suddenly he's scraping heaps of avian deposits off his roof. Elsewhere, Jenny's Sebring has a water retention problem in the driver's door, which is giving her mechanics a good laugh; Selene's about to kill her budding Hollywood career, and terrify her cat, by imitating the noises her Cadillac is making; and Dan has survived four years of driving in New York City, without Reverse. Has he earned a huge repair bill, on top of his spot in the Parallel Parking Hall of Fame? And, we know it's the season to be thankful, but why is a colonectal surgeon grateful to Tom and Ray for boosting his business? All that, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-11-17",
        seconds: 3226.122948,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-11-24.mp3",
        filename: "car_talk_2012-11-24.mp3",
        title: "#1247: Clutch Killer of the Month",
        description:
            "This week on Car Talk, John thinks his employee Steve is a great guy. However, Steve may have destroyed the clutch on the company truck, after only a few hours of driving. Enter Tom and Ray, prepared to stage a driving intervention with Steve, and maybe handle his employee performance review at the same time. Elsewhere, Faith just relocated from Maine to Alaska because she was longing for snow. Her Subaru seems displeased with the move, though, as it's begun making an alarming noise. Also, Susan swears that changing gears on her Saturn is like shifting through a bowl of Cream of Wheat, but her boyfriend swears she's crazy; and, speaking crazy, would you drive across country in a Ford Focus, with a boyfriend, three dogs, and two cats? Shelly's planning on trying, unless Tom and Ray can come up with a better plan--and there may only be a million or so better plans. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-11-24",
        seconds: 3212.041791,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-12-01.mp3",
        filename: "car_talk_2012-12-01.mp3",
        title: "#1248: Brake Stompers and Garage Hoggers",
        description:
            "This week on Car Talk, Diana has a new boyfriend, and a Stanza that's begun chewing up brake pads at an alarming rate. What are the chances these two facts are not a coincidence? Oh, maybe 100%? Elsewhere, Nan's trying to figure out how to get her new husband to share his garage with her Accord, and why the Accord won't start after it's parked in said garage. Any guesses on which question Tom and Ray might have an answer for? Also, Bob's got an exposed airbag in his Sonata and, as a result, a family that's embarrassed to be seen in the car with him. His proposed solution? Duct tape, of course! And, did Ben make a big mistake by giving into the lure of the Jaguar Fatale? All this, plus the truth about lying in Italy, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-12-01",
        seconds: 3233.007029,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-12-08.mp3",
        filename: "car_talk_2012-12-08.mp3",
        title: "#1249: The Vanagon of Sierra Madre",
        description:
            "This week on Car Talk, \"Alternator? We don't need no stinkin' alternator!\" Suzy is about to embark on a drive across Mexico in her Vanagon. Will Tom and Ray have any advice on how to prepare, aside from a pre-trip screening of Treasure of the Sierra Madre? Elsewhere, Michael stands to inherit his father-in-law's Lincoln, if he can figure out why it's stalling; Henry needs to know if he can still rely on his coat-hanger wielding, shade-tree mechanic pal Sammy, after a brake job failed to make Henry's Colt stop pulsing; and on Stump the Chumps, did Erica spring for a new transmission or a bungee cord to keep her Forester from popping out of gear? And, car dealers once again battle it out with members of Congress for the dubious title of Least Honest Profession. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-12-08",
        seconds: 3221.941451,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-12-15.mp3",
        filename: "car_talk_2012-12-15.mp3",
        title: "#1250: Tires Under the Tree",
        description:
            "This week on Car Talk, nothing says, \"I love you\" better than… four new Michelins? Patty is dismayed by her boyfriend's plan to give her tires this Christmas. Can Tom and Ray help her convince him to think a wee bit more romantically? Meanwhile, in Our Fair City, Peter's friend showed his devotion by climbing into Peter's trunk when it wouldn't close. He succeeded in closing it, and when they realized he had the only key, spent the next several hours inside. Said friend is a Graduate Student at MIT. (Why are we not surprised?) Also, Ed's worried his radiator might blow bubbles, after he misdirected a bottle of wiper fluid; Laura may need to find out if a transmission is in the alimony agreement with her ex-husband/ex-mechanic; and we learn what happens when a clutch-wrecker tries to change his ways. All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-12-15",
        seconds: 3226.036236,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-12-23.mp3",
        filename: "car_talk_2012-12-23.mp3",
        title: "#1251: The Suzy Saga",
        description:
            "This week on Car Talk, Suzy's drive across Mexico is off to a rocky start. She hasn't even crossed the border, and her Vanagon is already making a new noise that could foreshadow the Death of a Transmission. Will Tom and Ray counsel her to turn back, or just to go shopping for a good pair of noise-canceling headphones? Elsewhere, Patricia's Subaru is having troubles starting, and exacerbating the problem is a large buffalo grazing between her and her car; and Katie's right leg is showing its displeasure with her new Volvo by going numb when she drives it. Also, does Neil's son's decision to play the double bass mean Neil's on a one-way street to Minivan Land, and is Kelly's boyfriend nuts for insisting on warming up his truck for 10 minutes in 50 degree weather? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-12-23",
        seconds: 3214.979342,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://media.adonix.org/car_talk_2012-12-29.mp3",
        filename: "car_talk_2012-12-29.mp3",
        title: "#1252: Il Fiat Miracolo",
        description:
            "This week on Car Talk, what could make a Fiat's gas mileage increase exponentially over a few days? A holiday miracle, or might it be the same earthly reason said Fiat's mileage then decreases by the same amount? And, does it have anything to do with those guys laughing their butts off in the corner? Meanwhile, Rachel may need a miracle to keep her Camry's engine from jumping into the passenger seat, though opening her wallet might work just as well. Also, Delena's decided that 6 years is long enough to live with her Civic's oil leak; Darren is convinced his wife is subconsciously trying to kill his Land Rover; and, Rich wants to know if he can convert his Cavalier into a convertible. Sure, as long as he doesn't want to ever drive it again! And, Ray finally asks Tom the question that's been on everyone's minds for 25 years: What are you doing here? All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2012,
        date: "2012-12-29",
        seconds: 3218.004422,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
];
