/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/168693070/npr_168693070.mp3",
        filename: "car_talk_2013-01-05.mp3",
        title: "#1301: Schmutz on the Clutch",
        description:
            "January 5, 2013 • This week on Car Talk, Dana's Jetta is shaking violently in 1st Gear. Could the culprit be the dreaded (and highly technical) \"schmutz on the clutch?\" Meanwhile, in Dallas, Dr. Paul's life has been a Country-Western song: he totaled his car, his wife left him, and his dog died. Can Tom and Ray help him choose a new ride that will help him find a new love---and a new dog? Also, Science Museum educator Seniz needs a lesson from the space shuttle to understand the noise her Civic is making; Mark has discovered a new driving technique with the double bonus of being more efficient and making his wife thinks he's completely nuts; and on Stump the Chumps, did one answer solve three problems for Ed and his Jeep? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-01-05",
        seconds: 3227.003968,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/169232019/npr_169232019.mp3",
        filename: "car_talk_2013-01-12.mp3",
        title: "#1302: Male Braking Syndrome",
        description:
            "January 12, 2013 • This week on Car Talk, Tracy's husband has a brilliant (his word) approach to reducing brake wear--by stomping on them at the last possible second. Tracy thinks he's nuts and so does their dog-- he's afraid to get in the car. Elsewhere, Red was ready to live the dream in the '75 Pontiac he bought off a front lawn. Alas, his maiden voyage was cut short when the carpet burst into flames! Also, Wendy's Honda fogs up whenever her husband (and only her husband) rides in it; Linnea's Jetta has a squealing problem when she backs up; and could Peter's faulty cooling fan relax an entire nation, by introducing the Mandatory Meditative Minute? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-01-12",
        seconds: 3214.540975,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/169796611/npr_169796611.mp3",
        filename: "car_talk_2013-01-19.mp3",
        title: "#1303: Dumped, But Un-Towed",
        description:
            "January 19, 2013 • This week on Car Talk, Steve moved to Chicago for a job and a girlfriend. He lost both. But what's confusing him is why he didn't lose his ride, as well. His Acura was the only car that didn't get towed from a parking lot during a party. Did the parking deities take pity on him? Elsewhere, Chuck decided to cut his air conditioner belt because it was smoking, and now may find himself on the FBI's Most Wanted list; and Heidi may find out why her Check Engine light is blinking, if she can make it through a few Magliozzi detours into Kirchoff's laws, MIT admissions, and the U.S. Army. Also, the final chapter of the Suzy Saga. She made it home to Carlsbad, but did she manage to make it across Mexico in her Vanagon? Did she even make it TO Mexico in her Vanagon? All this and lots more, this week, on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-01-19",
        seconds: 3215.195442,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/170353558/npr_170353558.mp3",
        filename: "car_talk_2013-01-26.mp3",
        title: "#1304: How to Lose a Pinewood Derby",
        description:
            "January 26, 2013 • This week on Car Talk, Kathy is \"helping\" her son build his Pinewood Derby race car, and is looking for a few design tips. Can two MIT grads-- one of whom failed Physics twice-- lead her to Victory Row, or is this Cub Scout Den Mother barking up the wrong radio show? Elsewhere, Sophie thinks her Saab is laughing at her, and not just because it's delighted by her French accent; Ainsley's husband won't let her take her Honda to the car wash because he's worried it'll melt the Epoxy that's holding the car together; and Richard won Employee of the Month by driving 95 mph to deliver his boss' passport to the airport. But, will he be forced to sell his plaque to fix the problems that have plagued his Jeep ever since? And, our Historic, Folkloric Question of the Week comes from Julie: why do we drive on the right, if we're a former British colony? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-01-26",
        seconds: 3234.131134,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/170944689/npr_170944689.mp3",
        filename: "car_talk_2013-02-02.mp3",
        title: "#1305: The Great Snorkel Experiment",
        description:
            "February 2, 2013 • This week on Car Talk, Wendy's Honda was fogging up, but only when her husband was in the car with her. Tom and Ray postulated that hubby's breathing was causing the problem, and suggested Wendy experiment by having him breathe through a snorkel, out an open window. Now Wendy's back for Stump the Chumps with a full report on the Great Snorkel Experiment. Elsewhere, Adrienne found the perfect birthday present for her husband--700 pounds of rocks! Can her Saab handle the 300-mile trip, or does she need to transport one rock at a time? Also, Steve's DIY brake repair has resulted in his truck taking out two car ports; Matt's CRV is not putting out heat, which is a big problem, since Matt is in Anchorage; and, Rain got a rude Welcome Home from her Acura, after leaving it parked for three months: mold, and a thriving ant colony. All this, plus a tale of a very smart car radio, and lots more, this week, on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-02-02",
        seconds: 3216.999206,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/171602367/npr_171602367.mp3",
        filename: "car_talk_2013-02-09.mp3",
        title: "#1306: The Little Morris Minor That Couldn't",
        description:
            "February 9, 2013 • This week on Car Talk, Jim loves his 1957 Morris Minor, except for one minor inconvenience--its 36 horsepower isn't enough to get it up hills, so his passengers have to get out and push. Does Jim need to keep a few Clydesdales on hand for an occasional tow? Elsewhere, Mo had to drive her boss's Saab, and the next day it needed a few hundred dollars' worth of clutch repairs. Should she be dreading her next employee review? Also, on Stump the Chumps, we find out if Dr. Paul's life no longer resembles a Country-Western song; sisters Kathy and Jackie debate the merits of using mothballs to improve gas mileage; and could the secret to a happy marriage be two simple words: \"Yes, dear\"? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-02-09",
        seconds: 3205.962653,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/172195025/npr_172195025.mp3",
        filename: "car_talk_2013-02-16.mp3",
        title: "#1307: The Giving Trunk",
        description:
            "February 16, 2013 • This week on Car Talk, James thought he got a good deal when he bought his neighbor's Cadillac--and that's before the cash rebate, in the form of $3,200 hidden in the trunk. Should he hand the money over, or tear the rest of the car apart in search of more? Later, Tom and Ray are vexed by two noises: Scott thinks someone's playing a French Horn under the hood of his Explorer, and Jane keeps checking her Civic's trunk for the passenger who's banging on the sides. Also, Barry's lived a car-free life into his 30's, but his relocation to L.A. has him wondering if it's time to give in. But will a car lead him directly to Botox injections? And our deep question of the week: do we really need a Click AND a Clack? And if not, which Magliozzi's moot? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-02-16",
        seconds: 3199.231066,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/172774101/npr_172774101.mp3",
        filename: "car_talk_2013-02-23.mp3",
        title: "#1308: Geographically Undesirable",
        description:
            "February 23, 2013 • This week on Car Talk, Kate and Aaron's long-distance relationship has come to a road block. Aaron is afraid to drive, so Kate's doing all the traveling, and it's become a bit of a pain in the butt--figuratively, and literally. Can Tom and Ray help her get Aaron behind the wheel, or is this relationship headed for the crusher? Elsewhere, Erin inherited her Grandpa's Impala, and among its dozen or so problems, the most amusing is that when she turns on her high-beams, the directional signals don't work; Tony's sleeping on the sofa after two unsuccessful repairs to his wife's Subaru, and Strike Three might send him and his sleeping bag to the garage; and, Steve is wondering why his trusty Ford Ranger is suddenly causing boat payments, three at a time. Also, on Stump the Chumps, did Tom and Ray help Sam quiet his Accord long enough to sell it? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-02-23",
        seconds: 3206.965624,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/173322174/npr_173322174.mp3",
        filename: "car_talk_2013-03-02.mp3",
        title: "#1309: The Pit of Despair",
        description:
            "March 2, 2013 • This week on Car Talk, Kerry's Boston condo came with one unfortunate feature--a large crater in the parking lot that fills with water every time it rains. She's worried that driving through this \"pit of despair\" every day is killing her Honda. Are those fears warranted, and does Kerry need the number for Vinny's Late Night Concrete Services, Inc.? Elsewhere, Vincent \"inherited\" his daughter's Jeep, along with its tendency to shake, rattle and die above 2,000 RPM; Ben needs help convincing his girlfriend that cars are impervious to wind chill factors--especially German cars; and on Stump the Chumps, we find out if Tom and Ray helped lead Kathy's son to victory in the Pinewood Derby--and, why they didn't. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-03-02",
        seconds: 3211.999456,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/173907293/npr_173907293.mp3",
        filename: "car_talk_2013-03-09.mp3",
        title: "#1310: Ben and the Junkonauts",
        description:
            "March 9, 2013 • This week on Car Talk, Ben's band is about to embark on a cross-country tour. They can't get a van, so the vehicle of choice is Ben's ancient Volvo 145. Will they make it to any gigs on time, or will they be performing solely for Volvo mechanics across the U.S.? Elsewhere, Rush's Land Rover is now infused with the aroma of rancid butter, after a stick of it melted on his dashboard, and coursed its way through his entire ventilation system. Will he ever be able to get rid of the stink, without the use of a flame thrower? Also, Anwen's fuel pump is making noise, despite her mechanic's insistence that it's fine; physics teacher Mike needs a better answer than \"magic\" to explain rear view mirrors; and on Stump the Chumps, we find out if Prashanth introduced his new wife to his old Corolla, and if honesty earned him a trip to Divorce Court. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-03-09",
        seconds: 3204.001995,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/174505614/npr_174505614.mp3",
        filename: "car_talk_2013-03-16.mp3",
        title: "#1311: To Mud Flap or Not to Mud Flap",
        description:
            "March 16, 2013 • This week on Car Talk, John is wondering whether 'tis nobler not to spray water on his fellow drivers at the risk of increasing his new car's risk of rust--which is a poetic way of asking, should he get mud flaps installed on his new car? Elsewhere, Manny's Chevy S-10 in having trouble adjusting to its new home. Ever since he moved, it won't start after an overnight rain; and Piali's steering wheel is making noises that she thinks are scary, but her husband thinks are hilarious. Also, former Ferrari driver Steve wonders how he can adjust to a post-divorce life of driving a car with cloth seats; Connie's looking for the perfect car for a road trip from Bellingham, WA to Rio de Janiero; and when Lin's mechanic told her, \"your rear end's gonna fall off\"--we're pretty sure he was referring to her Explorer. At least, we hope he was referring to her Explorer. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-03-16",
        seconds: 3193.947098,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/175137343/npr_175137343.mp3",
        filename: "car_talk_2013-03-23.mp3",
        title: "#1312: When Martha Met Click & Clack",
        description:
            "March 23, 2013 • This week, the one and only Martha Stewart comes to Car Talk Plaza, to help bail out Tom and Ray on auto-domestic matters. How do you get crusted dog drool off a car? What's the best way to craft a shaving cream rosette on a wedding get-away car? And, how long does it take to cook a whole chicken on the engine manifold? Find out if Martha has any better automotive advice than our dynamic duo! Elsewhere, Patrick is baffled by his Camry's 50 percent drop in gas mileage; Dana's Jetta is making an alarming noise she'd like to blame on a friend; and Mark's mechanic insists that things always need to be replaced in pairs. Guess what? His mechanic is also the proud owner of a large Cabin Cruiser! Tune in for all this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-03-23",
        seconds: 3222.867324,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/175793168/npr_175793168.mp3",
        filename: "car_talk_2013-03-30.mp3",
        title: "1313: Aspen Rehabilitation",
        description:
            "March 30, 2013 • This week on Car Talk, Donna's husband refuses to part with his 1977 Dodge Aspen. It runs like a champ, but looks like the 1962 New York Mets. It's so beat up that, during a recent storm, more hailstones made it through holes in the car than actually hit the body. Is this a job for Uncle Nunzio's sabotage team, or Mr. Gigi's beautification squad? Elsewhere, David's Nissan is jerking while accelerating, making it look like he doesn't know how to drive stick, and worse, tossing his dog all over the truck; Pam is so concerned about her T-Bird's creaking noise that she waited five years to call us abut it; and could Tom's diagnosis of an overheating Subaru really cause MIT to revoke his diploma? Oh, and by the way, if your name is Homer Handelburg, have we got an offer for you! All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-03-30",
        seconds: 3222.001587,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/176438697/npr_176438697.mp3",
        filename: "car_talk_2013-04-06.mp3",
        title: "#1314: Stump the Salesman",
        description:
            "April 6, 2013 • This week on Car Talk, LaDell's new career as a car salesman was off to a good start, until he opened his mouth. He bragged to a customer about a car's torque and horsepower, the customer asked LaDell to explain the difference… and he's still waiting for an answer. Elsewhere, Liberty's Nissan is sending a clear message: Give me new ball joints, or I may give you death; Tony's 17-year-old son says the fumes from Dad's Saab are responsible for him dropping AP history and not cleaning his room anymore; and, Liz is wondering whether her trusty old Toyota truck can serve as a two-story home for her sled dogs. And, from our Expository Writing Department, we have a few choice metaphors and similes, including, \"He fell for her like his heart was a mob informant, and she was the East River.\" All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-04-06",
        seconds: 3209.961655,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/177151563/npr_177151563.mp3",
        filename: "car_talk_2013-04-13.mp3",
        title: "#1315: The 1962 Corvette Urn",
        description:
            "April 13, 2013 • This week on Car Talk, Marni is in possession of her late Dad's ashes, and his beloved 1962 Corvette. You see where this is going, right? How bad an idea is it for her to pour Dad's ashes into the gas tank, and is there a less combustible way she can make Dad one with his car? Elsewhere, Paul can't hear his Suburban's directional signal, and is convinced it's at fault, despite the fact that it manages to wake up his wife and daughters sleeping in the back seat; Gamin drove through a deep puddle, and her Civic is now making a noise that could be rust, a warp, or a dead fish; and Clive is wondering how his 18-year-old son managed to fry his new Camry's clutch in one afternoon. Also, on Stump the Chumps, did Tom's wacko diagnosis actually solve Kim's peculiar overheating problem? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-04-13",
        seconds: 3209.952653,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/178136431/npr_178136431.mp3",
        filename: "car_talk_2013-04-20.mp3",
        title: "#1316: Rambler Separation Anxiety",
        description:
            "April 20, 2013 • This week on Car Talk, Linda needs counseling after her Dad sold the family's beloved Rambler station wagon to a 17-year old neighbor, rather than hand it down. Will Tom and Ray offer closure, or tips on how to trick the kid into selling the car back? Meanwhile, Tim in Florida may be wishing his Mom had sold her Buick, rather than gift it to him. It's missing the most essential accessory for Orlando--a working air conditioner. Elsewhere, Sukey is trying to convince her insurance company that a fender-bender broke her fuel pump; Greg needs absolution after a DIY brake job gone bad; and how could a loose tailpipe cause a Cadillac to stop losing oil? Mike's mystery is our leading candidate for Bogus Answer of the Week! All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-04-20",
        seconds: 3228.169955,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/179487060/npr_179487060.mp3",
        filename: "car_talk_2013-04-27.mp3",
        title: "#1317: The Neon of Dorian Gray",
        description:
            "April 27, 2013 • This week on Car Talk, Ian's Neon has discovered the Fountain of Youth. When the car goes over 50 MPH, the odometer begins running backwards. Can Tom and Ray figure out what's going on before the car drives itself all the way back to the assembly plant? Elsewhere, automotive history is made in Oregon, as Jim becomes the first person ever to feel guilty about selling a used car that's performing too well for its new owner; on Stump the Chumps, we find out Dana's jerking Jetta was really due to the dreaded, \"Shmutz on the Clutch\"; and Tom and Ray finally get judged by their peers, as an 8th grade class reviews our show. Could Roger Ebert have topped, \"I think the show is a good idea because people like listening to idiots\"? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-04-27",
        seconds: 3216.911338,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/181142782/npr_181142782.mp3",
        filename: "car_talk_2013-05-04.mp3",
        title: "#1318: The Great Lion Escape",
        description:
            "May 4, 2013 • This week on Car Talk, would your mechanic ride 60 miles sitting on the engine of a Land Rover with his hand over the carburetor? What if the alternative was being stranded in an area of Tanzania where the lion population far exceeds the number of tow truck drivers? Happily for Newton, his Tanzanian guide was willing to ride the hot seat, and lead him to safety. All Tom and Ray need to do is explain why this worked--which may be more challenging. Closer to home, there's a new noise somewhere in Anne's Caravan, which started after she rushed her husband home from surgery. Is it the car, or is it his moans of pain? Also, Leslie in pondering whether her car decided to commit \"autocide\" by rolling itself down a hill; and budding shade-tree mechanic Andy thinks he might be getting repair advice that violates the Laws of Physics. All this and lots more, this week on, Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-05-04",
        seconds: 3220.646893,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/183169400/npr_183169400.mp3",
        filename: "car_talk_2013-05-11.mp3",
        title: "#1319: Click and Clack and Dear Old Ma",
        description:
            "May 11, 2013 • This week, get ready for some of our all-time favorite moments as Car Talk celebrates Mother's Day with a special appearance from Tom and Ray's long-suffering mom, Elizabeth. She'll spill the beans on what life was like in the Magliozzi household, and do her best to evade the question of which of her kids she liked best. She's also ready to give out advice to new Moms (\"you've got a long way to go, sweetheart!\"); get to the real reason one caller really wants to teach his Mom to drive (\"is she going to leave you a lot of money?\"); and, offer a final thought on Motherhood that will have Tommy blowing coffee out his nose. Lizzy may even be able to top her sons in figuring out why Sandy's Mitsubishi [I had to stop and think--Montero didn't register as a model to me] is groaning, and how Linda can stop the air leaks that are turning her Accord into a wind tunnel. It's an hour that's a staff favorite that's not to be missed, in our humble opinion. Join us for a visit to the Maternal Combustion Department, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-05-11",
        seconds: 3219.024875,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/185105268/npr_185105268.mp3",
        filename: "car_talk_2013-05-18.mp3",
        title: "#1320: A Sticky Situation",
        description:
            "May 18, 2013 • This week on Car Talk, a day of maple sugaring came to a bad end for John, when he spilled a 5-gallon container of syrup in his car. How can he get the sticky stuff out of the seatbelt holders, short of slipping a stack of pancakes in there to sop it up? Also, a classic Car Talk driveway moment, literally, as Jason pours gas down his truck's carburetor, and tries to start it on the air. Will the 20th time be the charm? And on Stump the Chumps, we find out whether Tom and Ray correctly diagnosed Paula's whistling Bronco. All this, plus Tommy celebrates the arrival of a brand new jalopy, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-05-18",
        seconds: 3215.954422,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/186608303/npr_186608303.mp3",
        filename: "car_talk_2013-05-25.mp3",
        title: "#1321: Bad Bread and a Chop Top Volvo",
        description:
            "May 25, 2013 • This week on Car Talk, Linda's husband proudly told her he'd \"fixed\" her Volvo--by cutting the roof off and turning it into something resembling a convertible. Is her car still safe to drive, without a football helmet? Meanwhile, Jeff relocated from New Orleans to New Mexico, and the higher altitude is wreaking havoc on his automatic breadmaker. Apparently Martha Stewart's line was busy this week, so we'll see if Tom and Ray can bring some life back to his loaves. We've also got a few bona fide car problems: Robert's Subaru keeps overheating, despite him replacing just about every part that could be responsible; Gary wants to know if he can take a 1300-mile road trip, all while down one cylinder in his Isuzu; and on Stump the Chumps, we find out if Tom and Ray correctly diagnosed Anne's growling minivan, and if her husband's vasectomy reversal has been fruitful. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-05-25",
        seconds: 3220.331202,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/187864290/npr_187864290.mp3",
        filename: "car_talk_2013-06-01.mp3",
        title: "#1322: The Citroen Invasion",
        description:
            "June 1, 2013 • This week on Car Talk, Denice's European friend is coming to the U.S., and bringing his Citroen with him. (We don't know if it will fit in the overhead luggage bin, or if he'll have to check it.) He's hoping to drive it from New York to Minnesota, but will the lack of French mechanics and parts leave him uttering, \"Mon Dieu!\" if he breaks down? Elsewhere, Jann's wondering how to get a dealer to let her test-drive a new car with a 77-pound dog that's prone to car sickness; Keller is preparing to sell his VW Bug, but there's that pesky matter of the missing floor on the passenger side; and Steve's Check Engine light comes on, only when he parks his Civic at the Pentagon. Has his car cracked a classified code? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-06-01",
        seconds: 3223.515782,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/190311049/npr_190311049.mp3",
        filename: "car_talk_2013-06-10.mp3",
        title: "#1323: The Lard Butt Indicator",
        description:
            "June 10, 2013 • This week on Car Talk, why does the horn in John's wife's Golf start blowing when he drives it? John's wife thinks he's setting off the \"lardbutt indicator\" under the driver's seat. Has VW really come up with something so sophisticated? Elsewhere, Wendy has discovered that giving up her beloved Super Beetle has done great harm to her social life. She used to be able to meet guys while working on its (many) problems. But, her new Toyota is both too reliable and too complicated. Also, Sara learns an expensive lesson in why you shouldn't let a Physics Grad student fix your fuel pump--with you and your dog stuck in the car while it's on he lift; and can Jeff safely use Coleman fuel in his Civic next time he gets stranded while camping? All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-06-10",
        seconds: 3211.978027,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/192042284/npr_192042284.mp3",
        filename: "car_talk_2013-06-15.mp3",
        title: "#1324: The No-Headliner Look",
        description:
            "June 15, 2013 • This week on Car Talk, the headliner in Cheryl's Chevy is falling down, and causing a series of bad-hair days. She'd like to fashion a replacement. Can Tom and Ray offer any interior decorating tips, or just suggest she use a better cream rinse? Elsewhere, Brent's Audi is leaking very expensive \"mineral oil\" power steering fluid. Does he need to spend big bucks to fix his steering, or can he try a cheaper fluid, like, say, Filippo Berio Extra Virgin Olive Oil? Also, Keller's got a wobbling wheel, but a much too interesting name and Graduate major to get a clear answer; and on Stump the Chumps we find out if Tom and Ray correctly diagnosed Tim's misdirected air conditioner, and if Tim was able to re-direct the repair bill to his Mom. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-06-15",
        seconds: 3213.994059,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/194619140/npr_194619140.mp3",
        filename: "car_talk_2013-06-22.mp3",
        title: "#1325: Look Ma, No Key",
        description:
            "June 22, 2013 • This week on Car Talk, after having his Dodge Omni crash into his parents' deck and run over him, Steve has decided it's time to deal with his car's quirk-- you can turn the car off and remove the key, while it's still in Drive. Will he go for a simple repair, or will he take Tom's advice to handcuff himself to the shifter so he'll never again forget to put it in Park? Elsewhere, Teri may be able to put her baking skills to use by creating a baguette-trunk interface to quiet her Accord; Nancy is concerned that she may have inherited the two-footed driving gene from her mom and aunt; and could a full-on Nikita Khrushchev shoe-banging help fix Eric's air conditioner? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-06-22",
        seconds: 3224.983447,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/197021860/npr_197021860.mp3",
        filename: "car_talk_2013-06-29.mp3",
        title: "#1326: A Chicken Under Every Hood",
        description:
            "June 29, 2013 • This week on Car Talk, how did the chicken get to church? That's what's puzzling Sara in Ohio, after her chicken stowed away somewhere outside the cab of her truck for a two-hour drive. Also, while we applaud DIY repair efforts, Josh in Montana may have gone too far when he tried to figure out the source of his truck's rattle by driving with his head out the door, looking underneath. Yes, the truck was moving. Yes, he was driving. And no, we aren't kidding. Elsewhere, Cathy is trying to figure out why her Sentra is going through head gaskets faster than Tommy goes through ex-wives; mechanic John is trying to figure out the labor rate for evil ex-girlfriends; and on Stump the Chumps, did Tom and Ray help Mike take ownership of his father-in-law's Lincoln? All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-06-29",
        seconds: 3214.911678,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/200343233/npr_200343233.mp3",
        filename: "car_talk_2013-07-09.mp3",
        title: "#1327: The Four-Wheeled Dowry",
        description:
            "July 9, 2013 • This week on Car Talk, Elisa's parents are so anxious for her to marry her live-in boyfriend, that they've offered to buy her a new car if Elissa and her beau tie the knot. Is this an offer she can't refuse, or will she be opening herself up to a lifetime of parental meddling--which may not be so bad if it means a lifetime of new cars. Elsewhere, newly employed Katherine would like to buy a new car, but is worried that she may have trouble making the payments on it, after rear-ending her boss' car on her second day. Also, Jay's wondering if a non-working tachometer can substitute for a non-working speedometer in his BMW; Chris' car has developed a seasonal allergy to starting; and Ann offers Case Study #265,498 of why you should never listen to your father when it comes to cars. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-07-09",
        seconds: 3215.326485,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/201822318/npr_201822318.mp3",
        filename: "car_talk_2013-07-13.mp3",
        title: "#1328: Dispersion via Dave's Chin",
        description:
            "July 13, 2013 • This week on Car Talk, Dave has discovered an electrical anomaly: his Audi's keyless remote works better when he points it at his chin rather than his car. Fortunately, he's come to the right place…for a completely bogus explanation. Elsewhere, Brett's Camry is giving him enough electrical shocks to turn him into a walking Van de Graaff Generator; Spencer learned why you should never touch your lug nuts in public on a hot day; and Beth's Accord is exhibiting all the symptoms of a bad clutch, with just one problem: it's an automatic. Also, in a follow-up to last week's show, we hear from Tracy, whose girlfriend's parents offered to buy them a car if they got married. Did he get the girl, and the Lexus to boot? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-07-13",
        seconds: 3227.979116,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/203975088/npr_203975088.mp3",
        filename: "car_talk_2013-07-20.mp3",
        title: "#1329: Let Sleeping Civics Lie",
        description:
            "July 20, 2013 • This week on Car Talk, all was well with Karen's Honda until her boyfriend gave it a tune-up--which promptly turned on the Check Engine light. We'll just skip past the question of whether he messed up, and go right to trying to figure out what he messed up. Elsewhere in Civic-land, Anna came out of work one day to discover an unwanted passenger in her car: a white rat. How did it get there, and how can she ever go near her car again? Also, our Physicist-on-Call Wolfgang checks in to help clarify, and de-bogusify, Ray's \"dispersion\" theory on the odd behavior of a keyless remote; and is Lara's starting problem really caused by her turning the key too fast? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-07-20",
        seconds: 3200.001361,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/206132663/npr_206132663.mp3",
        filename: "car_talk_2013-07-27.mp3",
        title: "#1330: The Exercise Diaries",
        description:
            "July 27, 2013 • This week's Car Talk kicks off with a harrowing tale of one man's journey into Dante's supplemental Circle of Hell: the local health club, where he spends one week at the merciless hands of Tanya the Trainer. Then it's off to Missouri, where Jon is concerned about whether the smell in his Chevy S-10 is coming from the truck-- or his fiancee. Elsewhere, \"Mom\" and her teenaged son are arguing over whether the best way to cool a car and keep 40 pounds of meat frozen in 90 degree weather is by turning the heat on full blast; and Rita's intermittent air conditioner problem has convinced her mechanic that she's just looking for an excuse to visit. And, on Stump the Chumps we find out if a Volkswagen really was equipped with a \"lard-butt indicator\" that made the horn blow at random times. All this and lots more,this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-07-27",
        seconds: 3208.986168,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/208642320/npr_208642320.mp3",
        filename: "car_talk_2013-08-03.mp3",
        title: "#1331: The Rhinetone Lincoln",
        description:
            "August 3, 2013 • This week on Car Talk, Savannah wants her car to shine. Literally. Given that it's a Plymouth Sundance, she faces a daunting task! A plethora of rhinestones will make this baby glitter but how does she affix it all without leaving a sparkling trail down the interstate? Also, Car Talk history is made as a caller asks Tom and Ray to settle a marital dispute by doing... nothing! Also, Larry's Lincoln died, and the CIA might be interested in whether he fixes it or not; Maxine learned the old mechanic's adage that a free brake job means never having to say you're sorry; and one diagnosis leads another caller to congratulate Tom and Ray for the finest piece of bamboozling ever. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-08-03",
        seconds: 3220.850658,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/210856438/npr_210856438.mp3",
        filename: "car_talk_2013-08-10.mp3",
        title: "#1332: The Bread Also Rises",
        description:
            "August 10, 2013 • We all know Tom and Ray's dismal record diagnosing car problems, so this week on Car Talk we find out how they did with something a little smaller--a bread maker. Jeff from New Mexico is back for a round of Stump the Chumps to tell us if the Magliozzi recipe made his loaves come out looking less like hockey pucks. Elsewhere, Vivek is puzzled by the puddle that forms under his seat when he uses his air conditioner; Leslie's husband told her she's ruining her car by not straightening the wheels when she parks; and Kirsten wants to know what questions to ask the guys who will be storing her Honda while she goes to Kosovo for two years. Our first question? Can Tommy sleep in it when his wife throws him out of the house. All this and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-08-10",
        seconds: 3224.803605,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/212962401/npr_212962401.mp3",
        filename: "car_talk_2013-08-17.mp3",
        title: "#1333: The Great Conversation Stopper",
        description:
            "August 17, 2013 • This week on Car Talk, Suzi bought a Porsche 911, partly to help her bond with her male colleagues. Unfortunately, she can't answer any of their questions about the car, and things are getting awkward around the water cooler. Can Tom and Ray give Suzi a quick Porsche 101 seminar, or are they even more clueless than she is? Earlier, our favorite brat, Melissa Peterson returns to remind Tom and Ray she still hates them... but as long as they're all on the phone together, would they mind helping convince her mother that her new scooter is safe? Andy's Infiniti's active suspension has become a bit hyper-active; Larry took his car for an oil change and almost got taken for new axles; and, in a follow-up from last week, Kirsten returns to tell us how the government plans to treat her beloved CRX while she's in Kosovo for two years. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-08-17",
        seconds: 3226.455488,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/215202999/npr_215202999.mp3",
        filename: "car_talk_2013-08-24.mp3",
        title: "#1334: The Pinkwater Measurement",
        description:
            "August 24, 2013 • This week on Car Talk, Click and Clack delve deep into scientific inquiry on the expanding American rump. The fruits of their labor? A new way to measure the human derriere. Presenting... the \"Pinkwater,\" after Tom and Ray's pal, his rotundity, Daniel Pinkwater. Also, Kathleen has a moral, ethical and economic dilemma: to buy a SUV or buck the big car trend? And Matthew is struggling with his car washing technique. He's striving for spotless perfection on his parent's Voyager. Could the Shawalla be the answer to all of his car-cleansing woes? All this and much more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-08-24",
        seconds: 3198.524626,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/217598812/npr_217598812.mp3",
        filename: "car_talk_2013-08-31.mp3",
        title: "#1335: The Fraternity of Teenagers",
        description:
            "August 31, 2013 • This week on Car Talk, Terri's trying to convince her teenaged son not to buy himself a 1960's muscle car. Tom and Ray are ready to back her up with a trunk full of reasons why he's more likely to meet girls if he's driving a 1986 Volvo (with mis-matched hubcaps). But their efforts may all be undone when they turn to Tom's son Alex to back them up. Elsewhere, Deena's hoping a horn transplant will cause other drivers to mistake her Chevy Nova for a diesel truck; Thomas is wondering if his local Quickie Lube guy was just trying to clean out his wallet when when he offered to clean Thomas' fuel injectors; and should Roe tell the friend who loaned her his Civic for three months that she spent a good portion of that time driving with the parking brake on? All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-08-31",
        seconds: 3226.943197,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/220126473/npr_220126473.mp3",
        filename: "car_talk_2013-09-07.mp3",
        title: "#1336: Haircut Etiquette",
        description:
            "September 7, 2013 • It's happened to all of us. You're on a long drive, when nature takes its course and you find yourself desperately needing to \"take a haircut.\" Finally, a restroom appears, but it's inside a fast-food restaurant. This week on Car Talk, we tackle the moral quandary--if you use this restroom, are you obligated to get fries with that? Elsewhere, Tom is worried whether his Nissan's shocks can handle an upcoming road trip. Click and Clack are more worried that Tom plans to make said road trip with his mother and his girlfriend. Also, Erica's goal of getting her Camry to 200,000 miles hits a noisy obstacle; a clay-gathering trip turns smoky for Charlie's Explorer; and Bill's attempt to replace a broken belt with a pair of tights failed. Did he use the wrong size? The wrong color? Find out, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-09-07",
        seconds: 3205.955193,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/222551545/npr_222551545.mp3",
        filename: "car_talk_2013-09-14.mp3",
        title: "#1337: The Stunad Stare",
        description:
            "September 14, 2013 • This week on Car Talk, Tom in Vermont would like to convince his son that towing a 1978 Land Cruiser cross-country with his girlfriend's small pickup truck is a bad idea. But, Tom's afraid that any words of caution will be thrown to the wind, just because of his \"Dad\" status. Should he try reverse psychology? Elsewhere, Lisa's hopes of meeting her cute neighbor have been complicated by the embarrassing screeching noise her Civic makes every morning; and Denise would like to find a way to keep her Ford Maverick running without a clothespin stuck in the carburetor. Also, since Leslie gave birth at a Chrysler dealership, should her minivan shopping begin and end there? All this, plus Opening Day for the new Puzzler season, and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-09-14",
        seconds: 3219.956667,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/224814293/npr_224814293.mp3",
        filename: "car_talk_2013-09-21.mp3",
        title: "#1338: Roadside Tonsorial Privileges",
        description:
            "September 21, 2013 • This week on Car Talk, the Great Haircut Debate continues, as listeners weigh on whether it's ethical to use a roadside McDonalds' restroom without buying anything. On the automotive front, Ellen's mechanic says he can tell her Dodge Caravan is dying by the smell of its oil. Tom and Ray smell a conspiracy between the mechanic and Ellen's husband, who wants a new Volvo. Also, how a car's transmission is like the family dog; a book from 1922 might help fix Nikki's noisy Jeep; and on Stump the Chumps, we find out if John's sister duped him when she sold him his old VW Golf. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-09-21",
        seconds: 3203.936304,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/227207737/npr_227207737.mp3",
        filename: "car_talk_2013-09-28.mp3",
        title: "#1339: Not the Wiggly Road!",
        description:
            "September 28, 2013 • This week on Car Talk, Nancy's three-year-old son is a puker. He gets car sick whenever Nancy drives on the winding Pacific Coast Highway, but comes through unscathed if Daddy is behind the wheel. Could the lead in Nancy's foot be the cause? Elsewhere, Sally's husband gave her a vintage Dodge Dart, but a brake problem has her wondering if he's really trying to bump her off. Also, Jake's car is turning into a Chia-Pontiac, growing hair in unusual places; Jason has three problems with his Dodge Colt, aside from the biggest problem--that he's driving a Dodge Colt; and Tom and Ray turn to you the audience for help figuring out the best way to drive over a washboard road. Is \"minimal contact\" a winning strategy? All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-09-28",
        seconds: 3214.995057,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/229574200/npr_229574200.mp3",
        filename: "car_talk_2013-10-05.mp3",
        title: "#1340: Arachnid and Pinion Steering",
        description:
            "October 5, 2013 • This week on Car Talk, Jeryldine's car is infested with spiders, and she has no idea how to get rid of them. If she follows Tom and Ray's advice, her car will also be full of birds, bats, lizards, and, most likely, still spiders. Elsewhere, after losing his girlfriend and her car, Glen's friend suggested he browse his neighbors' backyards for a replacement--car, that is. Will he find the Cabrio of his dreams, up on blocks? Also, Lacy thinks her Accord's engine is trying to escape, one piece at a time; Barry's dealer would be happy to work on his stuck parking brake, if Barry can only get the car to move from his garage; and on Stump the Chumps, we find out if Tom and Ray helped quiet Lisa's screeching Civic enough so she could talk to her cute neighbor. All this, plus the first Automotive Puzzler of the season, and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-10-05",
        seconds: 3215.441406,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/232745289/npr_232745289.mp3",
        filename: "car_talk_2013-10-12.mp3",
        title: "#1341: Kitty-Corner Snow Tires",
        description:
            "October 12, 2013 • This week on Car Talk, can Dave put two snow tires on his girlfriend's car, or does he need to buy a full set, as his tire dealer insists? Tom has a two-tire solution that may qualify for next year's Nobel Prize in Bad Advice. Elsewhere, Cathryn's car is going \"boom boom\" whenever her mechanic isn't around to hear it; Helen's Toyota gained and then lost an extra 100 miles per tank of gas after she moved to Salt Lake City, and, can Keith install an air conditioner in his Geo Metro, and still make it up a hill? Also, on Stump the Chumps, we find out if Tom and Ray got Pam's Volvo to stop smoking. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-10-12",
        seconds: 3215.172971,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/237778071/npr_237778071.mp3",
        filename: "car_talk_2013-10-19.mp3",
        title: "#1342: Road Trip of Destruction",
        description:
            "October 19, 2013 • This week's Car Talk features journeys both high and low. First, Tom and Ray salute aviation legend Larry Walters, who took flight in a lawn chair with balloons attached. Back on terra firma, Michaela and her siblings plan to take the family's 20-year-old car on a road trip from Oregon to, well, wherever the car finally dies. She's hoping to make it to Mexico. Tom and Ray think Salt Lake City might be a more reasonable target. Also, Mary Ann's mechanic's solution to her fuel problem could land him in jail; Heather's violating every scientific principle in getting her Subaru to start; and, on Stump the Chumps, we find out if Dale had loose spark plugs, or if Tom and Ray had loose screws when they made the diagnosis. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-10-19",
        seconds: 3224.076349,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/241026076/npr_241026076.mp3",
        filename: "car_talk_2013-10-26.mp3",
        title: "#1343: Hold the Cream Rinse",
        description:
            "October 26, 2013 • This week on Car Talk, Sharon's been experiencing a series of bad hair days when she drives long distances. Unfortunately, she couldn't get through to \"Follicle Talk,\" so she's turned to Tom and Ray. Can they stop laughing long enough to offer any useful advice? Elsewhere, Rick has a long list of reasons to justify adding a super charger to his Miata, and they're all bad; Doug's wife thinks the burning smell in his truck is dead bugs, and since he told her she's nuts, he's hoping it's anything else; and, Jon's mechanic is learning a lot about Jon's Accord--except how to fix it. All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-10-26",
        seconds: 3214.766553,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/242606295/npr_242606295.mp3",
        filename: "car_talk_2013-11-02.mp3",
        title: "#1344: Auto Acupuncture",
        description:
            "November 2, 2013 • This week on Car Talk, after Jody's mechanics failed to fix her Honda, she's considering an alternative treatment--acupuncture. So, where is an Accord's ch'i? Hopefully, not in the tires. Elsewhere, Steve promised his wife he'd fix her Volvo, but after sneaking off to three diffferent mechanics, he still can't figure out the problem. Also, should Frances trade her trusty Miata for her Uncle's beloved, but un-trusworthy Porsche; is half-way good enough for the spark plug Chuck cross-threaded; and, can Rebecca make it home for the holidays in her ancient Chevy, or will the next NPR fundraiser be dedicated to buying her a plane ticket? All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-11-02",
        seconds: 3213.934853,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/244163180/npr_244163180.mp3",
        filename: "car_talk_2013-11-09.mp3",
        title: "#1345: Forensic Mechanics",
        description:
            "November 9, 2013 • This week on Car Talk, Wendall's Bronco burst into flames and burnt to crisp, right after a 200 mile drive. Was it electrical? Fuel? A spouse holding an insurance policy? Elsewhere, Barry is hoping to find true love by fixing his co-worker's windshield wipers, and avoiding her jealous boyfriend; Donna needs a gracious way to tell her husband his theories about keeping her gas tank full are \"boooooguuss\"; and Deborah's lurching efforts to learn to drive a stick shift aren't being made any easier by her Civic's loud whine. Also, on Stump the Chumps we find out if Farmer Ben's manure spreader helped get his truck running smoothly again. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-11-09",
        seconds: 3223.990023,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/245647791/npr_245647791.mp3",
        filename: "car_talk_2013-11-16.mp3",
        title: "#1346: The Cavalier That Wouldn't Die",
        description:
            'November 16, 2013 • This week on Car Talk, Kate is desperate to get rid of her Chevy Cavalier, but her husband has vowed to keep it running for another 150,000 miles. Can Tom and Ray help her escape, and will it involve Uncle Vinny and a book of matches? Elsewhere, Sofia swears her Civic is making noise, but her mechanic says she\'s suffering from an "auditory hallucination"; and, on Stump the Chumps we find out if Christo can get his car running without banging on the fuel pump. Also, should Kate take her Corolla with her when she relocates from Ohio to St. Thomas? We know two mechanics/radio hosts who are willing to volunteer to join her. All this and more, this week on Car Talk.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-11-16",
        seconds: 3221.960408,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/246942484/npr_246942484.mp3",
        filename: "car_talk_2013-11-23.mp3",
        title: "#1347: Just Say Bang",
        description:
            'November 23, 2013 • This week on Car Talk, Tommy\'s life-long aversion to work meets its match in the U.S. Army, and his old pal Sgt. McNeely. But, little did Tommy know that his ill-fated attempt to avoid target practice would one day become official government policy in the U.K. In matters automotive, Alex loves his truck so much, he refers to its oil type as "Type O-Negative," but it may be time for it to meet its crusher; Fran can\'t decide whether to let her teenage daughter drive Grandpa\'s old Town Car, affectionately known as "The Party Barge"; and Tom and Ray try a new exit strategy for difficult questions: Diagnosis by Hypnosis. All this and lots more, this week on Car Talk.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-11-23",
        seconds: 3219.235692,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/247957749/npr_247957749.mp3",
        filename: "car_talk_2013-11-30.mp3",
        title: "#1348: Repair Via Rock",
        description:
            "November 30, 2013 • This week on Car Talk, Amy's head is spinning because her speedometer needle won't stop whizzing around in circles. Is a well-aimed rock her only hope of making it stop? Elsewhere, Suzanne's husband loves his vintage Ford Model A, but its gas fumes are destroying brain cells by the thousands. Also, Deanna's car battery tops New York City's \"Must Steal\" list; Romeo's muscle car lost its musle after a day of peeling out; and Allen's Volvo and TV are both turning themselves on at random times. Is it bad wiring, or a bad neighbor? All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-11-30",
        seconds: 3231.960136,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/249484570/npr_249484570.mp3",
        filename: "car_talk_2013-12-07.mp3",
        title: "#1349: Mechanics Standard Time",
        description:
            "December 7, 2013 • This week on Car Talk, Jim is wondering why his mechanic billed him for 8 hours of labor on a job that took only 4 hours, thereby launching a Magliozzi explanation of the mechanics' space-time continuum. Elsewhere, Lewis' VW dealer refused to honor a warranty repair, but may re-evaluate his position when he learns Lewis is an IRS agent; Abbie's friend gave her the most wacko suggestion we've ever heard to fix her car's alignment; and can Rachel hold us liable for the fender bender she caused because she was laughing at Car Talk? And, on Stump the Chumps, we find out if Tom and Ray helped put out the fire in Red's convertible, or if they just fanned the flames. All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-12-07",
        seconds: 3232.53424,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/251034251/npr_251034251.mp3",
        filename: "car_talk_2013-12-14.mp3",
        title: "#1350: Stop and Smell the Tailpipe",
        description:
            "December 14, 2013 • This week on Car Talk, what does Tommy's dog have in common with Helen's Volvo? Each tends to smell its own exhaust! But Tommy's dog isn't losing brain cells over it, while Helen may be. Elsewhere, Tom traded a set of teeth for a Chevy Caprice, but may have gotten the worse end of the deal; and, Bill's wife talked him into buying a new Impreza, but it may not be able to handle their daily drive across Big Bone Creek. Also, Jackie's pet python's dinner fell behind her dashboard, which wouldn't be a huge problem if it wasn't a live rat; and could Kai's sputtering Subaru be suffering from a case of Wandering Crud? All this and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-12-14",
        seconds: 3223.013016,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/256107111/npr_256107111.mp3",
        filename: "car_talk_2013-12-21.mp3",
        title: "#1351: Eddie and Edie Electron",
        description:
            "December 21, 2013 • This week on Car Talk, why does Michelle have to rock her car violently to get it to start? Tom and Ray have a highly advanced technical explanation, involving Eddie and Edie Electron. Elsewhere, the Magliozzis try to bring holiday peace to two married couples. First, Veronica's husband wants to re-live his childhood by buying a vintage Land Rover that's likely to spend more time sitting in the front yard than moving along the road. Later, Reed's wife wants to use his beloved Ford Bronco to tow her horse trailer. Also, retired mechanic Steve wants to try to change his own timing belt, but is worried about incurring the Wrath of Mom; and Jim's nephew used a bottle to scrape ice off the windshield of Jim's Tercel. Is the solution a buffing, or a bricking? All this and",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-12-21",
        seconds: 3215.511088,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/257898976/npr_257898976.mp3",
        filename: "car_talk_2013-12-28.mp3",
        title: "#1352: Bouncing Across Antarctica",
        description:
            "December 28, 2013 • This week on Car Talk, Summer has come to Antarctica, and the ride in John's Delta has gotten so bumpy that he and his colleagues are banging their heads on the ceiling. Closer to home, Leland's Toyota can't pull a hill. Tom and Ray should have no trouble diagnosing Leland's problem, if they can figure out what \"pull a hill\" means. Also, Steve's ex-wife has a trio of car problems, which Steve may be a little too intetrested in trying to solve; Charlie desperately wants to blame a transmission shop for his fan breaking off and damaging another car; and Erin's best solution to a math lesson gone awry may be to stand her Impreza on its side. All this plus the true meaning of Santa Fe, and more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2013,
        date: "2013-12-28",
        seconds: 3212.008231,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
