/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://cartalk.adonix.org/car_talk_2014-01-04.mp3",
        filename: "car_talk_2014-01-04.mp3",
        title: "#1401: Love (and a Mazda) in Ashes",
        description:
            "This week on Car Talk, Brent tried to start his girlfriend's Mazda, and wound up with the car, and his relationship both burnt to a crisp. Can Tom and Ray tell him where he went wrong, with the car or the girlfriend? Elsewhere, Ellen's very generous neighbor keeps giving her cases of undrinkable home-made wine. Can she put it to use as windshield wiper fluid? Also, Shelly's bad day at a casino got even worse when her car died on the drive home; and loyal delivery man Steve is suffering a severe case of \"New Parcel Truck Envy.\" Will Tom and Ray help sabotage his old, reliable truck? All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-01-04",
        seconds: 3223.207302,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-01-11.mp3",
        filename: "car_talk_2014-01-11.mp3",
        title: "#1402: Don't Look a Gift Dart Under the Hood",
        description:
            "This week on Car Talk, should Mary let her 17-year-old son accept his girlfriend's mother's offer to give him her vintage Dodge Dart? Is Mom offering the car as a dowry substitute? Elsewhere, Cathy may have to resort to riding around wearing a football helmet to get her husband to get rid of his old Corolla; Carl earns Bad Idea of the Week honors for wanting to mount a snow plow to the front of his mini-van; and Chana's Dad's advice about warming up her car may be a subtle way of telling her he thinks she's a stinko driver. Also, how on earth did a parking valet start Kenneth's Subaru with the key from Kenneth's Caravan? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-01-11",
        seconds: 3226.318594,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-01-18.mp3",
        filename: "car_talk_2014-01-18.mp3",
        title: "#1403: Another Chance to Fail Physics",
        description:
            "This week on Car Talk, if one car drafts behind another to improve its gas mileage, does the car in front suffer? Tom and Ray's answer, or lack thereof, may bring the late Physics Professor Tisza back from the grave, just to administer a dopeslap. Meanwhile, dopeslaps might also be in order for Jessica's mechanics, who will only discuss her car problems with her boyfriend, while ignoring her. Also, the solution to Nancy's Miata's hood problem may lie in her local tanning salon; Melanie is about to learn a very expensive lesson about what her oil pressure light means; and, one listener offers the real definition of \"primitive\" 4-wheel drive. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-01-18",
        seconds: 3226.962562,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-01-25.mp3",
        filename: "car_talk_2014-01-25.mp3",
        title: "#1404: Great Balls of Fire",
        description:
            "This week on Car Talk, Barry's holiday road trip through South Carolina got more exciting when his wife noticed the road behind them was on fire. Was it coincidence, or was Barry's truck an unwitting arsonist? Farther South, things are a little less exciting for Rick in Florida. His PT Cruiser's explosions are only taking place under the hood. Also, have you ever heard of a Himalayan Exhaust Transfusion? Neither have we, but it might be a great way to start a dead car on a cold day. Or, it could just be a wacko theory. And, our on-call Physics Professor Wolfgang checks in on the great drafting debate. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-01-25",
        seconds: 3220.964512,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-02-01.mp3",
        filename: "car_talk_2014-02-01.mp3",
        title: "#1405: Roadhog Day",
        description:
            "This week on Car Talk, we celebrate Road Hog Day! Will Tommy's car cast a shadow, or can we look forward to an early Spring? Then we're off to Maine, where Shlomit's husband likes to drive with two feet. Does the fact that he's a good dancer make it okay? Also, Alok learned an expensive lesson about the dangers of playing \"Hey guys, watch this,\" with his Mustang's clutch; Stephen's minivan doors are frozen shut, in part because his wife's chickens are occupying his garage; and on Stump the Chumps we find out if Tracy \"helped\" the abandoned car on her street lose its license plates, so it would get towed. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-02-01",
        seconds: 3229.32898,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-02-08.mp3",
        filename: "car_talk_2014-02-08.mp3",
        title: "#1406: Captain Destructo",
        description:
            'This week on Car Talk, from the wreckage of an old MG comes a new superhero, "Captain Destructo," ready to dope-slap stinko drivers--if he can ever get his car to run. Meanwhile, with Valentine\'s Day approaching, is it time for Beth to dump her boyfriend, after he unjustly accused her of damaging his Mustang? Elsewhere, Albee wants to sell his car to his mother-in-law, but may need to travel from Boston to Florida every month to change its bad spark plug. And, Roger\'s Toyota is emitting "Biblical" proportions of smoke after some oil changes. Is its "End Times" near? Also, should Donna leave her car running an extra 15 minutes on very cold nights to recharge the battery? What if 15 minutes turned into overnight, after her husband forgot to shut the car off? All this and more, this week on Car Talk.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-02-08",
        seconds: 3216.814422,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-02-15.mp3",
        filename: "car_talk_2014-02-15.mp3",
        title: "#1407: The Diamond in the Corolla",
        description:
            "This week on Car Talk, Dan's new used Corolla may have come with a bonus gift. The previous owner says she threw her engagement ring at her fiance and it fell behind the dashboard. Is the ring still there, or on the new fiancee of the mechanic who previously looked for it? Also this week, Jennifer says her Subaru stinks--literally. She describes its smell as a combination of \"old gas\" and \"dirty mechanic\". Will Tom and Ray be too offended to give a diagnosis? And, Turi's best solution for her smoking Acura may be to just throw her keys down the sewer; and Brother Roger got some advice on tires from a mechanic whose heart was in the right place--unfortunately, his mouth wasn't. All this, plus a Valentine's Day recap from Ray's house, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-02-15",
        seconds: 3224.422608,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-02-22.mp3",
        filename: "car_talk_2014-02-22.mp3",
        title: "#1408: Old Moses Blew Beets",
        description:
            "This week on Car Talk, beloved dog meets beloved car, and the results aren't good, as Will's dog Moses gets car sick in his truck; specifically, into the defroster vents. Can Will remove the chunks and the smell, or does he need to sell the truck to someone with a really bad sense of smell? Elsewhere, Kris' husband is a dedicated recycler. Unfortunately, he insists on crushing cans by driving over them, and the noise has Kris wondering if she needs to recycle her spouse. Also, what could make an already brutal Maine winter even worse? Eric's truck horn, which starts honking in zero degree weather, in the middle of the night. And, can Tom and Ray cure novice mechanic Jeremy of his bolt-breaking habit? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-02-22",
        seconds: 3230.194875,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-03-01.mp3",
        filename: "car_talk_2014-03-01.mp3",
        title: "#1409: The Curly Package",
        description:
            "This week on Car Talk, did Howard get the special Three Stooges option on his Lincoln, or is there another reason why it sounds like Curly whenever he gets out of the car. Elsewhere, Tom got conflicting advice on his Taurus' flashing oil light, and he's wondering who's the genius, and who's the quack. So, who better to ask than two genius quacks? Also, John's Land Cruiser may need a new steering box, or his mechanic may just be looking for another John-funded trip to Vegas; and on Stump the Chumps, we find out if Betsy's truck was really spewing gas because of mud chiggers. All this, plus how one listener's attempt to solve the Puzzler resulted in a police house call, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-03-01",
        seconds: 3224.708776,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-03-08.mp3",
        filename: "car_talk_2014-03-08.mp3",
        title: "#1410: Car Talk Vs The Marital Industrial Complex",
        description:
            "This week on Car Talk, will James and his fiancee incur the wrath of Miss Manners and their families by registering for gifts at Louie's Lexus rather than Chafing Dishes R Us? Elsewhere, Puzzler Master Will Shortz is having trouble starting his Saab. Will Tom and Ray trade a diagnosis for the answer to 9 Down? Also, Mike may need a gregarious gullible geek to help figure out why his car is creaking; Susan's brother hit new heights of bogosity by trying to convince her she's freezing in his car because it's too efficient; and can Eric spend his summer driving the Alcan highway with his dad and sister, and remain on speaking on terms with either one? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-03-08",
        seconds: 3221.00415,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-03-15.mp3",
        filename: "car_talk_2014-03-15.mp3",
        title: "#1411: Potholes and Bowling Balls",
        description:
            "This week on Car Talk, pothole season is in full swing. After her Toyota was almost swallowed by one crater, Sara's wondering what happens to the departed asphalt. Elsewhere, Steve drove over a bowling ball outside a topless bar, which sounds like a great joke set-up, but the punchline could be very expensive. Also, Shanthi is ready to buy a car, but has no place to park it. Does she need to move, or should she forget about the car and keep mooching rides from her friends? And, how can Johanna make sure her summer of teepee living doesn't start with her car getting washed away by spring flooding? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-03-15",
        seconds: 3215.923673,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-03-22.mp3",
        filename: "car_talk_2014-03-22.mp3",
        title: "#1412: The Truth Detector",
        description:
            "This week on Car Talk, Tom and Ray help test a device that should strike fear in the hearts of all mechanics: a voice biometrics-based lie detector. Elsewhere, Corinne can't seem to get an oil change without a broken dipstick as a bonus; Christine's keys are stuck in her ignition--which may not be too worrisome, since her car won't start; and can struggling musician Dan fix his van's exhaust with guitar strings and an orange juice can? Also, a story that offers even more proof why you should never drive like Tommy! All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-03-22",
        seconds: 3229.12449,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-03-29.mp3",
        filename: "car_talk_2014-03-29.mp3",
        title: "#1413: The Fall of the Dart",
        description:
            "This week on Car Talk, all good things must come to an end. So too, must all pieces of junk, as Tommy's beloved Dodge Dart finally heads to the crusher. Find out what caused its way-beyond-timely demise. Elsewhere, Fred decided to do a good deed and close the door of a stranger's parked truck. Unfortunately, a half hour later said truck caught on fire. Is Fred an unwitting arsonist? Also, Dr. Kenny takes a break from surgery to find out why his car's brakes have a mind of their own; and Monica's husband may need electroshock therapy to stop his odd behavior at stop lights. All this, plus a round of Stump the Chumps, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-03-29",
        seconds: 3226.82458,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-04-05.mp3",
        filename: "car_talk_2014-04-05.mp3",
        title: "#1414: Ode to the Dart",
        description:
            "This week on Car Talk, one listener's tribute to Tommy's dearly departed Dodge Dart will have William Wordsworth rolling over in his grave. \"For in the spot where Dart once sat, there's now but oil stains.\" Later, Tom and Ray try to rescue a spoon trapped in one car's vents, and a 20-dollar bill trapped in a driver's door; and, on a slighlty more urgent note, they try to keep Eric's engine from disintegrating. Elsewhere, Doug might become the Chuck Yeager of CV joints if he doesn't mind the risk of getting stuck on a railroad track; and can Environmental Studies major Carl do anything to ease his guilt over driving two ginormous gas guzzlers? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-04-05",
        seconds: 3209.984059,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-04-12.mp3",
        filename: "car_talk_2014-04-12.mp3",
        title: "#1415: The Ant Picnic",
        description:
            "This week on Car Talk, Mara has tried everything to rid her car of its ant infestation. Well, maybe not everything, since there are no burn marks. Tom and Ray have a way to lure them out that is at once incredibly creative-- and very stupid. Elsewhere, how does Diane reconcile her husband's desire to rebuild his BMW with her parent's need to get it off their farm, so the potatoes can be planted? Also, a lesson to car dealers: if you're going to make up a name for your wife, choose one you know how to spell. And, on Stump the Chumps, we find out if Tom, Ray, and Joan's husband can correctly diagnose her screeching Ford Festiva. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-04-12",
        seconds: 3217.025805,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-04-19.mp3",
        filename: "car_talk_2014-04-19.mp3",
        title: "#1416: I Dream of Fairlanes",
        description:
            "This week on Car Talk, the Auto-Psychiatry booth is open, as Dennis tries to figure out why he dreamed about being offered a 1966 Ford Fairlane. Is a Fairlane memory buried in his past, or to paraphrase Dr. Freud, is a heap just a heap? Meanwhile, over in the Auto-Relational Department, Donna treated herself to a spiffy Mazda Miata, but can't get her husband to relinquish the steering wheel. Also, Tamson's mechanic may be using the \"slow milking\" approach to diagnosing her Beetle's noise; Ray has a few final words on Tommy's Dart; and does Dave need driving lessons or relaxation therapy to prepare for a Summer trip through Ireland with five women? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-04-19",
        seconds: 3216.040612,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-04-26.mp3",
        filename: "car_talk_2014-04-26.mp3",
        title: "#1417: The Telltale Grease",
        description:
            "This week on Car Talk, Robin is racked with guilt after taking her Corolla to the dealer for its 30,000 mile service, rather than her trusty mechanic. Should she fess up before her mechanic notices there's someone else's grease under the hood? Elsewhere, Wendy's mechanic is so baffled by her Golf's noise that he's consulted a Ouija board; Dee tried to get rid of his truck's noise by driving it into the side of a car; and Amy's husband is brilliant at everything-- except keeping his car on the right side of the road. Also, should Scott listen to his uncle's advice and disconnect the odometer on his Accord? (Do we need to mention that Scott's uncle is a used-car salesman?) All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-04-26",
        seconds: 3232.819342,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-05-03.mp3",
        filename: "car_talk_2014-05-03.mp3",
        title: "#1418: The Ungrateful Passenger",
        description:
            "This week on Car Talk, Jere agreed to drive her sister's co-worker's husband to work. How did he thank her? By telling everyone (including Jere) she's a stinko driver. Elsewhere, Dorothy had to rig a wire to her Land Rover's fan to keep it from shredding the radiator, during her daily drive in Botswana. Will this brilliant solution cook her engine? Also, on Stump the Chumps, we find out if the \"Godfather strategy\" helped Joe convince his brother-in-law to remove an old Honda Civic from Joe's yard; and did a hammer and a \"Hey guys, watch this!\" really fix Hendie's brake noise? All this and more, this week no car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-05-03",
        seconds: 3217.971156,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-05-10.mp3",
        filename: "car_talk_2014-05-10.mp3",
        title: "#1419: The NYU Application",
        description:
            "This week on Car Talk, Tom and Ray say they've never met a noise they didn't like, but that's before they encountered the odd thumping sound Janet's truck is making. And then there's the sound of their dear Mom Elizabeth, calling to celebrate Mother's day by complaining about her sons' poor gift selections. Elsewhere, from the Questionable Ideas department, Mark wants to use his Ford Tempo to tow a trailer from Dallas to Pennsylvania; Jonathan is considering using a turkey baster to drain his car's power steering fluid; and Missy's 18-year old son wants to buy an Audi Quattro to keep on campus at Boston University. All this, plus the best college application essay ever, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-05-10",
        seconds: 3218.971224,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-05-17.mp3",
        filename: "car_talk_2014-05-17.mp3",
        title: "#1420: Eggs Prestone",
        description:
            "This week on Car Talk, Sasha learned a new recipe for dealing with a radiator leak--add black pepper and eggs. Did this combo save his engine, or at least provide brunch while he waited for a tow truck? Elsewhere, does Chip need to resort to \"tailpipe diplomacy,\" in the form of a cherry bomb, to get his neighbors to stop warming up their cars for 20 minutes every morning? Also, Bill and his wife are looking for a $700 car that makes them look eccentric rather than cheap; Jennifer's good deal on a used Volvo may not have been so good; and can Tom in California adjust to his new life as a car salesman without succumbing to the white belt and shoes? All this, plus one tourist's eye-opening visit to Car Talk Plaza, and lots more.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-05-17",
        seconds: 3218.154943,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-05-24.mp3",
        filename: "car_talk_2014-05-24.mp3",
        title: "#1421: My Dog Hates You Too",
        description:
            "We stopped tallying the hate mail we've received at Car Talk years ago. But one letter still remains on top of our pile of vituperative missives: this week's offering from one Melissa Peterson, a.k.a., \"That Little Twerp.\" Maybe it was her need to let us know that her dog hates our show as much as she does. But Tom and Ray will soldier on, despite Melissa's wrath, and try to convince Gloria that shutting off her car while going 80 miles per hour is not a great way to address its acceleration problems. Elsewhere, Tracy wants to blame her mom for her Civic's electrical system going wacko; and Tammy is trying without success to convince her husband that Boston drivers aren't the worst in the world. And, can Evan find a car with a gas pedal that won't destroy his knee? All this and more, this week, on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-05-24",
        seconds: 3226.74059,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-05-31.mp3",
        filename: "car_talk_2014-05-31.mp3",
        title: "#1422: Mattress Aerodynamics",
        description:
            "This week on Car Talk, Howard needs to drive a mattress from Boston to “Hunga-Dunga”, and wants to know how to keep it from flying off the roof of his car. Tom and Ray know one method that won’t work, as evidenced by an ill-fated attempt to transport 18 sheets of plywood. Elsewhere, Tina just learned a scary and stinky lesson why you shouldn’t drive drive down a mountain in Neutral; Jerry is looking for an alternative to the “stick and ballet pose” method he’s using to get his convertible top to work; and, on Stump the Chumps, we find out if Elisa accepted her parents’ bribe, um we mean, “generous offer” to buy her a new car if she married her live-in boyfriend. And, by popular demand, aonother reading of the Melissa letter. All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-05-31",
        seconds: 3220.936916,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-06-07.mp3",
        filename: "car_talk_2014-06-07.mp3",
        title: "#1423: Dead Bugs and a Burnt T-Bird",
        description:
            "This week on Car Talk, Gary's mother-in-law is blaming him for her car catching fire after he worked on the carburetor. Can Tom and Ray get Gary off the hook, and, more importantly, get his mother-in-law out of his house? Elsewhere, Barry's noticing a plethora of dead bugs on his windshield, and thinks driving faster should reduce the casulaty rate. Also, Denise may have bitten off more than she can chew by giving into her mid-life-crisis impulse buy of a vintage Volvo; Alan is considering a sitz bath to get his truck to start shifting; and Darlene can't decide which bubble-headed friend's advice to follow on filling her gas tank, so she's turning to two more bubble-heads. All this, plus one listener's rebuttal to Melissa Peterson, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-06-07",
        seconds: 3215.895079,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-06-14.mp3",
        filename: "car_talk_2014-06-14.mp3",
        title: "#1424: See Food Diet",
        description:
            "This week on Car Talk, Click and Clack fork over a diet not to be missed. Spoiler alert.... you're not actually allowed to eat! Then it's off to help Doctor Gary with an ethical conundrum. If he gives his mechanic car advice, can the mechanic start giving Gary medical tips? Carole wants to know what kind of car she should take to Africa, and has an automotive-fashion question: should she stock up on jog bras for the rough roads ahead? And in Phoenix, Caesar gets some help with his love life. All that, plus a spine tingling puzzler, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-06-14",
        seconds: 3152.331088,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-06-21.mp3",
        filename: "car_talk_2014-06-21.mp3",
        title: "#1425: Mechanics Fantasy Camp",
        description:
            "This week on Car Talk, can Bubba convince his neighbor that he doesn’t need to warm up his diesel monster truck for 30 minutes every morning, and not wind up with said monster truck driving across his front yard? Also, should Wendy dump her bureaucrat boyfriend after his cavalier response to her smoking car? Elsewhere, Paco’s van is stalling on right turns, and his kids are getting tired of having to get out and push; Lani’s trip to the gas staton got a little more exciting when flames shot out of the tank; and, suspense novelist David needs guidance on blowing up his hero’s Aston-Martin. Finally, what does Sylvia Poggioli really say when she hears Tom and Ray besmirching her radio? Find out, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-06-21",
        seconds: 3216.80034,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-06-28.mp3",
        filename: "car_talk_2014-06-28.mp3",
        title: "#1426: The Sleek Black Beauty",
        description:
            "This week on Car Talk, Tom recounts a day that will live in Magliozzi family infamy-when Ray sent his beloved 1965 AMC Ambassador, a.k.a., \"The Sleek Black Beauty,\" to the crusher. Elsewhere, Ron's check engine light has been on for 75,000 miles, and he's beginning to think it might be time to figure out what's causing it; Ellen's looking for an intervention to help cure her fiancé of his non-stop shopping for performance add-ons for their Blazer; and, can Casey's career as a bagpipe maker help rid his car of garter snakes? And, from the Department of Gender Numismatics, why do women pay for things with change and men don't? All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-06-28",
        seconds: 3237.027029,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-07-05.mp3",
        filename: "car_talk_2014-07-05.mp3",
        title: "#1427: The Beemer Smell",
        description:
            "This week on Car Talk, do BMW’s really have a unique aroma, and if so, how come Diane’s husband can smell it while she can’t? Is it only discernible to men on the verge of a mid-life crisis? Elsewhere, Ed’s having trouble shifting his car out of Park, and his solution may give his insurance company an ulcer; and, Tom and Ray try to stop Steven’s mirrors from twitching before he drives into a ditch. Also, how one student’s GPA plummeted after she listened to a single episode of Car Talk; and in an effort to improve inter-species communication, Tom and Ray translate mechanics’ grunts into English. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-07-05",
        seconds: 3227.970635,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-07-12.mp3",
        filename: "car_talk_2014-07-12.mp3",
        title: "#1428: Death Valley Dinesh",
        description:
            "This week on Car Talk, Dinesh is planning to spend his Summer vacation walking across Death Valley. Yes, really. Dinesh is worried about his support cars surviving the 120 degree daytime temps. Can Tom and Ray stop questioning Dinesh’s sanity long enough to advise? Elsewhere, Deb threw her husband’s BMW into Park while it was still moving. Did she do more damage to the car, or her marriage? Also, Steve wins Fun Dad of the Week— but it came with a full spousal dopeslap for driving across a stream that was deeper than expected; Mary is desperately trying to help her beloved mechanic Herman figure out why her Toyota won’t start; and, is it okay for Art History PhD’s to call themselves “Doctor”? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-07-12",
        seconds: 3228.234603,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-07-19.mp3",
        filename: "car_talk_2014-07-19.mp3",
        title: "#1429: Click and Clack Vs Electric Brakes",
        description:
            "This week on Car Talk, can Tom and Ray help Paul fix the electric brakes on his cattle trailer? Will the fact that they've never even heard of electric brakes stand in their way? Of course not! Elsewhere, Kate can't get her mechanic to take her Acura's brake problem seriously, and Alice and her husband can't agree on whether to take the high road or the low road to go visit their daughter. Also, Marian's truck is having trouble adjusting to life in Cleveland; Army Captain Rob may have to go AWOL to get out of a Summer road-trip with his in-laws, and should Erin ease her husband's descent into Minivan Land by letting him keep his BMW? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-07-19",
        seconds: 3224.999796,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-07-31.mp3",
        filename: "car_talk_2014-07-31.mp3",
        title: "#1430: The Andy Letter",
        description:
            "This week on Car Talk, do two people who don’t know what they’re talking about know more or less than one person who doesn’t know what he’s talking about? Andy thinks Tom and Ray’s recent “pas-de-deux of breathaking speculation” on electric brakes may have answered this question definitively. Elsewhere, Evan’s son stuffed a golf ball into her car’s exhaust, and she worried it may land a hole in one right in the middle of her engine; Christine can’t evict a colony of ants living in her car’s headliner; and Todd’s noisy truck gives Tom a chance to re-live his Army days wih the long-suffering Sgt. McNeeley. Also, one listner’s proposal to re-arrange the days of the week—it’s brilliant, even if it does leave us with five Tuesdays. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-07-31",
        seconds: 3225.187574,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-08-02.mp3",
        filename: "car_talk_2014-08-02.mp3",
        title: "#1431: The Bet",
        description:
            "This week on Car Talk, the Great Sleek Black Beauty bet is settled, as we find out if Patti’s mom made it from Houston to Boston in her Datsun. Does Ray need to start searching for a ’65 Ambassador, or is Tommy forever banned from uttering the words, “sleek black beauty”? Elsewhere, Jill’s Civic sounds like Frankenstein, and Aron’s Nissan is imitating Larry from the Three Stooges. Also, how can Craig make his minivan more sexy, other than trading it for a Porsche? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-08-02",
        seconds: 3227.012653,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-08-09.mp3",
        filename: "car_talk_2014-08-09.mp3",
        title: "#1432: Pinkwater and the BMW Owner's Manual",
        description:
            "This week on Car Talk, Daniel Pinkwater opened his BMW owner’s manual, and discovered it included exercise and diet tips. Is BMW being extra thoughtful or do they just want to make sure Daniel stays alive long enough to finish paying off the car? Elsewhere, Mary Lynn’s husband has been telling her to ignore her car’s scary thumping noise, so she’s hoping to get it fixed while he’s away in China. Also, Reine’s husband may have gotten his wallet flushed along with an unnecessary radiator flush; and Bob’s got a ’65 Ambassador convertible for sale, and heard there might be a radio show host in the market for one. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-08-09",
        seconds: 3223.983991,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-08-16.mp3",
        filename: "car_talk_2014-08-16.mp3",
        title: "#1433: The Male Automotive Ego",
        description:
            "This week on Car Talk, Emily dared to correctly diagnose her male friend's car problem (the horror!) but did her automotive intelligence ruin a potential relationship? Elsewhere, Ted’s solution to his van’s leaky exhaust may win a prize for modern sculpture, but will it also kill his engine? Also, Linda needs to use a hair dryer to start her car in weat weather; and from the “be careful what you wish for” department, Jeff wants to get his reluctant 18-year old son to start driving or risk never getting a date. Finally, yet another philosophical theory that explains Tom and Ray: “learned ignorance.” All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-08-16",
        seconds: 3215.032472,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-08-23.mp3",
        filename: "car_talk_2014-08-23.mp3",
        title: "#1434: Foreign Accent Syndrome",
        description:
            "This week on Car Talk, a Massachusetts man begins speaking with a French accent after an accident. Thus we are introduced to Foreign Accent Syndrome, a neurological oddity which Tommy will be happy to explain, if he can ever stop laughing. Elsewhere, what goes in, must come out—unless ”it” is a piece of the Berlin Wall, stuffed into the trunk of a BMW. A few thousand miles away, John is having the opposite problem—his Bronco’s dipstick refuses to stay in. Also, should Julie fess up about her fender bender in the family van? And, Crystie dropped a nail into her gas tank, and is worried about an explosion. Her mechanic and the Chevy dealer refuse to take her seriously—and she thinks Tom and Ray will? Find out, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-08-23",
        seconds: 3221.490816,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-08-30.mp3",
        filename: "car_talk_2014-08-30.mp3",
        title: "#1435: Richard, His Goats, and Doris",
        description:
            "This week on Car Talk, Richard the Goat Rescuer's new pals like to climb on things—including cars, and especially Richard's girlfriend's Alfa Romeo. Does Richard need to turn to shock therapy to ground the goats and save his relationship? Elsewhere, Jeff's Isuzu needs a new engine, but Jeff is worried that a transplant will irrevocably change his car's soul. Can Tom and Ray provide some divine guidance on this existential-automotive conundrum? Also, Helena and her husband found a dream used car with one idiosyncrasy—it only goes in Reverse. Good thing it came with a spare transmission in the trunk. And, guess what turned up in a government auction—Sonja Henie's tutu! Find out how, this week on Car Talk",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-08-30",
        seconds: 3226.937551,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-09-06.mp3",
        filename: "car_talk_2014-09-06.mp3",
        title: "#1436: The Spaceman Cometh",
        description:
            "This week on Car Talk, former Red Sox pitcher Bill “Spaceman” Lee plays a round of Stump the Chumps. Find out if Tom and Ray helped get Bill’s BMW running, or thrown one way over the backstop. Elsewhere, Jeff promised his girlfriend he’d get a driver’s license this Summer. The calendar has turned, and Jeff is still sans license, so what he needs now is a good excuse. Also, Ashley loves her Beetle, but it may be killing her with CO poisoning; Chris wants to know how big a dope slap to give her husband for keeping the heat on during a six-hour drive in 96 degree temperatures; and can Tom and Ray do any better diagnosing a broken lawnmower than they did on electric brakes? Well, they couldn’t do worse, right? All this and more, this week on Car",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-09-06",
        seconds: 3226.4322,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-09-13.mp3",
        filename: "car_talk_2014-09-13.mp3",
        title: "#1437: The Twin Schwinn Blowout",
        description:
            "This week on Car Talk, Darlene's bumpy road-trip prompts Ray to remember his explosive lesson about the dangers of over-inflated tires. Elsewhere, Cynthia hopes Tom and Ray can settle her brothers' tug-of-war over a vintage Camaro, but it's more likely they'll just add a Magliozzi family feud to the mix. Also, Bill's steering wheel is re-enacting \"Ghostbusters\" by oozing an odd substance; Marsha's wondering if adding oil to her coolant is the end of the world, or at least the end of her Previa; and on Stump the Chumps, we find out if marriage cured Ellen's fiance of his high-performance add-on addiction. All this, plus the return of the Puzzler, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-09-13",
        seconds: 3215.684082,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-09-20.mp3",
        filename: "car_talk_2014-09-20.mp3",
        title: "#1438: A Bad Case of Witzelsucht",
        description:
            "This week on Car Talk, Tom and Ray delve into the complexity of the mother-daughter relationship. Since they fit into neither category, fortunately their own Mom and sister both weigh in. All of this is prompted by Nancy’s ill-advised decision to tell her adult daughter she waited too long to rotate her tires. Elsewhere, Herbert loves his VW, except for its annoying habit of bursting into flames; Ronnie Sue’s underwear came to the rescue when she burst a heater hose; and can all of Tom and Ray’s behavior be symptoms of an obscure German medical condition called “Witzelsucht”? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-09-20",
        seconds: 3213.991383,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-09-27.mp3",
        filename: "car_talk_2014-09-27.mp3",
        title: "#1439: The Hyperbaric Chamber of Love",
        description:
            "This week on Car Talk, is Scott obligated to marry his girlfriend, after she passed out from carbon monoxide poisoning in his Land Cruiser? Elsewhere, Ginny and her husband disagree over the optimal speed to drive on a road populated with frogs without croaking them (sorry). Also, a year of a flashing brake lights and noisy brakes has convinced Jim his van may have a brake problem; Camille may have to purge her key ring to save her Golf; and will this week’s Puzzler Answer give Tom and Ray yet another F in Physics? Find out, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-09-27",
        seconds: 3222.7622,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-10-04.mp3",
        filename: "car_talk_2014-10-04.mp3",
        title: "#1440: The Twerp, The Geek, and the Swinger",
        description:
            "This week on Car Talk, Melissa Peterson (a.k.a., “That Little Twerp”) returns with another helpful Car Talk critique. How can Tom and Ray manage to be hippies and geeks at the same time? Elsewhere, Quentin needs to decide whether to take his grandfather’s Dodge Dart Swinger, or keep his blood pressure regulated by just taking Grandpa’s hat from the front seat. Also, Beth’s trailblazing adventure left her Jetta missing a few parts she hopes are non-essential; newly unemployed Bernadette is considering a move from one non-profit to another by entering the world of auto-repair, and on Stump the Chumps, we find out if Geoff’s noise really was the sound of one pad slapping. All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-10-04",
        seconds: 3223.963673,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-10-12.mp3",
        filename: "car_talk_2014-10-12.mp3",
        title: "#1441: Two Tanks in Every Trunk",
        description:
            'This week on Car Talk, Cheryl’s brother has a brilliant solution to his rotting gas tank that could set the entire state of New Jersey on fire—but does that make his idea any less brilliant? Elsewhere, Mike wants to drive his truck into the ground. Oh wait, the truck\'s "belt habit" might have already beat him to it. Tamara is considering dumping her beloved Vanagon for a car with modern conveniences, like a horn; and, can Jim make it through a New England winter in a Civic with no heat, and no dashboard? All this and lots more, this week on Car Talk.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-10-12",
        seconds: 3230.628209,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-10-18.mp3",
        filename: "car_talk_2014-10-18.mp3",
        title: "#1442: Door Tied Shut",
        description:
            "This week on Car Talk, Melissa’s driver’s door wouldn’t stay shut. So she ran to the nearest body shop, right? Um, no—she tied the door to the seat, and has been climbing in through the passenger seat for the last several weeks. Is it time for a Car Talk Cheapskate Intervention? Elsewhere, Colleen’s Dad told her she couldn’t drive his car because he had to break in its new brakes. Was this really a mechanic’s order, or could it be Dad’s way of telling Colleen he thinks she’s a lousy driver? Also, will a flush remove the debris that might be the only thing keeping Reed’s transmission from falling apart? And, if Katie thinks she has gas that’s too old for her cheap camp stove, why on earth is she considering dumping it into her $20,000 car? All this, and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-10-18",
        seconds: 3230.961995,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-10-25.mp3",
        filename: "car_talk_2014-10-25.mp3",
        title: "#1443: Men Who Pick",
        description:
            "This week on Car Talk, Jill has noticed a raft of men picking their noses in their cars. Is this topic too juvenile and tasteless even for Tom and Ray? Are you kidding? Tune in as they dive deep to try to explain why a man’s car is his nostril's sanctuary. In matters a bit more serious, Paul’s car is smoking like a chimney,and he’s hoping to find the right additive cocktail that will get it through to spring; Bernie and Rollie’s test drive at a dealer ended with an encounter with a light pole, and now the dealer is trying to get them to pay for the damage; and is Jenny or her budding bryologist fiance right about her Civic’s starting problem? All this and lots more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-10-25",
        seconds: 3223.984649,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-11-01.mp3",
        filename: "car_talk_2014-11-01.mp3",
        title: "#1444: His and Her Trailers",
        description:
            'This week on Car Talk, Wendy’s husband wants to rent two trailers to move their belongings across the country. That’s all well and good for his truck, but will it destroy her Accord? Elsewhere, J.D. just lost his girlfriend, and may be about to lose his beloved van, too. Can Tom and Ray help him save either one? Also, budding acupuncturist Jody wants to quiet her car by finding its chi; Jane wants to buy a stretch limo to drive around town in, but everyone thinks she’s nuts— except her grandkids, and Tommy; and how did Scott’s Ford Focus move across a Home Depot parking lot while he was shopping? All this, plus listener theories on in-car “Nasal Decloggery," and lots more, this week on Car Talk.',
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-11-01",
        seconds: 3232.053107,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-11-08.mp3",
        filename: "car_talk_2014-11-08.mp3",
        title: "#1445: Tommy, Riposa in Pace",
        description:
            "This week on Car Talk, we pay tribute to our beloved brother, friend, and co-host Tom Magliozzi, who passed away Monday, November 3rd. You’ll hear many of our favorite moments featuring Tom the consummate radio professional, Tom the philosopher king, Tom the storyteller, and ultimately Tom, the guy who enjoyed nothing more than to sit with his brother and all you listeners for an hour a week, laughing his butt off. This special edition of the show will be hosted by Ray. We’ll be listening, and we hope you will, too.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-11-08",
        seconds: 3358.936349,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-11-15.mp3",
        filename: "car_talk_2014-11-15.mp3",
        title: "#1446: Stop and Smell the Antifreeze",
        description:
            "This week on The Best of Car Talk, Alan thinks his Mercedes came with a 100,000-mile, self-destruct program. It’s suffered a series of problems since the odometer rolled over and, with the Check Engine light now linked to his MasterCard account, Alan thinks it may be time to move on. Elsewhere, Fred lied to his wife about loving his friend’s new car, and was punished by receiving the same car as a birthday present. Should he ‘fess up and risk the consequences, or suffer for the next 150,000 miles? Also, do Tom and Ray have enough liability insurance to help Keri soup up her Hornet scooter so she can win a rematch against a Vespa? All this and more, this week on Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-11-15",
        seconds: 3263.997528,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-11-22.mp3",
        filename: "car_talk_2014-11-22.mp3",
        title: "#1447: The 3-Speed Potter's Wheel",
        description:
            "This week on Car Talk, can Jim use an old car transmission as a potter's wheel? Reverse could come in handy next time he mis-throws a pot. Elsewhere, Cindy's friends say her Mercedes is scaring off prospective dates with guys whose cars aren't as nice as hers; grad student Christine's parents offered her a free Buick station wagon, but Christine can't decide if the embarrassment of driving it is too costly; and we meet Tom and Ray's new BFF—Sal, the quintessential New Yorker. Sal is a retired mailman, but he may still have to get up at the crack of dawn this winter if he wants his car to move. All this and more, this week on The Best of Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-11-22",
        seconds: 3266.000204,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-11-29.mp3",
        filename: "car_talk_2014-11-29.mp3",
        title: "#1448: The Chunk in the Trunk",
        description:
            "This week on The Best of Car Talk, did Tom and Ray help Dana and her friend remove a chunk of the Berlin Wall from his Dad's BMW? Dana's back for a round of Stump the Chumps. Spoiler alert: the word \"Dummkopfs\" is used. Elsewhere, David thinks his Volvo is giving him Legionnaire's Disease; Glenn has mice living in his Miata, and fears he'll have to bring them along on his road trip from New Orleans to Oregon. And, Leanne is hearing a horrible grinding noise when she uses her new key in her husband's Pathfinder. Is it coming from the car or her husband's teeth? All this and more, this week on The Best of Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-11-29",
        seconds: 3289.003787,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-12-06.mp3",
        filename: "car_talk_2014-12-06.mp3",
        title: "#1449: Dee's Hot Seat",
        description:
            "This week on Car Talk, Dee is freezing her butt off now that winter is here. Can Click and Clack help her toast her tush in her Dodge Durango? Sybil has a vexing noise, and becomes a garage apprentice as she heads out to the driveway to make the diagnosis. Meanwhile, Craig wants to know, what's the deal with gas tanks and why can't they all be on the same side? Jessica is hoping her Audi can be fixed so she doesn't have to make it through winter on her boyfriend's scooter. And David. Poor David. His Honda Accord is sending him to financial ruin. If he coughed up another eight cents a day, could he really be in a new car? All that, plus some earth shattering research on parking spaces, this week on The Best of Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-12-06",
        seconds: 3256.767778,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-12-13.mp3",
        filename: "car_talk_2014-12-13.mp3",
        title: "#1450: How to Calm An Angry Co-Host",
        description:
            "This week on Car Talk, have Tom and Ray found a more productive way to settle their disagreements than, \"You moron\"? Find out as they differ over whether John should dump his family's beloved Chevy before its hyper-sensitive brakes send the family dental bills into 7 figures. Elsehwere, Phil's wife thinks she'd be less paranoid about her car breaking down if she was married to a mechanic; Dennis is looking for a non-combative gesture to let other drivers know he's sorry for cutting them off; and after a year of listening to her Volvo moan Alice has decided it's finally time to figure out what's ailing it. All this, plus some gift ideas straight from the floors of Car Talk Plaza, and lots more, this week on The Best of Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-12-13",
        seconds: 3210.484331,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-12-20.mp3",
        filename: "car_talk_2014-12-20.mp3",
        title: "#1451: Excellence in Worthlessness",
        description:
            "This week on Car Talk, Tom and Ray are honored with the first (and probably last) award for Excellence in Worthlessness. They immediately prove themselves worthy, by dodging Dodie's question about overdrive on her Nissan, and instead focusing on the two sons who didn't help buy her the car. And, Rebecca's BMW's noise is less intriguing than why she broke up with the boyfriend who gave it to her. Also, how steamer trunks helped derail Steve's plan to restore a vintage Buick; And, why holiday overeating may not be such a bad idea. All this and more, this week on The Best of Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-12-20",
        seconds: 3256.976553,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
    {
        url: "https://cartalk.adonix.org/car_talk_2014-12-27.mp3",
        filename: "car_talk_2014-12-27.mp3",
        title: "#1452: Max and the Schnauzer",
        description:
            "This week on The Best of Car Talk, it's one of our all-time classic calls, and the shaggiest of shaggy dog stories—Max the mechanic's heroic attempt to replace his customer's beloved pet dog. Elsewhere, Major Tom's Jeep is acclimating to its new home in Colorado by doing 360's on ice; Toast's battery drains in the rain, even if the car isn't running; and Louann's Civic is fouling plugs, and her mood. Also, can Natalie welcome Dad home from vacation by saying anything other than, \"I dented your car?\" All this and more, this week on The Best of Car Talk.",
        artist: "Click and Clack",
        album: "Car Talk",
        year: 2014,
        date: "2014-12-27",
        seconds: 3242.091519,
        artists: ["Tom Magliozzi", "Ray Magliozzi"],
        channels: 1,
        genre: ["Humor", "Podcast", "Talk"],
    },
];
