/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/374795346/npr_374795346.mp3",
        filename: "car_talk_2015-01-03.mp3",
        title: "#1501: Le Crouching Tiger",
        description:
            "This week on the Best of Car Talk, \"60 Minutes\" correspondent Morley Safer turns the hot lights on Tom and Ray. Allegations of financial malfeasance? A class-action suit over bogus Puzzlers? No, Morley's just annoyed that he can't find parts for his beloved Peugeot, aka, the \"Crouching Tiger\" in his garage, and he blames Tom and Ray's relentless Peugeot bashing. Elsewhere, Jane is convinced her van's gas tank is shrinking; Peter killed his Accord's battery but can't understand why the alarm is still sounding; and, can Adrienne convince her daredevil husband that driving down mountain passes with the cruise control on is not good for her car, or their odds to live to see another ski weekend? All this, and lots more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-01-03",
        seconds: 3214.762132,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/376362178/npr_376362178.mp3",
        filename: "car_talk_2015-01-10.mp3",
        title: "#1502: Sonja Henie's Tutu",
        description:
            "Ever wonder why Tom and Ray exclaim, \"Sonja Henie's tutu!\", seem to need haircuts with an unusual urgency, or got the idea that somebody moved the Alamo? This week on The Best of Car Talk, we share the tales behind the phrases that usually make the guys blow milk out their noses just by their mere mention. In matters auttomotive, Judy's husband is telling her to ignore her ever-rising temperature gauge despite already cooking one engine; Will wants to put the entire windhsield wiper fluid industry out of business; and Paula's friend killed her battery by leaving the lights on, and then blamed her car. All this and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-01-10",
        seconds: 3251.857982,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/377993070/npr_377993070.mp3",
        filename: "car_talk_2015-01-17.mp3",
        title: "#1503: Return of the Schnauzer",
        description:
            "This week on The Best of Car Talk, we answer the question that has been keeping America awake for weeks—did Max the mechanic find a home for his namesake schnauzer? Elsewhere, Bob swears that smashing his Volvo into a rock improved its performance; Rick's girlfriend's VW spent the weekend in the shop and came back with an additional 20,000 miles on the odometer; and Lisa's Estonian Moskvitch dies, and will only re-start if she jams a piece of wood into the ignition. Also, Tom and Ray try to referee a family dispute over a boardgame and maange to turn Brain Quest into Dummy Quest. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-01-17",
        seconds: 3200.459887,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/379626985/npr_379626985.mp3",
        filename: "car_talk_2015-01-24.mp3",
        title: "#1504: The PII Range Rover",
        description:
            "This week on The Best of Car Talk, Danni bought a used Range Rover in the midst of what she calls pregnancy-induced insanity. Reality quickly set in, as her skyscraper-esque husband couldn't fit in the car, and it racked up a few thousand dollars in repair bills in no time. Should she cut her losses and dump this impulse buy? Elsewhere, Charlie had to replace his fuel pump three times in the last year, and is tired of having them fall on his chest; Kristy may need a stethoscope and a potato to figure out why her car is making noise; and physicist Robert is too busy trying to solve thermonuclear fusion to get his timing belt changed. All this, plus the tale of Sonja Henie's Zamboni, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-01-24",
        seconds: 3217.770431,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/382897153/npr_382897153.mp3",
        filename: "car_talk_2015-01-31.mp3",
        title: "#1505: My Brother, The Idiot",
        description:
            "This week on The Best of Car Talk, Ray decides to play Stormchaser, during one of the worst blizzards in Our Fair State's history. Fortunately, we have an eyewitness account of his bold, daring, and completely idiotic adventure—even his dog was scared! Elsewhere in the post-blizzard landscape, Susan is wondering if she can just leave her car buried in snow until the July 4th thaw; and Kristopher may need Lord Kelvin himself to convince his girlfriend to use her Golf's heater. Also, can Beth do anything do protect her white Camry from the local berry-eating mockingbird that's using it as a commode? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-01-31",
        seconds: 3214.963537,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/384571757/npr_384571757.mp3",
        filename: "car_talk_2015-02-07.mp3",
        title: "#1506: The Suburban and the Moose",
        description:
            "This week The Best of Car Talk kicks off with a tale that could only happen in Alaska. It starts with Mom spotting a moose near the driveway, and ends with the family's Suburban driving through their basement— and taking the oil furnace with it. Then, in preparation for Valentine's Day, we have two auto-marital disputes. Kit's husband is trying to convince her that her car's noise isn't the brakes, just its mudflaps; and Angelina's husband wants to put bigger tires on their Civic to improve its gas mileage. Also, why does Marcia's Maxima smell like flatulence, even when her husband isn't in the car? All this, plus a Puzzler from the Ceiling Light series, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-02-07",
        seconds: 3206.688345,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/386318910/npr_386318910.mp3",
        filename: "car_talk_2015-02-14.mp3",
        title: "#1507: An Airplane in Every Garage",
        description:
            "This week on The Best of Car Talk, how do Tom and Ray celebrate Valentine's day? With gifts likely to earn them each a few nights sleeping in the garage! But, in classic, \"those who can't do\" fashion, they're happy to give college student Zoey tips for meeting the cute guy working in her dorm. In matters more technical, (yet still wacko!), Ed needs help choosing an engine for the Miata-sized airplane he's building in his garage; and, Mary just bought a vintage Ford Galaxy sight unseen, and now she's scouting the area rest homes for a mechanic to work on it. Also, on Stump the Chumps, we find out if \"Fred\" ever confessed to his wife that he hates the Saab she bought him as a surprise gift. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-02-14",
        seconds: 3211.041224,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/388039708/npr_388039708.mp3",
        filename: "car_talk_2015-02-21.mp3",
        title: "#1508: Keep Your Chins Up",
        description:
            "This week on The Best of Car Talk, in true Magliozzi fashion, a brotherly pat on the back turns into an insult. Hopefully, Ray can recover in time to explain why Michelle's car radio changes the station whenever someone steps on the brake. Elsewhere, Cindy inherited Dad's car. The good news it has only 39,000 miles on it. The bad news is it also has the smell from 39,000 cigars Dad smoked while driving it. Also, can Brenda's relationship and her boyfriend's clutch both survive her learning to drive a stick shift in his BMW; and, can Ken avoid divorce number four by pre-screening partners based on their cars? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-02-21",
        seconds: 3197.892857,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/389789897/npr_389789897.mp3",
        filename: "car_talk_2015-02-28.mp3",
        title: "#1509: Vehicularly Immature",
        description:
            "This week on The Best of Car Talk, are Mari and her husband grown-up enough to graduate from a Neon to a Mercedes, even if it means having to brush their teeth and hair every day? Elsewhere, Abbie got into a fender bender with a Physics Professor, and hopes he can help her cover the rental car. Would she have better luck with someone from the Philosophy department? Also, Ben almost managed to set his car and vacuum cleaner both on fire on the same day; Kathie's boyfriend may need to be dumped for suggesting it's okay to tailgate; and, on Stump the Chumps, we find out if Dan's truck suffered from a \"classic case\" of Car Talk Bogus Answer Syndrome. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-02-28",
        seconds: 3211.019773,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/391483681/npr_391483681.mp3",
        filename: "car_talk_2015-03-07.mp3",
        title: "#1510: In Space, No One Can Start Your Audi",
        description:
            "This week on The Best of Car Talk, Dr. Anastas is having a slow day at NASA. How do we know? He's wondering how his car would fare in zero gravity, if he brought it along for a ride on NASA's \"Vomit Comet\" airplane. There might be some traction problems, but would the car even start? Elsewhere, Ann's snowboarding trip got more exciting when her tire caught fire heading down the mountain; Dana fears she's heading for an explosion after her husband epoxied her Civic's leaking radiator with J-B Weld; and, every time Dennis washes his wife's car, it won't start the next day. Also, the Great Winter Debate: if you shovel out a parking space, is it yours for keeps? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-03-07",
        seconds: 3202.839932,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/393020467/npr_393020467.mp3",
        filename: "car_talk_2015-03-14.mp3",
        title: "#1511: The Ultimate Road Trip",
        description:
            "This week on The Best of Car Talk, Mike and his uncle are planning to get their kicks on Route 66, driving the legendary highway from California to Chicago this summer. But the ultimate road trip demands the ultimate road trip car, right? So, anyone out there have a '54 Corvette you're willing to lend out to a couple of strangers? Elsewhere, Penny is wondering whether it was a good idea to buy a used Volvo from her ex-husband's new wife; and, Tom and Ray may have to resort to desperate measures to help Kevin turn off his oxygen sensor light. Speaking of desperate measures, Ellen pays a return visit to Stump the Chumps to let us know how far she had to go to get her husband to stop buying performance add-ons for his Blazer. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-03-14",
        seconds: 3205.273107,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/394511035/npr_394511035.mp3",
        filename: "car_talk_2015-03-21.mp3",
        title: "#1512: Lie, Lie, and Lie",
        description:
            "This week on The Best of Car Talk, John's car is a pigsty. As he prepares for a first date with a \"classy woman,\" should he tidy it up or let her see him for the slob he truly is? Elsewhere, Barry had a numskull moment and drove his Blazer into a ditch. Now he can't understand why the engine is running better post-submersion! Also, Chooch's beloved Accord has become melodramatic; a black-light oil leak check is either too expensive or too psychedelic for Dorothea's husband; and, Tom and Ray discover a new strategy for handling difficult callers—diagnosis by intimidation. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-03-21",
        seconds: 3242.976168,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/395993682/npr_395993682.mp3",
        filename: "car_talk_2015-03-28.mp3",
        title: "#1513: The Good Humor Kid",
        description:
            "This week on The Best of Car Talk, Joanna's 16-year-old son is ready for his first car, and what could be better than a vintage ice cream truck, complete with a working freezer and music?! Should Joanna buy the truck, and thank her lucky stars her son didn't ask for a Viper? Or is this aging freezer on wheels one push pop away from a disaster. Elsewhere, Sarah discovered that she can't get her dome light switch to work unless she pours water on it; Bear's 100,000-mile plugs have become 200,000-mile plugs after fusing themselves to the engine block; and Juliette's timing belt may be hanging on by a thread. Also, on Stump the Chumps we find out if John cleaned up his act and his disgustingly messy car for a date. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-03-28",
        seconds: 3242.236621,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/397517063/npr_397517063.mp3",
        filename: "car_talk_2015-04-04.mp3",
        title: "#1514: The Stingy Man Spends the Most",
        description:
            "This week on The Best of Car Talk, Richie tried to save money on oil changes by installing a dual-filtration system on his truck. The resulting acrid smoke seems to prove Tom and Ray's mantra that, \"It's the stingy man who pays the most.\" Elsewhere, Mare's husband accidentally inflated their tires to 90 PSI. Should Mare get rid of the tires, or her husband? Also, Scott's beloved \"Uncle Know-it-All\" gave him some questionable transmission advice, so he's turning to two Know-Nothings; John's trying to slow down his lead-foot son by putting blocks of wood under the gas pedal; and did you know that William Shakespeare was Italian? Neither did we, but Tom and Ray seem to think he was. There's much ado about a whole lot of nothing, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-04-04",
        seconds: 3192.475374,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/399010837/npr_399010837.mp3",
        filename: "car_talk_2015-04-11.mp3",
        title: "#1515: Perennial Potholes",
        description:
            "This week on The Best of Car Talk, the auto-confessional is open, as a former road crew worker explains how he made sure he'd always have a supply of potholes to repair every Spring; and Seminarian Matt seeks absolution for letting his Trooper leak oil all over his environmentalist landlord's driveway. Elsewhere, Tom and Ray try a new strategy for difficult calls. Will \"do whatever you want\" work any better than \"we have no idea what's going on?\" Also, Marlene's Montreal-Boston drive has become non-stop, because if she takes a break her car won't re-start; and could Debbie's black smoke have anything to do with the rag that was wrapped around her air filter? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-04-11",
        seconds: 3230.545057,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/400616420/npr_400616420.mp3",
        filename: "car_talk_2015-04-18.mp3",
        title: "#1516: Fiddletown or Bust",
        description:
            "This week on The Best of Car Talk, Tom's vegan daughter is about to head off to drive cross-country in her truck, and spend a year working on an organic farm. Should Tom have pre-emptive work done to make sure she doesn't get stuck in Carnivore Land? Elsewhere, Doug's noisy brakes have him wondering if his mechanics are too nice to be competent; Warren wants to give his Olds a fresh paint job, but his wife is convinced that will only speed its demise; and Mike is wondering why we hang fuzzy dice from rear-view mirrors, rather than, say, fuzzy socket wrenches. All this and lots more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-04-18",
        seconds: 3225.857891,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/402221465/npr_402221465.mp3",
        filename: "car_talk_2015-04-25.mp3",
        title: "#1517: Lock Him in the Cellar",
        description:
            "This week on the Best of Car Talk, should Heidi let her husband change her Volvo's timing belt? Before you answer, we should tell you that Heidi's husband is a tennis pro, with no repair experience, and that messing up this job will kill the engine. Wanna rethink your answer? Elsewhere, Craig's girlfriend's mother bought him a new truck. If Craig breaks up with the daughter, is it also splitsville with the truck? Also, Nathan dinged his girlfriend's Civic while driving it without a license—or her permission. Can Tom and Ray help him fix the car's thunk before the next sound is her giving Nathan a dope slap? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-04-25",
        seconds: 3229.906213,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/403803936/npr_403803936.mp3",
        filename: "car_talk_2015-05-02.mp3",
        title: "#1518: How To Ruin a Mid-Life Crisis",
        description:
            "This week on The Best of Car Talk, John dove head first into his mid-life crisis by buying a Miata. Then, he started obsessing over how best to preserve its soft top. Can Tom and Ray rescue John from his mid-life crisis crisis? Elsewhere, Alicia's Camry began coughing up furballs, and if that sounds nasty, just wait until Ray tells her what it's likely to cough up next. Also, Peggy wants to meet a guy by pretending to sell a car she doesn't own; Lewis' car is running great, but won't move; and can Joe save $400 by replacing his own radiator? Sure-- if he doesn't mind spending $500, plus the cost of the new radiator. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-05-02",
        seconds: 3235.47737,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/405510592/npr_405510592.mp3",
        filename: "car_talk_2015-05-09.mp3",
        title: "#1519: Sorry, Roomie!",
        description:
            "This week, on The Best of Car Talk, fuses keep blowing in Allison's car. Can it be fixed or would investing in her local auto parts store be a better choice? Meanwhile, Nat's Saab keeps running away from him. He needs help putting on the brakes before he looks like a fool, again, in front of his future in-laws. And Erin's roommate has too many cars... and not enough driveway. Can she convince her roomie to sell one set of wheels, or is it time for Click and Clack to help arrange an \"unfortunate accident\"? All that, and a non-bogus puzzler, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-05-09",
        seconds: 3207.515238,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/407278888/npr_407278888.mp3",
        filename: "car_talk_2015-05-16.mp3",
        title: "#1520: The Rule of Tens",
        description:
            "This week on The Best of Car Talk, can Bill keep his beloved Town Car after it hits 250,000 miies? Sure, if he follows a few simple rules such as never driving over 10 miles per hour, or more than a 10-minute walk from his house. Elsewhere, Heidi needs a new car to fit her two kids in carseats, and their Grandma. Can she somehow cram them all into her dream car, a Miata? Also, this week's Auto Noise Emporium features a whining Civic, a scraping Camry, and a Taurus with a vibraslap stuck in the air conditioner. All this and more this week on The Best of Car Talk",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-05-16",
        seconds: 3227.882404,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/409078952/npr_409078952.mp3",
        filename: "car_talk_2015-05-23.mp3",
        title: "#1521: Save the Siesta",
        description:
            "Some issues are so grave they require even the most politically averse to stand up. This week on The Best of Car Talk, Tom and Ray stand up in support of... the siesta. That's right. The mid-day nap needs saving, and is there anyone better to do it, than Tom and Ray? In matters automotive, Scott needs help getting his truck to start, and protecting it from his friend Fat Tony, with his big bucket o' tools; Mike appears to have found the rarest of creatures, an honest transmission repairman;, and Peggy swears she heard Tom and Ray recommend using kerosene to wash her new car and preserve its paint job. Also, can Gillian get a French-to-English translation for a truck part without disclosing she's a CIA agent? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-05-23",
        seconds: 3231.448322,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/410809675/npr_410809675.mp3",
        filename: "car_talk_2015-05-30.mp3",
        title: "#1522: My Wife The Truck",
        description:
            "This week on The Best of Car Talk, a certain motor mouth puts his mouth in gear, as Tom tells the world his wife looks like a truck. And guess who's listening? Along with this classic moment, Tom and Ray try to figure out why Marc's gas mileage dropped by 20 percent after a tune-up; whether Bob can set off a bug bomb in his car without killing himself along with the flies; and if Kara's Subaru can survive after she filled the gas tank with water. Also, is Ronnie going to suffer a fried tuchus if she buys a black car in the Sunshine State? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-05-30",
        seconds: 3213.47585,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/412507318/npr_412507318.mp3",
        filename: "car_talk_2015-06-06.mp3",
        title: "#1523: The Crush",
        description:
            "This week on The Best of Car Talk, Ann has the hots for her mechanic, and needs Tom and Ray's help on two fronts. First, she needs to break something so she has an excuse to bring in her car. Second, she needs to let Bubba (as we'll call him) know she's not as young as he thinks she is. Elsewhere, Jayne's car is losing oil and lots of it, but she has no idea where it's going; Wendy is wondering if her hood flying open is a sign it's time to dump her Mazda; and on Stump the Chumps, we find out if Bob got his truck's heat working in time for a North Carolina summer. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-06-06",
        seconds: 3225.344603,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/414223804/npr_414223804.mp3",
        filename: "car_talk_2015-06-13.mp3",
        title: "#1524: Janet vs. Lloyds of Lubbock",
        description:
            "This week on The Best of Car Talk, Janet's beloved Grand Marquis got flooded in Houston's torrential rains. Janet decided to keep the car, despite her insurance wanting to total it. How big a mistake did she make? Well, probably not as big as the one Michael is about to make. He bought a new VW Jetta with a stick shift, but his wife really wanted an automatic, so Michael is considering a transmission transplant. Elsewhere, Flap's husband can't follow directions 30 seconds after she tells him which way to go; Megan can't decide if her mechanic is a moron or a sleazeball; and on Stump the Chumps, we find out if Bob set off a bug bomb in his truck, assuming he has enough brain cells left to form a sentence. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-06-13",
        seconds: 3219.967279,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/416029936/npr_416029936.mp3",
        filename: "car_talk_2015-06-20.mp3",
        title: "#1525: While Mom's Away",
        description:
            "This week on The Best of Car Talk, Sarah thinks her husband and kids might have held a peeing contest in her minivan while she was away for the weekend. Will Tom and Ray find them innocent or guilty, and what was Sarah thinking by leaving them alone in the first place? Elsewhere, can three totaled Subarus combine to make one drivable one for Karen? Will John's radiator hang on until he finishes grad school? And, why does Mike's car die only on Sunday mornings? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-06-20",
        seconds: 3233.65322,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/418088265/npr_418088265.mp3",
        filename: "car_talk_2015-06-27.mp3",
        title: "#1526: Mama Was a Race Car Driver",
        description:
            "This week on The Best of Car Talk, Ben is scared to death to ride with his mom. She used to drive race cars, and still likes to treat Main Street as if it was Le Mans. Can Tom and Ray help Ben slow Mom down, or does he need to start hiding her keys? Elsewhere, Aaron thinks his Toyota is haunted by the spirit of Maurice Chevalier; Jamie wants to achieve his life's ambition of owning a vehicle with power steering; and, Kristina's truck is backfiring so loudly, everyone in 500-foot radius ducks and covers. Also, how could three drops of soda burn an Accord's leather seat? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-06-27",
        seconds: 3208.648866,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/420091630/npr_420091630.mp3",
        filename: "car_talk_2015-07-04.mp3",
        title: "#1527: Stella's Personal Billboard",
        description:
            "This week on The Best of Car Talk, how do you attract a guy who's whizzing by at 60 miles per hour? Stella is renting a highway billboard for a personal ad and, to make a questionable idea even worse, is turning to Tom and Ray for design help. Elsewhere, after having his brake pedal sink to the floor twice in stop-and-go traffic, Chris thinks it's time to either figure out what's wrong, or update his life insurance; deli salesman Frank may have to part with a couple of spiral cut hams to find out why his car is making noise; and, why does Mabel's Subaru sound like she's torturing a chihuahua when starts it? All this, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-07-04",
        seconds: 3237.521791,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/422108689/npr_422108689.mp3",
        filename: "car_talk_2015-07-11.mp3",
        title: "#1528: Forget the Car, Find a Convent",
        description:
            "This week on The Best of Car Talk, think an old Volvo is indestructible? Meet Arlene's daughter: destroyed the cooling fan and made things worse by pouring cold Mountain Dew into the overheating radiator. Can Arlene fix the Volvo and her daughter? Elsewhere, Glenn's unorthodox shifting is earning him glares and dope slaps from his wife; Kate's mechanic husband can't figure out her car's starting problem, despite the fact that he's shopping for a bigger boat; and Freudian therapy techniques may save Tom and Ray, as they try to solve Chet's steering and transmission problems. All that and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-07-11",
        seconds: 3291.979796,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/424149893/npr_424149893.mp3",
        filename: "car_talk_2015-07-18.mp3",
        title: "#1529: Chewbacca in the Back",
        description:
            "This week on The Best of Car Talk, Mike's Lincoln turns into a low-rider every time his 350-pound nephew rides in the back seat. Will it be cheaper for Mike to fix his suspension, or get his nephew to join Weight Watchers? Elsewhere, Marsha is worried her husband is too sane to drive her BMW without killing the clutch; Ralph's Suburban seems to be channeling the vintage TV game show \"Beat the Clock\"; and Lee's air conditioner started a thunderstorm in his Civic. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-07-18",
        seconds: 3202.611519,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/426244947/npr_426244947.mp3",
        filename: "car_talk_2015-07-25.mp3",
        title: "#1530: Male Answer Syndrome",
        description:
            "It is an affliction that has touched millions of lives, perhaps none more so than Tom and Ray— the need for guys to speak in great detail on things about which they know absolutely.... nothing. Nada. Squat. This week on The Best of Car Talk, we probe the signs, the symptoms and the causes of Male Answer Syndrome. Our case studies? Tom and Ray's attempts to figure out why Kristin's Sentra is stalling on turns after a near-fender bender; and whether Bruce's son can paint his Town Car and have the job last longer than three weeks. Thankfully, an MAS respite is in store, as we learn that Gina's husband is taking the fun out of his mid-life crisis convertible by being a little too careful—he's cleaning bugs off the windshield, while he's driving. Is Gina being too much of a nag trying to get him to stop, or are those dope slaps she's administering well earned? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-07-25",
        seconds: 3247.191043,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/428424843/npr_428424843.mp3",
        filename: "car_talk_2015-08-01.mp3",
        title: "#1531: Existential Stupidity",
        description:
            "This week on The Best of Car Talk, are Tom and Ray's seemingly moronic questions actually a form of deep philosophical inquiry, worthy of Kierkegaard or Camus? Probably not, but one listener's theory is at least worth a few laughs! Elsewhere, Debra is taking push-starting to a new level—she has to do it just to get her key to turn. Also, should Anne accept a free Range Rover or Mazda for her 16-year old son to drive? Fortunately, we have a 16 year-old Magliozzi on hand to counter Tom and Ray's advice to just let the kid walk. And, on Stump the Chumps, did Heidi manage to keep her husband from changing the timing belt on her Volvo himself? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-08-01",
        seconds: 3198.026871,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/430759713/npr_430759713.mp3",
        filename: "car_talk_2015-08-08.mp3",
        title: "#1532: The Alex Manifesto",
        description:
            "This week on The Best of Car Talk, Tommy's 16-year old son Alex explains why it's in the entire family's best interests for him to own his own car. We may need your help deciding whether Alex is full of wisdom, or something we can't say on a family show. Elsewhere, Nancy and her boyfriend are about to buy their first car together. He wants a vintage MG, but she's the one who'll have to keep it running, unless they find one with a sidecar for a mechanic. Also, Marc learns two valuable lessons. First, never buy an old Peugeot. Second, never pay your mechanic before he finishes the job; and is Heather's plan to play a practical joke on her brother's car too realistic? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-08-08",
        seconds: 3228.52322,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/432387764/npr_432387764.mp3",
        filename: "car_talk_2015-08-15.mp3",
        title: "#1533: The Geek Squeak",
        description:
            "This week on The Best of Car Talk, Dana's wife's brakes squeak only when he drives her car. Could it be holding a grudge, or is Dana driving too much like a geek? Elsewhere, Sylvia thinks her VW's problems may be a result of spending two years near a uranium mine; Jim is almost finished restoring a Land Cruiser, but is still searching for the perfect sound; and, on Stump the Chumps we find out if Ralph's Suburban really was playing \"Beat the Clock.\" All this, plus some of Wiliam Shakespeare's best un-published plays, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-08-15",
        seconds: 3229.775215,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/433814754/npr_433814754.mp3",
        filename: "car_talk_2015-08-22.mp3",
        title: "#1534: Gail, The Tollbooth Fugitive",
        description:
            "This week on The Best of Car Talk, one of our all-time favorite wackos. Gail is on the run from the law in three states, after evading a bridge toll because she didn't have exact change. Can Tom and Ray help bring her in from the cold? Elsewhere, Rebecca was living the dream with her Dart until it ran out of foil, and now she's living the nightmare; Kat's Volvo problems could disappear with a new transmission, or if she takes up a career in flower arranging; and newly single Justin needs a new babe magnet car, but doesn't trust his Corvette-driving brother's recommendations. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-08-22",
        seconds: 3187.308435,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/435849266/npr_435849266.mp3",
        filename: "car_talk_2015-08-29.mp3",
        title: "#1535: The Remote Fart Machine",
        description:
            "This week on The Best of Car Talk, Tom and Ray learn first-hand that women do indeed play practical jokes, courtesy of the 21st Century version of the whoopee cushion. The guys are also chastised for not recognizing the value of Art History majors, and neglecting the most important feature in a babe-magnet car. In matters automotive, Matt needs to find a car that can handle his 100,000-mile annual commute, and that will be kind to his tuchus; Marc is wondering if late-night TV could improve his Envoy's gas mileage; and what does Sirah's leaking clutch have in common with Ray's bleeding gums? Find out this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-08-29",
        seconds: 3268.500771,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/437832817/npr_437832817.mp3",
        filename: "car_talk_2015-09-05.mp3",
        title: "#1536: The Super Magliozzi Brothers",
        description:
            "This week on The Best of Car Talk, Tom and Ray have failed at radio, TV, and books, so why not add video game characters to the list? Also, Karl made a bad first impression on his new neighbors when the horn on his Civic wouldn't quit; Cass and her reunited husband can't agree on which of their four heaps to get rid of; Lee was advised to give his Mazda a kerosene bath; and, what does a Quickie-Lube oil change have in common with an enema? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-09-05",
        seconds: 3232.614444,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/439807965/npr_439807965.mp3",
        filename: "car_talk_2015-09-12.mp3",
        title: "#1537: The Great Montreal Hotel Fire",
        description:
            "\"Monsieur, your car! It ees burnt to a creesp!\" This week on The Best of Car Talk, one of our all-time favorite Magliozzi pranks. The cast includes Ray, a concierge named Henri, and a Ford LTD that has been, shall we say, carboniser. Elsewhere, Unitarian minister Carol finds herself tempted by the earthly pleasures of a Jetta; eternal grad student Erica hopes her Toyota's noise is serious enough to convince Dad to buy her a new car; Jodi's Cavalier may be too far down the path to Heapdom, New Jersey, to save; and if you keep taking a car apart and putting it back together, will you eventually wind up with two? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-09-12",
        seconds: 3333.750023,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/441769772/npr_441769772.mp3",
        filename: "car_talk_2015-09-19.mp3",
        title: "#1538: Aberrant Behavior Syndrome",
        description:
            "This week on The Best of Car Talk, Lee's mild-mannered wife's temper and vocabulary both take a dive, but only when she listens to our show. Are Tom and Ray carriers of a new form of ABS—Aberrant Behavior Syndrome? Meanwhile, tempers are also flaring out in California, where Jim's truck is polluting his entire town; and down in Hendersonville, Kentucky, where Brian's merging strategy is incredibly efficient, and also incredibly rude. Also, on Stump the Chumps we find out if Sarah's kids really held a peeing contest in her car while she was away; and, can Bill in Alaska get his forklift running in time to get us our halibut? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-09-19",
        seconds: 3311.706054,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/443770045/npr_443770045.mp3",
        filename: "car_talk_2015-09-26.mp3",
        title: "Car Talk #1539: Dashboard Jesus, Protect Us!",
        description:
            "This week on The Best of Car Talk, Click and Clack delve into the subject of dashboard icons and the best geographical position for a duct taped, plastic Jesus. After all, the roads are dangerous and drivers need all the protection they can get! Also, Sarah's minivan was stolen twice in one day (this is one case where the third time is not the charm!); John's tires are gonzo. Was it due to a defect or his laziness? And Liz's Honda has a horrible B.O. smell. Can she blame it on her husband? All that, plus the answer to this season's inaugural puzzler, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-09-26",
        seconds: 3282.057732,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/445590112/npr_445590112.mp3",
        filename: "car_talk_2015-10-03.mp3",
        title: "#1540: That Special Detergent Look",
        description:
            "This week on The Best of Car Talk, Ivan went for an oil change, and was told he needed a special detergent beause his oil was clumpy. Did his oil change guy base this on a close examination of Ivan's engine, or a quick guess on Ivan's gullibility? Also, can $170 be too much to spend on a dream car? In the case of the truck Michelle's husband just bought her, it might be. Can Tom, Ray, and a few thousand rolls of duct tape re-kindle Michelle's passion? Find out, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-10-03",
        seconds: 3250.684059,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/447479139/npr_447479139.mp3",
        filename: "car_talk_2015-10-10.mp3",
        title: "#1541: The Case of the Disappearing Pedals",
        description:
            "This week on The Best of Car Talk, Click and Clack dive headlong into relationship advice. The result? Further proof of their legendary status as relationship morons! Also, Nechama's hood is rusted shut. Can she play dumb, go for an oil change and hope the guys at the corner station fix it for free? Marge and her dad are at odds over the safety of talking on a cell phone while refueling. Can Tom and Ray calm the familial waters? Plus, Andrew is a 15-year old political hopeful looking for a car to impress the voters, and Paul needs a new cocktail for his car, which already has a smoking problem. All that, plus how do Tom and Ray prepare for the show? Find out this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-10-10",
        seconds: 3203.331179,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/449496302/npr_449496302.mp3",
        filename: "car_talk_2015-10-17.mp3",
        title: "#1542: Jerking to the High School Dance",
        description:
            'This week on The Best of Car Talk, can Bill learn how to drive stick in time to drive his date to the homecoming dance? Given that his other driving options are a minivan and a station wagon, we certainly hope so. Elsewhere, Heather wants to drive her Subaru from Seattle to Maine to visit her parents, but the car may not make it past Minnesota. Can Tom and Ray help facilitate this family reunion? And, did Abby damage her transmission by backing down a steep driveway in Drive, or is she suffering from Tom\'s diagnosis of "Female Guilt Syndrome"? And, do you have what it takes to be crowned Philosopher King? All this and more, this week on The Best of Car Talk.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-10-17",
        seconds: 3218.003946,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/451481504/npr_451481504.mp3",
        filename: "car_talk_2015-10-24.mp3",
        title: "#1543: Gabe's Drums",
        description:
            "This week on the Best of Car Talk, jazz drummer Gabe is tired of schlepping his kit from gig to gig on the New York subway. Is the solution one new car, or six new drum kits? Elsewhere, Sharon's friends at the retirement community are getting a little over-stimulated by her Taurus' lurid groan; Cathy and David are arguing over whether it's better to drive down Mount Washington with a screaming transmission or burning brakes; Max has a once in a lifetime opportunity to get a free Mustang—that's been sitting underwater for the last 7 years; and can Sarah's Saturn haul her belongings from Illinois to Arizona without dying in Nebraska? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-10-24",
        seconds: 3245.48644,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/453463149/npr_453463149.mp3",
        filename: "car_talk_2015-10-31.mp3",
        title: "#1544: I Stink, Therefore I Am",
        description:
            "This week on The Best of Car Talk, Fran and her boyfriend are both jocks, and as a result, her Taurus smells like a locker room. Will a few dozen Odor Eaters hanging from the rear view mirror get rid of the stink? Elsewhere, Margo's dad gave her his Cadillac, but her noisy brakes have Tom and Ray convinced Dad may be trying to bump Margo off; Matt wants to cure his wife of her habitual door slamming; Drew can't decide if his shuddering engine really is a problem, or if he's a moron; and, \"Martha\" bought a used van from a dealer six months ago, but has yet to be billed or pay a single cent for it. Should she keep quiet, fess up, or trade it in for a new one? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-10-31",
        seconds: 3225.398639,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/455154908/npr_455154908.mp3",
        filename: "car_talk_2015-11-07.mp3",
        title: "#1545: The Mechanic in the Redwood",
        description:
            "This week on The Best of Car Talk, Nathan is living in a redwood tree to protest deforestation. He's noticed that one of the trucks that passes his perch every day is running rough, so he's decided to take \"shade tree mechanic\" to a whole new level, and try to help his nemesis smooth out his ride. Elsewhere, after 30 years of clean driving, Esther has racked up three speeding tickets in the last six months. She's convinced it's the car's fault. Can she convince Tom and Ray to write her a Get Out of Jail Free letter? Also, Chris insists on turning off his Subaru's AC at Stop signs. He thinks he's saving the engine. Chris' wife thinks he's a wimp. What do Tom and Ray think? Find out, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-11-07",
        seconds: 3300.006417,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/456039727/npr_456039727.mp3",
        filename: "car_talk_2015-11-14.mp3",
        title: "#1546: Brilliant Bamboozling",
        description:
            "Tom and Ray have dispensed lots of booooogus advice over the years, but this week on Car Talk they've got one answer that's so whacked out, it wins one caller's award for the most brilliant piece of bamboozling he's ever heard. The guys may be on more solid ground convincing Benjamin that doing donuts in Dad's Camry may indeed have cooked the power steering pump. Also, should Kathy be concerned that her husband carries a picture of his long-lost Studebaker in his wallet— but not one of her? And, everything you need to know about friendship, explained in two minutes. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-11-14",
        seconds: 3252.97585,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/456930265/npr_456930265.mp3",
        filename: "car_talk_2015-11-21.mp3",
        title: "#1547: One Sensitive Dog",
        description:
            "This week on The Best of Car Talk, why did Bob's mild-mannered dog go wacko when Bob dumped his Mercedes and bought an Audi? Is the pooch status-obsessed, or is there an olfactory explanation? Elsewhere, Ellen's Camry smells like rotten eggs, and she thinks her dealer is blowing sulphur up her skirt, rather than fixing it. Also, Glen's vacation got a little more exciting when his rental car caught on fire. Was it Glen's fault, and, more important, did he tell the rental company? And on Stump the Chumps, we find out if Bill learned to drive a stick shift in time for the high school dance, and if his date is still speaking to him. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-11-21",
        seconds: 3250.23644,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/457698219/npr_457698219.mp3",
        filename: "car_talk_2015-11-28.mp3",
        title: "#1548: Throw Your Key down a Storm Drain",
        description:
            "This week on The Best of Car Talk, here's a first. Ephraim went to the dealer to complain that his Audi's gas mileage was too good. Apparently, said gas mileage nearly doubled when Ephraim's fiancee began driving the Audi, so there must be something wrong with the car, right? As Tom and Ray would say, \"Au contraire, piston puss!\" Elsewhere, Rachel's mechanic warned her of \"boulder intrusion\" if she doesn't replace a broken CV boot; Pam's Toyota is dripping molten lead from the dashboard; and Al and his brother are arguing over whether it's possible to park a truck in a position from which it's impossible to move. Also, how one listener is using Car Talk to help teach English. Yes, really. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-11-28",
        seconds: 3224.689138,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/458604964/npr_458604964.mp3",
        filename: "car_talk_2015-12-05.mp3",
        title: "#1549: When the Red Red Robin Comes Pecking at My Car",
        description:
            "This week on The Best of Car Talk, Heidi's Lincoln is under assault from a local bird that's itching for a fight, with its own reflection! Can Heidi save her car without ending up on the Audubon Society's Most Wanted list? Elsewhere, Shawn needs help with two annoying noises. One is coming from his Caravan, and the other is his wife laughing at him. Also, Janet and her small-town neighbors can't decide whether they should keep their cars running during their roadside chats; Steve's truck is bouncing its way down the highway; and glass artist Dara may have to make a couple of Click and Clack dashboard figurines if she wants help quieting her Subaru. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-12-05",
        seconds: 3207.227755,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/459499463/npr_459499463.mp3",
        filename: "car_talk_2015-12-12.mp3",
        title: "#1550: The Great Cow Magnet Caper",
        description:
            "This week on The Best of Car Talk, could cow stomach magnets have improved the gas mileage on Tim's Jaguar? Or is that udderly (sorry) ridiculous? And, down in Antarctica, Summer is coming, but Matt's vehicle is still having trouble when the thermometer dips below a balmy minus 40 degrees. Elsewhere, Tom and Ray are in the holiday spirit, with some creative gift suggestions for men, comforting advice for Adrian who wants to put a wreath on her car but is worried it'll spontaneously combust, and they've got news of a major holiday merger. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-12-12",
        seconds: 3224.151361,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/460411031/npr_460411031.mp3",
        filename: "car_talk_2015-12-19.mp3",
        title: "#1551: The Chevy in the Lake",
        description:
            "This week on The Best of Car Talk, Bill's truck rolled into a lake. There's one cable keeping it from sinking to the bottom. Should Bill call Jacques Cousteau for a rescue, or cut the cable? Elsewhere, Victoria is looking for a quartet of $2,000 cars for her sons; Jenny's newlywed husband lost 15 pounds, and his now-oversized wedding ring is missing in their Jeep's dashboard; and, on Stump the Chumps, we find out if David's car-induced cough is cured, and if his brain cells are still intact. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-12-19",
        seconds: 3263.988435,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/461118362/npr_461118362.mp3",
        filename: "car_talk_2015-12-26.mp3",
        title: "#1552: Blow it Out",
        description:
            "This week on The Best of Car Talk, Jill's pal keeps telling her she needs to do more highway driving to \"blow the stuff\" out of her car. Jill's not opposed to this, but what exactly is she trying to blow out? Elsewhere, Eleanor is leaving on a six-month, around-the-world bicycle tour and she wants to know what to do with her truck while she's gone. Tom and Ray want to know how Eleanor plans to pedal across a few oceans. Also, after Lauren's boyfriend drove down Mount Washington with the emergency brake on, Lauren is wondering if she needs new brakes, and/or a new boyfriend. And, Rich's broken gas gauge gives Tom and Ray a chance to fail Calculus, again! All that and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2015,
        date: "2015-12-26",
        seconds: 3250.796122,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
