/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/461779323/npr_461779323.mp3",
        filename: "car_talk_2016-01-02.mp3",
        title: "#1601: The Lexus witth Dragon Tracks",
        description:
            "January 2, 2016 • This week on the Best of Car Talk, Kim's husband couldn't resist buying a Lexus that had been sitting in an airport parking lot for four years. Kim thinks the car was used for nefarious deeds, and is plagued by bad vibes. But Kim's own purchase may make her husband's look sane by comparison. Meanwhile, another martial dispute is brewing in Alaska, where Samantha and her husband can't agree on the best place to hang dry cleaning. Can Tom and Ray referee his one, without knowing exactly what dry cleaning is, anyway? Also, Stephan's solution to his Golf's rough running was either brilliant or wacko; Jessica's power steering pump made a 90-degree turn; and on Stump the Chumps, we find out if John's wife made it from Buffalo to San Diego in her Cabriolet. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-01-02",
        seconds: 3232,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/462509293/npr_462509293.mp3",
        filename: "car_talk_2016-01-09.mp3",
        title: "#1602: Bad Analogies",
        description:
            "January 9, 2016 • This week on The Best of Car Talk, Steve expected to encounter snow during his winter cross-country drive, but he wasn't prepared for flurries inside his Pathfinder. Elsewhere, Nina's mechanic ripped off her Altima's heat shield, and Nina's worried about burning up on re-entry. Also, Jean's brakes started screeching after she got new pads, apparently with the \"banshee\" option; John's daughters' know-it-all boyfriends have convinced them they need to let their cars warm up for a loooong time on cold mornings; and Ray discovers new automotive healing powers. All this and lots more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-01-09",
        seconds: 3246,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/463321781/npr_463321781.mp3",
        filename: "car_talk_2016-01-16.mp3",
        title: "#1603: A Rolling Mercedes Gathers No Mold",
        description:
            "January 16, 2016 • This week on The Best of Car Talk, why are Helen's Mercedes' tires growing mold? Tom and Ray say it's because Helen drives the car infrequently, to which Helen replies, \"Au contraire Piston Pusses!\" Elsewhere, Linda's fiance insists on washing his car before a long trip, to improve its gas mileage. Is he right, or just falling prey to the old \"clean underwear\" theory? Also, Scott's wife gave him a homework assignment—write a paper explaining why he should keep the '77 MG that's been sitting untouched in their garage for the last year; and you'll be shocked, shocked to learn that John's \"cheap and reliable\" Ferarri is making a loud, and likely expensive, noise. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-01-16",
        seconds: 3276,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/464126005/npr_464126005.mp3",
        filename: "car_talk_2016-01-23.mp3",
        title: "#1604: Better Alive Than Pure",
        description:
            "January 23, 2016 • This week on The Best of Car Talk, Karen's mechanic may be taking period authenticity a little too far by refusing to install shoulder belts in Karen's new vintage Rambler. Elsewhere, Ron tried to find a vacuum leak with propane, and now has two fewer eyebrows to show for it; the VW Westfalia Josie inherited from her dad has been starting and wandering off on its own; and is that 150-pound log Lucia put in her Corolla's trunk, to stop it from fishtailing on the ice, doing more harm than good? And, are remote starters contributing to the decline of Western civilization? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-01-23",
        seconds: 3242,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/464992196/npr_464992196.mp3",
        filename: "car_talk_2016-01-30.mp3",
        title: "#1605: Me and My Blankie",
        description:
            "January 30, 2016 • This week on The Best of Car Talk, Paula swears the only way she can start her car on really cold mornings is by laying a warm blanket on the hood. Is there any possibility that Paula isn't completely nuts? Elsewhere, Dick's truck bounces when he steps on the brakes, but can Dick stay awake long enough for Tom and Ray to explain why? Also, a ski trip turned Jennifer's Geo into a low rider; Betsy's Toyota is sliding around Martha's Vineyard; and Peter's wife always said, \"A car is just a car\", until she drove Peter's new Jaguar. Is peter's new Jag now hers? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-01-30",
        seconds: 3218,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/465851180/npr_465851180.mp3",
        filename: "car_talk_2016-02-06.mp3",
        title: "#1606: Power to the People",
        description:
            "February 6, 2016 • This week on The Best of Car Talk, how can Doug diplomatically tell his wife she's a slob when it comes to cars, and should his new car be a stick shift, so she can't drive it? Ray's telling of his wife's turn from neatness to the dark side provides a cautionary tale. Also, on Stump the Chumps, we find out if Richard resorted to shock therapy to get his pet goats to stop climbing on his cars, and if Richard's girlfriend Doris started speaking to him again. And, why did Paul go to a cobbler instead of a body shop when his gas pedal fell through the floor of his Datsun? All this and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-02-06",
        seconds: 3221,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/466669059/npr_466669059.mp3",
        filename: "car_talk_2016-02-13.mp3",
        title: "#1607: Dope Slap Conditioning",
        description:
            "February 13, 2016 • This week on The Best of Car Talk, Cathy thinks she may have found Mr. Right, but he may not live to see their wedding day if he kills her Sentra's clutch. Can a few well-timed dope slaps save Cathy's car, and the relationship? Elsewhere, Nicki gets a primer in how to shop for a used truck, including wardrobe tips. Also, postal worker Jess' car has gone, well, postal when coasting to a stop; Randi is slowly being driven crazy by a golf ball rolling around in her Volvo; and Ken's mooing Ford qualifies him for the Car Talk Cockamamie Answer of the Week. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-02-13",
        seconds: 3210,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/467489636/npr_467489636.mp3",
        filename: "car_talk_2016-02-20.mp3",
        title: "#1608: Saddle Up!",
        description:
            "February 20, 2016 • This week on The Best of Car Talk, even with one infant on hand and twins on the way, Mara and her husband need a new car, but would rather drive a horse and buggy than a minivan. Will Tom and Ray send them to a dealership, or a stable? Elsewhere, Christine and her mom's cars are sending each other smoke signals from under the hood; Burt is hoping his oil leak replacement plan means he never has to do an oil change; and how should Mario take care of his Mercedes in Italy during the 10 months of the year he spends in Alaska? And, shouldn't his calendar be the other way around? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-02-20",
        seconds: 3238,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/468398426/npr_468398426.mp3",
        filename: "car_talk_2016-02-27.mp3",
        title: "#1609: You Can't Do it Unless the Number is Two",
        description:
            "February 27, 2016 • Even the best Puzzle Masters make an occasional mistake. But Martin Gardner and Will Shortz probably never had one of their errors exposed as dramatically (and hilariously) as Ray's recent mango tree Puzzler. Find out how it plays out, this week on the Best of Car Talk. Elsewhere, Robert's Mercedes dealer gave him a blanket and pen to apologize for over-filling his engine with oil. Should Robert have asked them to wrap a new engine in that blanket? Also, Carey thinks her husband's downshifting advice may be responsible for her Expedition's clunk, but the noise may have more to do with the 9,000 pounds of barbecue equipment Carey is hauling around; and, a tale of what happens when overly-encumbered by the thought process engineers try to paint an apartment. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-02-27",
        seconds: 3244,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/469334700/npr_469334700.mp3",
        filename: "car_talk_2016-03-05.mp3",
        title: "#1610: Flaming Volvos and Dangling Tahoes",
        description:
            "March 5, 2016 • This week on The Best of Car Talk, the Click and Clack Forensics team tries to figure out why Sarah's Volvo burst into flames on her way home from its 60,000 mile service. Elsewhere, the good news for Allison is that there are still sparks between her and her husband. The bad news is, we mean that literally. Can those sparks turn from shocking to amorous? Also, can Paul transform his Subaru into a convertible for Summer, and avoid a catastrophe? And, on Stump the Chumps, we find out if Bill cut the cable that was keeping his Tahoe from sinking to the bottom of a lake. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-03-05",
        seconds: 3328,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/470227224/npr_470227224.mp3",
        filename: "car_talk_2016-03-12.mp3",
        title: "#1611: Heather and the Black Widows",
        description:
            "March 12, 2016 • This week on The Best of Car Talk, Heather recovered her stolen Civic, but found a family of black widow spiders had taken up residence. She killed the mother with a shovel, but how can she evict the rest of the clan? Elsewhere, Howard ran out of brake fluid during a long drive, and is wondering if he could have used his bottle of tequila to fill in; Charlotte's VW dealer accused her of killing her clutch, but Charlotte's ex-husband and ex-boyfriend both leaped to her defense; and, Timothy is wondering if it's time to cut his losses on the Maserati that has him on a first-name basis with AAA. All this, plus the unfortunate tale of Tommy meeting Princess the pooch, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-03-12",
        seconds: 3275,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/471102026/npr_471102026.mp3",
        filename: "car_talk_2016-03-19.mp3",
        title: "#1612: The Inveterate Backseat Driver",
        description:
            "March 19, 2016 • This week on The Best of Car Talk, is \"Backseat Driver Syndrome\" incurable? Lani got used to yelling at her husband when he was a stinko driver, but now that he's doing better behind the wheel, she's still nagging from the passenger seat. Old habits die hard, it seems. Meanwhile, Christine is wondering if she needs to give up knitting in the passenger seat, lest a deploying airbag turn her needles into projectiles. Also, Jem needs to clean a stuck valve, but the gunk may be the only thing holding his engine together; Matthew's struggles to start his Jetta are giving his neighbor's lots of laughs; and even after three alignments, Russ still thinks his car may be headed for a ditch. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-03-19",
        seconds: 3317,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/471983605/npr_471983605.mp3",
        filename: "car_talk_2016-03-26.mp3",
        title: "#1613: Pikes Peak or Bust",
        description:
            "March 26, 2016 • This week on The Best of Car Talk, Anne's family is planning a cross-country road trip. Is their Mercury Villager up to the task, or likely to wind up being pushed off the top of Pike's Peak when the engine fails? Elsewhere, Arelene (sic) wants her recently retired husband to learn how to work on their six cars. He says cars are too complicated, but is he just blowing smoke? Also, Cindy's family loves the nurse they hired to take care of Cindy's mom, but she has a nasty habit of backing into garden gnomes (and other objects) whenever she drives; and, we don't know why Keith's electric winch gave out when he was hauling a tree stump, but we're pretty sure Keith deserved it. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-03-26",
        seconds: 3317,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/472811821/npr_472811821.mp3",
        filename: "car_talk_2016-04-02.mp3",
        title: "#1614: A Nice Juicy Pizza",
        description:
            'April 2, 2016 • This week on The Best of Car Talk, unearthed letters from summer camp prove that the child really is father to the man, at least when it comes to our Technical Spiritual and Menu Advisor, John "Bugsy" Lawlor. Elsewhere, Lee liberated herself from her mechanic by changing her own oil, but also got liberated from her cash when she poured the oil into her transmission; Cameron needs a lesson in how to burn rubber; and Carly becomes the poster child for Repair Avoidance Syndrome by not getting her shaking Civic looked at. Also, on Stump the Chumps, we find out if Eddie and Edie Electron made their way home in Michelle\'s Saturn. All this and more, this week on The Best of Car Talk.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-04-02",
        seconds: 3232,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/473655527/npr_473655527.mp3",
        filename: "car_talk_2016-04-09.mp3",
        title: "#1615: Auto Pyrotechnics",
        description:
            "April 9, 2016 • This week on The Best of Car Talk, low-budget filmmaker Seth wants to blow up a car for his latest project. Is there enough cash in our legal defense fund for Tom and Ray to even consider giving Seth any advice? Elsewhere, late-night TV might be the cure for Sarah's dented Taurus; a manure overload may have made Art's truck's steering &*%^! the bed; and, Stephan is bothered by his truck's knocking, but even more concerned about his mechanic's fix for it. Also, should Byron challenge the marital-industrial complex and insist on driving away from his wedding in his pickup truck? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-04-09",
        seconds: 3288,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/474513045/npr_474513045.mp3",
        filename: "car_talk_2016-04-16.mp3",
        title: "#1616: The Closet Leadfoot",
        description:
            "April 16, 2016 • This week on The Best of Car Talk, is Martha's Passat shifting rough because of a failing transmission, or Martha's bad driving habits? The Car Talk Leadfoot Personality Test may give the answer. Elsewhere, Martin's brilliant roadside fix for his loose muffler could wind up setting the entire Northeast on fire; Dick's car is blowing so much smoke he's on Pennsylvania's Most Wanted Polluters list; and, Elizabeth is wondering if she should let a sleeping nail lie, in her tire. Also, can Tom and Ray teach Beth how to parallel park without being able to see what's behind her? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-04-16",
        seconds: 3243,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/475418142/npr_475418142.mp3",
        filename: "car_talk_2016-04-23.mp3",
        title: "#1617: What Are Yews Doing",
        description:
            "April 23, 2016 • This week on The Best of Car Talk, can Liz use her Maxima to remove some unwanted shrubs from her yard, or will her bumper wind up as part of the landscape? Elsewhere, Nancy's 16-year-old son wants a Camaro. Will she be adbicating all parental responsibility if she buys him one, and is there a good alternative that's big, ugly, and cool? Also, Pam wants to ease her husband's guilt over denting her door; Charles succumbed to Male Answer Syndrome trying to diagnose his wife's noisy Voyager; and, is Kirk's steering problem a result of Post-Alignment Euphoria, or Post-Alignment Anxiety? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-04-23",
        seconds: 3282,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/476302616/npr_476302616.mp3",
        filename: "car_talk_2016-04-30.mp3",
        title: "#1618: Your Wife or a Cigar",
        description:
            "April 30, 2016 • This week on The Best of Car Talk, Tom and Ray demonstrate their unmatched ability to plant all four feet firmly in their mouths and endanger their marriages— all while diagnosing a simple vacuum leak. Later, however, they just might make amends by helping to save Beth's marriage, with a ruling on whether her Civic's clutch should be more afraid of Beth or her husband. Elsewhere, Susan is a philosophy professor by day, and a pig rescuer by night. Is there one vehicle that can handle both lifestyles, or does she need a dedicated Pigmobile? Also, Jackie's squealing brakes are wreaking havoc for her pet chihuahuas; and Daniel got a very unpleasant surprise when his mechanic removed his distributor cap—think Vincent Price in \"The Fly.\" All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-04-30",
        seconds: 3295,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/477166121/npr_477166121.mp3",
        filename: "car_talk_2016-05-07.mp3",
        title: "#1619: Our Not So Fair City",
        description:
            "May 7, 2016 • This week on The Best of Car Talk, Wyatt holds Tom and Ray responsible for the worst eight months of his life, and not because they gave him bogus car advice! It's a tale of woe and intrigue that ends with an almost cross-country escape in a VW Microbus. Elsewhere, Cynthia's kids want her to dump her beloved Subaru. Should she go along, if they give her a new BMW for Mother's Day? Also, Ben took his parents' Land Rover for a joy ride that ended in a cloud of smoke; Helen's the only one who can hear her Acura thump; and Dale's spark plug wires keep trying to escape. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-05-07",
        seconds: 3298,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/478070046/npr_478070046.mp3",
        filename: "car_talk_2016-05-14.mp3",
        title: "#1620: Camp Gone to the Dogs or Bust",
        description:
            "May 14, 2016 • This week on The Best of Car Talk, can Cathy drive her dog 2,000 miles to summer camp in a truck without AC, or should she spend big bucks to cool all involved? Elsewhere, Dorothea's dealer changed her belts, and now her car is shrieking. Does she need a big lawyer, or a big stick? Also, Richie's dual oil system proves the adage, \"The stingy man spends the most.\"; Tom and Ray ponder whether members of the Witness Protection Program get to hang out with each other; and did you know William Shakespeare was Italian? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-05-14",
        seconds: 3294,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/478997067/npr_478997067.mp3",
        filename: "car_talk_2016-05-21.mp3",
        title: "#1621: Odometer Dreams",
        description:
            "May 21, 2016 • This week on The Best of Car Talk, Bill's broken odometer fixed itself, right after Bill dreamed it was working. Will Tom and Ray have a mechanical explanation, a metaphysical explanation, or (most likely) a boooooogus explanation? Elsewhere, Toby wants her husband to get rid of her old BMW, but he's proving as immovable as the car; Sally is getting half her husband's mileage, and hopes it's not because she's buying cheap gas from Rotten Robbie; and Derek's dog would really appreciate it if Derek could get his Impreza to stop lunging forward. All this, plus a round of Stump the Chumps, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-05-21",
        seconds: 3304,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/479858755/npr_479858755.mp3",
        filename: "car_talk_2016-05-28.mp3",
        title: "#1622: Goodbye My Coney Island Baby",
        description:
            "May 28, 2016 • This week on The Best of Car Talk, Tom and Ray fulfill one listener's dream, while creating nightmares for everyone else, with a one-time only performance of the barbershop classic \"Goodbye, My Coney Island Baby.\" Assuming the FCC lets us get through the rest of the show, Mary wants to sell her Accord, but it needs $500 of repairs. Should she get it fixed, divulge the problems to a potential buyer, or say nothing? And, how crazy is she for thinking she'll get a good answer from two mechanics? Also, can Steph's Subaru haul her sailboat and wine collection 1300 miles without dying, and more importantly, without ruining the wine? And, is Caroline's poor clutch technique destroying her relationships? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-05-28",
        seconds: 3307,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/480766651/npr_480766651.mp3",
        filename: "car_talk_2016-06-04.mp3",
        title: "#1623: Huggable Radio Hosts Seek Automotive Friendships",
        description:
            "June 4, 2016 • This week on The Best of Car Talk, drawing on Tom's cast — or is it half vast? — matrimonial experience, Click and Clack attempt to decode cryptic personal ads. And, sticking to relationship advice, they weigh in on Nancy's dispute with her husband. Spoiler alert: Will Nancy ever let her hubby live down his bogus A/C theory? Meanwhile Mark's looking for a foolproof way to test seat belts that doesn't involve slamming into the back of a taxi cab. And is something really wrong with Dana's starter motor? Or are her parents just tired of her lounging on their couch? All that and more, this week on The Best of Car Talk. TThis week on The Best of Car Talk, Click and Clack attempt to decode cryptic personal ads. And, sticking with relationship advice, they weigh in on Nancy's dispute with her husband. Spoiler alert: Will Nancy ever let her hubby live down his bogus A/C theory? Meanwhile, Bob's Fiat is having issues ever since he got it painted and disturbed the car's \"delicate\" nature. Will his Fiat end up in a box just like Tommy's? And is something really wrong with Dana's starter motor or are her parents just sick of her lounging on their couch? Prepare yourself for another hour of automotive-relationship conundrums, this week on The Best of Car Talk. - See more at: http://admin-www.cartalk.com/content/1623-huggable-radio-hosts-seek-automotive-friendships#sthash.Q8BxoTq7.dpuf",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-06-04",
        seconds: 3288,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/481690389/npr_481690389.mp3",
        filename: "car_talk_2016-06-11.mp3",
        title: "#1624: Marriage Counselor Malpractice",
        description:
            "June 11, 2016 • This week on The Best of Car Talk, Grant's marriage counselor suggested he and his wife turn to Tom and Ray to help settle their auto-marital dispute over keeping the radio on while the car is off. Will Tom and Ray help bring peace, or will Grant's next appearance be on Divorce Court? Elsewhere, Mark decided to replace his working transmission, and has now gone through six failed rebuilds in 6 months. Does this earn him an equal number of dope slaps? Also, Mabel's Subaru is leaking oil from every orifice; Tulis' mechanic may be relying too much on prisms and crystals trying to fix her Civic's brakes; and, is Jessica car shocking her because of her clothes, her hair, or its ugly upholstery? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-06-11",
        seconds: 3310,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/482623927/npr_482623927.mp3",
        filename: "car_talk_2016-06-18.mp3",
        title: "#1625: The Rental Car Fugitive",
        description:
            "June 18, 2016 • This week on The Best of Car Talk, Bill parked his rental car on a beach, and discovered the next morning that the tide had rolled in—to the car. He's bailed the water, but hasn't told the rental company. Should he 'fess up? Elsewhere, on a scale of 1 to10, how stupid should Ryan feel about getting talked into an engine shampoo when he took his car for an oil change? How about 11? And, is a lucky doughnut enough to keep Tamatha's brakes from burning up for a third time? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-06-18",
        seconds: 3286,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/483532426/npr_483532426.mp3",
        filename: "car_talk_2016-06-25.mp3",
        title: "#1626: The Misappropriated Dream Truck",
        description:
            "June 25, 2016 • This week on Stump the Chumps, we find out if Michelle is happily driving around Spokane in her $700 dream truck, or if it's doing duty as a lawn ornament in her backyard. Elsewhere, Karlene's mechanic diagnosed her Explorer's annoying squeak as \"an annoying squeak,\" with no suggestions for quieting it. Can Tom and Ray do perhaps just a wee bit better? Also, Ed may need to resort to healing crystals to start his son's Taurus; Stan thinks his wife's aggressive air-conditioning use may pop a belt; and Larry has a chance to take part in a wonderful bonding experience with his 14-year old son, and is looking for any way to get out of it! All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-06-25",
        seconds: 3315,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/484505599/npr_484505599.mp3",
        filename: "car_talk_2016-07-02.mp3",
        title: "#1627: The Laying on of Hands",
        description:
            "July 2, 2016 • This week on The Best of Car Talk, John can only keep his car from stalling by opening the hood and touching the engine. Does this fix have anytinng to do with the fact that John's a Catholic priest? Elsewhere, Tom is looking for a \"girlfriend car,\" but can't decide if his wife should be able to drive it; Rick's friends are telling him his family road trip from Kansas to Disneyland may end in Wichita if he doesn't get a valve job; and way up north in Alaska, Linda needs to retro-fit her ATV so her sled dogs will get their off-season workouts. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-07-02",
        seconds: 3265,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/485385595/npr_485385595.mp3",
        filename: "car_talk_2016-07-09.mp3",
        title: "#1628: Remember When Your Car Blew Up, Dad?",
        description:
            "July 9, 2016 • This week on The Best of Car Talk, did Christy destroy her Dad's car 15 years ago by putting black tape over a flashing temperature light— and then continuing to drive? And is Dad ready to forgive and forget? It's one of our all-time favorite auto-familial disputes. Elsewhere, Andy got talked into replacing his front brakes to help stop a noise coming from the rear; Nancy's husband says she's risking death by keeping her air conditioning on recirculate; and should Mickey be concerned that she's on her 4th consecutive boyfriend who drives an '82 Honda? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-07-09",
        seconds: 3228,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/486313623/npr_486313623.mp3",
        filename: "car_talk_2016-07-16.mp3",
        title: "#1629: Death by Soap",
        description:
            "July 16, 2016 • This week on The Best of Car Talk, Greg was surprised when his truck started running poorly, until he learned that his four-year-old son had washed the inside of the gas tank with soap. Should Greg stick his kid with the repair bill? Elsewhere, Judy can't decide if her son-in-law is brilliant or wacko for raising the hood of his Volvo after every drive; Gil's Camry may be leaving a trail of clutch fluid from Houston to Phoenix; Debra's knocking is nothing compared to the sound of two hosts banging their heads together trying to figure out what's causing it; and, what does Gavin's car have in common with King Tut's tomb? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-07-16",
        seconds: 3291,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/487176483/npr_487176483.mp3",
        filename: "car_talk_2016-07-23.mp3",
        title: "#1630: The Muir Woods Capuccino Cart",
        description:
            "July 23, 2016 • Could anything ruin a walk through one of America's most beautiful and peaceful National Monuments? How about a radio show host complaining because he can't get an espresso? This week on The Best of Car Talk, the tale of Tom and Ray's ill-fated visit to the Muir Woods. Elsewhere, Bob's friend may be victim of \"Additive Placebo Syndrome\" by disabling his running lights to improve mileage; Harmony hopes to get off the hook for smashing her sister's car; and can Sasha learn how to drive a stick shift without giving her Dad a nervous breakdown? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-07-23",
        seconds: 3231,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/488054337/npr_488054337.mp3",
        filename: "car_talk_2016-07-30.mp3",
        title: "#1631: Tickling the Electrons",
        description:
            "July 30, 2016 • This week on The Best of Car Talk, Dennis' friend told him the best way to charge a low car battery is by turning on all the accessories. Does this earn immediate entry into the Wacko Theory Hall of Fame? Elsewhere, Julieta's boyfriend is blaming her driveway for his Camry's starting problem, which can only be cured by the correct curse words; Molly would like a little less cowbell in her Altima; and Gail explodes the myth that women don't play practical jokes. Also, how did a rental car's exhaust suck in Mike's daughter's shirt? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-07-30",
        seconds: 3255,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/488995126/npr_488995126.mp3",
        filename: "car_talk_2016-08-06.mp3",
        title: "#1632: The Hungry Water Theory",
        description:
            "August 6, 2016 • This week on The Best of Car Talk, distilled water may be too hungry for John to use it in his radiator. Will Ray's explanation of the hungry water theory help clarify things, or as usual, only further obfuscate matters? Elsewhere, Linda's husband proudly claimed to have \"fixed\" her Volvo—by chopping off its roof. Now is it safe for use as anything other than a planter? Also, Kunal wants to give his horn testosterone treatments; Diana's van could be a new form of germ warfare; and on Stump the Chumps we find out if Liz found her gas leak, and the perfect jumpsuit. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-08-06",
        seconds: 3251,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/489908275/npr_489908275.mp3",
        filename: "car_talk_2016-08-13.mp3",
        title: "#1633: A Big, Beautiful Piece of. Junk",
        description:
            "August 13, 2016 • This week on The Best of Car Talk, should Jason dump his beloved Camaro? It needs a new engine and completed its mission to help him find a girlfriend. Elsewhere, Shelly has the happiest dog in the world as her Explorer is spewing dog food from the vents; Oscar needs to decide whether to fix his wife's brakes or buy more life insurance for her; and should Barbara attempt her 6-month road trip in a VW Camper Van if she expects it to last more than 6 days? Also, from the land of Wacko theories, Teresa's husband thinks he has a better to chance to survive a collision if he's not wearing a seat belt; and our on-call chemist Jim Davis weighs in on Ray's hungry water theory. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-08-13",
        seconds: 3233,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/490763899/npr_490763899.mp3",
        filename: "car_talk_2016-08-20.mp3",
        title: "#1634: Con the Mechanic",
        description:
            "August 20, 2016 • This week on The Best of Car Talk, Nancy doesn't fully trust her mechanic so she's throwing around car jargon to bluff him into thinking she knows more than she does. But, her vocabulary has run dry. Will the official Click and Clack Thesaurus come to her rescue? Elsewhere, Greg's truck's wiring has become lunch for critters and the only way to save it may require giving up his beloved garage woodshop. Also, Kara's white-water rafting company may have to do the unthinkable and switch to automatic transmissions for their trucks; and on Stump the Chumps, we find out if Tom and Ray knocked their heads together well enough to diagnose Debra's truck's knocking sound. All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-08-20",
        seconds: 3318,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/491641349/npr_491641349.mp3",
        filename: "car_talk_2016-08-27.mp3",
        title: "#1635: Carson DeLake",
        description:
            "August 27, 2016 • This week on The Best of Car Talk, Tim's Dodge Dart rolled into a lake and went for a full dive. The car has been retrieved, but will it ever run again and not smell like fish? Elsewhere, Stu's girlfriend Carla accidentally added engine oil to his beloved ZX's power steering. So why are Tom and Ray asking Carla if she wants to dump Stu? Also, Julia fears her parents' marriage won't survive Dad's attempt to rebuild Mom's Suburban's engine; Karen's physicist husband has a bogus explanation for why her car is shaking; and on Stump the Chumps, we find out if Ed needed healing crystals to get his son's Taurus to start. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-08-27",
        seconds: 3274,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/492549091/npr_492549091.mp3",
        filename: "car_talk_2016-09-03.mp3",
        title: "#1636: Magliozzi's Ignoramus Principle",
        description:
            "September 3, 2016 • Move over Heisenberg! This week on the Best of Car Talk, one listener's new theory on Tom and Ray's ability to alter reality. Elsewhere, Anthony thinks his cheapo tires are making noise. His solution? Swap them with his wife's tires. Will Tom and Ray have a suggestion that won't land Anthony in divorce court? Also, Crash's Mazda is making him live up to his nickname by wandering all over the road; Kimberly is tired of having to whack her Subaru's starter; Dora has become a reluctant member of the Alternator of the week club; and does a cleaner car lead to a bigger mechanic's bill? All this, plus some words to live by and lots more, this week on The Best of car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-09-03",
        seconds: 3245,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/493428373/npr_493428373.mp3",
        filename: "car_talk_2016-09-10.mp3",
        title: "#1637: Latent Junkman Syndrome",
        description:
            "September 10, 2016 • This week on The Best of Car Talk, Joe's brother-in-law collects heaps. This wouldn't be a problem, except the cars wind up in Joe's backyard. And to make things even more complicated, Joe's brother-in-law owns the house. Can Tom and Ray untangle this family mess? Elsewhere, Sherry thinks her temperature gauge is going through menopause; Roseanna borrowed her friend's Subaru for the summer and fears she may be responsible for its new noise; and Klaus may need to learn how to drive his car with the engine off. All this, plus some fun things to say on elevators, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-09-10",
        seconds: 3246,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/494390844/npr_494390844.mp3",
        filename: "car_talk_2016-09-17.mp3",
        title: "#1638: Bernsteining the Clutch",
        description:
            "September 17, 2016 • This week on The Best of Car Talk, Leonard Bernstein is immortalized in automotive lore for a shifting technique he handed down to his son. Elsewhere, Adla got a rude welcome to Boston when someone stole the battery from her Civic; Jennifer made an ill-advised bet on steering wheels with her know-it-all 18-year-old nephew; Esther's low coolant light and buzzer might be trying to send her a subtle signal about the state of her cooling system; and is John's Thunderbird suffering from Radio Frequency Interference or Dying Transmission Syndrome? All this and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-09-17",
        seconds: 3266,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/495356596/npr_495356596.mp3",
        filename: "car_talk_2016-09-24.mp3",
        title: "#1639: Fell Off Truck",
        description:
            "September 24, 2016 • This week on The Best of Car Talk, Matt's bad day got a little worse when his Volvo fell off the tow truck that was hauling it from an accident. Will Tom and Ray's vast experience dropping cars help Matt figure out if his is still safe to drive? Elsewhere, should Jackie go braless when washing her car? We're talking about the car's bra here, not Jackie's. Also, Peter thinks he has a theremin player living in his car; Barb's smart-aleck son may actually be smarter than she thinks; and on Stump the Chumps, we find out if Victoria bought cars for her three sons and opted for a career in flower arranging over business school. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-09-24",
        seconds: 3248,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/496227199/npr_496227199.mp3",
        filename: "car_talk_2016-10-01.mp3",
        title: "#1640: Desperate Times, Desperate Fluids",
        description:
            "October 1, 2016 • This week on The Best of Car Talk, Andy's car overheated in the desert. With no water on hand, his girlfriend convinced him to use the only liquid available. We're bordering on TMI here, so we'll just say that Andy is now worried about said liquid's acid causing corrosion. Elsewhere, Judy and her Volvo just moved from Los Angeles to Chicago. What does she need to do to winterize her car, and herself? Also, Christian's clutch problems are threatening his career in pizza delivery; Magica's husband dropped a razor blade in the airbag compartment and thinks it's not a big deal; and should Louella risk her safety and sanity by teaching her teenage daughters how to drive stick shift? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-10-01",
        seconds: 3204,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/497191066/npr_497191066.mp3",
        filename: "car_talk_2016-10-08.mp3",
        title: "#1641: Sue, the Stinko Driver",
        description:
            "October 8, 2016 • This week on The Best of Car Talk, Sue's boyfriend is afraid to get in the car with her due to her long history of accidents, near misses, and traffic violations. Sue insists she's a safe driver, so a full-scale Car Talk intervention may be necessary. Elsewhere, Robin thinks her VW's steering problem calls for an exorcist, but Tom and Ray say an arsonist may be more helpful; Joe may need to choose between a bungee cord and a 2x4 if he doesn't want to spring for a new transmission; and can Randy just keep adding a quart of oil to her Civic and live her life? Depends on whether her life involves driving the car! All this, plus more than you ever wanted to know about the hazards of adding urine to a radiator. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-10-08",
        seconds: 3248,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/498085233/npr_498085233.mp3",
        filename: "car_talk_2016-10-15.mp3",
        title: "#1642: Leah, We're Here For You",
        description:
            "October 15, 2016 • This week on the Best of Car Talk, Click and Clack answer the desperate plea of a depressed college student. Leah is contemplating the meaning of life and writes to Car Talk seeking answers. (Clearly more competent talk show hosts were busy!) Can Tom and Ray set her straight and help poor Leah find happiness? Meanwhile Hope's massive mutt has taken to riding on top of her pickup, and Paul's daughters are annoyed at his selective hearing. Will they hate dear old dad even more if he follows Click and Clack's advice? All that and more, in this week's automotively therapeutic episode of The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-10-15",
        seconds: 3205,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/498986324/npr_498986324.mp3",
        filename: "car_talk_2016-10-22.mp3",
        title: "#1643: Dave From Bemidji",
        description:
            "October 22, 2016 • This week on The Best of Car Talk, gather round for the greatest road trip story ever told. Dave and his girlfriend drove from Alaska to Minnesota in an overheating Chevy Cavalier with an old campfire grill jammed into the catalytic converter, a crescent wrench with no sockets, and one big zit on Dave's forehead. In more mundane matters, Patrice's VW bus won't start, John Mark's backseat passengers are getting their feet soaked when he makes a turn, and Alana's gas tank is spitting fuel back out after she fills it. Also, how should Rich wake up a Buick that's been napping for four years, and is the threat of fire enough to convince Jim that replacing his tailpipe might count as a \"necessary repair\"? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-10-22",
        seconds: 3247,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/499893064/npr_499893064.mp3",
        filename: "car_talk_2016-10-29.mp3",
        title: "#1644: Mayonnaise on My Dipstick",
        description:
            "October 29, 2016 • This week on The Best of Car Talk, Tim doesn't know if he should be worried about the substance on his Fury's dipstick, or if he should just make a tuna salad sandwich with it. Elsewhere, Tonia likes her next door neighbor but is less fond of the noxious chemicals he uses on his car; Larry wants to convince his wife it's okay to buy a used car from a rental company but a tale from Ray's past may change his mind; and Dara is having trouble selling a car that used to belong to the fire chief. Should she forget about selling the car and just advertise its spotlight? All this, plus the great Cathy/Kathy challenge, and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-10-29",
        seconds: 3240,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/500838801/npr_500838801.mp3",
        filename: "car_talk_2016-11-05.mp3",
        title: "#1645: The Bionic Bug",
        description:
            "November 5, 2016 • This week on The Best of Car Talk, Rita's VW won't start after being flooded during a hurricane. Does it have a future on the road, or just as a saltwater aquarium? Elsewhere, Bob discovered an unusual feature in his BMW as a result of his father-in-law being locked in the car for a half-hour; Dan's neighbor is convinced Dan's Acura has oil problems based only on the racket it makes when Dan drives home; and Chuck thinks his wife's parking brake technique is too quiet. Also, on Stump the Chumps, Tommy faces the Great Cathy/Kathy Challenge! All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-11-05",
        seconds: 3187,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/501852349/npr_501852349.mp3",
        filename: "car_talk_2016-11-12.mp3",
        title: "#1646: Tanya the Trainer",
        description:
            "November 12, 2016 • This week, The Best of Car Talk kicks off with the tale of one man's descent to Dante's supplemental Circle of Hell, the local health club, where he is at the merciless hands of his personal trainer, Tanya. Then we're off to Virginia, where Shelia's Maxima smells like someone burned her dry cleaning. Elsewhere, Ethan's preparing to sell his truck, which was struck by lightning. Should he advertise it as \"pre-disastered\" or keep quiet? Also, from the don't-try-this-at- home department, Marty's dad got their vintage car started by sucking gas through the exhaust with a shop vac, and he still has his eyebrows! All this and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-11-12",
        seconds: 3217,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/502711392/npr_502711392.mp3",
        filename: "car_talk_2016-11-19.mp3",
        title: "#1647: The Shrink-Wrapped Land Rover",
        description:
            "November 19, 2016 • This week on The Best of Car Talk, Mike and his sons are about to embark on a two-year around the world sailing voyage, but the vintage Land Rover Mike's been restoring won't be much use at sea. Should he sell it or will late-night TV provide the perfect storage solution? Elsewhere, Lisa's wondering how much restitution she's entitled to for allowing her husband to buy a used Corvette; Charlotte's daughter spent $300 on a truck and may have overpaid; and Arnie's Accord's harmonic balancers won't stay balanced. Also, Tom and Ray may need to consult Junk & Wagnalls' encyclopedia to diagnose Sandy's hum. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-11-19",
        seconds: 3279,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/503440917/npr_503440917.mp3",
        filename: "car_talk_2016-11-26.mp3",
        title: "#1648: The Black Hole of Auto Metaphysics",
        description:
            "November 26, 2016 • This week on the Best of Car Talk, one listener postulates that a non-essential repair on an old car creates a parallel universe where everything else starts to break. Sorry, but for proof, you may have to tune to the Sci-Fi Channel. Elsewhere in the land of semi-wacko theories, Mark was told he could use rice to clean a carburetor, and Joyce's boyfriend insists on leaving his Taurus' trunk open overnight to keep it dry. Also, can Stephanie blame her mom for killing her Subaru's clutch, and is Mike's snowblower really not starting because it's too cold? And, John's mechanic ran into the age-old dilemma: Is it better to admit stupidity or gaslight the customer? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-11-26",
        seconds: 3243,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/504471662/npr_504471662.mp3",
        filename: "car_talk_2016-12-03.mp3",
        title: "#1649: If You Suck a Sock",
        description:
            "December 3, 2016 • This week on The Best of Car Talk, Bob is worried his car may have a permanent case of athlete's foot (or worse) after a sock got sucked into the engine. Find out how the sucking transpired and whether Tom and Ray can stop laughing long enough to ease Bob's fears. Elsewhere, Patty's Accord began mooing at her. Is her best option to try milking it? Also, Elizabeth came home from Thanksgiving to discover her Volvo's windows permanently fogged; Marlene got talked into buying an electric anti-rust device for her new car; and Mike may re-think his desire for a \"heavy duty\" clutch after he hears Tom and Ray's tale of the customer known as Mr. Heavy Duty and his enlarged left foot. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-12-03",
        seconds: 3233,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/505105470/npr_505105470.mp3",
        filename: "car_talk_2016-12-10.mp3",
        title: "#1650: The Snort Track",
        description:
            "December 10, 2016 • This week on the Best of Car Talk, can Ray grant one listener's Christmas wish by snorting less? And why can't Bob stop laughing about his Geo's starting problem? Elsewhere, Alan's Lincoln is starting to sound eerily like his mother; Karen's Caravan's dashboard is telling her she's always going 120 miles per hour on an empty gas tank; Steph wants to tempt the Blowout Gods by removing his Miata's spare tire so he'll have more trunk space; and Ariel is thinking of buying her first car and is wondering what level of protection she needs to bring to the dealer. Will a Rottweiler do or a big guy named Bruno? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-12-10",
        seconds: 3245,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/505986373/npr_505986373.mp3",
        filename: "car_talk_2016-12-17.mp3",
        title: "#1651: Predestination of Lightning",
        description:
            "December 17, 2016 • This week on the Best of Car Talk, Evelyn wants to know why a bolt of lightning spared her car and struck the road 20 feet away instead. Tom and Ray think Evelyn should just say a few kind words to the deity of her choice and move on, but will nonetheless offer a pseudo-scientific answer that's guaranteed to have MIT demanding its diplomas back. Elsewhere we find out if Bob's wife's car survived sucking a sock into the engine on Stump the Chumps; Gary's steering noise is scaring away his girlfriends; and did Barbara do more damage to her husband's truck, or her marriage, by driving a mile without any oil? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-12-17",
        seconds: 3276,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/506844912/npr_506844912.mp3",
        filename: "car_talk_2016-12-24.mp3",
        title: "#1652: Ode to a Monte Carlo",
        description:
            "December 24, 2016 • This week on The Best of Car Talk, we thought nobody could be more devoted to an old heap than Tommy, but then we met Lita who has written a poem about her Monte Carlo—we're just relieved she didn't try to rhyme anything with \"rust bucket.\" Elsewhere, Steve moved to Chicago for a job and a girlfriend. He lost both, but he's most confused about why his Acura was the only car not towed from a party. Also, the holiday season brings good cheer and the annual squeak to Betsy's Town and Country; Kate's temporary fix for her frozen door locks is hilarious, and incredibly dangerous; and, did the hottest man in show business set Melinda's radio on fire? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-12-24",
        seconds: 3248,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/507708209/npr_507708209.mp3",
        filename: "car_talk_2016-12-31.mp3",
        title: "#1653: The Mustang Compost Bin",
        description:
            "December 31, 2016 • This week on The Best of Car Talk, Mary loaded her Mustang's trunk with compost two months ago. Her husband says it's rotting the floor, but Mary wants to keep the compost all winter for ballast. One added wrinkle: Mary got the Mustang because her husband works for Ford—at least, for the time being. Elsewhere, Carla would love to escape from Alaska for a bit, but the fact that her truck will only drive backwards is making it difficult. Also, can Kathy figure out her Stratus's burnt popcorn smell without asphyxiating her sons? And is Justin's engine making noise, or is he just hearing people laughing a him for driving an old Beetle? All this, plus a plea for more civil Hate Mail, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2016,
        date: "2016-12-31",
        seconds: 3271,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
