/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/576202456/npr_576202456.mp3",
        filename: "car_talk_2018-01-06.mp3",
        title: "#1801: Schmutz on the Clutch",
        description:
            "January 6, 2018 • This week on The Best of Car Talk, Dana's Jetta jerks in 1st Gear, and Tom and Ray have a highly technical explanation. Elsewhere, Mark thinks his \"straighten the curves\" driving technique is more efficient and saves wear and tear. It's also driving his wife crazy, which may be another plus as far as Mark is concerned. Also, Suzy checks in with the final report on her attempted drive across Mexico in a VW Vanagon; Andy felt like he was driving naked and after confirming he was wearing pants, determined his automatic seat belt wasn't so automatic anymore; and Joddy's (yes, that's how he spells it) Chrysler dealer says it will cost $300 to replace a missing nut, which is well, kinda nuts. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-01-06",
        seconds: 3228.103084,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/577849647/npr_577849647.mp3",
        filename: "car_talk_2018-01-13.mp3",
        title: "#1802: The Theory of Displaced Suffering",
        description:
            "January 13, 2018 • This week on The Best of Car Talk, Tom and Ray invoke the teachings of Daniel Pinkwater to convince Mary Ann that a really dumb car decision could improve every other aspect of her life. Alas, the Pinkwater philosophy won't help Paul, who is learning an expensive lesson about what happens when you don't test drive an old van before buying. Elsewhere, Ron has noticed an epidemic of padiddles (cars with one headlight out) since a recent cold snap; Lesley is looking for an antifreeze that will actually work in an Alaska winter (without giving her veterinary practice new patients); and does Tommy suffer from Chronic Fatigue Syndrome or Italian Male Malaise? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-01-13",
        seconds: 3233.649887,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/579335284/npr_579335284.mp3",
        filename: "car_talk_2018-01-20.mp3",
        title: "#1803: Rocks in your Saab",
        description:
            "January 20, 2018 • This week on The Best of Car Talk, can Adrienne use her Saab to deliver hundreds of pounds of rocks for her husband's birthday, or does Adrienne have rocks in her head? Elsewhere, Sarah's Taurus smells like waffles and maple syrup, so unless she spilled any IHOP leftovers down the vents, she may be shopping for a new engine or a new car. Also, Tracy and her dog both need help convincing her husband to use his brakes and abandon his \"conservation of memomentum\" theory; Jim's friends are trying to convince him his van wlll have an easier time starting if he turns on the lights before turning the key; Chris can spend a few hundred dollars to turn off his Mazda's EGR light or invest in official Click and Clack black tape; and Daniel Pinkwater weighs in on his Theory of Displaced Misery. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-01-20",
        seconds: 3179.302494,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/581285221/npr_581285221.mp3",
        filename: "car_talk_2018-01-27.mp3",
        title: "#1804: I'm Doing You a Favor. I'm Giving You an F!",
        description:
            "January 27, 2018 • This week on The Best of Car Talk, Tom gets the rare opportunity to fail Physics a third time as he and Ray try to help Kathy \"help\" her son design his Pinewood Derby race car. Elsewhere, Bridget's car is making a whisking sound that's only a little less scary than Tom and Ray's attempts to mimic it; Pam's Volvo is smoking more than her husband and arousing the ire of the Amherst, VA police department; and Johnny's attempt to fix his Jeep may require him to avoid wearing rayon pants. Also, new research that demonstrates the male brain's oscillation between pure genius, and pure incompetence. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-01-27",
        seconds: 3204.446803,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/582975557/npr_582975557.mp3",
        filename: "car_talk_2018-02-03.mp3",
        title: "#1805: If It Ain't Broke, Don't Break It",
        description:
            "February 3, 2018 • This week on The Best of Car Talk, Jim replaced a torn CV joint on one side of his Subaru and then decided to replace the other side, just so it wouldn't feel left out. Now, Jim's car is \"undulating\" on the highway. Is Jim's good deed going punished? Elsewhere, Carla can't figure out which of her brothers she shouldn't drive like, when it comes to shifting; Ainsley's bumper is being held on with epoxy and her husband won't let her take it through the car wash, fearing the bumper will be left behind; UPS driver Steve wonders why his colleagues all get new trucks and he's still driving a beater; and does Scott have a French horn player living under the hood of his Explorer? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-02-03",
        seconds: 3241.39263,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/584768235/npr_584768235.mp3",
        filename: "car_talk_2018-02-10.mp3",
        title: "#1806: Unstick My Dipstick",
        description:
            "February 10, 2018 • This week on The Best of Car Talk, despite the best efforts of every vice-grip holder in a 30-mile radius, Lyle can't move her truck's dipstick. Is her only option to turn the truck upside down and hope gravity does the trick? Meanwhile, the laws of space and time are being challenged in Colorado, where Ian's girlfriend's odometer is spinning backwards. Should she trade her car in before or after it hits negative numbers? Also, Jay's Civic was running perfectly until he attempted some DIY maintenance, and now the car is revving high and getting lousy gas mileage; Erin's turn signals fail if she turns on the high beams in the 3-tone Impala she inherited from her grandfather; and Steve poses the philosophical question, why do bad things come to cars in the threes, in the worst possible weather? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-02-10",
        seconds: 3215.411587,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/586770003/npr_586770003.mp3",
        filename: "car_talk_2018-02-17.mp3",
        title: "#1807: Scotch and Diesel",
        description:
            "February 17, 2018 • This week on The Best of Car Talk, Rick's diesel Rabbit ran out of fuel and the only liquid Rick had on hand was a bottle of scotch. Could he have poured the scotch into the tank or would Rick have been better off drinking it and waiting for the tow truck? Elsewhere, a tree fell on Murli's Corolla (we think it made a sound), and he doesn't know whether to replace the roof or have it straightened; Sally's steering column is sending smoke signals; and Kerry needs help navigating the \"Pit of Despair\", a giant water-filled pothole in her building's parking lot. Also, on Stump the Chumps, we find out if Tom and Ray helped Kathy lead her son to victory in the Pinewood Derby, and how much he lost by. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-02-17",
        seconds: 3223.480839,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/588516343/npr_588516343.mp3",
        filename: "car_talk_2018-02-24.mp3",
        title: "#1808: Belted In",
        description:
            "February 24, 2018 • This week on The Best of Car Talk, Brenda's shoulder belt got stuck in her jacket zipper effectively trapping her in her car. Embarrassing? Sure, but not as embarrassing as Tom and Ray's friend who tried to drive her car from the back seat. Elsewhere, Ben's band wants to take his vintage Volvo on tour from Seattle, and wants to know if he can book any shows beyond, say, Tacoma. Also, Albee wants to sell a sputtering and stalling LeBaron to his mother-in-law, which is probably one way to guarantee she never visits; Judy swears her Olds is making noise. Her mechanics are telling her she's crazy, but at least they're doing it politely; and Gretchen thinks she may have gotten too good a deal from the guy who got the mud out of her Sentra. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-02-24",
        seconds: 3231.858503,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/590550801/npr_590550801.mp3",
        filename: "car_talk_2018-03-03.mp3",
        title: "#1809: Ferrariless in Seattle",
        description:
            "March 3, 2018 • This week on The Best of Car Talk, Steve needs help adjusting to a life with four cylinders and cloth seats, after his recent divorce forced him out of his Ferrari and into a Camry. Elsewhere, Deirdre's mechanic has a hair-brained scheme to weld new teeth on her Volvo's flywheel. Is it worth doing, even if it's just for laughs? Also, Connie needs help choosing the right car for her road trip to Rio de Janeiro; Daniel needs to stop replacing distributor caps, and replace his mechanic, if he wants to find out why his Sentra stops running; Piali's best response to her squeaking steering wheel may be a swear box; and is Lyle's strategy of putting a pizza box in front of the radiator a boooogus way to warm his car? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-03-03",
        seconds: 3203.554218,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/592582367/npr_592582367.mp3",
        filename: "car_talk_2018-03-10.mp3",
        title: "#1810: Next Stop, Yak Husbandry?",
        description:
            "March 10, 2018 • This week on The Best of Car Talk, Whitney's husband insists on waiting until the low fuel lights comes on before getting gas. Is he damaging their car, and even if he is, would curing this habit damage his psyche? Elsewhere, Tom thinks his mechanic is suffering from \"Symmetry Neurosis\" for insisting on replacing parts in pairs. Also, Ricardo had his car trucked from San Francisco to Boston and now its clutch is cooked; Dana loaned her Jetta to a friend and got it back with a new noise; and Howard's Lincoln is emitting a whooping noise when he gets of the car. Did he buy the extremely limited Three Stooges Curly Package? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-03-10",
        seconds: 3218.934671,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/594541304/npr_594541304.mp3",
        filename: "car_talk_2018-03-17.mp3",
        title: "#1811: The Fall's Gonna Kill You",
        description:
            "March 17, 2018 • This week on The Best of Car Talk, Tom and Ray turn to the wisdom of Butch Cassidy to help settle a dispute between Erin's husband and friend over shifting. Then, the guys help James and his fiancee take on the Marital-Industrial Complex by registering for gifts at Louie's Lexus rather than Chafing Dishes R Us. Also, Bob loves the former police car he just bought but may need to replace a part he doesn't believe exists; Anita's truck has developed a heavy breathing sound; and Eric is looking for the perfect vehicle for a family trip along the Al-Can Highway. Maybe he should be looking for four perfect vehicles? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-03-17",
        seconds: 3211.286871,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/596666290/npr_596666290.mp3",
        filename: "car_talk_2018-03-24.mp3",
        title: "#1812: The Truth Detector",
        description:
            "March 24, 2018 • This week on The Best of Car Talk, Judith figures two mechanics would be the perfect test subjects for her voice-biometrics lie detector. But her choice of Tom and Ray might cause the machine to just give up. Elsewhere, Outdoor Studies major Ted is about to graduate and plans to drive his vintage Dodge van from upstate New York to Alaska. Ted might be studying a lot of the outdoors—waiting for tow trucks. Also, Cindy's car got really loud after she replaced the exhaust system; Justin's Civic has water pouring in through the speakers when it rains; and Christine's key is stuck in her ignition which has less urgency now that the car won't start. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-03-24",
        seconds: 3190.893741,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/598504954/npr_598504954.mp3",
        filename: "car_talk_2018-03-31.mp3",
        title: "#1813: You Can't Go Back",
        description:
            "March 31, 2018 • This week on The Best of Car Talk, Gloria's mechanic told her not to put her car into reverse first thing in the morning. Does Gloria need to build a circular driveway so she can follow this advice or can it be consigned to the Land of Old Wives Tales. Elsewhere, LaDell just started selling cars and already made his first mistake, bragging about a car's torque without knowing what torque is. Can Tom and Ray help him avoid future faux pas? Also, Liberty's new motto may be \"Give me ball joints, or give me death\"; ski bum Chris is wondering how to handle her truck which spent a cold winter abandoned in Chicago; and can Liz's truck handle her growing family of sled dogs? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-03-31",
        seconds: 3199.935397,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/600493458/npr_600493458.mp3",
        filename: "car_talk_2018-04-07.mp3",
        title: "#1814: Dad, How Could You?",
        description:
            "April 7, 2018 • This week on The Best of Car Talk, Linda is suffering acute separation anxiety, after her dad sold the family's beloved Rambler to a neighborhood teen. Can Tom and Ray help Linda get closure or suggest a few semi-legal strategies to get the car back? Elsewhere, Rita's \"soon to be ex-husband\" says she should always use the parking brake, and she's convinced he must be wrong because she's dumping him. Also, Mike's attempt to show off his ability to shift into third gear cost him Reverse; Gamin's Civic is making noise ever since she drove through a deep puddle; and is there enough Prozac in the world to get Christine and her mom through driving lessons? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-04-07",
        seconds: 3179.954354,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/602454391/npr_602454391.mp3",
        filename: "car_talk_2018-04-14.mp3",
        title: "#1815: The Four Door Planter",
        description:
            "April 14, 2018 • This week on The Best of Car Talk, the junkyard refused to haul away Ruth's beloved Dodge Colt. So the big question is, does it have a future as an arboretum or a terrarium? Elsewhere, Alan's relocating from Dallas to Vermont and wants to know if his Bronco needs to be outfitted with anything other than snow tires and Bronko Nagurski long underwear. Also, Nathan learned an expensive lesson about what happens when you tow a boat in 5th gear; Jeff is prepared to strap someone to the hood to help diagnose his Grand Am's \"arthritic knee\" noise; and on Stump the Chumps, we find out if Dana's Jetta really was suffering from schmutz on the clutch. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-04-14",
        seconds: 3225.473946,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/604571154/npr_604571154.mp3",
        filename: "car_talk_2018-04-21.mp3",
        title: "#1816: Imprudent and Unwise",
        description:
            "April 21, 2018 • This week on The Best of Car Talk, Ray recounts a dark day in Massachusetts history—when the powers that be decided his 16-year-old son was worthy of a driver's license. Elsewhere, it's planting season on Diane's parents' farm and they'd like her husband to remove the BMW with a blown engine residing there. Also, Nirav's Wrangler's horn blared at 5 AM and now won't honk at all. Might the angry neighbor with a sledge hammer and wire cutters be responsible? Ira's Jeep had one leaky injector, but he was told nature required him to replace all six; Tim can't turn his wipers off unelss he bangs on the steering column; and Michelle's husband gave her some bogus advice about not using the parking brake. How bogus? Depends on how likely he is to beat up two puny radio hosts. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-04-21",
        seconds: 3197.388413,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/606733469/npr_606733469.mp3",
        filename: "car_talk_2018-04-28.mp3",
        title: "#1817: Slow Milking",
        description:
            "April 28, 2018 • This week on The Best of Car Talk, Tamsen's mechanics are replacing lots of parts on her Super Beetle (and there weren't that many to begin with), but not the part that's causing the car to vibrate. Are they genuinely clueless or just using a dairy farm technique? Elsewhere, Dennis dreamed that someone gave him a '66 Ford Fairlane. Will Drs. Magliozzi make a house call to help him interpret it? Also, Kathleen's trying to save miles on her leased car by \"straightening the curves\"; Johanna is moving into a teepee for the summer and is worried about her car washing away (we'd be more concerned about the teepee); and Donna's husband hijacked her new Miata, insisting he needed to drive it to \"break it in properly\"; and we proudly unveil the Car Talk Listener Rebate Program. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-04-28",
        seconds: 3203.548254,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/608739990/npr_608739990.mp3",
        filename: "car_talk_2018-05-05.mp3",
        title: "#1818: The Power of Carrot Cake",
        description:
            "May 5, 2018 • This week on The Best of Car Talk, Wendy is worried that her mechanic's difficulty diagnosing her noisy Golf is affecting his mental health. Is a round of baked goods therapy the cure? Meanwhile, Robin is having her own issues with guilt after forsaking her regular mechanic and taking her Corolla to the dealer for its 30,000 mile service. Also, Jonathan doesn't know whether to celebrate or fear winning the argument with his wife over speed bumps; Tina's brake problem could be her ticket to stardom in Vegas; and Scott's uncle suggested he unplug his Accord's odometer to keep its mileage down. We probably don't need to tell you this, but Scott's uncle is a used car salesman. Will Tom and Ray advise Scott on how to do this, or call the Feds? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-05-05",
        seconds: 3219.62034,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/610645923/npr_610645923.mp3",
        filename: "car_talk_2018-05-12.mp3",
        title: "#1819: The Power of Nothingness",
        description:
            "May 12, 2018 • This week on The Best of Car Talk, Dayton's speedometer only works occasionally. Tom's advice? Take the Zen approach, and do nothing. Might Ray consider Dayton's budget for speeding tickets while crafting his reply? Elsewhere, Missy's son is headed to college this fall and wants to take an Audi Quattro with him, to Our Fair City. Should Missy spend the summer trying to talk him out of it? Also, Scott and his father-in-law have different views on accelerating while shifting; Char's Mercedes dies if she drives for two hours with the sunroof open; and Mark wants to know if his Ford Tempo can survive hauling a trailer with all his worldly possessions from Dallas to Philadelphia. He might do better trying to get from Dallas to Fort Worth. And, in honor of Mother's Day, Elizabeth Magliozzi checks in on her boys' undershirt status. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-05-12",
        seconds: 3228.641859,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/612619364/npr_612619364.mp3",
        filename: "car_talk_2018-05-19.mp3",
        title: "#1820: Tailpipe Diplomacy",
        description:
            'May 19, 2018 • This week on The Best of Car Talk, Chip likes his neighbors, but they insist on warming up their cars for 20 minutes every morning, and the noise and smell are driving Chip crazy. A well-placed cherry bomb might convince them to stop, but is there a more peaceful solution at hand? Elsewhere, Tom started selling cars two weeks ago, and is worried about the potential side effects. Also, Jennifer chose the worst city possible to learn how to drive a stick shift; Bill and his wife are looking for a $700 car that says "eccentric" rather than "cheapskate"; and Jeff relocated from New Orleans to a few thousand feet above sea level. His car handled the move, but his bread maker is producing hockey pucks. Can Tom and Ray put some lift into Jeff\'s loaves? All this and more, this week on The Best of Car Talk.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-05-19",
        seconds: 3254.868254,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/614654467/npr_614654467.mp3",
        filename: "car_talk_2018-05-26.mp3",
        title: "#1821: The Tupperware Theory",
        description:
            "May 26, 2018 • This week on The Best of Car Talk, Barbara's husband is a burper. At the gas station, he insists on shaking the car to squeeze in a few extra drops. Will Tom and Ray help Barbara convince her husband to stop belching out wacko ideas? Elsewhere, Denise's friend is coming from Germany, with his Citroen (assuming it fits the carry-on bin), and planning to drive it from New York to Minnesota. Will he make it past the Hudson River? Also, Steve's Check Engine light comes on only when he parks at the Pentagon; Kailash's mechanic told him his Escort has \"Break Squeak Syndrome,\" but Tom and Ray think this diagnosis has one \"s\" too many; and, (another) Barbara needs help retrieving the keys that fell behind her dashboard, along with the dozen or so household items she's unsuccessfully used to try to retrieve them. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-05-26",
        seconds: 3250.724467,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/616408552/npr_616408552.mp3",
        filename: "car_talk_2018-06-02.mp3",
        title: "#1822: How Scientists Go Bad",
        description:
            "June 2, 2018 • This week on The Best of Car Talk, Teddi's Camry screeches when she starts it. She's developed lots of techniques that seem to avoid the noise, but is she mistaking correlation for causation? Elsewhere, John's wife says he's triggering the Lardbutt Indicator in her Golf causing the horn to blare at random times, only when he's driving it. Also, mobile dog groomer Gwen needs to decide whether to repaint or replace her company van; Wendy's looking for a car she can work on herself to help her meet guys; and can Jeff use his camping stove fuel in his Civic in an emergency? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-06-02",
        seconds: 3311.93576,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/618915060/npr_618915060.mp3",
        filename: "car_talk_2018-06-11.mp3",
        title: "#1823: The Family That Bondos Together",
        description:
            "June 11, 2018 • This week on the Best of Car Talk, Ike wants to spend the summer restoring an old truck with his 15-year-old son. Will this be a memorable father-son experience for all the wrong reasons? Elsewhere, Lisa's white Rabbit convertible top has gone gray, despite the use of every cleaning chemical known to humankind. Also, Nancy is worried that two-footed driving may be hereditary; Brent's Audi is leaking the most expensive oil on the planet; and the previous owner of Gary's Morris put in a positive ground. Is it really possible for wipers to run backwards? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-06-11",
        seconds: 3272.928277,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/620640347/npr_620640347.mp3",
        filename: "car_talk_2018-06-16.mp3",
        title: "#1824: We Will Bury You",
        description:
            "June 16, 2018 • This week on The Best of Car Talk, Eric may need to channel the late Nikita Khrushchev if he wants air conditioning this summer. Meanwhile, Tama may need to clear out the Old Spice aisle to get the stink out of her Jeep so she can sell it. Also, Steve can remove his Omni's key while the car is still in drive which is pretty cool, except for that time the car ran over him; Teri's Accord is making noise in a place where there's nothing that can make noise; and Jordan's Taurus introduces a new Car Talk motto, \"They don't care what we say, and we don't care what they do.\" All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-06-16",
        seconds: 3288.217347,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/622810084/npr_622810084.mp3",
        filename: "car_talk_2018-06-23.mp3",
        title: "#1825: Male Moron Syndrome",
        description:
            "June 23, 2018 • This week on The Best of Car Talk, genetics suggest that men inherit intelligence from their mothers, which as Tom and Ray postulate, leaves one likely source for the \"Hey guys, watch this!\" gene. And to prove that point, Josh in Montana is testing the theory by trying to find the source of his truck's rattling noise by examining the under carriage—while the truck is moving. Also, Sara can't figure out how her pet chicken survived a ride under the hood of her Tahoe; John the mechanic needs to know the labor rate for evil ex-girlfriends; Cathy's Sentra is sending her to the poor house; and on Stump the Chumps, we find out if Michael fixed his father-on-law's Town Car and inherited it in the process. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-06-23",
        seconds: 3287.188617,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/624928460/npr_624928460.mp3",
        filename: "car_talk_2018-06-30.mp3",
        title: "#1826: The Waning of Waxing",
        description:
            "June 30, 2018 • This week on The Best of Car Talk, Andy loves waxing his car, but his friends tell him he's wasting his time. Has paint technology made waxing passe, save for the mental health benefits? Elsewhere, Diane thinks her husband's claim that BMWs have a unique aroma is a bogus attempt to justify his mid-life crisis; Melissa traded her car to her ex-husband for a rifle and a skiff, but he thinks he got ripped off; and Ed's solution to a sticky shifter may give his insurance company an ulcer. Also, how one student's GPA plummeted after she listened to a single episode of Car Talk; and a new wieght loss plan that's guaranteed to work—the Geriatric Diet. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-06-30",
        seconds: 3251.03873,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/626835025/npr_626835025.mp3",
        filename: "car_talk_2018-07-07.mp3",
        title: "#1827: Porca Miseria",
        description:
            "July 7, 2018 • This week on The Best of Car Talk, one listener corrects the record on what NPR's Sylvia Poggioli really says when Tom and Ray besmirch her network by their very presence. You may share Sylvia's horror when you hear our hosts struggle to figure out why Patty's MG will only travel 2 feet at a time. Elsewhere, Wendy's broken air conditioner indicates her relationship may also be busted; Deb threw her husband's BMW into park before coming to a full stop, and doesn't know if she should be more concerned about the resulting noises from the car or her spouse; and, Steven got cheers from his kids and a dope slap from his wife after driving his Trooper across a stream. How did the car respond? All this, plus a ringing defense of PhD's and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-07-07",
        seconds: 3270.09322,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/629076223/npr_629076223.mp3",
        filename: "car_talk_2018-07-14.mp3",
        title: "#1828: The Bet",
        description:
            "July 14, 2018 • You send just one of your brother's heaps to the crusher, and you never hear hear the end of it. But this week on the Best of Car Talk, Patti's mom's attempt to drive her Datsun from Houston to Boston may spare Ray from ever having to hear the phrase \"sleek black beauty\" again. Elsewhere, Casey's career making bagpipes may be the only way to rid his Civic of the garter snakes that have taken residence. Also, Gloria's Jetta is losing power on the highway, and her work-around might get her killed; John may have replaced the wrong \"gizmachi\" to try to get the raw gas smell out of his Town Car; and Maz hears birds chortling when she downshifts her Fiat. All this, plus the legendary Melissa Peterson letter, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-07-14",
        seconds: 3303.85449,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/631107963/npr_631107963.mp3",
        filename: "car_talk_2018-07-21.mp3",
        title: "#1829: The Full Chicago",
        description:
            "July 21, 2018 • Everyone knows a joke is less funny if you have to explain it. But if the joke wasn't funny in the first place, it's not really a problem. So, this week on the Best of Car Talk, Tom and Ray explain the origin of one of their favorites, a \"full Chicago.\" In matters automotive, Caroline is concerned about her Toyota's low idle and her husband's insistence they wear bicycle helmets in the car for safety. Also, Sarah's car seems to have become a magnet for thieves and wayward trucks looking for something to hit; Bob is trying to imagine a life without power steering; Tom and Ray advise Jamie on how to fake a natural death for his Excel; and on Stump the Chumps we find out if John was triggering the Lardbutt Indicator in his wife's Golf. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-07-21",
        seconds: 3286.192336,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/633390935/npr_633390935.mp3",
        filename: "car_talk_2018-07-28.mp3",
        title: "#1830: Moronic Existentialism",
        description:
            "July 28, 2018 • This week on The Best of Car Talk, between Being and Nothingness is—a loose heat shield? One listener suggests Tom and Ray's baffling car advice is actually the dawning of a new line of deep philosophical thought. Elsewhere, Mary Jane hopes the guys can help save her marriage by not answering her husband's call about his Ford Fairlane; Sandy may need to be bribed to get a diagnosis for her noisy Accord; David parked his Civic in the garage for a week and now the parking brake is stuck; and Barry can't understand why his Mercedes is a bug magnet. Finally, why is Jeff's CD radio messing up his cruise control? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-07-28",
        seconds: 3278.88712,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/635608388/npr_635608388.mp3",
        filename: "car_talk_2018-08-04.mp3",
        title: "#1831: The More Perfect Elevator",
        description:
            "August 4, 2018 • This week on The Best of Car Talk, Tom and Ray venture far afield as they consider one listener's idea that could revolutionize elevator operations (within the confines of still going up and down)— if anyone can make heads or tails of it. Later, on Stump the Chumps, we find out if our hosts helped Jeff's breadmaker resume making loaves instead of hockey pucks. To mollify NPR, we'll also wrestle with a few car questions. Drea wants to know if steam cleaning the engine is really a good way to pamper her Nissan; Elizabeth's BMW's door locks have gone wacko and she can only get in the car if she grabs the handle at exactly the right moment; Evan's wondering what became of the golf ball her 3-year-old son stuck up the tailpipe; and do Paul's lug nuts have to be tightened following a religous code? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-08-04",
        seconds: 3274.21898,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/637829216/npr_637829216.mp3",
        filename: "car_talk_2018-08-11.mp3",
        title: "#1832: The Alternator Ashram",
        description:
            "August 11, 2018 • This week on The Best of Car Talk, Elizabeth's Audi is going through an alternator a month. Is the problem inside her car, or are they being built by the wrong group of Tibetan monks? Elsewhere, Aron's Nissan is channeling the Three Stooges; Kristin learned there's no such thing as a free brake inspection; Ann's about to learn why she should never listen to her father — or her kids' father — when it comes to cars; and Patti settles Tom and Ray's great Sleek Black Beauty bet with news on her mom's attempt to drive a Datsun from Texas to Massachusetts. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-08-11",
        seconds: 3248.427619,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/639835708/npr_639835708.mp3",
        filename: "car_talk_2018-08-18.mp3",
        title: "#1833: Ted the Shim Master",
        description:
            "August 18, 2018 • This week on The Best of Car Talk, Ted put his carpentry skills to work by redirecting his van's leaky exhaust through a series of pipes outside the van. His pipe-shrouded van might scare off clients, and he may have greatly increased the chances of setting the van on fire, but is Ted still worthy of a Click and Clack Genius award? Elsewhere, Jeff is concerned that his Eagle Scout son doesn't want to drive, but he may want to give the kid another merit badge, for good sense; Peter has gotten half a dozen bad diagnoses for his truck's shifting problem—including floor mats—and may be about to get one more; and are Tom and Ray leading practitioners of \"Learned Ignorance\"? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-08-18",
        seconds: 3258.456825,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/641844414/npr_641844414.mp3",
        filename: "car_talk_2018-08-25.mp3",
        title: "#1834: Foreign Accent Syndrome",
        description:
            "August 25, 2018 • This week on The Best of Car Talk, our all-time favorite neurological oddity: a Massachusetts man begins speaking with a French accent following an accident. Could a whack to the noggin make Tom and Ray speak like actual mechanics? Also, three tales of things that aren't where they're supposed to be. John's dipstick keeps popping out, Crystie dropped a nail into her gas tank, and Dana's friend has a piece of the Berlin Wall lodged in his dad's BMW's trunk. And, Julie \"backed into a car that wasn't there\" and didn't confess to her husband. Is it time to come clean? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-08-25",
        seconds: 3249.020272,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/643935792/npr_643935792.mp3",
        filename: "car_talk_2018-09-01.mp3",
        title: "#1835: The Soul of an Isuzu",
        description:
            "September 1, 2018 • This week on The Best of Car Talk, Jeff's Isuzu Trooper needs a new engine, but he's worried that a transplant will change his car's very identity. Does a car have a soul, and does Jeff need a mechanic or an exorcist? Elsewhere, Helena and her husband found a dream used car with one idiosyncrasy—it only goes in reverse. Good thing it came with a spare transmission in the trunk. Also, Roe borrowed her friend's Civic for three months and was so protective of the clutch that she kept forgetting to release the parking brake; the one and only Melissa Petersen makes a startling admission about her dog's true feelings towards Ray; and guess what turned up in a government auction—Sonja Henie's tutu! All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-09-01",
        seconds: 3253.291315,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/645829056/npr_645829056.mp3",
        filename: "car_talk_2018-09-08.mp3",
        title: "#1836: Mom, Karen, and the Rottweiler",
        description:
            "September 8, 2018 • This week on The Best of Car Talk, Tom's Pathfinder needs new shocks, and given that he's about to embark on a road trip with his mom, girlfriend, and dog, he'd better buy the right ones. Elsewhere, Alan's undercover surveillance work has been a bit compromised by his over-active windshield wipers. Also Carolyn's husband insists on treating their automatic transmission as if it's a stick shift; a ton of clay may have been too much for Charlie's Explorer to carry; and Bill tried to use his daughter's tights to replace a broken serpentine belt, but they flew apart. Were they the wrong size? The wrong color? And would Tom and Ray have done better as hairdressers than mechanics? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-09-08",
        seconds: 3253.88229,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/648230456/npr_648230456.mp3",
        filename: "car_talk_2018-09-15.mp3",
        title: "#1837: Siphoning for Dummies",
        description:
            "September 15, 2018 • This week on The Best of Car Talk, Rory's ego is in trouble, after he failed to siphone gas from his car to his lawn tractor. Has siphoning gotten more difficult, or is Rory just incompetent? Elsewhere, Tom doesn't know if it's worth cautioning his son about driving cross country in a pickup truck, if all he'll get in return in the \"stunad stare\". Also, Maggie's gauges stop working only when she drives by the Mall of America; Darlene's road trip from Colorado to San Francisco felt like she was floating on air, likely because she really was; and on Stump the Chumps, we find out if marriage cured Ellen's fiance of his obsession with performance add-ons. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-09-15",
        seconds: 3268.885351,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/650730324/npr_650730324.mp3",
        filename: "car_talk_2018-09-22.mp3",
        title: "#1838: It's Only a Car",
        description:
            "September 22, 2018 • This week on The Best of Car Talk, Beryl won custody of her husband's old Mercedes in their divorce. She loves the car, but may be moving from Texas to the Great Frozen North and isn't wild about driving it in the snow. Should she dump it, put money into making it safer, or follow Tom and Ray's Plan C? Elsewhere, Tony's Chevy may have tried to kill his mother-in-law with brakes that didn't brake; Ginny and her husband are arguing over the best way to avoid croaking frogs on the road; and Ellen's mechanic says her oil has the smell of engine death. Is he really smelling the oil or just his cologne? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-09-22",
        seconds: 3266.047075,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/652927798/npr_652927798.mp3",
        filename: "car_talk_2018-09-29.mp3",
        title: "#1839: The Chia Pontiac",
        description:
            "September 29, 2018 • This week on The Best of Car Talk, Jake's car is growing hair on top and to make things worse, it clashes with the car's color. Did someone slip Rogaine into Jake's gas and does he need a paint job or a cream rinse to deal with it? Elsewhere, Nancy's 3-year old son gets carsick when she drives \"the wiggly road\", aka, The Pacific Coast Highway, but does fine when Dad''s behind the wheel. Also, Jason's car has three problems and may get three wrong answers; Mike agreed to pull his neighbor's engine, and is about to learn he's going to have to pull a lot more, too; and, Sally's dream car may be trying to kill her. All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-09-29",
        seconds: 3297.025737,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/655137419/npr_655137419.mp3",
        filename: "car_talk_2018-10-06.mp3",
        title: "#1840: Two Geeks and a Twerp",
        description:
            "October 6, 2018 • This week on The Best of Car Talk, Melissa Petersen returns with another helpful critique. But how can Tom and Ray be geeks and hippies at the same time? Elsewhere, Quentin can't decide whether to restore his grandfather's Dodge Dart Swinger (the most inaccurately named car ever?), or re-gift it to the nearest crusher. Also, Moon's trip to the Grand Canyon was marked by an argument with his wife over air conditioning; Bernadette is considering a career change from one non-profit to another by becoming a mechanic; and should Diane add a paint overcoat to her daughter's Jetta, or is this (yet another) dealer scam? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-10-06",
        seconds: 3265.079773,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/657127358/npr_657127358.mp3",
        filename: "car_talk_2018-10-13.mp3",
        title: "#1841: If You Don't Think Too Good, Don't Think Too Much",
        description:
            "October 13, 2018 • This week on The Best of Car Talk, Rick has lots of reasons to justify adding a supercharger to his Miata. Unfortunately, they're all harebrained. Will the wisdom of baseball legend Ted Williams help dissuade Rick, or does a mid-life crisis trump all? Speaking of harebrained, Cheryl's brother is driving around with a rotted gas tank, and the fuel lines re-routed to a tank in his trunk. Also, Tamara's family needs help saying goodbye to their beloved Vanagon; Mike may be facing a winter without power steering; and Melissa's husband is about to learn what happens when you cheap out on snow tires. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-10-13",
        seconds: 3219.370136,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/659135100/npr_659135100.mp3",
        filename: "car_talk_2018-10-20.mp3",
        title: "#1842: The Debris Theory",
        description:
            "October 20, 2018 • This week on The Best of Car Talk, Reid wants to save his Audi's transmission by flushing it, but his mechanic thinks the gunk is the only thing keeping the tranny from self-destructing. Will Tom and Ray embrace the debris theory? Elsewhere, Colleen's dad used the \"break brake-in' theory\" to insist he had to drive the family to the movies. Was this science or just a way to tell Colleen he thinks she's a stinko driver. Also, Melissa is relying on a rope to keep her driver's door shut; Katie wants to use white gas that's too old for her camp stove in her Corolla; and Tommy pulls out one of his most ingenious ideas to help David get away with buying only two snow tires instead of four. Of course, David may not make it through winter, but does that make it any less brilliant? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-10-20",
        seconds: 3211.512812,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/661332969/npr_661332969.mp3",
        filename: "car_talk_2018-10-27.mp3",
        title: "#1843: Clink and Clank",
        description:
            "October 27, 2018 • This week on the Best of Car Talk, Greg's truck is making noise. The good news is Tommy came prepared with Ford's official book of car noises. The bad news is Greg's truck is a Dodge. Elsewhere, Rollie's test drive turned eventful when he backed into a light pole and is on the run from a dealer with an insurance deductible. Also, David's cruise control is out of control when the headlights are on; Chella is pondering a life without third gear; and Sharon is wondering why so many men are driving around picking their noses. All this, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-10-27",
        seconds: 3240.545782,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/663882092/npr_663882092.mp3",
        filename: "car_talk_2018-11-03.mp3",
        title: "#1844: Nasal Decloggery",
        description:
            "November 3, 2018 • Who knew there was a pseudo-technical name for picking your nose in your car? This week on The Best of Car Talk, listeners who weren't completely disgusted by last week's discussion offer their analysis of automotive nostril penetrations. Elsewhere, Charlotte and her husband decided to spice up their lives by adopting four children and want to make things even more exciting by finding an old car they can use as a jungle gym. Also, Jody is searching for her Accord's chi, so she can use acupuncture to get rid of a ticking noise; JD just lost his girlfriend and fears his truck's engine will be the next to go; and will a nice grapefruit stabilize John's Jeep's oil pressure? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-11-03",
        seconds: 3225.204989,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/666513357/npr_666513357.mp3",
        filename: "car_talk_2018-11-10.mp3",
        title: "#1845: The Miracle Spray",
        description:
            "November 10, 2018 • This week on The Best of Car Talk, why do Tom and Ray think Heather is crazy for believing that starter fluid is solving her Subaru's starting problem? Elsewhere, grad student Rebecca is considering driving from Connecticut to Indiana in a car that likely won't make it to the New York border; Frances's love for her Miata is being tested by the chance to inherit her uncle's Porsche; and did Chris's brother find love in a hyperbaric chamber after he and his girlfriend passed out from CO poisoning? All this, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-11-10",
        seconds: 3231.144036,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/668876384/npr_668876384.mp3",
        filename: "car_talk_2018-11-17.mp3",
        title: "#1846: Stop and Smell the Antifreeze",
        description:
            "November 17, 2018 • This week on The Best of Car Talk, Alan thinks his Mercedes was born with a 100,000 mile death gene. Ever since the odometer rolled over, the car's been nothing but trouble and now Alan is ready to dump it. Might he be acting a bit prematurely? Elsewhere, Dave's commute may get more complicated this winter, because his Audi's heater only works on right turns; Keri wants to soup up her scooter after it lost a race to a Vespa; and is Michael going to set off his airbag by drumming along with the Who? Also, two of the best listener car noise renditions we've ever heard. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-11-17",
        seconds: 3274.225125,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/670522890/npr_670522890.mp3",
        filename: "car_talk_2018-11-24.mp3",
        title: "#1847: Would You Rather Be Right Or Happy",
        description:
            "November 24, 2018 • This week on The Best of Car Talk, Doug's dashboard began billowing smoke the first time he ran his defroster. His wife diagnosed it as roasting bugs, and Doug forgot Tommy's first rule of marital happiness when he told her, \"You're nuts.\" Could she have been right, and can Doug get out of the doghouse? Elsewhere, Alex may need help finding closure over his beloved pickup, while Christine can't decide whether to accept her parents' offer of their Buick station wagon; and Tracy wishes someone would haul away the mysterious Stanza that's been sitting in front of her house for the last two months. Also, can Jim use an old transmission to run his potter's wheel? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-11-24",
        seconds: 3287.905873,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/672524278/npr_672524278.mp3",
        filename: "car_talk_2018-12-01.mp3",
        title: "#1848: The Rolling Punchline",
        description:
            "December 1, 2018 • This week on the Best of Car Talk, Heidi's car is making a scary noise and having trouble steering--and worse, she can't find a mechanic who will take her seriously. Maybe because the car is an '87 Peugeot? Meanwhile, Allen's earning his spot on mechanics' and TV techs' Top 10 Wacko Customer list with a Volvo that's starting itself and a TV that's turning itself on. Also, can Sharon ignore her husband and put a wreath on her Tahoe without voiding the Excess Pine Needle Intake clause of her warranty? And, will Lewis get better treatment from his VW dealer if he flashes his IRS agent card? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-12-01",
        seconds: 3370.946961,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/674936628/npr_674936628.mp3",
        filename: "car_talk_2018-12-08.mp3",
        title: "#1849: Rave on, Rachel",
        description:
            "December 8, 2018 • Paging Chief Counsel Hugh Louis Dewey! Rachel got into a fender bender because she was distracted by laughing at Car Talk. Are Tom and Ray liable? Elsewhere, Tom got a Caprice Wagon in exchange for a set of teeth he made, but the car's knocking sound is making him wonder if he should have only provided molars. Also, Abbie got some dodgy, and perhaps life-threatening advice on how to check her car's alignment; Dee can't accept a life without heated seats; and Phil is wondering if his wife really would be happier if she married a mechanic. All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-12-08",
        seconds: 3380.059297,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/677036869/npr_677036869.mp3",
        filename: "car_talk_2018-12-15.mp3",
        title: "#1850: How to Calm an Angry Co-Host",
        description:
            "December 15, 2018 • When one host insists that cars are made to be junked while the other won't drive anything not equipped with an AARP card, it's time for an intervention. So this week on The Best of Car Talk, Tom and Ray explore new ways of politely calling each other \"jerk.\" Meanwhile, John needs to weigh his love for the family heirloom Chevelle against the dental bills its sensitive power brakes are causing. Elsewhere, Anwen's mechanic was one fuel pump short of diagnosing her Volvo's noise; Andrew's Corolla howls, but only at 30 miles per hour; and Craig ponders the age old question, why are gas filler doors not all on the same side? Also, John's wife and a friend are planning to drive from Buffalo to San Diego in a Cabriolet. Do they needs to take breaks every 10 hours, or every 90 minutes? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-12-15",
        seconds: 3369.82898,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/679480987/npr_679480987.mp3",
        filename: "car_talk_2018-12-22.mp3",
        title: "#1851: Excellence in Worthlessness",
        description:
            "December 22, 2018 • This week on The Best of Car Talk, finally an award Tom and Ray could achieve GOAT status in—wasting time. They'll demonstrate their dominance by ignoring Dodie's perfectly good question about leaving her car in overdrive, and instead relentlessly pry/probe into why only two of Dodie's four sons chipped in to buy her the car. Elsewhere, Bob's Cavalier has no heat, even though he's replaced just about every piece of the system; Patricia's Subaru is having trouble starting, which is making it even more difficult to navigate around the buffalo living in her front yard; and Steve thinks he may have bitten off more than he can chew by taking on a Buick Roadmaster restoration. And, on Stump the Chumps, we find out if Joan made it to Madagascar without flying with a set of tires in her bags. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-12-22",
        seconds: 3352.613311,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/680884063/npr_680884063.mp3",
        filename: "car_talk_2018-12-29.mp3",
        title: "#1852: The Perilous Bridge of Intimacy",
        description:
            "December 29, 2018 • This week on the Best of Car Talk, Steve is spending a lot of time helping his ex-wife Tammy navigate a trinity of car problems. Is he perhaps too invested, given the \"ex\" status of their relationship? Elsewhere, high schooler Natalie's Dad was away, so she borrowed his van, and (of course) got it dented. Can she fix it before Dad gets home, or does she need to 'fess up, or blame it on Mom? Also, Toast's battery drains in the rain; Julie has half a key stuck in her driver's door; and Jonathan's Volvo has a sagging rear end. Find out if Tom and Ray's resolution to stop giving stupid answers can actually make it to New Year's Day, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2018,
        date: "2018-12-29",
        seconds: 3271.074082,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
