/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/682504364/npr_682504364.mp3",
        filename: "car_talk_2019-01-05.mp3",
        title: "#1901: Love and a Charred Mazda",
        description:
            "January 5, 2019 • This week on The Best of Car Talk, Brent accidentally set his girlfriend's Mazda on fire while trying to start it and now the car and the girlfriend are both exes. Can Tom and Ray help stop him from torching his next relationship? Elsewhere, Adrienne's ski instructor husband thinks it's okay to treat mountain roads like a downhill course and drive with the cruise control on. Meanwhile, Susan's husband, a theoretical physicist wants to use their car battery to power their house during the next blackout. Also, Jane's gas tank seems to have shrunk in half; Mark can't remove his oil filter, thanks to his daughter and a small collision; and is June turning her 4-Wheel Drive into a No-Wheel Drive by taking speed bumps too fast? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-01-05",
        seconds: 3185,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/684787256/npr_684787256.mp3",
        filename: "car_talk_2019-01-12.mp3",
        title: "#1902: The Roat to Boatdom",
        description:
            "January 12, 2019 • This week on The Best of Car Talk, is Sarah responsible for her backyard mechanic's professional development? He may have messed up replacing her Accord's clutch. Should Sarah give him another shot, this time on the transmission? Elsewhere, Kathy needs help getting her husband to dump his beloved Corolla before the gas tank falls out and Mary can't decide whether her son should accept his girlfriend's mother's offer of a free Dart. Also, Larry's got a question involving ground straps, lightning, and life insurance; Paula's friend left her lights on and blamed the car for the battery dying; and are Chana's father and husband's advice both ice cold on warming up her car? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-01-12",
        seconds: 3244,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/686840461/npr_686840461.mp3",
        filename: "car_talk_2019-01-19.mp3",
        title: "#1903: Dummy Quest",
        description:
            "January 19, 2019 • This week on The Best of Car Talk, Carol needs help refereeing a family argument over a car question in the game Brain Quest and charter \"Densa\" members Tom and Ray show her she came to the exact wrong place. Elsewhere, Dr. Ron is hoping to prove to his wife that he's not the one killing their clutches. Fortunately for him, there may be another suspect available. Also, Bob's Volvo seems to have more power after bending the exhaust during a game of Driveway Tag; a valet used Kenneth's Dodge key to start Kenneth's Subaru and Lisa is relying on a piece of wood jammed into the ignition to keep her Moskvitch running. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-01-19",
        seconds: 3222,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/689000414/npr_689000414.mp3",
        filename: "car_talk_2019-01-26.mp3",
        title: "#1904: Great Balls of Fire",
        description:
            "January 26, 2019 • This week on The Best of Car Talk, was Barry's truck an unwitting arsonist? He was driving home when the lights dimmed and flames began shooting out the back, setting the road on fire. Elsewhere, Danni bought a used Range Rover while in the midst of \"Pregnancy Induced Insanity\" (her words) and the car is already draining her wallet faster than her kid's college tuition will. Also, Amy's mechanics may have replaced the wrong half of her engine; Charlie has replaced his fuel pump three times in the last year and his back would really like him to find one that can last more than a few months; and, forget Sonja Henie's Tutu. We have the tale of Sonja Henie's Zamboni! All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-01-26",
        seconds: 3229,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/690946329/npr_690946329.mp3",
        filename: "car_talk_2019-02-02.mp3",
        title: "#1905: The Plow Minivan",
        description:
            "February 2, 2019 • This week on The Best of Car Talk, can Carl mount a snow plow on the front of his Plymouth Voyager? Sure, if he wants to destroy it. But Carl may have other options, that don't involve moving to Florida. Elsewhere, Elizabeth's truck hasn't started in months. In that time, it briefly caught on fire and was decorated with holiday lights by Elizabeth's neighbors. Can she restore its dingity by getting it running again? Also, Rick's girlfriend's VW spent a weekend at her mechanic's, and came back with 20,000 new miles on the odometer; Michael's horn has become a neighborhood nuisance; and Jessica can't get her mechanics to talk to her instead of her boyfriend. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-02-02",
        seconds: 3199,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/692978855/npr_692978855.mp3",
        filename: "car_talk_2019-02-09.mp3",
        title: "#1906: Once Upon a Bird Clock",
        description:
            "February 9, 2019 • This week on The Best of Car Talk, is the phrase, \"Yes, dear,\" the key to a happy marriage--even if it's delivered with a smirk? The saga of one of Ray's most annoying purchases helps illustrate. In matters automotive, retired math teacher Angelina can't find a formula to back up her husband's claim that bigger tires will improve their Civic's gas mileage. Also, Tom and Ray are guaranteed to diagnose why Leland's Toyota can't pull a hill, if they can figure out what \"pull a hill\" means; and Tom seizes on one of his most brilliant/wacko/unencumbered-by-the-thought-process explanations for Kim's overheating engine. All this and more this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-02-09",
        seconds: 3202,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/695433715/npr_695433715.mp3",
        filename: "car_talk_2019-02-16.mp3",
        title: "#1907: A Plane in Every Garage",
        description:
            "February 16, 2019 • This week on The Best of Car Talk, Ed is building an airplane in his garage. It's not a model plane; it's one Ed actually intends to fly in. If you need more evidence that Ed has questionable judgment, he's asking Tom and Ray for advice on choosing an engine. Elsewhere, Cindy suffered CO poisoning, accidentally drove 70 mph in 3rd gear, and killed her engine. Subaru replaced it under warranty, but Cindy is feeling guilty about not giving them full disclosure. Also, Diane needs help convincing her husband to drive his shiny new pickup and stop throwing money at his ancient Chevy Citation; and meet our new superhero, Captain Destructo! All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-02-16",
        seconds: 3232,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/697305891/npr_697305891.mp3",
        filename: "car_talk_2019-02-23.mp3",
        title: "#1908: Brake and Seek",
        description:
            "February 23, 2019 • This week on The Best of Car Talk, every time Michelle's friend steps on the brake, his car radio changes the station. If this only happened during our show, Tom and Ray could just compliment the radio on its good taste and move on, but they'll have to conjure some plausible explanation. Elsewhere, Leslie thinks her Chrysler committed autocide by rolling away while parked at her in-laws. Also, Cindy loves the Olds she inherited from dad, but could live without the cigar smell that came with it; and 3-time marriage loser Ken thinks he may have better luck next time by scouting mates based on what they drive. All this, plus some brotherly advice gone haywire, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-02-23",
        seconds: 3229,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/699673334/npr_699673334.mp3",
        filename: "car_talk_2019-03-02.mp3",
        title: "#1909: He Can Fry the Fish and Watch the Cat",
        description:
            "March 2, 2019 • Hey, would you happen to have a PhD in mockingbird poop? If so, Beth could use your help. She has to park her Camry below the home of a mockingbird that enjoys eating berries, and, um, has an active digestive system. Will Tom and Ray have any useful suggestions to help Beth poop-proof her car? Elsewhere, Shlomit's husband drives with two feet. Does the fact that he's a dancer make this any less wacko? Also, Scott keeps losing parking lot traffic cone races to his wife and is looking for ways to help him win, however underhanded; Abbie needs help persuading a physics professor to help her rent a car after he damaged hers; and Dan bought a used Corolla that may have come with the previous owner's engagement ring hiding behind the dash. How did it get there? Find out this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-03-02",
        seconds: 3278,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/701862814/npr_701862814.mp3",
        filename: "car_talk_2019-03-09.mp3",
        title: "#1910: Poise, Courage and Idiocy",
        description:
            "March 9, 2019 • This week on The Best of Car Talk, Ann discovered her tire was on fire while driving home from a snowboarding trip. Her response demonstrates three of Tom and Ray's most admired qualities. Now, can they convince her to use some common sense? Elsehwere, Dana is concerned her husband has become overly attached to JB Weld; Dennis is being punished for the good deed of washing his wife's car; and Chris and her husband are arguing over whether shoveling snow out of a parking space grants ownership. Also, NASA researcher Anastas can't get a grant to find out if his Audi would perform in zero gravity, so he's turning to the next worst option, Tom and Ray. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-03-09",
        seconds: 3261,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/704064346/npr_704064346.mp3",
        filename: "car_talk_2019-03-16.mp3",
        title: "#1911: The California Way",
        description:
            "March 16, 2019 • This week on The Best of Car Talk, Penny bought her ex-husband's third wife's old Volvo. If that sounds complicated, wait until you hear everything Penny's done to try to figure out why the car is overheating. Elsewhere, Scott's Festiva died after driving through a deep puddle and Scott's friend is trying to convince him his tailpipe managed to suck water and blow out exhaust at the same time. Also, Chandler is pondering a life without hubcaps after hers were stolen; Mike is looking for the right car to help his uncle get his kicks on Route 66; and Kathy needs help navigating the mind of the modern mechanic, who happens to be her husband. And, on Stump the Chumps, did Ellen finally find a way to distract her husband from the JC Whitney catalogue? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-03-16",
        seconds: 3267,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/706155313/npr_706155313.mp3",
        filename: "car_talk_2019-03-23.mp3",
        title: "#1912: Witness Intimidation",
        description:
            "March 23, 2019 • This week on The Best of Car Talk, Tom and Ray unveil a new strategy for stubborn callers. If they can't diagnose Laraine's noisy Acura, can they browbeat her into changing the symptoms? Elsewhere, Richard's Land Cruiser is shooting flames out the tailpipe, which could be a cause for concern or a chance to have some fun. Also, Julia is about to own her first car, and wants to know how to take care of it, aside from walking it twice a day; Dorothea's mechanic wants to run a psychedelic blacklight test to find her Volvo's oil leak; and should John clean his car before a first date, or let her see him for the slob he really is? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-03-23",
        seconds: 3228,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/708321428/npr_708321428.mp3",
        filename: "car_talk_2019-03-30.mp3",
        title: "#1913: The Immortal Timing Belt",
        description:
            "March 30, 2019 • This week on The Best of Car Talk, Juliette's timing belt has lasted more than 230,000 miles. Should she replace it before she gets stranded on the Lake Pontchartrain Causeway, or see if it can make it all the way back from the moon? Elsewhere, Joanna is grateful her 16-year-old son doesn't want a Viper for his first car, but she is a little concerned that he has his eyes on a vintage ice cream truck. Also, Sarah keeps spilling water into her Saab's poorly located ignition; Deborah's Corolla is shaking after a clutch job, which may be a case of FOL (Fell Off Lift); Bear may need to change his 100,000-mile spark plugs' name to \"lifetime\" since they're frozen in place; and on Stump the Chumps, we find out if John cleaned his car, or let a first date see him for the slob he truly is. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-03-30",
        seconds: 3222,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/710566189/npr_710566189.mp3",
        filename: "car_talk_2019-04-06.mp3",
        title: "#1914: Random Acts of Stupidity",
        description:
            "April 6, 2019 • This week on The Best of Car Talk, Fred saw a truck parked in the rain with its door open, so he did what any good guy would do—he closed the door. 30 minutes later, the truck was on fire, and Fred may have caused it. Good intentions also went awry for Mare's husband, he put air in her Celica's tires, but mistook her car for a bicycle and filled them all the way to 90 psi. The parade of bad ideas continues with Richie who may have cooked his engine by experimenting with a synthetic oil dual filtration system; Scott's \"Uncle Know It All\" who thinks overdrive should be avoided at all costs; Liz, who plans to drive from Oregon to Alaska in an '85 Blazer; and our very own Ray, postulating that William Shakespeare was Italian. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-04-06",
        seconds: 3273,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/713027814/npr_713027814.mp3",
        filename: "car_talk_2019-04-13.mp3",
        title: "#1915: SUV Absolution",
        description:
            "April 13, 2019 • This week on The Best of Car Talk, Carl is about to receive his Master's degree in Coastal Management and is wracked with guilt about owning two gas guzzling SUVs. Will converting emissions systems help him feel better and keep the seas at bay? Elsewhere, Brian's drive to work is quicker and more scenic than his wife's, but on washboard roads, so is he going to spend all that saved time in his mechanic's lobby waiting for a new suspension? Also, Dr. Kenny is so concerned about his Civic's brakes that he's stepping out of surgery to seek help; Debbie's mechanic found a rag stuck in the remains of her Peugeot's oil filter; and Monica's husband insists on shifting his automatic transmission into neutral at stop lights to let the transmission rest. Does his brain need a nap? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-04-13",
        seconds: 3264,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/715443870/npr_715443870.mp3",
        filename: "car_talk_2019-04-20.mp3",
        title: "#1916: Desperate Measures",
        description:
            "April 20, 2019 • This week on The Best of Car Talk, Amy's brilliant husband's brain doesn't have room to process a few small details while driving, like keeping the car in his lane. Amy's screams of terror don't seem to be helping him improve, so she may need to figure out a creative (and potentially disgusting) way to convince him she needs to drive. Elsewhere, seminary student Matt's truck is leaking oil onto someone else's driveway and fixing it would cost more than the truck is worth. Also, Tom's daughter is about to take a year off college to work on an organic farm 3,000 miles away. He's wondering if her truck can handle the drive, or if she'll need to find an organic farm 2,995 miles closer; Ellen's Sable has a flatulence problem; and Kimberly's BMW is having even more trouble adjusting to living in New York City than she is. All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-04-20",
        seconds: 3249,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/717784191/npr_717784191.mp3",
        filename: "car_talk_2019-04-27.mp3",
        title: "#1917: Double Fault",
        description:
            "April 27, 2019 • This week on The Best of Car Talk, Heidi's husband is a tennis pro, with a limited grasp of English, and an aversion to reading instructions. So he should have no problem changing her Volvo's timing belt, right? Elsewhere, Nathan dinged his girlfriend's Civic while driving it without her permission (or a license). Can Tom and Ray help him cover up his crime, at least until she hears the show? Also, June agreed to teach her friend's teenaged son to drive, but has no idea where to begin; Andrew's Toyota has a bad case of crud accretion in the radiator; and over in Botswana, Dorothy's baboon behavior studies are on track thanks to a piece of wire keeping her Land Rover's fan from destroying the radiator. Is there a more permanent solution, other than Dorothy relying on Jane Goodall's Greatest Hits video for her studies? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-04-27",
        seconds: 3223,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/720260095/npr_720260095.mp3",
        filename: "car_talk_2019-05-04.mp3",
        title: "#1918: The Ungrateful Passenger",
        description:
            "May 4, 2019 • This week on The Best of Car Talk, Jere agreed to drive her sister's co-worker's husband to work. Not only is he annoying in the car, when he gets to work he complains about Jere's driving behind her back. Does Jere need to switch to a one-seater? Elsewhere, Mark's Trooper is oozing fluid onto his feet. He thinks the fluid is red, but he might just be wearing red socks. Also, Sharon's trying to live with a stalling truck without killing the starter or clutch; Alicia's Camry has a furball problem; and is John negating the mid-life crisis benefits of his Miata by worrying whether to park indoors to preserve the hood? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-05-04",
        seconds: 3293,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/722406675/npr_722406675.mp3",
        filename: "car_talk_2019-05-11.mp3",
        title: "#1919: The Tao of Fred Glass",
        description:
            "May 11, 2019 • This week on the Best of Car Talk, Erin's roommate doesn't drive her old car but won't get rid of it, and Erin is tired of having to move it every day. Is Erin's best solution philosophical or conflagratory? Elsewhere, Nathaniel's attempt to show off his Saab to his future in-laws went downhill, literally, when it rolled down their driveway on its own. Also, Dee's truck sounds like singing dogs; Norm wants to know how to get his Stanza running after storing it over the winter, but will first have to incur Tommy's wrath over a sore knee; and Nancy wants to convince her husband that his Acura can live without a bra. All this, plus Tom and Ray's brilliant new \"do whatever you want\" strategy, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-05-11",
        seconds: 3261,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/724986184/npr_724986184.mp3",
        filename: "car_talk_2019-05-18.mp3",
        title: "#1920: Crushed Cans and Loose Lug Nuts",
        description:
            "May 18, 2019 • This week on The Best of Car Talk, two matters of life and death. Jose may have done serious damage to a wheel but doesn't want to pay a dealer to find out if it's on the verge of falling off. Elsewhere, Kris may kill her husband if he continues to crush cans for recycling by driving over them. Also, Jason is pouring gas into the carburetor to get his truck to start, but may be better off just pouring gas on to the seats; Rebecca inherited her ex-boyfriend's BMW, complete with annoying rubbing noise; and John's maple sugaring trip ended with him spilling 5 gallons of syrup in his car. Anyone got pancakes to help soak it up? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-05-18",
        seconds: 3283,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/726963791/npr_726963791.mp3",
        filename: "car_talk_2019-05-25.mp3",
        title: "#1921: No Sleep Till Hunga Dunga",
        description:
            "May 25, 2019 • This week on Car Talk, Howard needs to drive a mattress from Boston to \"Hunga-Dunga\" and wants to know how to get negative lift, and keep it from flying off the roof of his car. Tom and Ray know one method that won't work, as evidenced by an ill-fated attempt to transport 18 sheets of plywood. Elsewhere, Peggy swears she heard the guys recommend mixing kerosene and water to wash a car, but isn't calling to sue for damages. Also, Scott's concerned about his truck not starting, but more worried about his friend \"Fat Tony\" fiddling around with his big bucket o'tools; John managed to lock himself out of his car with the engine running and chose the most painful way to shut it off; and if Tom and Ray help Gillian translate a French truck description, are they really doing work for the CIA? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-05-25",
        seconds: 3267,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/510208/728885601/npr_728885601.mp3",
        filename: "car_talk_2019-06-01.mp3",
        title: "#1922: If It Blows, It Blows",
        description:
            "June 1, 2019 • This week on The Best of Car Talk, climbing Mt. Adams apparently wasn't exciting enough for Glen. When he discovered his truck was leaking gas on the way home, he decided to keep driving. While Glen undoubtedly tops this week's dope slap count, Denise won't be far behind. She celebrated a \"significant birthday\" by buying a 1961 Volvo online sight unseen. As you might imagine, it arrived with enough problems to keep any mechanic's boat fueled for the entire season. Also, Marc's Corolla's gas mileage began dropping, and every attempted fix has only continued the decline; Bob wants to know if he can set off a bug bomb in his truck without damaging the electronics (we're a little more concerned about his lungs); and there's only one problem with Tom and Ray's brilliant diagnosis that Beth's Accord needs a new clutch. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-06-01",
        seconds: 3304,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/06/20190604_cartalk_1923electronics.mp3",
        filename: "car_talk_2019-06-08.mp3",
        title: "#1923: Emboldened Electrons",
        description:
            "June 8, 2019 • Rob's car has trouble starting unless he holds the key in the start position for several seconds. Does Ray's Emboldened Electrons theory mean Rob's electrical system needs to read Profiles in Courage? Elsewhere, Gary is guilty until proven innocent for his mother-in-law's T-Bird catching fire, and even exculpatory evidence may not get him off the hook. Also, Isla's had to replace her Jeep's brake pads three times in the last year, and Midas says she's run out of free replacements; Carly has been living with a shaking Civic for two years; and Avital's ex-boyfriend is trying to convince her that motor oil behaves like bottled salad dressing.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-06-08",
        seconds: 3302,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/06/20190612_cartalk_1924_belize.mp3",
        filename: "car_talk_2019-06-15.mp3",
        title: "#1924: Belize It or Not",
        description:
            "June 15, 2019 • This week on The Best of Car Talk, Nancy is looking for a vehicle she and her family can take to Belize for a year. Other than something big enough to haul back Cuban cigars for Tom and Ray, what should she be looking for? Elsewhere, Diane's husband thinks she's nuts for insisting there's more resistance in her gas pedal when the tank is full; Rebecca's best solution for her Accord's shifting problem may be to return the car to her Dad; Lily hopes her Taurus's intermittent air conditioning can be resolved by buying a new Mustang; and Sandy's neighbors really want her to figure out why her car screeches first thing in the morning. Also, on Stump the Chumps, we find out if Bob tried to bomb the flies out of his truck. All this, plus one listener's fondest Car Talk memory, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-06-15",
        seconds: 3312,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/06/20190618_cartalk_1925momsaway.mp3",
        filename: "car_talk_2019-06-22.mp3",
        title: "#1925: While Mom's Away",
        description:
            "June 22, 2019 • This week on The Best of Car Talk, Sarah left town for a weekend and came home to an array of disasters, including a minivan that smells like urine. Did her kids and husband hold a Physics-defying peeing contest while she was away? Elsewhere, Sissy's husband may blow out the bogosity meter with his argument that she needs to park with the wheels straight to keep her car from going out of alignment; Paul's life turned into a country song when he totaled his car, his wife left him, and his dog died; and service advisor Charlie needs help figuring out how to blame his customers for their short brake life. Also, on Stump the Chumps, did Tom and Ray get the heat working in Bob's Cavalier, or did summer get the heat working in Bob's Cavalier? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-06-22",
        seconds: 3287,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/06/20190626_cartalk_1926_mit_wants_its_diploma_back.mp3",
        filename: "car_talk_2019-07-01.mp3",
        title: "#1926: MIT Wants Its Diploma Back",
        description:
            "July 1, 2019 • Tom and Ray run through the entire table of elements trying to identify the white powder in Ann's Subaru's radiator. If only they could put that much effort into figuring out why the car is blowing through heater cores! Elsewhere, Jamie wants to achieve his modest life ambition of owning a truck with power steering, but doesn't know whether to also go diesel; Dr. Gary is having doubts about his professional services exchange with his mechanic neighbor; Doug needs to decide whether he wants to become the \"Chuck Yeager of CV joints\", or risk being stranded on a railroad track; and Anna discovered a rat in her Civic's passenger seat--how did it get there? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-07-01",
        seconds: 3291,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/07/20190702_cartalk_1927_call_stella-a9ee3a97-f21c-4639-a1d3-d91e5f3d32da.mp3",
        filename: "car_talk_2019-07-06.mp3",
        title: "#1927: Call Stella",
        description:
            "July 6, 2019 • Stella is renting a highway billboard for a personal ad. What size font should she use to attract the right guy, and should she divulge she's a lawyer? Elsewhere, Frank may need to offer a couple of spiral cut hams to find out why his car is squealing; Kelly was told never to change his transmission fluid, but that may not be his concern, since his truck appears to be out of transmission fluid; Chris' brake pedal sank to the floor, but Tom and Ray are more interested in his askew cassette cases; and can Mabel's screeching Subaru really be explained by, \"Twinkle Twinkle Little Star, Power Equals I Squared R\"? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-07-06",
        seconds: 3279,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/07/20190709_cartalk_ep1928-imstupids-brother.mp3",
        filename: "car_talk_2019-07-13.mp3",
        title: "#1928: I'm Stupid's Brother",
        description:
            "July 13, 2019 • Tom and Ray prove they are their brother's keepers, until Ray's explanation for Becky's smelly Toyota goes too far off the deep end. Elsewhere, Arlene bought an old Volvo for her teenage daughter, who promptly drove it off road and tried to fix its overheating by pouring Mountain Dew in the radiator. Does Arlene need to find her daughter a better teacher, or a convent? Also, Kate's mechanic husband can't figure out why her car has touble starting; Warren wants to treat his Olds to a paint job, but his wife is convinced that will make it die within two months; and Newton is still trying to figure out how his driver in Africa kept his Land Rover running for 60 miles by sitting on the engine with his hand over the carburetor. All this, plus the truth about lying, and lots more.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-07-13",
        seconds: 3299,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/07/20190716_cartalk_1929_electric_brakes.mp3",
        filename: "car_talk_2019-07-20.mp3",
        title: "#1929: Electric Brakes",
        description:
            "July 20, 2019 • This week on The Best of Car Talk, our all-time favorite demonstration of Male Answer Syndrome. The electric brakes on Paul's cattle trailer engage when he uses his turn signal. Will Tom and Ray's ready acknowledgment that they know nothing about electric brakes stop them from offering a diagnosis? Of course not! Is there any chance of it being a correct diagnosis? Of course not! Elsewhere, Alice and her husband are enjoying retirement by arguing over whose route to their daugher's house is better for their car. Also, Ralph's Suburban is channeling an old TV game show; Cathy's son locked her keys in the trunk and the retrieval has led to lots of chipped teeth; and will Marsha's husband's shifting habits kill her clutch permaturely? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-07-20",
        seconds: 3313,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/07/20190723_cartalk_1930_the_andy_letter.mp3",
        filename: "car_talk_2019-07-27.mp3",
        title: "#1930: The Andy Letter",
        description:
            "July 27, 2019 • This week on The Best of Car Talk, Tom and Ray's noble, but doomed, attempt to diagnose a problem with electrical brakes may have helped another listener resolve a different conundrum: Do two people who don't know what they're talking about know more or less than one person who doesn't know what he's talking about? Elsewhere, Rob needs to find a way out of a 5,000 mile road trip with his in-laws; Erin is on what may be a misguided quest to convince her husband to dump his BMW; and Kate's Acura's brakes slip when the temperature goes over 103, which seems extra serious since she lives in Las Vegas. So why are her mechanics looking at her like she's crazy? All this, plus how not to set your sideview mirrors, and lots more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-07-27",
        seconds: 3319,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/07/20190730_cartalk_1931_eggs_prestone.mp3",
        filename: "car_talk_2019-08-03.mp3",
        title: "#1931: Eggs Prestone",
        description:
            "August 3, 2019 • This week on the Best of Car Talk, can an omelet save an engine? A friend suggested that Sasha use eggs in his cracked radiator. Was this advice to actually stop the leak, or just to give Sasha something to snack on while waiting for the tow truck? Elsewhere, John put wooden blocks under the gas pedal to slow down his leadfoot son; but is worried that the speeding tickets savings may need to go towards a new transmission. Also, Debra may need to resort to whacking the steering wheel to start her car; Ron's horn sounds when he turns his steering wheel; on Stump the Chumps, we find out if Heidi had to lock her husband in the cellar to keep him from changing her timing belt; and, are Tom and Ray's stupid questions really profound existential Philosophy? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-08-03",
        seconds: 3250,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/08/20190808_cartalk_1932_unforced_errors_2.mp3",
        filename: "car_talk_2019-08-10.mp3",
        title: "#1932: A Series of Unforced Errors",
        description:
            "August 10, 2019 • This week on The Best of Car Talk, Marc bought a used Peugeot for $100, and, believe it or not, that wasn't his worst mistake. Now he's got a car he can't drive, and a mechanic who can't get the part, but did obtain cash from Marc's wallet. Elsewhere, Edward needs a monthly subscription to replace his Altima's distributors; Mary's husband insists on leaving the car running while he pumps gas because he's never seen one blow up, perhaps not realizing that's because everyone else turns their cars off; Nigel may be better off not knowing what his mechanic did to get his Mercedes to pass the smog test; and Heather is looking for the perfect practical joke to play on her brother, through his vintage Toyota Supra. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-08-10",
        seconds: 3261,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/08/20190812_cartalk_1933_geek_squeak.mp3",
        filename: "car_talk_2019-08-17.mp3",
        title: "#1933: The Geek Squeak",
        description:
            "August 17, 2019 • This week on The Best of Car Talk, Dana's wife's Volvo's brakes squeak, but only when Dana drives the car. Does his wife have a heavy foot or is Dana driving too much like a geek? Elsewhere, Louise made the mistake of taking her car to a specialist rather than a GP to diagnose a clunk; Sylvia thinks her Rabbit's array of problems are due to radiation poisoning from being parked near a uranium mine; and on Stump the Chumps, we find out if Tom and Ray correctly diagnosed why Ralph's Suburban was imitating an old TV game show. Also, a date goes awry when a Jaguar is mistaken for something else; and a few of Shakespeare's plays not coming to a stage near you. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-08-17",
        seconds: 3235,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/08/20190815_cartalk_1934_tea_and_a_haircut.mp3",
        filename: "car_talk_2019-08-24.mp3",
        title: "#1934: Tea and a Haircut",
        description:
            'August 24, 2019 • This week on The Best of Car Talk, one listener undertakes a bold, yet reckless experiment to find the correlation between drinking iced tea and needing to take a haircut. Is the real question "if", or "how fast"? Elsewhere, Robert bought a used truck and thinks its previous owner misnamed it. Can he re-christen it without changing its identity? Also, the only way to get into Paul\'s $200 car is by climbing over the hood, which, to nobody\'s surprise, has fried the battery; Maxine\'s mechanics \'fessed up to putting the wrong fluid in her brake reservoir, but maybe not so much about which fluid; Christine\'s Accord has become home to an ant colony; and Ray shows off his deep understanding of dew dynamics. Or is that "doo doo dynamics"? All this and more, this week on The Best of Car Talk.',
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-08-24",
        seconds: 3255,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2019/08/20190828_cartalk_1935_think_of_the_tucchus.mp3",
        filename: "car_talk_2019-08-31.mp3",
        title: "#1935: Think of the Tucchus",
        description:
            "August 31, 2019 • This week on The Best of Car Talk, Matt needs a car that can handle his annual 100,000 mile commute, and no, we didn't add too many zeros there. Matt is looking for reliability and good gas mileage, but Tom and Ray think he should be a bit more self-centered, particularly on the body part that will be chained to the seat for all those miles. Elsewhere, Marc is wondering if add-ons like the \"Crap-a-Chip\" will really improve his SUV's horrible mileage. Also, Mary Anne's air conditioning is cooling her passengers but not herself; Chip is wondering what fried his van's exhaust manifold; and Tom and Ray's efforts to help Becky deal with a film on her windshield are derailed by the Car Talk Studio Pranks department. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-08-31",
        seconds: 3227,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/09/20190905_cartalk_1936_magliozzi_bros-35d8d6c5-6a86-46e9-bfc7-61595e7978ce.mp3",
        filename: "car_talk_2019-09-07.mp3",
        title: "#1936: The Super Magliozzi Brothers",
        description:
            "September 7, 2019 • This week on The Best of Car Talk, two preteen kids present \"Car Talk: The Video Game,\" and prove they're a lot more creative and have better marketing skills than anyone in our office. But, they probably can't beat Tom and Ray on car questions, right? We won't test that, but, the brothers will try to figure out why Martha's van stops moving and acts like it's run out of gas; what made Karl's horn start blaring early Sunday morning; and which heap Cass and her newly reunited husband should keep. Also, should Lee listen to a retired mechanic's advice and run his car for 15 seconds with a pint of kerosene and no oil? And, our listeners weigh in on whether or not to name a car. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-09-07",
        seconds: 3290,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/09/20190910_cartalk_1937_hotel_fire-ede61e9f-cc88-42af-af30-e6d69aa499ef.mp3",
        filename: "car_talk_2019-09-14.mp3",
        title: "#1937: The Great Montreal Hotel Fire",
        description:
            "September 14, 2019 • This week on The Best of Car Talk, the best prank ever in Magliozzi history, as Ray's family vacation is interrupted by the unfortunate news that his beloved Ford LTD has \"burned to a crisp.\" Elsewhere, grad student Erica hopes her Celica's rattle is serious enough to get Mom and Dad to buy her a new car; Jodi's oil burning may put her Cavalier well ahead Erica's car on the path to heapdom; Unitarian Minister Carol is being tempted by a shiny Jetta; and can Vince put the leftover gas from his weedwacker in his car without destroying it? Also, if you keep taking a car apart and putting it back together, will you eventually wind up with two? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-09-14",
        seconds: 3293,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/09/20190916_cartalk_1938_theresa_syndrome-235d6b98-376d-4b76-bf56-b199bfd980ae.mp3",
        filename: "car_talk_2019-09-21.mp3",
        title: "#1938: Theresa Syndrome",
        description:
            "September 21, 2019 • This week on The Best of Car Talk, Lee's mild-mannered wife's temper and vocabulary both take a dive, but only when she listens to our show. Are Tom and Ray carriers of a new form of ABS—Aberrant Behavior Syndrome? Meanwhile, tempers are also flaring out in California, where Jim's truck is polluting his entire town; and down in Hendersonville, Kentucky, where Brian's merging strategy is incredibly efficient, and also incredibly rude. Also, on Stump the Chumps we find out if Sarah's kids really held a peeing contest in her car while she was away; and, can Bill in Alaska get his forklift running in time to get us our halibut? All this, plus the return of the Puzzler, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-09-21",
        seconds: 3231,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/09/20190924_cartalk_1939_if_thats_what_it_is-c6692b4d-766f-4f90-aeb3-6828b57db3bf.mp3",
        filename: "car_talk_2019-09-28.mp3",
        title: "#1939: If That's What It Is",
        description:
            "September 28, 2019 • This week on The Best of Car Talk, Anne's mechanic can't identify the gunk blowing out of her car's ventilation system, but he does know that whatever it is, fixing it will cost $1000...if that's what it is. Sounds like a new mechanic's mantra to us! Elsewhere, Linda is still trying to figure out how a gas attendant put her radiator cap on backwards; Alan is baffled by the diamond patterns he sees on rear windshields, especially when he's wearing polarized sunglasses; and is Andy safer keeping his doors locked while driving on the highway? And, has our pal Daniel Pinkwater found his true calling, as a scientific measurement? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-09-28",
        seconds: 3274,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/10/20191002_cartalk_1940_junkaraderie-f2c28087-d808-4d4c-84d1-d8ba090a461c.mp3",
        filename: "car_talk_2019-10-05.mp3",
        title: "#1940: Junkaraderie",
        description:
            "October 5, 2019 • This week on The Best of Car Talk, Michelle's husband paid $170 for her dream car, and she thinks he may have overpaid. It's just missing a few things, such as the rear windshield, the gas cap, chunks of the floor...and we haven't even gotten to all the problems under hood. Fortunately, Michelle is talking to a guy who can appreciate junk, and Tommy is as excited as her husband about this dream turned nightmare. Elsewhere, Mary discovered how big a rock it would take to kill her lawn mower; Matt is looking for music recommendation to drown out his Civic's brake noise; and can Tom and Ray convince Andrea the noise she thinks is coming from the dashboard is actually originating 3 feet away; and our on-call Physicist Wolfgang helps ease Ray's gastrointestinal distress. All this and lot more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-10-05",
        seconds: 3313,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/10/20191009_cartalk_1941_bryology-a00f517c-30a0-4451-bfe4-a183aa90c457.mp3",
        filename: "car_talk_2019-10-12.mp3",
        title: "#1941: Bryology This, Pal",
        description:
            "October 12, 2019 • This week on The Best of Car Talk, Jenny's fiance, a budding bryologist, thinks she's crazy because she swears her car is more difficult to start when its low on gas. Should he stick to moss and stay away from fuel dynamics, let alone female psychology? Elsewhere, Angela's smelling something sweet from her dashboard, but the cost to fix it will be mighty sour; Eric is wondering how a $4 part could require $358 in labor to replace; and David is trying to decide which of two heaps to dump, when the answer should probably be both. And, in the midst of New England foliage season, New Hampshire native Kurt has lots of time in traffic to profile the tourist drivers slowing him down the most. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-10-12",
        seconds: 3251,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/10/20191015_cartalk_1942_bad_options-1b57531a-1d88-46cb-a586-6a77ca440df1.mp3",
        filename: "car_talk_2019-10-19.mp3",
        title: "#1942: A Bevy of Bad Options",
        description:
            "October 19, 2019 • This week on The Best of Car Talk, should Bill risk humiliation and passenger nausea by trying to learn how to drive a sitck shift in time for the high school dance? Given that his options are the family minivan or station wagon, he may need to go for it, and have a handy supply of barf bags on hand. Elsewhere, Jane's neighbor's dog is biting her Subaru's tires and chasing her car. Jane is thinking a healthy dose of pepper spray may help dissuade Fido, but Tom and Ray may have a more (or less ) humane solution. Also, Abby's Accord has a burning smell since she accidentally backed down a friend's steep driveway in drive; Steve promised his wife he could fix her oil problem three months ago, but is stumped; and can Ray convince John his air conditioning is making noise, even when it's off? All this, plus a quiz for the Philosopher King, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-10-19",
        seconds: 3263,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/10/20191022_cartalk_1943_cream_rinse-ef12a01b-870e-44bc-8759-655f44beec28.mp3",
        filename: "car_talk_2019-10-26.mp3",
        title: "#1943: Cream Rinse",
        description:
            "October 26, 2019 • This week on The Best of Car Talk, Tom and Ray stray ever further into terra incognita, as they try to help Sharon figure out why her hair looks lousy after a long drive. Procter and Gamble may have issues with Ray's diagnosis. Elsewhere, Sharon's car is making a \"lurid groan\" when she turns. The noise is making her a star at the retirement home, but should she be worried about it? Also, from the marital disputes department, Cathy thinks her husband erred by driving down Mt. Washington in 1st gear rather than riding the brakes; and Lynn is worried that a cold water car wash on a hot day can warp her brakes. And, has the New York Times really found the world's funniest joke? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-10-26",
        seconds: 3260,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/10/20191029_cartalk_1944_stink-5cf22565-ab90-4665-b654-edab976d9d35.mp3",
        filename: "car_talk_2019-11-02.mp3",
        title: "#1944: I Stink, Therefore I Am",
        description:
            "November 2, 2019 • This week on The Best of Car Talk, Fran and her boyfriend are both jocks, and as a result her Taurus smells like a locker room. Will a few dozen Odor Eaters hanging from the rear view mirror get rid of the stink? Elsewhere, Fritzie has two Peugeots, one of which has died. Should she keep it around, so its partner has company? Also, Margo's Dad gave her his Cadillac, but her noisy brakes have Tom and Ray convinced Dad may be trying to bump Margo off; Matt wants to cure his wife of her habitual door slamming; and \"Martha\" bought a used van from a dealer six months ago, but has yet to be billed or pay a single cent for it. Should she keep quiet, 'fess up, or trade it in for a new van? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-11-02",
        seconds: 3327,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/11/20191104_cartalk_1945_phantom_foot-b5587cc6-be1c-4dcc-8471-99d80c4a76b1.mp3",
        filename: "car_talk_2019-11-09.mp3",
        title: "#1945: Phantom Foot",
        description:
            "November 9, 2019 • This week on The Best of Car Talk, Amy's husband is no longer driving a stick shift but is still using both feet, keeping his left foot on the brake. Is this dangerous and can Tom and Ray help Amy find something else for him to do with that foot? Elsewhere, Esther is looking for a Get Out of Speeding Tickets Free card due to her car's stuck idle; Edabeth's Volvo sounds like an airplane readying for takeoff; and Nathan wants to take shade tree mechanic to a whole new level. He's camping out in a redwood tree to protest deforestation, and has noticed that one of the trucks passing by every day is running rough. Can he diagnose this from his leafy perch? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-11-09",
        seconds: 3290,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/11/20191112_cartalk_mmmdonuts-0079a3b3-29cc-4cd4-937f-31881e507dda.mp3",
        filename: "car_talk_2019-11-16.mp3",
        title: "#1946: Mmm, Donuts",
        description:
            "November 16, 2019 • This week on the Best of Car Talk, Ben and his brother took their dad's Camry for a ride--in reverse, in the neighbor's yard, with the steering wheel cocked all the way to one side. They had a great time! The Camry's power steering, not so much. Elsewhere, Al and his friend disagree over whether to take speed bumps with two wheels or four; Kathy is miffed that her husband carries a picture of his beloved Studebaker in his wallet, but not one of her; Wendall, and his insurer, want to know why his truck caught on fire; and did a neighborly gesture really kill Daniel's alternator, as his wife predicted? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-11-16",
        seconds: 3319,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/11/20191118_cartalk_1947_ray_caught_working-79718661-d5e9-4e00-8540-efab46cd2831.mp3",
        filename: "car_talk_2019-11-23.mp3",
        title: "#1947: Ray Caught Working",
        description:
            "November 23, 2019 • This week on the Best of Car Talk, we demonstrate just how much effort goes into. . . .embarrassing Tom and Ray. You didn't think we were talking about putting effort into the show, were you? Elsewhere, \"Sweetie\" has to decide whether to rebuild her Explorer's transmission or limp along without 5th gear, and Tom and Ray have to decide how many times they can call her Sweetie without getting into big trouble. Also, should Ruth follow her husband's or father's conflicting advice on tire pressure; Ellen thinks her mechanic is blowing sulfur up her skirt over her Camry's smell; Glen spilled a little oil and set his rental car engine on fire; and on Stump the Chumps, we find out if Bill managed to drive a stick shift to the high school dance and save his social life. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-11-23",
        seconds: 3307,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/11/20191125_cartalk_1948_honesty-46adacd8-6520-4325-aede-9ffcd1aa3d93.mp3",
        filename: "car_talk_2019-11-30.mp3",
        title: "#1948: Honesty Will Always Get You in Trouble",
        description:
            "November 30, 2019 • This week on The Best of Car Talk, Prashanth's new wife is about to come to America for the first time. Should he greet her with his beat-up Corolla, spring for a new car, or try to fake it by renting something until it's too late for her to turn back to India? Elsewhere, Al stands accused of \"careless parking\"—his brother says Al pulls into the garage in a way that makes it impossible to back out. Is this even physically possible? Also, Father Bob needs a heavy duty flasher, so he can hear his turn signals; a piece of hot molten lead fell on Pam's foot from under the dash while she was driving; and, Deanna's Civic's battery has been stolen several times in the last few months. Does she need a Rottweiler under the hood? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-11-30",
        seconds: 3410,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/12/20191204_cartalk_1949_stop_and_chat-403e4e77-795e-4c31-a45d-d984fbf14371.mp3",
        filename: "car_talk_2019-12-07.mp3",
        title: "#1949: Stop and Chat",
        description:
            "December 7, 2019 • Out in Gustavas, Alaska, Janet and her neighbors like to stop and talk to each other when they're driving. One of the topics: whether their cars are better off idling or being shut off during the conversation. This week on the Best of Car Talk, Tom and Ray weigh in, and one Magliozzi manages to book himself a night sleeping in the garage. Elsewhere, Heidi's Lincoln is under attack from a bird that's pecking at its own reflection. Can Heidi protect her car without landing on the Audubon Society's Most Wanted list? Also, Shawn's Caravan seems to be channeling Maurice Chevalier; John got a smokey lesson in what happens when you leave the filler cap off after an oil change; and Steve's truck is bouncing like a basketball on bumpy roads. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-12-07",
        seconds: 3340,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/12/20191210_cartalk_1950_great_cow_magnet-6208a1ff-b917-453e-b850-5a08506994e8.mp3",
        filename: "car_talk_2019-12-14.mp3",
        title: "#1950: The Great Cow Magnet Caper",
        description:
            "December 14, 2019 • This week on The Best of Car Talk, could cow stomach magnets have improved the gas mileage on Tim's Jaguar? Or is that udderly (sorry) ridiculous? Meanwhile, down in Antarctica, summer is coming, but Matt's vehicle is still having trouble when the thermometer dips below a balmy minus 40 degrees. And, Tom and Ray are in the holiday spirit with some creative gift suggestions for men, comforting advice for Adrian who wants to put a wreath on her car but is worried it will spontaneously combust, and a lesson for Scott that it is the stingy man who spends the most. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-12-14",
        seconds: 3352,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/12/20191217_cartalk_one_truck_dangling-60757aa5-7eb3-4dea-a33a-a11c3bf211d3.mp3",
        filename: "car_talk_2019-12-21.mp3",
        title: "#1951: One Truck a-Dangling",
        description:
            "December 21, 2019 • This week on The Best of Car Talk, Bill Bailey's truck made a horrible noise and lost reverse. But, the fun really began when it rolled into a lake after Bill got home. Now the only thing keeping it from sinking is one cable. Elsewhere, Victoria is looking for a quartet of $2,000 cars for her sons; Jenny's newlywed husband lost 15 pounds and his now-oversized wedding ring is missing in their Jeep's dashboard; Lindsay is wondering whether to charge her husband with sabotage after he drove her Malibu 300 miles in 2nd gear; and on Stump the Chumps, we find out if David lost his car-induced cough, but kept all his brain cells. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-12-21",
        seconds: 3383,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/12/20191223_cartalk_blowitout-142fd99a-6391-47db-b990-60a211503d36.mp3",
        filename: "car_talk_2019-12-28.mp3",
        title: "#1952: Blow it Out",
        description:
            "December 28, 2019 • This week on The Best of Car Talk, Jill's pal keeps telling her she needs to do more highway driving to \"blow the stuff\" out of her car. Jill's not opposed to this on principle, but she would like to know what she's trying to blow out. Elsewhere, Eleanor is leaving on a 6-month around the world bicycle tour and she wants to know what to do with her truck while she's gone. Tom and Ray want to know how Eleanor plans to pedal across a few oceans?! Also, after Lauren's boyfriend drove down Mount Washington with the emergency brake on, Lauren is wondering if she needs new brakes, and a new boyfriend. And, on Stump the Chumps, we find out if Marc rescued his Peugeot from his mechanic, and whether he wishes he hadn't. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2019,
        date: "2019-12-28",
        seconds: 3406,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
