/*
 * Copyright (C) 2025 Ty Busby
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MetaData } from "./metadata";

export const playlist: MetaData[] = [
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2019/12/20191230_cartalk_2001_needlepoint-9957f50f-7853-4eb8-81b5-aad03970d9cd.mp3",
        filename: "car_talk_2020-01-06.mp3",
        title: "#2001: That's Worth Needlepoint!",
        description:
            "January 6, 2020 • This week on The Best of Car Talk, Kim and her husband each made questionable car purchases. He got an abandoned Lexus, while she went for an ancient VW Campervan. Who gets bragging rights for being more wacko? Meanwhile, another marital dispute is brewing in Alaska, where Samantha and her husband can't agree on the best place to hang dry cleaning. Can Tom and Ray referee his one, without knowing exactly what dry cleaning is? Back on the wacko front, Stephan's solution to his Golf's rough running may earn him the \"Big W\" on his repair slip. And on Stump the Chumps, we find out if John's wife made it from Buffalo to San Diego in her Cabriolet, in less than six months. All this, plus Math with Dummies, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-01-06",
        seconds: 3248,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/01/20200107_cartalk_2002_we_have_a_problem-8d401598-d563-4c24-b4da-1ef2bfd148c9.mp3",
        filename: "car_talk_2020-01-13.mp3",
        title: "#2002: Falls Village, We Have a Problem",
        description:
            "January 13, 2020 • This week on The Best of Car Talk, Nina's mechanic ripped off her Altima's heat shield and said she can live without it. But Nina's seen enough Star Trek episodes to worry she might burn up on re-entry without it. Elsewhere, Steve expected to encounter snow during his winter cross-country drive, but he wasn't prepared for flurries inside his Pathfinder. Also, Jean's brakes started screeching after she got new pads, apparently with the \"banshee\" option; John's daughters' know-it-all boyfriends have convinced them they need to let their cars warm up for a loooong time on cold mornings; and Ray discovers new automotive healing powers. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-01-13",
        seconds: 3276,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/01/20200114_cartalk_2003_optimal_rust-47d10de5-1047-4bdf-b3e5-47859d8129ab.mp3",
        filename: "car_talk_2020-01-18.mp3",
        title: "#2003: Optimal Rust",
        description:
            "January 18, 2020 • This week on the Best of Car Talk, Steve's wife gave him a homework assignment--write a paper explaining why he should keep the '77 MG he bought a year ago, but has left sitting in the garage. But does Steve love it enough to defend it? Elsewhere, Helen's tires are growing mold. Tom and Ray say it's because Helen drives the car infrequently, to which Helen replies, \"Au contraire Piston Pusses!\" Also, Linda's fiance insists on washing his car before a long trip, to improve its gas mileage; Heather thinks an opera singer is hanging out under her Civic; and, you'll be shocked, shocked to learn that John's \"cheap and reliable\" Ferrari is proving to be neither. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-01-18",
        seconds: 3301,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/01/20200121_cartalk_2004_ready_for_summer-036d7f09-944d-4c62-a5c0-2708a22ff0db.mp3",
        filename: "car_talk_2020-01-25.mp3",
        title: "#2004: Are You Ready For Summer",
        description:
            "January 25, 2020 • This week on The Best of Car Talk, let's escape winter for a few minutes with a ride in the '75 Pontiac convertible Red, just bought off someone's front lawn. Hey, are those flames shooting up from the carpet? Elsewhere, a potential fire is just one reason Gladys is too scared to use the remote starter she got for Christmas. Also, Trent thinks his van suffered a stroke, taking out the power window, blinker and tail lights; Josie inherited a VW Westfalia with the annoying habit of starting itself and and driving off; and Lucia put a 150-pound log in her Corolla's trunk to prevent fish-tailing in the snow, but is worried it might be doing damage elsewhere. All this, plus the real origins of 4-Wheel Drive, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-01-25",
        seconds: 3260,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/01/20200129_cartalk_2005_roadhog_day-bf0e122d-8ba7-4ad8-898d-0964e448dd19.mp3",
        filename: "car_talk_2020-02-01.mp3",
        title: "#2005: Roadhog Day",
        description:
            "February 1, 2020 • This week on The Best of Car Talk, Tom, Ray, and our callers anxiously await the annual sign from Tommy's Dodge Dart that winter may end early. Up in Maine, Paula's Subaru won't start in really cold weather unless she lies a heated blanket on the engine for 10 minutes. She's getting tired of waiting, and having her neighbors think she's nuts. Meanwhile, out on Martha's Vineyard, Betsy's Toyota Echo is sliding around in the snow, making it difficult to get to team sword dancing practice. Also, Deanie's husband and father are arguing over the best time to check the dipstick; and Peter's wife always said, \"A car is just a car\", until she drove his new Jaguar, and decided it was a little different from her Accord. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-02-01",
        seconds: 3289,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/02/20200204_cartalk_2006_cheapskateism-52e93826-9a9a-4530-bc27-ba5faefd4906.mp3",
        filename: "car_talk_2020-02-08.mp3",
        title: "#2006: Brotherhood of Cheapeskatism",
        description:
            "February 8, 2020 • This week on the Best of Car Talk, meet Tommy's new best friend, Paul. After the screws holding Paul's gas pedal fell through the rusted floor of his '78 Datsun, Paul eschewed a body shop and found a cheap fix at his local cobbler. Now he needs a podiatrist to help with the limp his brilliant solution gave him. Elsewhere, neat freak Doug thinks his wife is a slob when it comes to cars, so he's considering buying a stick shift so she can't drive it. Also, Kathy's sister's boss suggested putting mothballs in her VW Bus's gas tank to improve mileage; Donna's husband was told to leave his car running an extra 15 minutes in really cold weather to charge the battery, but can't remember to shut it off; and on Stump the Chumps, did Dr. Paul find a new car and a new girlfriend, after his life turned into a country song? All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-02-08",
        seconds: 3281,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/02/20200210_cartalk_dopeslap-37c073f5-d4b4-4f0d-9be8-c762d05c5936.mp3",
        filename: "car_talk_2020-02-15.mp3",
        title: "#2007: The Pavlovian Dope Slap",
        description:
            "February 15, 2020 • This week on The Best of Car Talk, Cathy thinks she may have found Mr. Right, but he may not live to see their wedding day if he kills her Sentra's clutch. Can a rigorous training program save Cathy's car, and the relationship? Elsewhere, Nicki gets a primer in how to shop for a used truck, including wardrobe tips. Also, Kate needs to slow down her neighbor who's zooming around their small island in his Malibu; Arleigh's car is afflicted by the \"Elvis Idle\"; and after Melissa cranked the heater to dry some wet clothes on her dashboard, she was shocked to discover her blower motor had died. Is there any chance this was just a coincidence? Find out, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-02-15",
        seconds: 3288,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/02/20200220_cartalk_2008_moses_blew_beets-1d1f4708-c314-49e6-8e80-647c84f3bd58.mp3",
        filename: "car_talk_2020-02-22.mp3",
        title: "#2008: Moses Blew Beets",
        description:
            "February 22, 2020 • Will's beloved dog Moses got carsick and puked on the dashboard of Will's now not-so-beloved Ford Ranger. Will's mechanic wants a couple hundred bucks to remove the dashboard and clean out the vents. Is there a cheaper, if messier, solution? Elsewhere, Jeffrey and his girlfriend disagree over how often to wash the road salt off their cars in the winter--their dispute might have something to do with the fact that Jeffrey drives a junky Tercel while his girlfriend has a shiny Subaru Legacy. Also on the relationship front, Beth's boyfriend says her fender bender on an icy road is the reason why only one rear wheel is spinning on his Mustang. His accusation may be the reason he may soon be Beth's ex-boyfriend. And, why does Kenneth's car sound like a cow mooing when it slows down?",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-02-22",
        seconds: 3297,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/02/20200225_cartalk_2009_saddle_up-ea8c3f59-4f8c-4b63-af97-8dc1c306de5f.mp3",
        filename: "car_talk_2020-02-29.mp3",
        title: "#2009: Saddle Up",
        description:
            "February 29, 2020 • This week on The Best of Car Talk, Mara's husband says he'd rather drive a horse and buggy than a minivan. But, with one kid on hand, and twins on the way, are there any options other than an Odyssey or spurs? In another auto-marital dispute, Pat and her husband disagree over whether driving their daughters 3/10 of a mile to school in cold weather is killing their car. Also, after meditating for three months, Conrad found his Civic in an immovable state, thanks to a frozen parking brake; Peter wants to rid his garage of bats, but may wind up on the ASPCA's Most Wanted list; and, trying to solve one of Ray's Puzzlers leads to a police visit. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-02-29",
        seconds: 3255,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/03/20200303_cartalk_2010_freedom_from_perfection-92d07336-d51f-4a26-b7e6-180aebdb98c6.mp3",
        filename: "car_talk_2020-03-07.mp3",
        title: "#2010: Freedom From Perfection",
        description:
            "March 7, 2020 • This week on The Best of Car Talk, Deb is extending 3-minute errands into 20-minute excursions, because her headlights won't turn off until the car warms up. Is her best fix a new switch, or loose wires and liberation? Elsewhere, the good news for Allison is that there are still sparks between her and her husband. The bad news is, we mean that literally. Also, the Click and Clack Forensics team tries to figure out why Sarah's Volvo burst into flames on her way home from its 60,000-mile service; Paul wants to take a Sawzall to his Subaru and transform it into a convertible; and, on Stump the Chumps, we find out if Bill cut the cable that was keeping his Tahoe from sinking to the bottom of a lake. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-03-07",
        seconds: 3299,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/03/20200311_cartalk_2011_black_widows-ee472d78-52bd-40e1-8e5a-e026f25f7ad7.mp3",
        filename: "car_talk_2020-03-14.mp3",
        title: "#2011: Attack of the Black Widows",
        description:
            "March 14, 2020 • This week on The Best of Car Talk, Heather recovered her stolen Civic, but found a family of black widow spiders had taken up residence. She killed the mother with a shovel, but how can she evict the rest of the clan? Elsewhere, Howard ran out of brake fluid during a long drive and is wondering if he could have used his bottle of tequila to fill in; Timothy is wondering if it's time to cut his losses on the Maserati that has him on a first-name basis with AAA; and could Tanya's loss of reverse lead to the Superball bumper? All this, plus the unfortunate tale of Tommy meeting Princess the pooch, the most polite hate message in the history of email, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-03-14",
        seconds: 3322,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/03/20200317_cartalk_2012_auto_darwinism-f592ba94-b7e9-414f-9436-14c3a9d4951a.mp3",
        filename: "car_talk_2020-03-21.mp3",
        title: "#2012: Automotive Darwinism",
        description:
            "March 21, 2020 • This week on The Best of Car Talk, after driving in Massachusetts for the first time, Addie is baffled by the concept of the rotary. Happily, Tom and Ray can explain its true purpose. Elsewhere, is \"Backseat Driver Syndrome\" incurable? Lani got used to yelling at her husband when he was a stinko driver, but now that he's doing better behind the wheel, she's still nagging from the passenger seat. Also, Christine is wondering if she needs to give up knitting in the passenger seat, lest a deploying airbag turn her needles into projectiles; Jem needs to clean a stuck valve, but the gunk may be the only thing holding his engine together; and even after three alignments, Russ still thinks his car may be headed for a ditch. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-03-21",
        seconds: 3272,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/03/20200325_cartalk_sacrificialbattery-eeb83eaf-4cb4-40b4-bf74-06058e864108.mp3",
        filename: "car_talk_2020-03-28.mp3",
        title: "#2013: The Sacrificial Battery",
        description:
            "March 28, 2020 • This week on The Best of Car Talk, did the battery in Keith's electric winch give up its life to lift a tree trunk? If so, how can Keith honor its memory? Elsewhere, Anne's family is planning a cross-country road trip. Is their Mercury Villager up to the task, or likely to wind up being pushed off the top of Pikes Peak when the engine fails? Also, Arlene wants her recently retired husband to learn how to work on their six cars. He says cars are too complicated, but is he just blowing smoke? And, Cindy's family loves the nurse they hired to take care of Cindy's Mom, but she has a nasty habit of backing into garden gnomes (and other objects) whenever she drives. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-03-28",
        seconds: 3257,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/03/20200331_cartalk_2014_a_nice_juicy_pizza-332677e7-5776-493a-9e50-6bd613e5647e.mp3",
        filename: "car_talk_2020-04-04.mp3",
        title: "#2014: A Nice Juicy Pizza",
        description:
            "April 4, 2020 • This week on The Best of Car Talk, unearthed letters from summer camp prove that the child really is the father to the man, at least when it comes to our Technical, Spiritual and Menu Advisor, John Bugsy Lawlor. Elsewhere, Lee liberated herself from her mechanic by changing her own oil, but also got liberated from her cash when she poured the oil into her transmission; Author Cameron needs a lesson in how to burn rubber; and, Jane and her husband want to buy a stretch limo to cruise around town in, because, well, why not? Also, on Stump the Chumps, we find out if Eddie and Edie Electron made their way home in Michelle's Saturn. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-04-04",
        seconds: 3279,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/04/20200406_cartalk_2015_the_popsodent-dc94aeed-fbd1-4dda-84cd-744a4be8e68a.mp3",
        filename: "car_talk_2020-04-11.mp3",
        title: "#2015: The Popsodent",
        description:
            "April 11, 2020 • This week on The Best of Car Talk, Sarah's about to graduate from college, and is ready to address the 5,000 dents her Taurus has suffered from years of being parked in campus lots. Will she find the solution on late-night TV? Elsewhere, really low-budget filmmaker Seth wants to blow up a car for his latest project. Is there enough cash in our legal defense fund for Tom and Ray to even consider giving Seth any advice? Also, a manure overload may have made Art's truck's steering &*%^! the bed; and Stephan is bothered by his truck's knocking, but even more concerned about his mechanic's fix for it. And, should Byron challenge the marital-industrial complex and insist on driving away from his wedding in his pick-up truck? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-04-11",
        seconds: 3249,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/04/20200409_cartalk_2016_the_stick_fix-77295a44-29e6-4c73-a934-797563e61a21.mp3",
        filename: "car_talk_2020-04-18.mp3",
        title: "#2016: The Stick Fix",
        description:
            "April 18, 2020 • This week on The Best of Car Talk, Martin drove off a ledge and dislodged his muffler. He found a stick to keep it in place. Will this brilliant solution set New Hampshire and the entire Northeast on fire? Elsewhere, Tom and Ray administer the Leadfoot Personality Test to try to figure out whether Martha is responsible for her Passat's rough shifting, or if she can blame a failing transmission. Also, Dick's car is blowing so much smoke he's on Pennsylvania's Most Wanted Polluters list; and, Elizabeth is wondering if she should let a sleeping nail lie--in her tire. And, can Tom and Ray teach Beth how to parallel park when she can't see what's behind her? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-04-18",
        seconds: 3248,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/04/20200413_cartalk_dark-and-stormy-3fac3f45-beeb-40fc-ad01-3afb30fdcb8e.mp3",
        filename: "car_talk_2020-04-25.mp3",
        title: "#2017: It Was a Dark and Stormy Night",
        description:
            "April 25, 2020 • This week on The Best of Car Talk, a salute to Edwards Bulwer-Lytton, the writer who set the bar for bad opening sentences with, \"It was a dark stormy night.\" Can any current authors hope to match him? Elsewhere, Liz wants to use her Maxima to remove some unwanted shrubs from her yard, but is worried her bumper will wind up as part of the landscape. Elsewhere, Nancy's 16-year old son wants a muscle car. Will she be abdicating all parental responsibility if she buys him one, and is there a good alternative that's big, ugly, and cool? Also, Pam wants to ease her husband's guilt over denting her door; Charles succumbed to Male Answer Syndrome trying to diagnose his wife's noisy Voyager; and, is Kirk's steering problem a result of Post-Alignment Euphoria, or Post-Alignment Anxiety? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-04-25",
        seconds: 3245,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/04/20200427_cartalk_2018_wife_or_cigar-04cf09d3-f386-484e-a186-b929db7e620f.mp3",
        filename: "car_talk_2020-05-02.mp3",
        title: "#2018: Your Wife or a Cigar",
        description:
            "May 2, 2020 • This week on The Best of Car Talk, Tom and Ray demonstrate their unmatched ability to plant all four feet firmly in their mouths and endanger their marriages— all while diagnosing a simple vacuum leak. Later, however, they just might make amends by helping to save Beth's marriage, with a ruling on whether her Civic's clutch should be more afraid of Beth or her husband. Elsewhere, Susan is a philosophy professor by day, and a pig rescuer by night. Is there one vehicle that can handle both lifestyles, or does she need a dedicated Pigmobile? Also, Jackie's squealing brakes are wreaking havoc for her pet chihuahuas; and Daniel got a very unpleasant surprise when his mechanic removed his distributor cap—think Vincent Price in \"The Fly.\" All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-05-02",
        seconds: 3308,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/05/20200505_cartalk_2019_click_clack_mom-352355a8-a457-499d-b4eb-b5d978bacb7f.mp3",
        filename: "car_talk_2020-05-09.mp3",
        title: "#2019: Click & Clack & Mom",
        description:
            "May 9, 2020 • This week, Car Talk celebrates Mother's Day with a special appearance from Tom and Ray's long-suffering mom, Elizabeth. She'll spill the beans on what life was like in the Magliozzi household, and do her best to evade the question of which of her kids she liked best. She's also ready to give out advice to new moms (\"You've got a long way to go, sweetheart!\"); get to the real reason one caller really wants to teach his mom to drive (\"Is she going to leave you a lot of money?\"); and, offer a final thought on Motherhood that will have Tommy blowing coffee out his nose. Lizzy may even be able to top her sons in figuring out why Sandy's Mitsubishi is groaning, and how Linda can stop the air leaks that are turning her Accord into a wind tunnel. Join us for a visit to the Maternal Combustion Department, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-05-09",
        seconds: 3254,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/05/20200507_cartalk_2020_waccabuc_flash-ad380511-aa24-4406-802f-d9ab365f4232.mp3",
        filename: "car_talk_2020-05-18.mp3",
        title: "#2020: The Waccabuc Flash",
        description:
            "May 18, 2020 • This week on The Best of Car Talk, paging Agents Mulder and Scully! Sally drove under a wire, heard a loud noise and saw a flash of light in her console. Is Waccabuc, New York the new Area 51? Elsewhere, Wyatt holds Tom and Ray responsible for the worst eight months of his life, and not because they gave him bogus car advice! It's a tale of woe and intrigue that ends with an almost cross-country escape in a VW Microbus. Also, Cynthia's kids want her to dump her beloved Subaru. Should she go along, if they give her a new BMW? And, Dorothea's dealer changed her belts, and now her car is shrieking. Does she need a big lawyer, or a big stick? All this, plus Tom and Ray ponder whether members of the Witness Protection Program get to hang out with each other, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-05-18",
        seconds: 3261,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/05/20200515_cartalk_2021_odometer_dreams-5756e20b-bbbf-474c-a85f-4ecd4c7f5450.mp3",
        filename: "car_talk_2020-05-23.mp3",
        title: "#2021: Odometer Dreans",
        description:
            "May 23, 2020 • This week on The Best of Car Talk, Bill's broken odometer fixed itself, right after Bill dreamed it was working. Will Tom and Ray have a mechanical explanation, a metaphysical explanation, or (most likely) a boooooogus explanation? Elsewhere, Toby wants her husband to get rid of her old BMW, but he's proving as immovable as the car; Sally is getting half her husband's mileage, and hopes it's not because she's buying cheap gas from Rotten Robbie; and Derek's dog would really appreciate it if Derek could get his Impreza to stop lunging forward. All this, plus a round of Stump the Chumps, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-05-23",
        seconds: 3248,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/05/20200527_cartalk_asktheethicist-a9661c85-7a5f-4762-8417-041eeb5c28af.mp3",
        filename: "car_talk_2020-05-30.mp3",
        title: "#2022: Ask the Ethicist",
        description:
            "May 30, 2020 • This week on The Best of Car Talk, Mary wants to sell her Accord, but it has a leaky water pump. Does she get the work done, knock the price down, or none of the above? Can Tom and Ray put their inner mechanic aside, and guide her to a clear conscience, or do they need an outside consult? Elsewhere, Tina just learned a scary and stinky lesson about why you shouldn't drive drive down a mountain in neutral; Jerry is looking for an alternative to the \"stick and ballet pose\" method he's using to get his convertible top to work; and we revisit the Waccabuc Incident: Was Sally's vision of a flashing light an atmospheric abnormality, or a call to the mothership? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-05-30",
        seconds: 3310,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/06/20200604_cartalk_2023_proverbial-2551d07b-f145-4edf-bc00-0cc49871a54e.mp3",
        filename: "car_talk_2020-06-06.mp3",
        title: "#2023: Proverbial Declarification",
        description:
            "June 6, 2020 • This week on The Best of Car Talk, a quiz for the Master of Puzzler Obfuscation. Can Ray un-declarify some well-known proverbs? Elsewhere, Caroline's poor clutch technique may be destroying her relationships; Nancy boyfriend's MR2 is burning oil, which may say more about his personality than the car; and John's pickup sounds like Buddy Rich is playing drums under the hood. Also, is something really wrong with Dana's starter motor or have her parents taken action to get her to stop lounging on their couch? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-06-06",
        seconds: 3259,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/06/20200609_cartalk_2024_faster_than_the_speed_of_light-2ee44132-6a92-4884-9df6-7faefc758666.mp3",
        filename: "car_talk_2020-06-13.mp3",
        title: "#2024: Faster Than the Speed of Light",
        description:
            "June 13, 2020 • This week on The Best of Car Talk, physics research suggests that Tom may in fact be Superman. You've never seen them photographed together, have you? Elsewhere, Grant's marriage counselor suggested he and his wife turn to Tom and Ray to help settle their auto-marital dispute over keeping the radio on while the car is off. Will our hosts bring peace, or will Grant's next appearance be on Divorce Court? Also, Mark decided to replace his working transmission, and has now gone through six failed rebuilds in 6 months; Mabel's Subaru is leaking oil from every orifice; Tulis's mechanic may be relying too much on prisms and crystals trying to fix her Civic's brakes; and is Jessica's car shocking her because of her clothes, her hair, or its ugly upholstery? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-06-13",
        seconds: 3269,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/06/20200615_cartalk_2025_a_sympathetic_ear-34773b29-8728-4b49-a89c-82b94a4e32a6.mp3",
        filename: "car_talk_2020-06-20.mp3",
        title: "#2025: A Sympathetic Ear",
        description:
            "June 20, 2020 • This week on The Best of Car Talk, Ryan took his car in for an oil change and got talked into an engine shampoo. Will Tom and Ray reassure him that he's not a complete idiot? At least he didn't get a cream rinse. Elsewhere, Bill parked his rental car on a beach, and discovered the next morning that the tide had rolled in—to the car. He's bailed the water, but hasn't told the rental company. Also, Ray channels Frank Costanza to try to diagnose Kevin's clicking noise; Jean is suffering a run of flat tires in her driveway; and, is a lucky doughnut enough to keep Tamatha's brakes from burning up for a third time? All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-06-20",
        seconds: 3308,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/06/20200622_cartalk_2026_sherlock_holmes-22661623-a84b-473f-837d-3865eb2d53a7.mp3",
        filename: "car_talk_2020-06-27.mp3",
        title: "#2026: Sherlock Holmes, Eat Your Heart Out",
        description:
            "June 27, 2020 • This week on The Best of Car Talk, Stephanie's Volvo began making noise after she moved from California to Oregon. Tommy uses brilliant deductive reasoning to come up with a completely bogus explanation. Elsewhere, Karlene's mechanic diagnosed her Explorer's annoying squeak as \"an annoying squeak,\" with no suggestions for quieting it. Can Tom and Ray do perhaps just a wee bit better? Also, Ed may need to resort to healing crystals to start his son's Taurus; Larry has a chance to take part in a wonderful bonding experience with his 14-year old son and is looking for any way to get out of it; and on Stump the Chumps, we find out if Michelle is happily driving around Spokane in her $700 dream truck or if it's doing duty as a lawn ornament in her backyard. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-06-27",
        seconds: 3300,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/06/20200629_cartalk_2027-dregs-theory-e2e9a017-5180-4043-a907-2cbf0d40f74c.mp3",
        filename: "car_talk_2020-07-04.mp3",
        title: "#2027: The Dregs Theory",
        description:
            "July 4, 2020 • This week on The Best of Car Talk, Donna's husband warned her not to let her new Camry's gas tank fall below 1/4 full, because the dregs might damage a crucial part. Does the fact that this part no longer exists automatically throw this advice into the Land of the Booooooogus? Elsewhere, John can only keep his car from stalling by opening the hood and touching the engine. Does this fix have anything to do with the fact that John's a Catholic priest? Also, Tom is looking for a \"girlfriend car,\" but can't decide if his wife should be able to drive it; Michael will inherit his father-in-law's Town Car if he can figure out it's odd steering and stalling problem; and way up north in Alaska, Linda needs to retro-fit her ATV so her sled dogs will get their off-season workouts. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-07-04",
        seconds: 3271,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/07/20200706_cartalk_sorry_dad-7c5cfa50-b182-40b3-84c7-3ac122e110aa.mp3",
        filename: "car_talk_2020-07-11.mp3",
        title: "#2028: Sorry, Dad",
        description:
            "July 11, 2020 • This week on The Best of Car Talk, did Christy destroy her dad's car 15 years ago by putting black tape over a flashing temperature light— and then continuing to drive? And is Dad ready to forgive and forget? It's one of our all-time favorite auto-familial disputes. Elsewhere, Andy got talked into replacing his front brakes to help stop a noise coming from the rear; Nancy's husband says she's risking death by keeping her air conditioning on recirculate; and should Mickey be concerned that she's on her fourth consecutive boyfriend who drives an '82 Honda? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-07-11",
        seconds: 3280,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/07/20200708_cartalk_cleandeath-ec920477-152c-46ed-bc49-0e657fb484d2.mp3",
        filename: "car_talk_2020-07-18.mp3",
        title: "#2029: A Clean Death",
        description:
            "July 18, 2020 • This week on The Best of Car Talk, Greg was surprised when his truck started running poorly, until he learned that his four-year-old son had washed the inside of the gas tank with soap. Should Greg stick his kid with the repair bill? Elsewhere, Judy can't decide if her son-in-law is brilliant or wacko for raising the hood of his Volvo after every drive; Gil's Camry may be leaving a trail of clutch fluid from Houston to Phoenix; Debra's knocking is nothing compared to the sound of two hosts banging their heads together trying to figure out what's causing it; and, what does Gavin's car have in common with King Tut's tomb? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-07-18",
        seconds: 3273,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/07/20200721_cartalk_2030_additive_placebo_syndrome-d8c09474-2e53-4b07-b28d-0de638764810.mp3",
        filename: "car_talk_2020-07-25.mp3",
        title: "#2030: Additive Placebo Syndrome",
        description:
            "July 25, 2020 • This week on The Best of Car Talk, Bob's friend swears his Passat is getting an extra mile per gallon since he disabled the daytime running lights. Is this possible, or is he working overtime to believe it's happening? Elsewhere, Harmony stands accused of smashing her sister's car by taking her foot off the brake, but swears her foot never left the pedal; Bruce's son's Town Car needs a paint job but it will cost more than the car is worth; and Gina's husband is taking the fun out of his mid-life crisis convertible by being a little too careful—he's cleaning bugs off the windshield, while he's driving. Is Gina being too much of a nag trying to get him to stop, or are those dope slaps she's administering well earned? All this, plus the definitive explanation of Male Answer Syndrome and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-07-25",
        seconds: 3297,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/07/20200728_cartalk_2031_electrons-3158e7eb-7ba9-4c08-adeb-64da860a11eb.mp3",
        filename: "car_talk_2020-08-01.mp3",
        title: "#2031: Tickling the Electrons",
        description:
            "August 1, 2020 • This week on The Best of Car Talk, Dennis' friend told him the best way to charge a low car battery is by turning on all the accessories. Does this earn immediate entry into the Wacko Theory Hall of Fame? Elsewhere, Julieta's boyfriend is blaming her driveway for his Camry's starting problem, which can only be cured by the correct curse words; Molly would like a little less cowbell in her Altima; and Gail explodes the myth that women don't play practical jokes. Also, how did a rental car's exhaust suck in Mike's daughter's shirt? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-08-01",
        seconds: 3272,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/08/20200804_cartalk_2032_hungry_water-0c3bcde1-1f43-4be0-8a16-c713d767eca9.mp3",
        filename: "car_talk_2020-08-08.mp3",
        title: "#2032: The Hungry Water Theory",
        description:
            "August 8, 2020 • This week on The Best of Car Talk, distilled water may be too hungry for John to use it in his radiator. Will Ray's explanation of the hungry water theory help clarify things, or as usual, only further obfuscate matters? Elsewhere, Diana's van could be a new form of germ warfare; Rhadd's wild idling leaves him, Tom, and Ray all wishing our hosts were smarter; and, on Stump the Chumps we find out if Liz found her gas leak, and the perfect jumpsuit. Also, Todd's noisy truck gives Tom a chance to re-live his Army days with the long-suffering Sgt. McNeeley. Everybody will go on pass this weekend except Private Maaagleeeozi! All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-08-08",
        seconds: 3283,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/08/20200811_cartalk_2033_big_junk-6124aa96-ded9-476d-8b79-375d39551e37.mp3",
        filename: "car_talk_2020-08-15.mp3",
        title: "#2033: A Big, Beautiful, Piece of Junk",
        description:
            "August 15, 2020 • This week on The Best of Car Talk, should Jason dump his beloved Camaro? It needs a new engine and completed its mission to help him find a girlfriend. Elsewhere, Shelly has the happiest dog in the world as her Explorer is spewing dog food from the vents; Oscar needs to decide whether to fix his wife's brakes or buy more life insurance for her; and should Barbara attempt her 6-month road trip in a VW Camper Van if she expects it to last more than 6 days? Also, from the land of Wacko theories, Teresa's husband thinks he has a better to chance to survive a collision if he's not wearing a seat belt; and our on-call chemist Jim Davis weighs in on Ray's hungry water theory. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-08-15",
        seconds: 3253,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/08/20200817_cartalk_2034_con-5e482d9c-09ba-412c-9b73-12670a1dc7e6.mp3",
        filename: "car_talk_2020-08-22.mp3",
        title: "#2034: Con the Mechanic",
        description:
            "August 22, 2020 • This week on The Best of Car Talk, Nancy doesn't fully trust her mechanic so she's throwing around car jargon to bluff him into thinking she knows more than she does. But, her vocabulary has run dry. Will the official Click and Clack Thesaurus come to her rescue? Elsewhere, Greg's truck's wiring has become lunch for critters and the only way to save it may require giving up his beloved garage wood shop. Also, Kara's white-water rafting company may have to do the unthinkable and switch to automatic transmissions for their trucks; and on Stump the Chumps, we find out if Tom and Ray knocked their heads together well enough to diagnose Debra's truck's knocking sound. All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-08-22",
        seconds: 3272,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/08/20200824_cartalk_everybody_wins-f4c10aa1-eb74-40cf-b222-ea3b87685db4.mp3",
        filename: "car_talk_2020-08-29.mp3",
        title: "#2035: Everybody Wins",
        description:
            "August 29, 2020 • This week on The Best of Car Talk, Julia's worried that her Dad's attempt to replace the engine in Mom's Suburban might stress their marriage. Tom and Ray think it may make their bond stronger than ever, even if the car is destroyed. Elsewhere, Tim's Dodge Dart rolled into a lake and went for a full dive. The car has been retrieved, but will it ever run again and not smell like fish? Also, Karen's physicist husband has a bogus explanation for why her car is shaking; Kelley wants to fix her Civic's brakes herself; and, Stu's girlfriend Carla accidentally added engine oil to his beloved ZX's power steering. So why are Tom and Ray asking Carla if she wants to dump Stu. All this, plus a round of Stump the Chumps, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-08-29",
        seconds: 3257,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/08/20200826_cartalk_2036_ignoramus-3f05e0c8-6ded-4fca-9ec7-ae8d66d41dfe.mp3",
        filename: "car_talk_2020-09-05.mp3",
        title: "#2036: Magliozzi's Ignoramus Principle",
        description:
            "September 5, 2020 • Move over, Heisenberg! This week on the Best of Car Talk, one listener's new theory on Tom and Ray's ability to alter reality. Elsewhere, Anthony thinks his cheapo tires are making noise. His solution? Swap them with his wife's tires. Will Tom and Ray have a suggestion that won't land Anthony in divorce court? Also, Crash's Mazda is making him live up to his nickname by wandering all over the road; Kimberly is tired of having to whack her Subaru's starter; Dora has become a reluctant member of the Alternator of the week club; and does a cleaner car lead to a bigger mechanic's bill? All this, plus some words to live by and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-09-05",
        seconds: 3257,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/wc/2020/09/20200909_wc_latent-c795dd9a-cbcf-43fb-9736-f6b4f892a59b.mp3",
        filename: "car_talk_2020-09-12.mp3",
        title: "#2037: Latent Junkman Syndrome",
        description:
            "September 12, 2020 • This week on The Best of Car Talk, Joe's brother-in-law collects heaps. Why is this Joe's problem? The cars wind up in his backyard. And to make things even more complicated, Joe's brother-in-law owns the house. Can Tom and Ray untangle this family mess? Elsewhere, Sherry thinks her temperature gauge is going through menopause; Roseanna borrowed her friend's Subaru for the summer and fears she may be responsible for its new noise; and Klaus may need to learn how to drive his car with the engine off. All this, plus some fun things to say on elevators, and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-09-12",
        seconds: 3275,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/09/20200914_cartalk_2038_clutch-288dd35d-3738-4cdf-ba45-d09f105f2c63.mp3",
        filename: "car_talk_2020-09-19.mp3",
        title: "#2038: Bernsteining the Clutch",
        description:
            "September 19, 2020 • This week on The Best of Car Talk, Leonard Bernstein is immortalized in automotive lore for a shifting technique he handed down to his son. Elsewhere, Adla got a rude welcome to Boston when someone stole the battery from her Civic; Jennifer made an ill-advised bet on steering wheels with her know-it-all 18-year-old nephew; Esther's low coolant light and buzzer might be trying to send her a subtle signal about the state of her cooling system; and is John's Thunderbird suffering from Radio Frequency Interference or Dying Transmission Syndrome? All this and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-09-19",
        seconds: 3291,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/09/20200922_cartalk_2039_fell_off_truck-25de8174-dd79-4a3f-b84e-1ba858333603.mp3",
        filename: "car_talk_2020-09-26.mp3",
        title: "#2039: Fell Off Truck",
        description:
            "September 26, 2020 • This week on The Best of Car Talk, Matt's bad day got a little worse when his Volvo fell off the tow truck that was hauling it from an accident. Will Tom and Ray's vast experience dropping cars help Matt figure out if his is still safe to drive? Elsewhere, should Jackie go braless when washing her car? We're talking about the car's bra here, not Jackie's. Also, Peter thinks he has a theremin player living in his car; Barb's smart-aleck son may actually be smarter than she thinks; and on Stump the Chumps, we find out if Victoria bought cars for her three sons and opted for a career in flower arranging over business school. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-09-26",
        seconds: 3321,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/10/20201001_cartalk_2040_desperate_fluids-9b6a98fa-1f56-4454-a0d9-59b38a697693.mp3",
        filename: "car_talk_2020-10-03.mp3",
        title: "#2040: Desperate Times Call For Desperate Measures",
        description:
            "October 3, 2020 • This week on The Best of Car Talk, Andy's car overheated in the desert. With no water on hand, his girlfriend convinced him to use the only liquid available. We're bordering on TMI here, so we'll just say that Andy is now worried about said liquid's acid causing corrosion. Elsewhere, Judy and her Volvo just moved from Los Angeles to Chicago. What does she need to do to winterize her car, and herself? Also, Christian's clutch problems are threatening his career in pizza delivery; Magica's husband dropped a razor blade in the airbag compartment and thinks it's not a big deal; and should Louella risk her safety and sanity by teaching her teenage daughters how to drive stick shift? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-10-03",
        seconds: 3327,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/10/20201005_cartalk_2041_exorcist-cb4eb5ee-1f01-4b4c-b20a-2a7ed805a4f8.mp3",
        filename: "car_talk_2020-10-10.mp3",
        title: "#2041: Exorcist or Arsonist",
        description:
            "October 10, 2020 • This week on The Best of Car Talk, Robin and our hosts have different approaches for ger VW's devilish steering problem. Elsewhere, Sue's boyfriend is afraid to get in the car with her due to her long history of accidents, near misses, and traffic violations. Sue insists she's a safe driver, so a full-scale Car Talk intervention may be necessary. Also, Joe may need to choose between a bungee cord and a 2x4 if he doesn't want to spring for a new transmission; and can Randy just keep adding a quart of oil to her Civic and live her life? Depends on whether her life involves driving the car! All this, plus more than you ever wanted to know about the hazards of adding urine to a radiator. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-10-10",
        seconds: 3276,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/10/20201014_cartalk_dont_start-0d527b7e-7228-4e8e-8eb7-8d99ecc93143.mp3",
        filename: "car_talk_2020-10-17.mp3",
        title: "#2042: Don't Start",
        description:
            "October 17, 2020 • This week on The Best of Car Talk, Rich inherited a Buick that's been napping for four years. Can he start it right up without destroying it,or being enveloped in smoke? Elsewhere, Patrice's VW bus won't start, John Mark's backseat passengers are getting their feet soaked when he makes a turn, and Alana's gas tank is spitting fuel back out after she fills it. Also, is the threat of fire enough to convince Jim that replacing his tailpipe might count as a \"necessary repair\"? And, will a strategically placed blanket and light bulb really reduce Judy's engine wear by 95%? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-10-17",
        seconds: 3351,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/10/20201021_cartalk_2043_clickenomics-ad7259f1-3f84-4a69-8b40-97b16804925f.mp3",
        filename: "car_talk_2020-10-24.mp3",
        title: "#2043: Clickonomics",
        description:
            "October 24, 2020 • This week on Car Talk, how many thousands of dollars can one hour of lousy car advice pump into an ailing economy? Well, when that hour starts with a Saab owner who's going to be transmission shopping, we may be able to match the Gross Domestic Product of Guinea-Bissau. Or better. Things take a turn for the bearish, though, when Jacob scores a free do-over on his timing belt replacement-- and when Lee's Lincoln turns out to need a new \"Whoop Tube.\" (How do you figure costs of replacing an imaginary part?) Happily, Laura brings us back on track. She loves her Camry so much, she can't wait to dump it and get something more suited to her growing dog. Also, someone may be messing around with mileage markers in Montana; and, on Stump the Chumps, did Tom and Ray help save Mark's socks from being soaked by transmission fluid? All this, and lots more, this week on Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-10-24",
        seconds: 3307,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/10/20201028_cartalk_2044_sap-56a2d4cf-558d-4d03-915b-627f9f44cfa2.mp3",
        filename: "car_talk_2020-10-31.mp3",
        title: "#2044: You Sap",
        description:
            "October 31, 2020 • This week on The Best of Car Talk, Yousef's quickie oil change place recommended that he use special high mileage/high price oil in his Saturn. Yousef swears the car is performing better, but his fiancee is convinced that Yousef got suckered. Will Tom and Ray be any more sympathetic, or will they try to sell Yousef the Brooklyn Bridge? Elsewhere, Tim found something resembling mayonnaise on his Fury's dipstick. Should he be worried, or should he just make a tuna salad sandwich with it? Also, Tonia likes her next door neighbor but is less fond of the noxious chemicals he uses on his car; Larry wants to convince his wife it's okay to buy a used car from a rental company but a tale from Ray's past may change his mind; and the great Cathy/Kathy challenge. All this and more this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-10-31",
        seconds: 3294,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-podcasts/podcast/npr/cartalk/2020/11/20201102_cartalk_2045_bionic_bug-897fac29-5e4d-44db-af48-92f9e0fb4645.mp3",
        filename: "car_talk_2020-11-07.mp3",
        title: "#2045: The Bionic Bug",
        description:
            "November 7, 2020 • This week on The Best of Car Talk, Rita's VW won't start after being flooded during a hurricane. Does it have a future on the road or just as a saltwater aquarium? Elsewhere, Bob discovered an unusual feature in his BMW as a result of his father-in-law being locked in the car for a half-hour; Dan's Acura may have oil problems, if his neighbor's hearing is right; and Chuck thinks his wife's parking brake technique is too quiet. Also, college sudent Kim wants help with a take-home Physics exam. Man, did she call the wrong number! All this, the Great Cathy/Kathy Stump the Chumps Challenge, and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-11-07",
        seconds: 3284,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/11/20201112_cartalk_exercise.mp3",
        filename: "car_talk_2020-11-14.mp3",
        title: "#2046: The Exercise Diaries",
        description:
            "November 14, 2020 • This week, The Best of Car Talk kicks off with the tale of one man's descent to Dante's supplemental Circle of Hell, the local health club, where he is at the merciless hands of his personal trainer, Tanya. Then we're off to Virginia, where Shelia's Maxima smells like someone burned her dry cleaning. Elsewhere, Ethan's preparing to sell his truck, which was struck by lightning. Should he advertise it as \"pre-disastered\" or keep quiet? Also, from the don't-try-this-at- home department, Marty's dad got their vintage car started by sucking gas through the exhaust with a shop vac, and he still has his eyebrows! All this and lots more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-11-14",
        seconds: 3290,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/11/20201118_cartalk_shrink.mp3",
        filename: "car_talk_2020-11-21.mp3",
        title: "#2047: The Shrink Wrapped Land Rover",
        description:
            "November 21, 2020 • This week on The Best of Car Talk, Mike and his sons are about to embark on a two-year around the world sailing voyage, but the vintage Land Rover Mike's been restoring won't be much use at sea. Should he sell it or will late-night TV provide the perfect storage solution? Elsewhere, Lisa's wondering how much restitution she's entitled to for allowing her husband to buy a used Corvette; Charlotte's daughter spent $300 on a truck and may have overpaid; and Arnie's Accord's harmonic balancers won't stay balanced. Also, Tom and Ray may need to consult Junk & Wagnalls' encyclopedia to diagnose Sandy's hum. All this and more, this week on the Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-11-21",
        seconds: 3254,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/11/20201123_cartalk_2048_black_hole.mp3",
        filename: "car_talk_2020-11-28.mp3",
        title: "#2048: The Black Hole of Auto Metaphysics",
        description:
            "November 28, 2020 • This week on the Best of Car Talk, one listener postulates that a non-essential repair on an old car creates a parallel universe where everything else starts to break. Sorry, but for proof, you may have to tune to the Sci-Fi Channel. Elsewhere in the land of semi-wacko theories, Mark was told he could use rice to clean a carburetor, and Joyce's boyfriend insists on leaving his Taurus' trunk open overnight to keep it dry. Also, can Stephanie blame her mom for killing her Subaru's clutch, and is Mike's snowblower really not starting because it's too cold? And, John's mechanic ran into the age-old dilemma: Is it better to admit stupidity or gaslight the customer? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-11-28",
        seconds: 3319,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/12/20201201_cartalk_2049-the-brake-stomper.mp3",
        filename: "car_talk_2020-12-05.mp3",
        title: "#2049: The Brake Stomper",
        description:
            "December 5, 2020 • This week on The Best of Car Talk, Diana has a new boyfriend, and a Stanza that's begun chewing up brake pads at an alarming rate. What are the chances these two facts are not a coincidence? Oh, maybe 100%? Elsewhere, Bob is worried his car may have a permanent case of athlete's foot (or worse) after a sock got sucked into the engine; Patty may need to milk her Accord to get it to stop mooing; and, Elizabeth came home from Thanksgiving to discover her Volvo's windows permanently fogged. And Mike may re-think his desire for a \"heavy duty\" clutch after he hears Tom and Ray's tale of the customer known as Mr. Heavy Duty and his enlarged left foot. All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-12-05",
        seconds: 3406,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/12/20201209_cartalk_2050_stop_the_snort.mp3",
        filename: "car_talk_2020-12-12.mp3",
        title: "#2050: Stop the Snort",
        description:
            "December 12, 2020 • This week on the Best of Car Talk, can Ray grant one listener's Christmas wish by snorting less? And why can't Bob stop laughing about his Geo's starting problem? Elsewhere, Alan's Lincoln is starting to sound eerily like his mother; Karen's Caravan's dashboard is telling her she's always going 120 miles per hour on an empty gas tank; Steph wants to tempt the Blowout Gods by removing his Miata's spare tire so he'll have more trunk space; and Ariel is thinking of buying her first car and is wondering what level of protection she needs to bring to the dealer. Will a Rottweiler do or a big guy named Bruno? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-12-12",
        seconds: 3413,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/12/20201215_cartalk_2051_lightning.mp3",
        filename: "car_talk_2020-12-19.mp3",
        title: "#2051: Predestination of Lightning",
        description:
            "December 19, 2020 • This week on the Best of Car Talk, Evelyn wants to know why a bolt of lightning spared her car and struck the road 20 feet away instead. Tom and Ray think Evelyn should just say a few kind words to the deity of her choice and move on, but will nonetheless offer a pseudo-scientific answer that's guaranteed to have MIT demanding its diplomas back. Elsewhere we find out if Bob's wife's car survived sucking a sock into the engine on Stump the Chumps; Gary's steering noise is scaring away his girlfriends; and did Barbara do more damage to her husband's truck, or her marriage, by driving a mile without any oil? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-12-19",
        seconds: 3410,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
    {
        url: "https://chrt.fm/track/138C95/prfx.byspotify.com/e/play.podtrac.com/npr-510208/ondemand.npr.org/anon.npr-mp3/npr/cartalk/2020/12/20201222_cartalk_untowed.mp3",
        filename: "car_talk_2020-12-26.mp3",
        title: "#2052: Untowed and Unbowed",
        description:
            "December 26, 2020 • This week on The Best of Car Talk, Steve moved to Chicago for a job and a girlfriend. He lost both, but he's kept his sense of humor, and is just kinda confused about why his Acura was the only car not towed from a party. Elsewhere, we thought nobody could be more devoted to an old heap than Tommy, until we met Lita who has written a poem about her Monte Carlo—we're just relieved she didn't try to rhyme anything with \"rust bucket.\" Also, the holiday season brings good cheer and the annual squeak to Betsy's Town and Country; Kate's temporary fix for her frozen door locks is hilarious, and incredibly dangerous; and, did the hottest man in show business set Melinda's radio on fire? All this and more, this week on The Best of Car Talk.",
        artist: "Car Talk",
        album: "The Best of Car Talk",
        year: 2020,
        date: "2020-12-26",
        seconds: 3431,
        artists: ["Car Talk", "Click and Clack"],
        channels: 1,
        genre: ["Humour"],
    },
];
